### ISSUE TITLE
32bit release support?

### ISSUE THREAD

**Issue by IguanaMeow** [probonopd/linuxdeployqt#100]
Are there any plans to release a binary that supports 32bit versions of linux?

**Comment by probonopd** [comment]
It should be possible to compile linuxdeployqt on a 32-bit system, but currently I have no plans to do so because 64-bit is mainstream now.

**Comment by probonopd** [comment]
A similar tool written by me has 32-bit versions now: https://github.com/probonopd/go-appimage/releases/tag/continuous
