### ISSUE TITLE
linuxdeployqt exits with code "1"

### ISSUE THREAD

**Issue by hyOzd** [probonopd/linuxdeployqt#106]
linuxdeployqt exits with code "1" even though the operation is successful and I don't see any error messages. AFAIK anything except "0" is considered  and error.

**Comment by probonopd** [comment]
Can you please provide more details: Distribution, version, application to be packaged, Qt version and where it is coming from. Thanks.

**Comment by hyOzd** [comment]
Distro: Linux Mint 18.1 (based on ubuntu 16.04)
Qt version: 5.6.2

Application is my own [serialplot](https://bitbucket.org/hyOzd/serialplot/).

**Comment by probonopd** [comment]
Please run with `-verbose=3`. Toward the end, you should see

```
Embedding ELF...
Marking the AppImage as executable...
Success
Log: ret 0
Log: WEXITSTATUS(ret) 0
Log: result: 0
```

Do you get the same?

**Comment by hyOzd** [comment]
I had tried that and i specifically looked for 'result: X' line. But didnt see it. No apperent error messages either. I can send you a full log tomorrow.

On May 7, 2017 1:26:34 PM GMT+03:00, probonopd <notifications@github.com> wrote:
>Please run with `-verbose=3`. Toward the end, you should see
>
>```
>Embedding ELF...
>Marking the AppImage as executable...
>Success
>Log: ret 0
>Log: WEXITSTATUS(ret) 0
>Log: result: 0
>```
>
>Do you get the same?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/probonopd/linuxdeployqt/issues/106#issuecomment-299696079

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by probonopd** [comment]
Please run with `-verbose=3` and paste the last 10 lines here. Thanks.

**Comment by hyOzd** [comment]
@probonopd I'm so sorry. I've been using an older version (release 1). I've specifically checked this but.. I shouldn't have trusted my eyes. Latest version works fine. Sorry again :(
