### ISSUE TITLE
master segfaults

### ISSUE THREAD

**Issue by probonopd** [probonopd/linuxdeployqt#108]
master segfaults for unknown reasons

```
tests/tests.sh: line 65:  7871 Segmentation fault      (core dumped) ../../../linuxdeployqt-*-x86_64.AppImage nonfhs/QtWidgetsApplication
```

**Comment by TheAssassin** [comment]
The issue is caused by the weird Qt5Core patching, which has been obsoleted according to @probonopd. We'll remove it for that reason. After finishing some infrastructure for future segfaults, I'll squash the work on my fork, and will contribute it upstream.

**Comment by probonopd** [comment]
Likely caused by https://github.com/NixOS/patchelf/issues/124

**Comment by TheAssassin** [comment]
I think I fixed it by using a stable patchelf version I found in the Debian Jessie repositories (version 0.8-2, as of writing this comment). Squashing, amending and pushing to the PR.

**Comment by probonopd** [comment]
Thank you very much @TheAssassin, greatly appreciated!
