### ISSUE TITLE
PrivateWidgets library is not being deployed

### ISSUE THREAD

**Issue by Ribtoks** [probonopd/linuxdeployqt#113]
Environment: [Qt 5.6.2 official] [Ubuntu 16.04 x64]

I'm deploying my Qt app [Xpiks](https://github.com/ribtoks/xpiks) with the [following script](https://github.com/Ribtoks/xpiks/blob/master/src/xpiks-qt/deploy_lin.sh) with _linuxdeployqt_.

When I start AppImage afterwards it segfaults when loading `main.qml` file. I have investigated that and it appears that `linuxdeployqt` does not deploy `libwidgetsplugin.so` (located at `$QT_BIN/qml/QtQuick/PrivateWidgets` path) to the resulting AppDir. So this needs to be done separately as it is not shown by the `ldd` but rather loaded by Qt in runtime (I suppose).

**Comment by probonopd** [comment]
Thanks for investigating this. Is the rest of `QtQuick/PrivateWidgets` deployed properly?

**Comment by Ribtoks** [comment]
@probonopd This is the only .so file of PrivateWidgets. There's only `qmldir` file and .so. There're a lot of PrivateWidgets .qml files but they reside in a different path and are not related to this problem.

**Comment by probonopd** [comment]
> There's only qmldir file and .so.

That _might_ have to do with the cause for the problem. How is the system supposed to know that this `.so` is needed by the application?

**Comment by Ribtoks** [comment]
@probonopd `macdeployqt` and `windeployqt` work correctly. I've fixed problem of `linuxdeployqt` in my PR. Nothing besides that.

**Comment by probonopd** [comment]
Thanks @Ribtoks will merge once https://github.com/probonopd/linuxdeployqt/issues/108 is fixed.
