### ISSUE TITLE
Prevent Qt from loading plugins from 'unexpected' places

### ISSUE THREAD

**Issue by probonopd** [probonopd/linuxdeployqt#12]
windeployqt does the following:

> Patch the preconfigured Qt path in Qt5Core to '.'. This allows one to immediately test whether the generated package is self-contained, without Qt being able to 'fall back' to the installed Qt for loading plugins. It is also fixing a potential security issue where Qt tries to load plugins
> from 'unexpected' places. The effect is the same as adding a qt.conf file with all the defaults. However, a lot of people consider adding a qt.conf ugly.

https://github.com/RSATom/Qt/blob/master/qttools/src/windeployqt/utils.cpp#L924-L971
https://codereview.qt-project.org/#/c/121731/

Maybe linuxdeployqt should do that too.

**Comment by ddurham2** [comment]
Yes it should.  It's just a matter of opening the deployed copy of Qt5Base.so and replacing the first instance of "qt_prfxpath={256bytes}" (256+12 bytes total) with "qt_prfxpath=.{255 \0 bytes}" (still 256+12 bytes total).  The buffer in the qt source code is exactly this size.


https://codereview.qt-project.org/#/c/121731/

**Comment by probonopd** [comment]
Yes I think it should be done, but http://code.qt.io/cgit/qt/qttools.git/tree/src/macdeployqt is not doing it.

**Comment by probonopd** [comment]
@msorvig mentioned in #qt-labs:

> Is that to prevent loading plugins from the Qt install? macdeployqt uses qt.conf for that purpose

**Comment by probonopd** [comment]
> Yes it should. It's just a matter of opening the deployed copy of Qt5Base.so and replacing the first instance of "qt_prfxpath={256bytes}" (256+12 bytes total) with "qt_prfxpath=.{255 \0 bytes}" (still 256+12 bytes total). The buffer in the qt source code is exactly this size.
> 
> https://codereview.qt-project.org/#/c/121731/

This makes me wonder whether we could use it to set a prefix to somewhere relative to Qt5Base.so, hence removing the need for a `qt.conf` file. This would be super neat!
