### ISSUE TITLE
Qt 5.8 QtWebEngineProcess dependencies

### ISSUE THREAD

**Issue by Gjergj** [probonopd/linuxdeployqt#122]
Deploying a Qt 5.8 application with QWebEngineView requires  the resources and translations directories inside libexec also.
Without them the application crashes.

**Comment by Gjergj** [comment]
Digging deeper, on https://doc.qt.io/qt-5/qtwebengine-deploying.html#deploying-resources I saw webengine that resources are expected at 

> QLibraryInfo::location(QLibraryInfo::TranslationsPath) 
on linux and windows.

 I extracted the appimage to a squashfs directory like so
> ./Application-x86_64.AppImage --appimage-extract
and 
>QLibraryInfo::location(QLibraryInfo::TranslationsPath) 
says 
>/home/gjergji/Desktop/squashfs-root
But QtWebEngineProcess crashes without having resources and translations in the same directory.

**Comment by probonopd** [comment]
`linuxdeployqt` _should_ take care of this already, but apparently you are running into a bug. Can you please explain which application you are trying to bundle, and on which build system?

**Comment by Gjergj** [comment]
I am trying to bundle my own application.
The build system is on Linux Mint 18.1, gcc 5.4

**Comment by probonopd** [comment]
It's a bit difficult for me to reproduce this without having access to the application to be bundled. Please check https://github.com/probonopd/linuxdeployqt/blob/f6664faaf90a6bf72ee9fe2e62d4bebe5733b10d/shared/shared.cpp#L1074-L1127 - can you identify why it fails in your situation?

**Comment by Gjergj** [comment]
The resources and translations directories should be inside libexec too.
Perhaps 
[https://github.com/probonopd/linuxdeployqt/blob/f6664faaf90a6bf72ee9fe2e62d4bebe5733b10d/shared/shared.cpp#L1089-L1122](https://github.com/probonopd/linuxdeployqt/blob/f6664faaf90a6bf72ee9fe2e62d4bebe5733b10d/shared/shared.cpp#L1089-L1122)
should be duplicated as 
```
         if(fhsLikeMode){
            QFileInfo qfi(appDirInfo.binaryPath);
            QString qtTargetDir = qfi.absoluteDir().absolutePath() + "/../";
            dstLibexec = qtTargetDir + "/libexec";
            dstResources = qtTargetDir + "/" + dstLibexec + "/resources";
            dstTranslations = qtTargetDir + "/" + dstLibexec + "/translations";
        } else {
            dstLibexec = appDirInfo.path + "/libexec";
            dstResources = appDirInfo.path + "/" + dstLibexec + "/resources";
            dstTranslations = appDirInfo.path + "/" + dstLibexec + "/translations";
        }
        QDir().mkpath(dstResources);
        QDir().mkpath(dstTranslations);

        sourcePath = QDir::cleanPath(qtDataPath + "/resources/qtwebengine_resources.pak");
        destinationPath = QDir::cleanPath(dstResources + "/qtwebengine_resources.pak");
        copyFilePrintStatus(sourcePath, destinationPath);
        sourcePath = QDir::cleanPath(qtDataPath + "/resources/qtwebengine_devtools_resources.pak");
        destinationPath = QDir::cleanPath(dstResources + "/qtwebengine_devtools_resources.pak");
        copyFilePrintStatus(sourcePath, destinationPath);
        sourcePath = QDir::cleanPath(qtDataPath + "/resources/qtwebengine_resources_100p.pak");
        destinationPath = QDir::cleanPath(dstResources + "/qtwebengine_resources_100p.pak");
        copyFilePrintStatus(sourcePath, destinationPath);
        sourcePath = QDir::cleanPath(qtDataPath + "/resources/qtwebengine_resources_200p.pak");
        destinationPath = QDir::cleanPath(dstResources + "/qtwebengine_resources_200p.pak");
        copyFilePrintStatus(sourcePath, destinationPath);
        sourcePath = QDir::cleanPath(qtDataPath + "/resources/icudtl.dat");
        destinationPath = QDir::cleanPath(dstResources + "/icudtl.dat");
        copyFilePrintStatus(sourcePath, destinationPath);
        // Translations:
        sourcePath = QDir::cleanPath(qtTranslationsPath + "/qtwebengine_locales");
        destinationPath = QDir::cleanPath(dstTranslations + "/qtwebengine_locales");
        recursiveCopy(sourcePath, destinationPath);
```
Untested code

**Comment by probonopd** [comment]
What makes you think that the resources and translations directories should be subdirectories of the libexec directory? According to http://doc.qt.io/qt-5/qt-conf.html this doesn't seem to be the case, at least in the defaults.

**Comment by probonopd** [comment]
Which Qt are you using on your Linux Mint 18.1? The one that came with the system, or the one provided by the Qt company, or the one from https://launchpad.net/~beineri/+archive/ubuntu/opt-qt58-trusty?

I have had very good results using https://launchpad.net/~beineri/+archive/ubuntu/opt-qt58-trusty.

**Comment by Gjergj** [comment]
If i did not have them in the libexec directory the app crashes.
I am using Qt5.8 from the Qt Company.

**Comment by probonopd** [comment]
When you build linuxdeployqt from git master, then it now creates `qt.conf` files (again). Please test whether the problem persists with these. Possibly they need to be further expanded to include the defaults from http://doc.qt.io/qt-5/qt-conf.html.

**Comment by Gjergj** [comment]
I will test in the next two days.
