### ISSUE TITLE
Errors with "ldd: not found" on Qt applications

### ISSUE THREAD

**Issue by probonopd** [probonopd/linuxdeployqt#128]
`linuxdeployqt` is supposed to run `qmake`, determine the path to the Qt instance that should be bundled, and set `LD_LIBRARY_PATH` to point there so that the Qt libraries can be picked up by `ldd` (which `linuxdeployqt` uses internally).

https://github.com/probonopd/linuxdeployqt/blob/3df78b975a391b7c56d0b615d7140cef13f0bd7b/shared/shared.cpp#L1075

However, in order to need `qmake` only if the application to be deployed is a Qt application, we do this only if it has been detected that the application to be deployed is actually a Qt application.

https://github.com/probonopd/linuxdeployqt/blob/3df78b975a391b7c56d0b615d7140cef13f0bd7b/shared/shared.cpp#L1025

```
if(qtDetected != 0)
```

The problem is that `qtDetected` doesn't get set because it gets set only after we run `LddInfo` which [terminates linuxdeployqt execution ](https://github.com/probonopd/linuxdeployqt/blob/3df78b975a391b7c56d0b615d7140cef13f0bd7b/shared/shared.cpp#L304)when it encounters "not found" in the output (which it does, since `LD_LIBRARY_PATH` hasn't been set to the Qt directory to be bundled at that point yet.

So we should only `exit(1);` if we still get "not found" __after__ we have set `LD_LIBRARY_PATH` to the Qt location.

@rullzer this would also remove the need to change the `rpath` in the payload executable prior to running `linuxdeployqt`. Maybe you can send a PR?

**Comment by rullzer** [comment]
I'll look into it :)

**Comment by probonopd** [comment]
@rullzer please check if 697b126 solves it

**Comment by probonopd** [comment]
...and https://github.com/probonopd/linuxdeployqt/commit/9d9192f31b31f3046997711e268bf32a6e9bd28d
