### ISSUE TITLE
Pre-release(5) linuxdeployqt must use Qt5.8?

### ISSUE THREAD

**Issue by stereomatchingkiss** [probonopd/linuxdeployqt#129]
Qt : Qt5.6.2 64bits
os : ubuntu16.04.1
desktop : KDE

I download newest version of linuxdeployqt and want to deploy an [app](https://github.com/stereomatchingkiss/QImageScraper/blob/master/README.md) by it.  The 

I got a messages like this after I run the AppImage

> /home/ramsus/Qt/Qt/5.6/gcc_64/lib/libQt5Core.so.5: version `Qt_5.8' not found (required by ../../../linuxdeployqt-continuous-x86_64.AppImage)

Following are the step I tried to use linuxdeployqt

1 : export PATH, so linuxdeployqt can find correct qmake version

PATH=/home/ramsus/Qt/Qt/5.6/gcc_64/bin:$PATH

2 : export LD_LIBRARY_PATH because ldd cannot find libQt5WebEngine.so.5

export LD_LIBRARY_PATH=/home/ramsus/Qt/Qt/5.6/gcc_64/lib:$LD_LIBRARY_PATH

3 : run linuxdeployqt

./../../linuxdeployqt-continuous-x86_64.AppImage QImageScraper 

The only contain one file only(QImageScraper), do I need to throw more files into that folder?

**Comment by probonopd** [comment]
linuxdeployqt _should_ be using the Qt that is bundled inside its AppImage, something seems to be going wrong there.

**Comment by Skycoder42** [comment]
As a workaround, you can use this script. It will build and install linuxdeployqt into your Qt installation with the Qt you have installed. This should always create a working version:

https://github.com/Skycoder42/QtIFW-Advanced-Setup/blob/master/get_linuxdeployqt_compat.sh

**Comment by probonopd** [comment]
You may be running into https://github.com/probonopd/linuxdeployqt/issues/128.

`export LD_LIBRARY_PATH` breaks it because this way you are trying to load an older Qt version than `linuxdeployqt` was built with, which fails.

Please retry without `export LD_LIBRARY_PATH` once https://github.com/probonopd/linuxdeployqt/issues/128 is fixed.

**Comment by stereomatchingkiss** [comment]
Thanks for the reply, I will wait for the release of next version

**Comment by probonopd** [comment]
@stereomatchingkiss please check if 697b126 solves it ([download latest build](https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage)).

**Comment by zingmars** [comment]
Nope. If anything, the latest build broke for those of us using 5.8.

`./qtdeploy.AppImage: /opt/qt58/lib/libQt5Core.so.5: version 'Qt_5.9' not found (required by ./qtdeploy.AppImage)`

**Comment by probonopd** [comment]
What is qtdeploy? Please unset LD_LIBRARY_PATH and try again.

**Comment by zingmars** [comment]
It's how I named the executable (wget (...) -O qtdeploy.Appimage).

**Comment by probonopd** [comment]
Please `unset LD_LIBRARY_PATH` directly before you run it.

**Comment by zingmars** [comment]
Right, it seems that I had missed my CI script setting LD_LIBRARY_PATH before the build script. This did indeed work. Thanks!

**Comment by tresf** [comment]
@probonopd I'm running into this exact same issue after installing the Qt5.8 version available for Ubuntu 14.04.

Adding `unset LD_LIBRARY_PATH` prior to calling `linuxdeployqt` fixes this problem.  Is this command safe in all instances (such as using the built-in Qt5.2) or is it only needed for situations where we've installed a custom Qt5 version?  If so, having a way to detect the environment would be a nice stop-gap, as I put myself in this situation after referencing an example PR for Travis-CI.

**Comment by probonopd** [comment]
I think `unset LD_LIBRARY_PATH` is needed in situations where the Qt to be deployed is a lower version than the version used to build `linuxdeployqt`.

**Comment by probonopd** [comment]
Maybe we should link Qt statically to avoid this. It's a shame the Qt company doesn't provide static Qt for download in an easy way.
