### ISSUE TITLE
Cryptic error: $ID.desktop file not found

### ISSUE THREAD

**Issue by orbifx** [probonopd/linuxdeployqt#134]
If the desktop file is not in `appdir`, the error is

> $ID.desktop file not found

Which looks more like an interpretation issue rather than a missing/misplaced file.
A hint would be nice.

**Comment by probonopd** [comment]
Please call `linuxdeployqt` like this:

```
linuxdeployqt ./path/to/appdir/usr/share/application_name.desktop`
```

`linuxdeployqt` should then use `application_name.desktop` as the desktop file, and will, in this example, use `application_name` as the ID. The "ID" terminology is coming from [AppStream](https://www.freedesktop.org/software/appstream/docs/sect-Metadata-Application.html) (the use of which is optional).

**Comment by orbifx** [comment]
Is it worth documenting this in the wiki?

**Comment by TheAssassin** [comment]
Will be more useful to state it clearly in the usage guide found in the README. I tried to use linuxdeployqt exactly like described there, and found several caveats, too.

Feel free to send a PR that improves the usage instructions.
