### ISSUE TITLE
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled

### ISSUE THREAD

**Issue by AmirAfendin** [probonopd/linuxdeployqt#150]
`QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DoubleBuffer), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile)) `

trying to deploy https://doc.qt.io/qt-5/qtquickcontrols2-gallery-example.html

**Comment by AmirAfendin** [comment]
I tried on ubuntu 16.04 and 14.04 both have the same issue

**Comment by nnttoo** [comment]
I have got this kind of problem before, and can be solved by executing linuxdeployqt twice or by manually copying the xcbglintegrations folder inside plugins folder, maybe this also works for you.

**Comment by TheAssassin** [comment]
I agree. Please try to run it twice. linuxdeployqt sometimes gets in trouble to collect all dependencies recursively on the first try, but the second run resolves them properly.

**Comment by AmirAfendin** [comment]
thanks friends, copying xcbglintegrations folder helped

**Comment by TheAssassin** [comment]
Feel free to reopen if you have further problems.

**Comment by martinrotter** [comment]
Bumped into the bug too. But this really looks like a bug to me. I would say that running generator twice is just a workaround...

**Comment by TheAssassin** [comment]
@martinrotter if you can provide some additional information (IRC chat would be fine, #appimage on freenode, but a link to your app and build script might help already), I'll re-open the issue and we'll try to find the cause. Running linuxdeployqt twice is a workaround for a bunch of problems which nobody really got to debugging, and it'd be great to find real fixes.

**Comment by martinrotter** [comment]
@TheAssassin Basically [this](https://github.com/martinrotter/rssguard/blob/master/resources/scripts/.travis-install-linux.sh), but do not run both lines 19 and 20. Run only line 20 and skip line 19, then you will have the AppImage with the bug. Basically as I made the diff the folder `xcbglintegrations` was missing from `plugins` subfolder.

**Comment by aospan** [comment]
Try this fix https://github.com/probonopd/linuxdeployqt/pull/188 ?
