### ISSUE TITLE
Missing dependency errors running RS.AppImage on a Debian 9 Host

### ISSUE THREAD

**Issue by dtschmitz** [probonopd/linuxdeployqt#151]
```
./RetroShare06-12345678-x86_64.AppImage: /lib/x86_64-linux-gnu/**libc.so.6**: version `GLIBC_2.25' not found (required by /tmp/.mount_RetroSSqRHgT/usr/bin/../lib/libgnutls.so.30)
./RetroShare06-12345678-x86_64.AppImage: /lib/x86_64-linux-gnu/**libz.so.1**: version `ZLIB_1.2.9' not found (required by /tmp/.mount_RetroSSqRHgT/usr/bin/../lib/libpng16.so.16)
[19:15:10] <Mercurania> [1]+ Salida 1 ./RetroShare06-12345678-x86_64.AppImage 
```
I don't have in my AppDir/usr/lib those files.  
(Thus far, the App has run without issues on my VM Arch system.)
Don't scold me about Arch.  :)
Please review and advise.  Thanks! -- Dietrich

**Comment by probonopd** [comment]
The distribution you are trying to run this on is older than the distribution you used to compile the AppImage ingredients. This AppImage needs a newer system to run (or you need to compile it on an older system).

**Comment by dtschmitz** [comment]
Here's the full extent of build files in my AppDir /usr/lib:

> [root@ThinkPad lib]# pwd
/home/dts/retroshare-git/RetroShare06.AppDir/usr/lib
[root@ThinkPad lib]# ls
libasyncns.so.0             libpulse.so.0
libavahi-client.so.3        libqgsttools_p.so.1
libavahi-common.so.3        libQt5Core.so.5
libavcodec.so.57            libQt5DBus.so.5
libavformat.so.57           libQt5Gui.so.5
libavutil.so.55             libQt5Multimedia.so.5
libbluray.so.2              libQt5MultimediaWidgets.so.5
libbz2.so.1.0               libQt5Network.so.5
libcap.so.2                 libQt5OpenGL.so.5
libcrypto.so.1.0.0          libQt5PrintSupport.so.5
libcrypto.so.1.1            libQt5Widgets.so.5
libcups.so.2                libQt5X11Extras.so.5
libcurl.so.4                libQt5XcbQpa.so.5
libdbus-1.so.3              libQt5Xml.so.5
libdc1394.so.22             libraw1394.so.11
libdouble-conversion.so.1   libschroedinger-1.0.so.0
libdw.so.1                  libsndfile.so.1
libEGL.so.1                 libsoxr.so.0
libelf.so.1                 libspeexdsp.so.1
libffi.so.6                 libspeex.so.1
libFLAC.so.8                libsqlcipher.so.0
libfreetype.so.6            libssh2.so.1
libgcrypt.so.20             libssh.so.4
libGLdispatch.so.0          libssl.so.1.0.0
libGLX.so.0                 libssl.so.1.1
libgmodule-2.0.so.0         libswresample.so.2
libgmp.so.10                libswscale.so.4
libgnutls.so.30             libsystemd.so.0
libgomp.so.1                libtasn1.so.6
libgraphite2.so.3           libtbb.so.2
libgsm.so.1                 libtheoradec.so.1
libgstapp-1.0.so.0          libtheoraenc.so.1
libgstaudio-1.0.so.0        libthreadutil.so.6
libgstbase-1.0.so.0         libtiff.so.5
libgstpbutils-1.0.so.0      libudev.so.1
libgstphotography-1.0.so.0  libunistring.so.2
libgstreamer-1.0.so.0       libunwind.so.8
libgsttag-1.0.so.0          libupnp.so.6
libgstvideo-1.0.so.0        libva-drm.so.1
libHalf.so.12               libva.so.1
libharfbuzz.so.0            libva-x11.so.1
libhogweed.so.4             libvdpau.so.1
libicudata.so.59            libvorbisenc.so.2
libicui18n.so.59            libvorbis.so.0
libicuuc.so.59              libvpx.so.4
libIex-2_2.so.12            libwebpmux.so.3
libIlmImf-2_2.so.22         libwebp.so.7
libIlmThread-2_2.so.12      libX11-xcb.so.1
libImath-2_2.so.12          libx264.so.148
libixml.so.2                libx265.so.116
libjasper.so.4              libXau.so.6
libjpeg.so.8                libxcb-glx.so.0
libkrb5.so.3                libxcb-icccm.so.4
libkrb5support.so.0         libxcb-image.so.0
liblz4.so.1                 libxcb-keysyms.so.1
liblzma.so.5                libxcb-randr.so.0
libmicrohttpd.so.12         libxcb-render.so.0
libmodplug.so.1             libxcb-render-util.so.0
libmp3lame.so.0             libxcb-shape.so.0
libnettle.so.6              libxcb-shm.so.0
libnghttp2.so.14            libxcb-sync.so.1
libnsl.so.1                 libxcb-util.so.1
libogg.so.0                 libxcb-xfixes.so.0
libopencore-amrnb.so.0      libxcb-xinerama.so.0
libopencore-amrwb.so.0      libxcb-xkb.so.1
libopencv_core.so.3.2       libXdmcp.so.6
libopencv_imgcodecs.so.3.2  libXext.so.6
libopencv_imgproc.so.3.2    libXfixes.so.3
libopencv_videoio.so.3.2    libxine.so.2
libopenjp2.so.7             libXi.so.6
libopus.so.0                libxkbcommon.so.0
liborc-0.4.so.0             libxkbcommon-x11.so.0
libpcre2-16.so.0            libxml2.so.2
libpcre.so.1                libxslt.so.1
libpng16.so.16              libXss.so.1
libpsl.so.5                 libxvidcore.so.4
libpulsecommon-10.0.so

**Comment by dtschmitz** [comment]
So, I'll build it on an older version Distro.  Do you have a sense for which Distro other Devs are using for the build process?  If so, which?

**Comment by probonopd** [comment]
CentOS 6 and Ubuntu 14.04 are common choices.
