### ISSUE TITLE
libstdc++.so.6: version `GLIBCXX_3.4.20' not found

### ISSUE THREAD

**Issue by dtschmitz** [probonopd/linuxdeployqt#153]
linuxdeployqt log: 
```
Desktop file as first argument: "./RS.AppDir/usr/share/applications/retroshare06.desktop"
desktopExecEntry: "RetroShare06"
desktopIconEntry: "retroshare06"
Found binary from desktop file: "/home/am/Downloads/rs/RS.AppDir/usr/bin/RetroShare06"
FHS-like mode with PREFIX, fhsPrefix: "/home/am/Downloads/rs/RS.AppDir/usr"
app-binary: "/home/am/Downloads/rs/RS.AppDir/usr/bin/RetroShare06"
appDirPath: "/home/am/Downloads/rs/RS.AppDir"
relativeBinPath: "usr/bin/RetroShare06"
Found icons from desktop file: ("/home/am/Downloads/rs/RS.AppDir/retroshare06.xpm", "/home/am/Downloads/rs/RS.AppDir/usr/share/icons/hicolor/24x24/apps/retroshare06.png", "/home/am/Downloads/rs/RS.AppDir/usr/share/icons/hicolor/64x64/apps/retroshare06.png", "/home/am/Downloads/rs/RS.AppDir/usr/share/icons/hicolor/128x128/apps/retroshare06.png", "/home/am/Downloads/rs/RS.AppDir/usr/share/icons/hicolor/48x48/apps/retroshare06.png", "/home/am/Downloads/rs/RS.AppDir/usr/share/pixmaps/retroshare06.xpm")
preExistingToplevelIcon: "/home/am/Downloads/rs/RS.AppDir/retroshare06.xpm"
ERROR: ldd outputLine: "/home/am/Downloads/rs/RS.AppDir/usr/bin/RetroShare06: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/am/Downloads/rs/RS.AppDir/usr/bin/RetroShare06)"
ERROR: Please ensure that all libraries can be found by ldd. Aborting.
```
The library is present:
```
am@am-Standard-PC-i440FX-PIIX-1996:~/Downloads/rs$ ls -l /usr/lib/x86_64-linux-gnu/libstdc++.so.6
lrwxrwxrwx 1 root root 19 May  7  2016 **/usr/lib/x86_64-linux-gnu/libstdc++.so.6 -> libstdc++.so.6.0.19**
```
Operating environment: qemu-kvm Ubuntu14.04 installation.
A build of RetroShare from 7/17/17 was build from src, then installed with make install.

LDD output for /usr/bin/retroshare:
[rsdeps.zip](https://github.com/probonopd/linuxdeployqt/files/1163638/rsdeps.zip)
Please review and advise.  -- Dietrich

**Comment by probonopd** [comment]
`/usr/lib/x86_64-linux-gnu/libstdc++.so.6` is too old. It seems like RetroShare06 was compiled against a newer version?

**Comment by dtschmitz** [comment]
@probonopd  wrote: `/usr/lib/x86_64-linux-gnu/libstdc++.so.6 is too old. It seems like RetroShare06 was compiled against a newer version?`
I built RS from source in the 14.04 vm environment.

**Comment by probonopd** [comment]
Does your compiled version run at all, prior to using `linuxdeployqt`?

**Comment by dtschmitz** [comment]
Yes it runs:
[Screenshot from 2017-07-20 17:09:52.png.zip](https://github.com/probonopd/linuxdeployqt/files/1163695/Screenshot.from.2017-07-20.17.09.52.png.zip)

**Comment by probonopd** [comment]
I don't mean `/usr/bin/retroshare` but `/home/am/Downloads/rs/RS.AppDir/usr/bin/RetroShare06`. Does it run, prior to using `linuxdeployqt`?

**Comment by dtschmitz** [comment]
I'll spare you what happened.  in this commit the Dev decided to change the binary name and a few other things /usr/bin/RetroShare06 is now /usr/bin/retroshare.  I am going to close this and keep my head down.  Thanks.
