### ISSUE TITLE
Created in Debian Jessie, Got undefined symbol error in Fedora

### ISSUE THREAD

**Issue by librehat** [probonopd/linuxdeployqt#157]
Vanilla Debian Jessie 8.9 64-bit OS, all packages installed from the Debian official repository.

I was trying to pack https://github.com/shadowsocks/shadowsocks-qt5 as AppImage so I followed all steps in README.md in my local Debian VM. I've successfully created an AppImage file. It seems working fine in Debian. However, after I copied it out to the host OS (Fedora 26 64-bit), I couldn't run the AppImage file but got an error:

    ./Shadowsocks-Qt5-x86_64.AppImage: symbol lookup error: /lib64/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates

**Comment by TheAssassin** [comment]
Looks like libharfbuzz wasn't bundled by linuxdeployqt. It is not in the [exclude list](https://github.com/AppImage/AppImages/blob/master/excludelist) which means that something prevented linuxdeployqt from bundling it. Can you provide the linuxdeployqt log of your Debian build? Ideally, re-run with `-verbose=3`.

**Comment by librehat** [comment]
[logs.txt](https://github.com/probonopd/linuxdeployqt/files/1203241/logs.txt)
```
appdir/
├── AppRun -> usr/bin/ss-qt5
├── shadowsocks-qt5.desktop
├── shadowsocks-qt5.png
└── usr
    ├── bin
    │   ├── qt.conf
    │   └── ss-qt5
    ├── lib
    │   ├── libappindicator.so.1
    │   ├── libatk-1.0.so.0
    │   ├── libbotan-1.10.so.0
    │   ├── libbz2.so.1.0
    │   ├── libcairo.so.2
    │   ├── libcrypto.so.1.0.0
    │   ├── libdatrie.so.1
    │   ├── libdbus-1.so.3
    │   ├── libdbusmenu-glib.so.4
    │   ├── libdbusmenu-gtk.so.4
    │   ├── libffi.so.6
    │   ├── libfreetype.so.6
    │   ├── libglapi.so.0
    │   ├── libgmodule-2.0.so.0
    │   ├── libgmp.so.10
    │   ├── libgraphite2.so.3
    │   ├── libgthread-2.0.so.0
    │   ├── libharfbuzz.so.0
    │   ├── libicudata.so.52
    │   ├── libicui18n.so.52
    │   ├── libicuuc.so.52
    │   ├── libindicator.so.7
    │   ├── libjpeg.so.62
    │   ├── libpcre.so.3
    │   ├── libpixman-1.so.0
    │   ├── libpng12.so.0
    │   ├── libqrencode.so.3
    │   ├── libQt5Core.so.5
    │   ├── libQt5DBus.so.5
    │   ├── libQt5Gui.so.5
    │   ├── libQt5Network.so.5
    │   ├── libQt5Widgets.so.5
    │   ├── libQtShadowsocks.so
    │   ├── libthai.so.0
    │   ├── libv4l2.so.0
    │   ├── libv4lconvert.so.0
    │   ├── libX11-xcb.so.1
    │   ├── libXau.so.6
    │   ├── libxcb-dri2.so.0
    │   ├── libxcb-dri3.so.0
    │   ├── libxcb-glx.so.0
    │   ├── libxcb-icccm.so.4
    │   ├── libxcb-image.so.0
    │   ├── libxcb-keysyms.so.1
    │   ├── libxcb-present.so.0
    │   ├── libxcb-randr.so.0
    │   ├── libxcb-render.so.0
    │   ├── libxcb-render-util.so.0
    │   ├── libxcb-shape.so.0
    │   ├── libxcb-shm.so.0
    │   ├── libxcb-sync.so.1
    │   ├── libxcb-util.so.0
    │   ├── libxcb-xfixes.so.0
    │   ├── libxcb-xkb.so.1
    │   ├── libXcomposite.so.1
    │   ├── libXcursor.so.1
    │   ├── libXdamage.so.1
    │   ├── libXdmcp.so.6
    │   ├── libXext.so.6
    │   ├── libXfixes.so.3
    │   ├── libXinerama.so.1
    │   ├── libXi.so.6
    │   ├── libxkbcommon.so.0
    │   ├── libxkbcommon-x11.so.0
    │   ├── libXrandr.so.2
    │   ├── libXrender.so.1
    │   ├── libxshmfence.so.1
    │   ├── libXxf86vm.so.1
    │   └── libzbar.so.0
    ├── plugins
    │   ├── bearer
    │   │   ├── libqconnmanbearer.so
    │   │   ├── libqgenericbearer.so
    │   │   └── libqnmbearer.so
    │   ├── imageformats
    │   │   ├── libqgif.so
    │   │   ├── libqico.so
    │   │   └── libqjpeg.so
    │   └── platforms
    │       └── libqxcb.so
    └── share
        ├── applications
        │   └── shadowsocks-qt5.desktop
        └── icons
            └── hicolor
                └── 512x512
                    └── apps
                        └── shadowsocks-qt5.png
```

I can see `libharfbuzz.so` bundled in the directory.

**Comment by probonopd** [comment]
Still, _someting_ is trying to load `/lib64/libharfbuzz.so.0` from your system.

Please run `LD_DEBUG=libs appdir/AppRun` and try to find out what is doing this.

**Comment by librehat** [comment]
```

**Comment by librehat** [comment]
[ld_debug.txt](https://github.com/probonopd/linuxdeployqt/files/1203252/ld_debug.txt)
I can't find anything useful in the output :/

**Comment by probonopd** [comment]
You see that it says `(RUNPATH from file appdir/AppRun)` on __some__ lines? We need to find out why it doesn't do this on the line responsible for libharfbuzz...

**Comment by librehat** [comment]
Yes I do see those. But it doesn't have this for libharfbuzz...

**Comment by probonopd** [comment]
...which seems to be the issue (to be investigated)

**Comment by librehat** [comment]
So I just built Qt myself with `-no-xcb -no-harfbuzz`, however, harfbuzz still appears in `ldd`... It seems some other libraries than Qt pulls in harfbuzz

**Comment by probonopd** [comment]
Yes, let's find out which one.

**Comment by librehat** [comment]
I've found it out: `/usr/lib/libappindicator.so.1`

**Comment by probonopd** [comment]
And what loads that?

**Comment by librehat** [comment]
This application `ss-qt5` does

**Comment by probonopd** [comment]
Is that the application you are packaging? What does
```
patchelf --print-rpath usr/bin/ss-qt5
```
say?

**Comment by librehat** [comment]
It says `$ORIGIN/../lib/`

I don't know...

**Comment by probonopd** [comment]
Ah right, what does
```
patchelf --print-rpath appdir/usr/lib/libappindicator.so.1
```
say?

**Comment by librehat** [comment]
It says `$ORIGIN`

**Comment by librehat** [comment]
I'm not sure if it's caused by `libfreetype.so.6`. After I removed `libfreetype.so.6` and `libharfbuzz.so.0` from the bundle, it can be launched without problem on my Fedora

**Comment by TheAssassin** [comment]
See https://github.com/AppImage/AppImages/pull/323.

**Comment by Dekker1** [comment]
I seem to be dealing with the same issue, but the current solution is not working for me. My Qt application requires both `libfreetype.so.6` and `libharfbuzz.so.0` according to the `ldd` output of the binary. Currently `linuxdeployqt` is not including either of these within the packaged libraries (which seems to be the current fix), but running the package build on Ubuntu on a Fedora machine gives the same error as in the first post:
`symbol lookup error: /lib64/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates
`
I'm running using the following command: `linuxdeployqt $BINARY -bundle-non-qt-libs -no-translations -no-copy-copyright-files`.

Has their been any progress on this issue?

**Comment by probonopd** [comment]
Can you please describe how to exactly reproduce the issue, and please provide a download link to your AppImage for inspection? Thanks.

**Comment by Dekker1** [comment]
My apologies, it seems that the problem I have only occurs in correspondence with a snap package and that because of the similarity with this issue I arrived at the wrong conclusion. Thank you for the quick response and this great packaging tool though!

**Comment by probonopd** [comment]
Please comment here if you think the problem continues to exist, then we will reopen.
