### ISSUE TITLE
Do not overwrite pre-existing AppRun

### ISSUE THREAD

**Issue by probonopd** [probonopd/linuxdeployqt#159]
In some situations we want to run `linuxdeployqt` twice and sneak in a custom AppRun file. `linuxdeployqt` should honor it and not overwrite it.

Example:
https://github.com/probonopd/cubelister/blob/patch-1/.travis.yml

**Comment by TheAssassin** [comment]
Indeed a very useful feature. The [workaround](https://github.com/probonopd/linuxdeployqt/wiki/Custom-wrapper-script-instead-of-AppRun) is not always applicable, and is just that, a workaround.

**Comment by probonopd** [comment]
The workaround being

```
./linuxdeployqt*.AppImage --appimage-extract
./squashfs-root/usr/bin/appimagetool ./appdir/
```

**Comment by probonopd** [comment]
Reference:
https://code.wireshark.org/review/#/c/30953/3/CMakeLists.txt

**Comment by probonopd** [comment]
Successfully tested, hence merging #335.
