### ISSUE TITLE
Handle pre-existing libraries in AppDir

### ISSUE THREAD

**Issue by probonopd** [probonopd/linuxdeployqt#160]
`linuxdeployqt` currently does not handle the case where `make install` already placed libraries into the AppDir. `ldd` doesn't find them there.

The user needs to manually export `LD_LIBRARY_PATH`.

We don't know into which weird places `make install` may have put things, but we could at least abort and give a warning if we see pre-existing libraries in the AppDir which don't have `rpath` set to `$ORIGIN*`.

Example:
https://github.com/probonopd/linuxdeployqt/issues/159

**Comment by TheAssassin** [comment]
I already suspected that this was the problem with @aurhat's cubelister application. The libraries didn't have an rpath set, exporting `LD_LIBRARY_PATH` is possible but annoying.

I suppose it is safe to set the rpath to `$ORIGIN*` by default when there's none set already.

**Comment by probonopd** [comment]
Well, we don't even know where inside the AppDir they are and where the app may expect them to be. Maybe we want to move them to usr/lib... maybe not...

**Comment by TheAssassin** [comment]
`make install` will most likely put them where you would expect them, a.k.a. `<prefix>/lib`. We recommend to use `--prefix=/usr` and `DESTDIR=AppDir`. I would only support these directories.

**Comment by probonopd** [comment]
True...

**Comment by probonopd** [comment]
But then you have people putting stuff into subdirectories of that... like Nextcloud client, which cost me an evening...

**Comment by christopherpow** [comment]
I can't get linuxdeployqt to pick up pre-existing libraries even if I export LD_LIBRARY_PATH. I may not be doing things exactly right, but I have an executable that depends on several other libraries. I create a "dist" folder. Copy app.desktop and app.png into it. Copy all pre-existing libraries into it. Then export LD_LIBRARY_PATH=./dist; linuxdeployqt ./dist/app.desktop. When I look into dist/lib I do not see all of the libraries and running the app image requires LD_LIBRARY_PATH=. ./app

**Comment by probonopd** [comment]
@christopherpow is your application open source and available on GitHub? Then I can have a look.

**Comment by christopherpow** [comment]
http://github.com/christopherpow/nesicide.git

I haven't pushed the desktop or icon files yet though.

Thanks!

**Comment by probonopd** [comment]
Please push them too, thanks. They are needed for linuxdeployqt to work.

**Comment by christopherpow** [comment]
I've pushed now. All of my scripting madness is in build/. linux-deploy.sh.

**Comment by probonopd** [comment]
Thanks. Can you get it to [build on Travis CI](https://github.com/probonopd/linuxdeployqt#using-linuxdeployqt-with-travis-ci) until the point where one invokes linuxdeployqt? If you can do that, then I'll have a look whether I can take it from there.
Thanks!

https://github.com/probonopd/linuxdeployqt#using-linuxdeployqt-with-travis-ci

**Comment by christopherpow** [comment]
I've committed what might be a proper yaml. I'm watching the build now. Fantastic stuff! I've also badged the repository with the build status. My guess is that it will ultimately fail because linux-deploy.sh won't do the right thing. But I'm not sure. We shall soon see.

**Comment by christopherpow** [comment]
The build appears to be succeeding but I forgot to put the wget for linuxdeployqt. One more try. :)

**Comment by probonopd** [comment]
@christopherpow please try to follow the examples more closely, don't forget the `unset` command, e.g., https://github.com/christopherpow/nesicide/compare/master...probonopd:patch-1

Also don't forget something like `INSTALL_ROOT=appdir` so that `find appdir/` will give you appdir/usr/bin/ and appdir/usr/share, etc. - in the end you will run `linuxdeployqt` on this.

**Comment by christopherpow** [comment]
Not sure where the Qt 5.9 package is now. Nor how to find it. https://travis-ci.org/christopherpow/nesicide/builds/287634494

**Comment by probonopd** [comment]
https://launchpad.net/~beineri/+archive/ubuntu/opt-qt591-trusty

**Comment by probonopd** [comment]
You were missing a "1"

**Comment by christopherpow** [comment]
Guess I followed your example too closely. :)

**Comment by christopherpow** [comment]
Well at least now it runs linuxdeployqt. It's not including the app libs, as expected. I'm not sure what to do with the appdir stuff...perhaps i'll have to add the INSTALL_ROOT to the make invocations in build.sh.

**Comment by probonopd** [comment]
Please try copying the app libs into `/usr/lib/x86_64-linux-gnu/` so that `ldd` (which `linuxdeployqt uses internally) can find them there. If it can detect them using ldd, it will copy them over into the AppDir.

**Comment by probonopd** [comment]
Here is also an affected build: https://travis-ci.org/sithlord48/atcore/builds/297589116

**Comment by christopherpow** [comment]
What do I need to do with that?

**Comment by probonopd** [comment]
Nothing; please follow https://github.com/probonopd/linuxdeployqt/issues/160#issuecomment-336531131

**Comment by christopherpow** [comment]
I am.

**Comment by probonopd** [comment]
https://github.com/probonopd/linuxdeployqt/commit/b5e9de73315c66ea8bfe97307c4da909589d3029 and https://github.com/probonopd/linuxdeployqt/commit/099f3c04334680ed85871346a4d613c06e0dde52 should fix this. Feel free to reopen if needed.
