### ISSUE TITLE
No plugins found!

### ISSUE THREAD

**Issue by Muhand** [probonopd/linuxdeployqt#162]
Every time I try to use linuxdeployqt with my VLC application I get an error saying:
`[00000000028d8638] core libvlc error: No plugins found! Check your VLC installation.
VLC-Qt Error: libvlc failed to load!`
Here is the command I am using 
`/home/me/Downloads/linuxdeployqt-continuous-x86_64.AppImage /home/me/Desktop/test/src/build-test-Desktop_Qt_5_7_0_GCC_64bit-Release/test -qmldir='/home/muhand/Desktop/test/src/test' -appimage`

Also this is an image of the error I am getting:
![capture](https://user-images.githubusercontent.com/12287547/29504999-822262c8-8611-11e7-8603-eb1c2080a1a1.PNG)

**Comment by probonopd** [comment]
`linuxdeployqt` does not know how to handle VLC plugin. You would need to handle those manually. @darealshinji has excellent first-hand knowledge of this, maybe he can give you a hint.

Be sure to check out https://github.com/darealshinji/vlc-AppImage

**Comment by darealshinji** [comment]
My VLC AppImage build uses Qt4 which seems a bit less complicated to bundle (?).

**Comment by Muhand** [comment]
@probonopd Do you have any reference I can follow to handle it manually? I am a little bit beginner in this topic. So any lead can help. Not sure what to google as well.

@darealshinji Thank you, I will take a look at the source probonopd linked and also try Qt4.

**Comment by probonopd** [comment]
@Muhand you need to make your application load the VLC plugins from a path relative to the application rather than from an absolute path, so that the application becomes fully relocateable (= can be moved to diifferent locations in the filesystem without breaking). How to do this is outside the scope of AppImage.

**Comment by Muhand** [comment]
Got you!
Thanks a lot.
