### ISSUE TITLE
Cannot build project with Qt Creator

### ISSUE THREAD

**Issue by vadrian89** [probonopd/linuxdeployqt#167]
Like the title states, I am unable to build the project in Qt Creator.   
I open project, set it up, but when I build it gives:  

`/usr/bin/ld: warning: libicui18n.so.56, needed by /home/adi/Programe/Qt/5.8/gcc_64/lib/libQt5Core.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libicuuc.so.56, needed by /home/adi/Programe/Qt/5.8/gcc_64/lib/libQt5Core.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libicudata.so.56, needed by /home/adi/Programe/Qt/5.8/gcc_64/lib/libQt5Core.so, not found (try using -rpath or -rpath-link)
/home/adi/Programe/Qt/5.8/gcc_64/lib/libQt5Core.so: referinţă nedefinită către `ucal_clone_56'
/home/adi/Programe/Qt/5.8/gcc_64/lib/libQt5Core.so: referinţă nedefinită către `ucnv_close_56'
/home/adi/Programe/Qt/5.8/gcc_64/lib/libQt5Core.so: referinţă nedefinită către `ucol_setAttribute_56'
/home/adi/Programe/Qt/5.8/gcc_64/lib/libQt5Core.so: referinţă nedefinită către `ucnv_setSubstChars_56'
/home/adi/Programe/Qt/5.8/gcc_64/lib/libQt5Core.so: referinţă nedefinită către `ucal_close_56'
/home/adi/Programe/Qt/5.8/gcc_64/lib/libQt5Core.so: referinţă nedefinită către `ucal_openTimeZoneIDEnumeration_56'
/home/adi/Programe/Qt/5.8/gcc_64/lib/libQt5Core.so: referinţă nedefinită către `ucnv_fromUnicode_56'
/home/adi/Programe/Qt/5.8/gcc_64/lib/libQt5Core.so: referinţă nedefinită către `uenum_close_56'
/home/adi/Programe/Qt/5.8/gcc_64/lib/libQt5Core.so: referinţă nedefinită către `ucnv_getDefaultName_56'
/home/adi/Programe/Qt/5.8/gcc_64/lib/libQt5Core.so: referinţă nedefinită către `ucal_inDaylightTime_56'
/home/adi/Programe/Qt/5.8/gcc_64/lib/libQt5Core.so: referinţă nedefinită către `ucnv_compareNames_56'
/home/adi/Programe/Qt/5.8/gcc_64/lib/libQt5Core.so: referinţă nedefinită către `ucal_open_56'
/home/adi/Programe/Qt/5.8/gcc_64/lib/libQt5Core.so: referinţă nedefinită către `ucnv_getAlias_56'
/home/adi/Programe/Qt/5.8/gcc_64/lib/libQt5Core.so: referinţă nedefinită către `ucnv_countAvailable_56'
/home/adi/Programe/Qt/5.8/gcc_64/lib/libQt5Core.so: referinţă nedefinită către `u_strToLower_56'
/home/adi/Programe/Qt/5.8/gcc_64/lib/libQt5Core.so: referinţă nedefinită către `ucal_getDefaultTimeZone_56'
/home/adi/Programe/Qt/5.8/gcc_64/lib/libQt5Core.so: referinţă nedefinită către `ucal_openCountryTimeZones_56'
/home/adi/Programe/Qt/5.8/gcc_64/lib/libQt5Core.so: referinţă nedefinită către `ucal_getDSTSavings_56'
/home/adi/Programe/Qt/5.8/gcc_64/lib/libQt5Core.so: referinţă nedefinită către `ucol_close_56'
/home/adi/Programe/Qt/5.8/gcc_64/lib/libQt5Core.so: referinţă nedefinită către `ucal_openTimeZones_56'
/home/adi/Programe/Qt/5.8/gcc_64/lib/libQt5Core.so: referinţă nedefinită către `ucnv_getStandardName_56'
/home/adi/Programe/Qt/5.8/gcc_64/lib/libQt5Core.so: referinţă nedefinită către `ucnv_countAliases_56'
/home/adi/Programe/Qt/5.8/gcc_64/lib/libQt5Core.so: referinţă nedefinită către `ucol_open_56'
/home/adi/Programe/Qt/5.8/gcc_64/lib/libQt5Core.so: referinţă nedefinită către `ucnv_open_56'
/home/adi/Programe/Qt/5.8/gcc_64/lib/libQt5Core.so: referinţă nedefinită către `ucal_setMillis_56'
/home/adi/Programe/Qt/5.8/gcc_64/lib/libQt5Core.so: referinţă nedefinită către `ucal_get_56'
/home/adi/Programe/Qt/5.8/gcc_64/lib/libQt5Core.so: referinţă nedefinită către `uenum_next_56'
/home/adi/Programe/Qt/5.8/gcc_64/lib/libQt5Core.so: referinţă nedefinită către `ucnv_getMaxCharSize_56'
/home/adi/Programe/Qt/5.8/gcc_64/lib/libQt5Core.so: referinţă nedefinită către `ucol_strcoll_56'
/home/adi/Programe/Qt/5.8/gcc_64/lib/libQt5Core.so: referinţă nedefinită către `u_errorName_56'
/home/adi/Programe/Qt/5.8/gcc_64/lib/libQt5Core.so: referinţă nedefinită către `ucnv_getAvailableName_56'
/home/adi/Programe/Qt/5.8/gcc_64/lib/libQt5Core.so: referinţă nedefinită către `ucal_getTimeZoneDisplayName_56'
/home/adi/Programe/Qt/5.8/gcc_64/lib/libQt5Core.so: referinţă nedefinită către `u_strToUpper_56'
/home/adi/Programe/Qt/5.8/gcc_64/lib/libQt5Core.so: referinţă nedefinită către `ucnv_toUnicode_56'
/home/adi/Programe/Qt/5.8/gcc_64/lib/libQt5Core.so: referinţă nedefinită către `ucol_getSortKey_56'` 

referinţă nedefinită către = undefined reference to

Same goes for Qt 5.9.1, while my other local projects build normally.
Any ideeas?  
I can't remember if I set different from my last time I worked on the project as I worked on it in a VM and deleted that VM last week.

**Comment by probonopd** [comment]
We are building on Travis CI, please see the scripts invoked by
https://github.com/probonopd/linuxdeployqt/blob/master/.travis.yml

**Comment by vadrian89** [comment]
Oh ok, thank you for clearing out to me.
