### ISSUE TITLE
Improve "{.png,.svg,.svgz,.xpm} not present but defined in desktop file" error message

### ISSUE THREAD

**Issue by TheAssassin** [probonopd/linuxdeployqt#172]
Example: https://travis-ci.org/AppImage/AppImageUpdate/builds/294313776#L2139

I put icons into `usr/share/icons/hicolor`, but linuxdeployqt ignored their existence and showed this error. The fix was to put them into a subdirectory like `usr/share/icons/hicolor/128x128`, and although those files are just stubs and don't have that resolution etc., the call worked just fine.

We should change the behavior here so that linuxdeployqt considers icons within the entire `usr/share/icons` directory.

**Comment by probonopd** [comment]
The behavior is acually correct, https://github.com/AppImage/AppImageKit/issues/258#issuecomment-271186247

Some desktops (such as KDE Plasma) will only show icons if they are in a subdirectory for a defined image size. If we would allow icons in other places, then they would not show up in those desktops.

**Comment by TheAssassin** [comment]
But what does this have to do with the build itself, where the icon is copied to the AppDir root anyway? I don't think enforcing this standard does make too much sense, the constraints mentioned in the other comment aren't verified/applied anyway.

linuxdeployqt could also just show a warning to help the user debug these issues, i.e., look for the icon in the directory, and either show a warning to the user or fix the issue itself.

**Comment by jamthejame** [comment]
Hello Guys,
Pardon for cutting in, but it seems that i'm having something of a similar problem.  Tried to appimage Spotify (as i believe AppImage is the future when it comes to mobility and international business operations), however, seemed to follow guidance of GibHut chats and solution to get to the following:

[Desktop Entry]
Name=Spotify
GenericName=Music Player
Comment=Spotify streaming music client
Icon=spotify-client
Exec=spotify %U
TryExec=spotify
Terminal=false
Type=Application
Categories=Audio;Music;Player;AudioVideo;
MimeType=x-scheme-handler/spotify;

rtook@rtook-X553MA:~$ sudo ./appimagetool-x86_64.AppImage -v /home/rtook/Spotify.AppDir
Desktop file: /home/rtook/Spotify.AppDir/spotify.desktop
Name: Spotify
Icon: spotify-client
Exec: spotify %U
Comment: Spotify streaming music client
Type: Application
Categories: Audio;Music;Player;AudioVideo;
/home/rtook/Spotify.AppDir/usr/bin/spotify used for determining architecture x86_64
End of checks
/home/rtook/Spotify.AppDir/usr/share/spotify/spotify used for determining architecture x86_64
End of checks
Using architecture x86_64
App name for filename: Spotify
dest_path: Spotify-x86_64.AppImage
/home/rtook/Spotify.AppDir should be packaged as Spotify-x86_64.AppImage
spotify-client{.png,.svg,.svgz,.xpm} not present but defined in desktop file

This "not present but defined in desktop file" has been an issue on every appimage i try to create. Any ideas or suggestions of what I might be doing wrong?  

FYI: move the spotify-client icon to the executable without .png extension.

**Comment by TheAssassin** [comment]
Please join our IRC channel, where this is way easier to discuss. #AppImage on Freenode.

**Comment by probonopd** [comment]
A 256x256 pixel icon needs to be placed, e.g., in 

```
Spotify.AppDir/usr/share/icons/hicolor/256x256/apps/spotify-client.png
```

**Comment by probonopd** [comment]
The error message should say something to this regard.

**Comment by probonopd** [comment]
As per https://github.com/AppImage/AppImageKit/commit/49d4934fbccf20fd9ee6dfcf51cbf89da2247442 it now says

```
/home/ubuntu/workspace/appimagetool.AppDir should be packaged as appimagetool-x86_64.AppImage
appimagetool{.png,.svg,.svgz,.xpm} defined in desktop file but not found
For example, you could put a 256x256 pixel png into
/home/ubuntu/workspace/appimagetool.AppDir/usr/share/icons/hicolor/256x256/apps/appimagetool.png
```

**Comment by jamthejame** [comment]
So i followed your instructions: new build and created directory with 256x256 pixel png as stated in the e.g above... however, still the same issue using appimagetool, Please Advise:

rtook@rtook-X553MA:~$ sudo ./appimagetool-x86_64.AppImage -v ~/spotify
Desktop file: /home/rtook/spotify/spotify.desktop
Name: Spotify
Icon: spotify-client
Exec: spotify %U
Comment: Spotify streaming music client
Type: Application
Categories: Audio;Music;Player;AudioVideo;
/home/rtook/spotify/usr/bin/spotify used for determining architecture x86_64
End of checks
/home/rtook/spotify/usr/share/spotify/spotify used for determining architecture x86_64
End of checks
Using architecture x86_64
App name for filename: Spotify
dest_path: Spotify-x86_64.AppImage
/home/rtook/spotify should be packaged as Spotify-x86_64.AppImage
spotify-client{.png,.svg,.svgz,.xpm} not present but defined in desktop file

**Comment by probonopd** [comment]
@jamthejame please ask Spotify to provide an official AppImage for download. We are happy to help Spotify developers do this.

**Comment by jamthejame** [comment]
Simon,

This is not about Spotify developers, this is about the company being able
to use your product on linux application.  Spotify was merely a test, just
like audacity before.  We're looking to find the simplest way to build
appimage using appimagetools, so even linux novice would be able to get it
done on the simple products.  I'm more interested in finding out the true
issue, that if you're open to helping me do it, as you are the master of
AppImage.

**Comment by TheAssassin** [comment]
@jamthejame you're not making it very easy for us to help you either. We can't see the structure of your AppDir, we just get some extracts from the logs which you found useful. Your question lacks a _lot_ of information. Ideally, you'd provide your build script, maybe a link to your repository (or a zip without binaries as you're apparently aiming for packaging proprietary apps), the full build logs, all your file contents etc. etc. etc.

To be able to interactively request the information we need, I invited you to IRC. As you left so quickly last time, are afk at the moment, and wrote to me in private chat, I guess you're new to it, so I'd recommend you to read this first: https://workaround.org/getting-help-on-irc/

Of course we'll help you if we can.
