### ISSUE TITLE
--appimage-version does not show commit

### ISSUE THREAD

**Issue by probonopd** [probonopd/linuxdeployqt#174]
Bad:

```
me@host:~$ Downloads/linuxdeployqt-continuous-x86_64.AppImage --appimage-version
Version: continuous
```

Good:

```
me@host:~$ Downloads/appimagetool-x86_64.AppImage --appimage-version
Version: continuous-127-g45fbe3e
```

In `appimagetool` we use `-DVERSION_NUMBER=\"$(git describe --tags --always --abbrev=7)\"`. Need to do this here as well but I don't know where to start, since we have no `build.sh` bash script where I could do this manually.

**Comment by probonopd** [comment]
I have to admit that since @Skycoder42's reshuffling I don't find things anymore. Maybe you can help?

**Comment by probonopd** [comment]
Also @TheAssassin could you implement something like here
https://github.com/AppImage/AppImageUpdate/blob/2a677f00a7812f428ee19df7558b31b2391dcaed/src/main.cpp#L16-L17
for `linuxdeployqt` as well?

**Comment by Skycoder42** [comment]
@probonopd Everything regarding sources should be in the `tools/linuxdeployqt` folder. The version settings, as well as global configuration can be found in `.qmake.conf` (on root level). The compiled in version is set by the `MODULE_VERSION` qmake variable.

That version number is currently not used in the sources, as it seems. One could add `DEFINES += "MODULE_VERSION=\\\"$$MODULE_VERSION\\\""` to the pro file to make it available in c++. Not shure how to set the appimage version though.
