### ISSUE TITLE
Failure to generate zsync file

### ISSUE THREAD

**Issue by sithlord48** [probonopd/linuxdeployqt#177]
no zsync files are being created when run thru travis.
one project i have installed zsync (as pre TheAssassin's advice) . still not getting a *.AppImage.zsync file. 
another project (atcore) that did have zsync file on previous releases is now missing it from current.  
 
https://github.com/sithlord48/blackchocobo/releases/tag/continuous
https://github.com/sithlord48/atcore/releases/tag/continuous

**Comment by probonopd** [comment]
Possibly solved by https://github.com/probonopd/linuxdeployqt/commit/5b4339a0f65cca4a168d52036921a30716cfcd47

**Comment by probonopd** [comment]
Please retry and let us know whether this can be closed now.

**Comment by probonopd** [comment]
zsync file is now available in the above location, so closing.
