### ISSUE TITLE
Why use patchelf and not objcopy from binutils?

### ISSUE THREAD

**Issue by gyunaev** [probonopd/linuxdeployqt#192]
Objcopy is standard tool to modify ELF.

**Comment by probonopd** [comment]
Can it insert rpaths into libraries that had none before? Or reorder segments to make space for longer strings?

**Comment by gyunaev** [comment]
It can create sections in a file via --add-section and I don't see any restrictions on string lenghts in its man page. I used it for my projects a few years ago (also section patching) and it worked well.

**Comment by TheAssassin** [comment]
@gyunaev this is not (only) about patching ELF sections, but more importantly, patching the rpath, as @probonopd said. As long as objcopy can't perform this action, it won't be an option.

Also, I don't see a point in using another tool just for the sake of it. The tool is bundled in appimagetool's AppImage anyway. And, as we found recently, there are distributions that don't ship objcopy by default.
