### ISSUE TITLE
Sometimes bundles the wrong Qt

### ISSUE THREAD

**Issue by probonopd** [probonopd/linuxdeployqt#2]
When I build an application in Qt Creator, then it has its rpath point to the Qt directory that came with Qt Creator, and that was used for compiling the application.

linuxdeployqt should use that location as the source location when bundling libraries, but it doesn't and bundles Qt from the host system instead, which is guaranteed to break due to version mismatches. Possibly related to #1.

When building an app using Qt Creator, it looks like this:

```
ldd /home/me/build-untitled3-Desktop_Qt_5_7_0_GCC_64bit-Debug/untitled3
	linux-vdso.so.1 =>  (0x00007fff61bef000)
	libQt5Widgets.so.5 => /tmp/.mount_QtCreator-5.7.0-x86_64/5.7/gcc_64/lib/libQt5Widgets.so.5 (0x00007f7f27dcf000)
	libQt5Core.so.5 => /tmp/.mount_QtCreator-5.7.0-x86_64/5.7/gcc_64/lib/libQt5Core.so.5 (0x00007f7f276b4000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f7f27319000)
...
```
linuxdeployqt currently wrongly tries to bundle the system Qt from the rpath (`/usr/lib` rather than the one in `/tmp/.mount_QtCreator-5.7.0-x86_64/5.7/gcc_64` from the example above):

```
Log: Deploying plugins from "/usr/lib/plugins"
ERROR: file copy failed from "/usr/lib/plugins/platforms/libqxcb.so"
ERROR:  to "/home/me/build-untitled3-Desktop_Qt_5_7_0_GCC_64bit-Debug/plugins/platforms/libqxcb.so"
ERROR: file copy failed from "/usr/lib/plugins/printsupport/libcupsprintersupport.so"
ERROR:  to "/home/me/build-untitled3-Desktop_Qt_5_7_0_GCC_64bit-Debug/plugins/printsupport/libcupsprintersupport.so"
Log: Created configuration file: "/home/me/build-untitled3-Desktop_Qt_5_7_0_GCC_64bit-Debug/qt.conf"
```
After running linuxdeployqt it looks like this
```
ldd /home/me/build-untitled3-Desktop_Qt_5_7_0_GCC_64bit-Debug/untitled3/home/me/build-untitled3-Desktop_Qt_5_7_0_GCC_64bit-Debug/untitled3: /home/me/build-untitled3-Desktop_Qt_5_7_0_GCC_64bit-Debug/lib/libQt5Core.so.5: version `Qt_5.7' not found (required by /home/me/build-untitled3-Desktop_Qt_5_7_0_GCC_64bit-Debug/untitled3)
/home/me/build-untitled3-Desktop_Qt_5_7_0_GCC_64bit-Debug/untitled3: /home/me/build-untitled3-Desktop_Qt_5_7_0_GCC_64bit-Debug/lib/libQt5Core.so.5: version `Qt_5' not found (required by /home/me/build-untitled3-Desktop_Qt_5_7_0_GCC_64bit-Debug/untitled3)
/home/me/build-untitled3-Desktop_Qt_5_7_0_GCC_64bit-Debug/untitled3: /home/me/build-untitled3-Desktop_Qt_5_7_0_GCC_64bit-Debug/lib/libQt5Widgets.so.5: version `Qt_5' not found (required by /home/me/build-untitled3-Desktop_Qt_5_7_0_GCC_64bit-Debug/untitled3)
	linux-vdso.so.1 =>  (0x00007ffd7effc000)
	libQt5Widgets.so.5 => /home/me/build-untitled3-Desktop_Qt_5_7_0_GCC_64bit-Debug/lib/libQt5Widgets.so.5 (0x00007f78b8681000)
	libQt5Core.so.5 => /home/me/build-untitled3-Desktop_Qt_5_7_0_GCC_64bit-Debug/lib/libQt5Core.so.5 (0x00007f78b8176000)
	libstdc++.so.6 => /home/me/build-untitled3-Desktop_Qt_5_7_0_GCC_64bit-Debug/lib/libstdc++.so.6 (0x00007f78b7db3000)
```
Which means that the wrong Qt libraries have been copied to the bundle location...

**Comment by probonopd** [comment]
If we find no better solution, we could do like https://github.com/aurelien-rainone/macdeployqtfix and ask the user to provide the "path of Qt libraries used to build the Qt application". However I think this is not elegant and the original macdeployqt doesn't need it.

**Comment by probonopd** [comment]
qtPath _sometimes_ contains the correct value...

**Comment by probonopd** [comment]
In 4c0da30 it seems to be working... for the moment...

**Comment by Larpon** [comment]
To me it seems unreliable to let variables lay the foundation of any sane way of collecting correct path info. Variables can be, and often are, tangled with in very unpredictable maners. On top they are user-space which mean anyone or anything can change them whenever see fit. The most reliable and 'portable' way so far, as I see it, is still the output from `ldd`? You could have a dependency resolver (class or function) with a simple interface that underneath have implementations for using `ldd` or the `ld.so.conf` approach as you describe [here](https://github.com/probonopd/linuxdeployqt/issues/24#issue-178921340) - or whatever may come up in the future.

**Comment by probonopd** [comment]
As was suggested on the Qt mailing list, we need to replace the `ldd` calls with our own implementation. Pull requests welcome :-)

**Comment by Larpon** [comment]
I'm not currently on the list - can you point me to the [thread](http://lists.qt-project.org/pipermail/development/)?

**Comment by probonopd** [comment]
http://lists.qt-project.org/pipermail/development/2016-September/thread.html#27180

**Comment by Larpon** [comment]
Ouch I can see now why `ldd` is not a winner :)

**Comment by probonopd** [comment]
__Do not rely on information from from QLibraryInfo::__ since it points to the Qt used by the linuxdeployqt executable, which, if it is inside an AppImage, comes with its own bundled Qt defined in its `qt.conf`. Rather we should use the Qt in `/tmp/.mount_QtCreator-5.7.0-x86_64/5.7/gcc_64` from the example above.

Using `QLibraryInfo::` currently results in 

```
Log: Deploying QML imports 
Log: Application QML file search path(s) is ("/home/me/qakexamples/qakexamplesapp/qml")
Log: Looking for qmlimportscanner at "/tmp/.mount_2aFvEE/bin/qmlimportscanner"
Log: Fallback, looking for qmlimportscanner at "/tmp/.mount_2aFvEE/qmlimportscanner"
ERROR: Valid qmlImportsPath not found at "/tmp/.mount_2aFvEE/qml"
ERROR: Possibly your Qt library has the wrong information in qt_prfxpath, e.g., because it was moved since it was compiled
```
due to this.

I don't know how to get the path to the correct Qt reliably; it might be necessary for the user to pass it in as an argument.

**Comment by probonopd** [comment]
windeployqt says:
```
The simplest way to use windeployqt is to add the bin directory of your Qt
installation (e.g. <QT_DIR\bin>) to the PATH variable and then run:
  windeployqt <path-to-app-binary>
```

So we could also do that; check for qmake and assume that the Qt to be used is next to it.

**Comment by probonopd** [comment]
Implemented. Make sure you export the PATH to the Qt you want to bundle, so that `qmake -v` shows the correct Qt to be bundled.
