### ISSUE TITLE
deploying widget application return translation error

### ISSUE THREAD

**Issue by robosina** [probonopd/linuxdeployqt#205]
Hi, If I write a program using Qt widget and want to deploy it, I get below errors

    4bit-Release/deploy2 
    Not using FHS-like mode
    app-binary: "/home/saeed/qtProject/build-deploy2-Desktop_Qt_5_9_3_GCC_64bit-Release/deploy2"
    appDirPath: "/home/saeed/qtProject/build-deploy2-Desktop_Qt_5_9_3_GCC_64bit-Release"
    relativeBinPath: "deploy2"
    WARNING: "/home/saeed/qtProject/build-deploy2-Desktop_Qt_5_9_3_GCC_64bit-Release/qt.conf" already exists, will not overwrite.
    ERROR: lconvert not found at "/tmp/.mount_linuxd883Yfw/usr/bin/lconvert"
    ERROR: Failed to copy translations

are these translations is important?

**Comment by TheAssassin** [comment]
Well, if your program lacks translations, that shouldn't lead to an error. This looks like a bug, yes.

**Comment by probonopd** [comment]
Which Qt (downloaded from where) are you using? And does it contain `lconvert`?

**Comment by TheAssassin** [comment]
@probonopd:

```
ERROR: lconvert not found at "/tmp/.mount_linuxd883Yfw/usr/bin/lconvert"
```

It looks like linuxdeployqt is trying to use an `lconvert` from the mounted linuxdeployqt AppImage. Do we copy `lconvert` from the system Qt installation into the AppImage on Travis?

**Comment by probonopd** [comment]
No...

@robosina can you please link to/share the script you are using which calls `linuxdeployqt`?

**Comment by TheAssassin** [comment]
In that case, we should add a check beforehand to ensure a valid Qt installation is available that contains the tools.

**Comment by probonopd** [comment]
Yes, I _thought_ we had this but apparently it's at least not working in all cases...

**Comment by TheAssassin** [comment]
Also, there's a second bug, it shouldn't just try to call that path although it doesn't exist.

**Comment by probonopd** [comment]
True, although I don't understand yet why it is doing this. Logfile and more information needed.

**Comment by TheAssassin** [comment]
Could it be that the Qt function which searches for the path of a yet-to-be-called binary just returns *some* path in case the binary doesn't exist elsewhere? Do we even use it?

**Comment by robosina** [comment]
I haven't any translation file or something else, it is a simple widget , so I use -no-translations option, anyway after copy files to second linux it seems that program doesn't work

**Comment by robosina** [comment]
I paste output of below command to paste ubuntu you can access to it [via this link](https://paste.ubuntu.com/26315402/)

./linuxdeployqt-continuous-x86_64.AppImage /home/saeed/qtProject/build-deploy2-Desktop_Qt_5_9_3_GCC_64bit-Release/deploy2 -verbose=2

**Comment by probonopd** [comment]
According to the line `Log: Using qmake:  "/usr/bin/qmake"` you are using a system-provided qmake. What happens if you build on Ubuntu 14.04 (trusty) with https://launchpad.net/~beineri/+archive/ubuntu/opt-qt592-trusty?

**Comment by robosina** [comment]
@probonopd 
I copy `qmake` from qt library to `/usr/lib/x86_64-linux-gnu/qt5/bin`

and it seems that everything is OK now and I don't see that error

**Comment by robosina** [comment]
I download AppImage via [this](https://github.com/probonopd/linuxdeployqt/releases) link

**Comment by probonopd** [comment]
This is the linuxdeployqt AppImage. I was referring to the AppImage or AppDir of the application you are deploying, so that we can test it. Thank you.

**Comment by robosina** [comment]
It's easy and template widget for qt widget application (I didn't wrote any line code in my application for that)

**Comment by probonopd** [comment]
OK, so you think we can close this ticket?

**Comment by robosina** [comment]
Yeah, I guess this error happend because of my fault.

**Comment by JackLau1222** [comment]
Hi, I encouter the same prblem when i try to deploy my qt project with translation file.
There are details(-verbose=2):
```Shell
WARNING: "/OpenConverter/src/build/qt.conf" already exists, will not overwrite.
Log: Using "/OpenConverter/src/build/translations" as translations directory for App
Log: Using "/usr/share/qt5/translations"  to search for Qt translations
ERROR: lconvert not found at "/linuxdeployqt/bin/lconvert"
ERROR: Failed to copy translations
Log: "appimagetool -v '/OpenConverter/src/build' -n -g"
fuse: device not found, try 'modprobe fuse' first

Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
open dir error: No such file or directory
Log: ret 32512
Log: WEXITSTATUS(ret) 127
```
It seems lack lconvert tools, i manually compile the linuxdeployqt in my computer and there are no this tool in output product.

**Comment by probonopd** [comment]
Do you have `/dev/fuse`?
Or are you running on something like Docker? (Then you need to set `APPIMAGE_EXTRACT_AND_RUN=1`.)
All of which should be obvious from looking at 

```
Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
```

I am genuinely wondering how we could write this message so that people actually understand it. Any hints appreciated. Thanks!

**Comment by JackLau1222** [comment]
You're right, i'm running this on docker environment.
But i don't actually understanding how to set `APPIMAGE_EXTRACT_AND_RUN=1`
i try to set it in env like this, but it still doesn't work:
```Shell
root@afd8d78d1689:/linuxdeployqt/bin# export APPIMAGE_EXTRACT_AND_RUN=1
root@afd8d78d1689:/linuxdeployqt/bin# ./linuxdeployqt /OpenConverter/src/build/OpenConverter -appimage           
linuxdeployqt 10 (commit 0448055), build <local dev build> built on 2025-01-07 04:09:24 UTC
Not using FHS-like mode
app-binary: "/OpenConverter/src/build/OpenConverter"
appDirPath: "/OpenConverter/src/build"
relativeBinPath: "OpenConverter"
Keeping existing AppRun
qmakePath 3= ""
WARNING: "/OpenConverter/src/build/qt.conf" already exists, will not overwrite.
ERROR: lconvert not found at "/linuxdeployqt/bin/lconvert"
ERROR: Failed to copy translations
appimagetool, continuous build (commit 5735cc5), build <local dev build> built on 2023-03-08 22:52:04 UTC
NOTE: Using the output of 'git rev-parse --short HEAD' as the version:
      0448055
      Please set the $VERSION environment variable if this is not intended
Desktop file: /OpenConverter/src/build/default.desktop
Categories entry not found in desktop file
.desktop file is missing a Categories= key
root@afd8d78d1689:/linuxdeployqt/bin# ./linuxdeployqt /OpenConverter/src/build/OpenConverter -appimage --verbose=2
linuxdeployqt 10 (commit 0448055), build <local dev build> built on 2025-01-07 04:09:24 UTC
ERROR: Error: arguments must not start with --, only -: "--verbose=2" 
```
May you tell me more details about this, please?
