### ISSUE TITLE
linuxdeployqt doesn't add other libraries like opencv

### ISSUE THREAD

**Issue by robosina** [probonopd/linuxdeployqt#206]
Hello,
I'm using qt for image processing stuff so I use `opencv` in my projects, when I write a program without using opencv the `linuxdeployqt` deploy my program correctly but when I use `opencv` library it seems that the program can't add opencv library to binary directory and program doesn't work!!
how we could use `linuxdeployqt` when we use opencv library with qt (the library I need is opencv_core.3.3.so!! is there a way to add it manually? )

**Comment by TheAssassin** [comment]
You are not providing very much information (like, what project, how do you call linuxdeployqt, etc.). My only guess would be that you didn't call it with `-bundle-non-qt-libs`.

**Comment by probonopd** [comment]
Did you use the `-bundle-non-qt-libs` option?
Also, please run

`ldd path/to/your/application`

Does it show opencv? Please paste the output here.
