### ISSUE TITLE
Please provide some version information

### ISSUE THREAD

**Issue by KurtPfeifle** [probonopd/linuxdeployqt#210]
Just like (almost) all of the other tools provided by the developers of the AppImage suite of tools (which are strongly recommended by them for 3rd party developers to prepare their software for shipment) *`linuxdeployqt`* should also support a flag to retrieve version information. For completeness and consistency, all the following should be supported:

    ./linuxdeployqt -V
    ./linuxdeployqt -version
    ./linuxdeployqt --version

---- 

Oh, and once it does, it should of course also report this option in its short usage info screen (i.e. when called without any arguments).

**Comment by probonopd** [comment]
I second this. @TheAssassin since you have experience with fancy version statements, may I ask you to port this over here as well? Thanks.

**Comment by TheAssassin** [comment]
> ./linuxdeployqt --version

Not sure whether that can be supported by the Qt argument parser. But as all the other parameters are prefixed with a single dash, too, I don't think that'd be a blocker.

I would go a step further and always print a version statement.

**Comment by probonopd** [comment]
> I would go a step further and always print a version statement.

Agree!

**Comment by TheAssassin** [comment]
Working on a patch. After merging my alternative CMake build configuration, I copied the code and adjusted it a bit from AppImageUpdate's code. However, I have to somehow call subprocesses from qmake to get this to work. I am not a Qt/qmake expert (haven't really used it before), so that might take a while.

**Comment by TheAssassin** [comment]
After hours of debugging and tinkering with qmake's weird syntax, I managed to get this to work properly. See #226. If the build goes well, I'll merge the PR, and close this issue.

**Comment by probonopd** [comment]
Thank you!
