### ISSUE TITLE
sqldrivers missing in AppiImage (travis) 

### ISSUE THREAD

**Issue by yschutz** [probonopd/linuxdeployqt#211]
Hello, 
I have build an AppImage of (https://github.com/yschutz/ThermusQt) with travis. 

At run time, the sqlite driver cannot be loaded: 

QSqlDatabase: QSQLITE driver not loaded

and no available drivers is found. 

In the AppImage these drivers are in usr/plugins/sqldrivers ... 

What did I do wrong ? Thanks for your assistance

Yves

**Comment by probonopd** [comment]
Hello and welcome to linuxdeployqt. I have answered in the other ticket, so let's continue there:  https://github.com/yschutz/ThermusQt/issues/3. Thanks.

**Comment by robert7** [comment]
I got here by google as I had similar problem "QSQLITE driver not loaded" after building AppImage with Travis CI ...

I then figured out the solution - in my case it was missing file `squashfs-root/usr/plugins/sqldrivers/libqsqlite.so` then found out, I need to add "libqt5sql5-sqlite" dependency package..  (weird that, if I build the same outside Travis CI, then it works also without the dependency)

so maybe it will help someone
