### ISSUE TITLE
Deploying app built against pre-compiled Qt version not working (uses system/apt version)

### ISSUE THREAD

**Issue by Larpon** [probonopd/linuxdeployqt#22]
Hi - thanks for this fantastic project

I've been trying to deploy an app that's dynamically linked to a Qt version (5.7) installed via the MaintenanceTool (from Qt Online Installer 2.0.3-2)

The system I'm building it on (Kubuntu 14.04) also happen to have an older version of Qt installed (Qt 5.2.1) via apt-get.

The application runs as expected outside the AppImage

The output from `ldd` on my executable correctly shows the path to the linked libQt5*.so files from the correct Qt 5.7 version

But the AppImage created by linuxdeployqt gives the following error after execution:

```
./dynappimg.AppImage: /tmp/.mount_l6DycG/lib/libQt5Qml.so.5: no version information available (required by ./dynappimg.AppImage)
./dynappimg.AppImage: /tmp/.mount_l6DycG/lib/libQt5Gui.so.5: no version information available (required by ./dynappimg.AppImage)
./dynappimg.AppImage: /tmp/.mount_l6DycG/lib/libQt5Quick.so.5: no version information available (required by ./dynappimg.AppImage)
./dynappimg.AppImage: /tmp/.mount_l6DycG/lib/libQt5Network.so.5: no version information available (required by ./dynappimg.AppImage)
./dynappimg.AppImage: /tmp/.mount_l6DycG/lib/libQt5Core.so.5: no version information available (required by ./dynappimg.AppImage)
./dynappimg.AppImage: /tmp/.mount_l6DycG/lib/libQt5Core.so.5: no version information available (required by ./dynappimg.AppImage)
./dynappimg.AppImage: relocation error: ./dynappimg.AppImage: symbol qt_version_tag, version Qt_5.7 not defined in file libQt5Core.so.5 with link time reference
```

After some guesswork I manually tried copying in the installed Qt 5.7 libraries to the generated AppDir/lib directory and ran AppImageAssistant again:

```
./dynappimg.AppImage: error while loading shared libraries: libicui18n.so.56: cannot open shared object file: No such file or directory
```

Copied more libs from the Qt5.7 installation to /lib which led me to:

```
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Reinstalling the application may fix this problem.
Aborted (core dumped)
```

Copied in libqxcb.so to the `platforms` folder (this was empty in the AppDir?)

Finally I got around to:

```
QQmlApplicationEngine failed to load component
qrc:///main.qml:66 Type Core unavailable
qrc:///qml/Core.qml:4 plugin cannot be loaded for module "QtMultimedia": Cannot load library /tmp/.mount_ByHBdg/qml/QtMultimedia/libdeclarative_multimedia.so: (/tmp/.mount_ByHBdg/qml/QtMultimedia/libdeclarative_multimedia.so: symbol _ZTI23QDeclarativeVideoOutput, version Qt_5_PRIVATE_API not defined in file libQt5MultimediaQuick_p.so.5 with link time reference)
```

Did some more copying from the 5.7 install - and finally the AppImage ran.
I'm pasting the above snippets to let future googlers find this :)

Anyway it looks like linuxdeployqt can't handle, or at least, misinterpret the output from `ldd` when linked .so files is not the system / apt version?

I've tried passing various locations to linuxdeployqt `-libpath` parameter with no luck:

```
/path/to/Qt/5.7/gcc_64/
```

and

```
/path/to/Qt/5.7/gcc_64/lib/
```

I'll be glad to provide some more info if need be

**Comment by Larpon** [comment]
I think this is very much the same problem as #2 ?

**Comment by probonopd** [comment]
Li @Larpon thanks for trying linuxdeployqt.

Yes, I think this is #2. Please try the following (replace `/tmp/.mount_QtCreator-5.7.0-x86_64/5.7/` with the path where you installed Qt with the installer):

```
export QT_PLUGIN_PATH=/tmp/.mount_QtCreator-5.7.0-x86_64/5.7/gcc_64/plugins/
export LD_LIBRARY_PATH=/tmp/.mount_QtCreator-5.7.0-x86_64/5.7/gcc_64/lib/
export QTDIR=/tmp/.mount_QtCreator-5.7.0-x86_64/5.7/gcc_64 # not needed?
```
prior to running linuxdeployqt. It should then bundle the correct Qt.
After the AppImage has been created, unset the variables again:

```
unset QT_PLUGIN_PATH
unset LD_LIBRARY_PATH
unset QTDIR
```

Does it work for you this way?

**Comment by Larpon** [comment]
I tried building it again with your variables sat.

On first try I got:
```
QQmlApplicationEngine failed to load component
qrc:///main.qml:66 Type Core unavailable
qrc:///qml/Core.qml:4 plugin cannot be loaded for module "QtMultimedia": Cannot load library /tmp/.mount_IFgZLg/qml/QtMultimedia/libdeclarative_multimedia.so: (/tmp/.mount_IFgZLg/qml/QtMultimedia/libdeclarative_multimedia.so: symbol _ZTI23QDeclarativeVideoOutput, version Qt_5_PRIVATE_API not defined in file libQt5MultimediaQuick_p.so.5 with link time reference)
```
... major improvement from when I reported the bug :)
copying in `libQt5MultimediaQuick_p.so.5` and re-building with AppImageAssistant gave me:
```
QQmlApplicationEngine failed to load component
qrc:///main.qml:66 Type Core unavailable
qrc:///qml/Core.qml:4 plugin cannot be loaded for module "QtMultimedia": Cannot load library /tmp/.mount_677yfX/qml/QtMultimedia/libdeclarative_multimedia.so: (/tmp/.mount_677yfX/qml/QtMultimedia/libdeclarative_multimedia.so: symbol _ZN20QAbstractVideoFilter16staticMetaObjectE, version Qt_5 not defined in file libQt5Multimedia.so.5 with link time reference)
```
Then copying in `libQt5MultimediaQuick.so.5` and re-building with AppImageAssistant gave me:
```
defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.mediaplayer"
defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.mediaplayer"
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior 2, swapInterval 1, profile  0) 
Aborted (core dumped)
```
Which made me give up - all these errors hint that it's not the correct files :)

**On a side note**
I've tried using `linuxdeployqt` on my other Kubuntu 16.04 development machine (not to be confused with the 14.04 build machine) - this has both 5.6 AND 5.7 installed from Qt Online Installer (I'm trying to make an AppImage of a 5.6 build):
```
QQmlApplicationEngine failed to load component
qrc:///main.qml:1 plugin cannot be loaded for module "QtQuick": The plugin '/tmp/.mount_S0BZ6w/qml/QtQuick.2/libqtquick2plugin.so' uses incompatible Qt library. (5.7.0) [release]
```
This indicates that it's mixing the versions :) (I've double checked that it's my 5.6 build I'm trying to make an AppImage from)

This was using your variable exports from above - so it's both progress and then not :)

**Comment by probonopd** [comment]
Can you tell me which app you are trying to bundle so that I can reproduce?

**Comment by Larpon** [comment]
It's unfortunately a commercial project - but I can provide you with the verbose output from linuxdeployqt?

**Comment by probonopd** [comment]
@Larpon that would help a lot. Especially Qml hasn't been tested so far in practice.

**Comment by Larpon** [comment]
I believe the attached example should behave much the same (maybe except for any QtMultimedia issues as I don't remember it being used) - it's an example app for a "QML Aid Kit" I'll be opensourcing sometime soon anyway - structure of the project is fairly Qt-ish.

If it doesn't work for some reason I think you can get the basic idea of what's wrong anyway just by:
1. Download http://download.qt.io/official_releases/online_installers/qt-unified-linux-x64-online.run
2. Install Qt Creator and Desktop (gcc) versions of 5.6 and/or 5.7 to some custom location ex. `/home/user/env/Qt/`
3. Use downloaded Qt Creator and create a new project from the wizard:
![image](https://cloud.githubusercontent.com/assets/768942/18815209/b9507956-8329-11e6-80f7-b1de72d968a4.png)

Should give you an application that's dynamically linked partially to the newly installed Qt version libraries and the rest should be system libraries - a classic Qt Creator project :)

[qakexamples.tar.gz](https://github.com/probonopd/linuxdeployqt/files/491634/qakexamples.tar.gz)

On a side note I think "[tiled](https://github.com/bjorn/tiled)" also might be a good candidate for testing out AppImages - if you don't know it already. It builds out of the box with the Online installers as well - at least on my setup.

**Comment by probonopd** [comment]
> Should give you an application that's dynamically linked partially to the newly installed Qt version libraries and the rest should be system libraries - a classic Qt Creator project :)

That's guaranteed to fail. All of Qt must come from the system or from the newly installed Qt version but you cannot mix and match... anyhow, let me test it.

**Comment by probonopd** [comment]
I get this when Qt Creator tries to launch the app, before any linuxdeployqt is run:

```
Starting /home/me/Downloads/build-qakexamples-Desktop_Qt_5_7_0_GCC_64bit-Debug/qakexamplesapp/qakexamplesapp...
QML debugging is enabled. Only use this in a safe environment.
QQmlApplicationEngine failed to load component
qrc:///main.qml:2 module "QtQuick.Controls" is not installed
qrc:///main.qml:1 module "QtQuick" is not installed
qrc:///main.qml:2 module "QtQuick.Controls" is not installed
qrc:///main.qml:1 module "QtQuick" is not installed
```

**Comment by Larpon** [comment]
Correct. The application will only be linked to a specific Qt version - not
a mix of ex. 5.6 and 5.7. I meant a mix of Qt libs and system libraries -
libpng, for example, will be your system version :)

**Comment by Larpon** [comment]
Hmm.. Regrading your error have you installed the correct components? Can you compile and run an fresh/new QtQuick application? If you can't then there's something wrong with the install - it's pretty picky if you interfere manually with the directory structure and such - so a reinstall might be in place. Usually the Maintenance Tool will give you a hint

**Comment by Larpon** [comment]
If the app doesn't run outside your AppImage it won't run inside either I'd say. So if you can get any QtQuick/QML based application running outside first - that should be a perfect starting point

**Comment by probonopd** [comment]
Yes, I need to investigate that first.

**Comment by Larpon** [comment]
I've spend a little time on making a project that solve this problem:
https://github.com/Larpon/linuxdeployqt.py
It's `ldd` all the way but seems pretty robust on my setup so far

**Comment by Larpon** [comment]
- not the problem you have with your install though :/

**Comment by probonopd** [comment]
Cool. But hey, why make another one and not contribute here? (I am also more a Python guy and this is my first Qt project...)

**Comment by Larpon** [comment]
I'll gladly contribute here. It looked a bit cumbersome to implement in Qt/C++ at first glance and I needed it to build and release my games faster - so I went the python way :) I'll gladly put some of the efforts and lessons learned into this project.

I've written a couple of games with Qt but it's mostly done in QML + javascript to keep things simpler for me - so my C++ skills are rusty.

Does the tool have to be in Qt/C++? (a thing I was in doubt about when looking around here)

**Comment by probonopd** [comment]
> Does the tool have to be in Qt/C++?

Yes, if we want to have it become a part of Qt some day... also I assume it is the language most Qt developers are most familiar with :-)

**Comment by Larpon** [comment]
Fair enough I guess :)

**Comment by probonopd** [comment]
I can now create QtQuick applications thanks to https://github.com/probonopd/AppImages/commit/e48b49ad99098a0ab653aedc759f0dfcb144e0d3; turns out my QtCreator AppImage was subtly broken because it had the wrong  qt_prfxpath hardcoded in libQt5Core.

**Comment by probonopd** [comment]
It is now possible to bundle qakexamples:

```
wget https://github.com/probonopd/linuxdeployqt/files/491634/qakexamples.tar.gz
tar xf qakexamples.tar.gz

# Build qakexamples in Qt Creator

# Build linuxdeployqt in Qt Creator - do NOT use the readymade AppImage
# due to https://github.com/probonopd/linuxdeployqt/issues/2#issuecomment-252347654

/home/me/build-linuxdeployqt-Desktop_Qt_5_7_0_GCC_64bit-Debug/linuxdeployqt/linuxdeployqt /home/me/build-qakexamples-Desktop_Qt_5_7_0_GCC_64bit-Debug/qakexamplesapp/qakexamplesapp -qmldir=/home/me/qakexamples/qakexamplesapp/qml -verbose=3 -bundle-non-qt-libs -appimage

ls -lh /home/me/build-qakexamples-Desktop_Qt_5_7_0_GCC_64bit-Debug/qakexamplesapp.AppImage 
-rwxr-xr-x 1 me me 39M Oct  7 22:08 /home/me/build-qakexamples-Desktop_Qt_5_7_0_GCC_64bit-Debug/qakexamplesapp.AppImage

# qakexamplesapp.AppImage works!
```

**Comment by Larpon** [comment]
Good stuff!

**Comment by probonopd** [comment]
@Larpon is this still a concern with the latest git version?

**Comment by Larpon** [comment]
I've got this on my list - I'll check back when I get to check it

**Comment by probonopd** [comment]
@Larpon please let me know if this can be closed.

**Comment by Larpon** [comment]
I will - I've been a busy bee lately. I'm trying to kickstart a gamedev business from scratch so time is an issue atm. It's still on my list :) I'll do what I can to squeeze it in next week

**Comment by probonopd** [comment]
@Larpon please reopen if you think that the issue persists.

**Comment by Larpon** [comment]
@probonopd - I will. I've been on  other projects ever since so I haven't had a chance to reproduce it

**Comment by biswajitcsecu** [comment]
it is a time pass valueless site............fu!!

**Comment by probonopd** [comment]
Err... what?
