### ISSUE TITLE
No output on terminal and no files copied

### ISSUE THREAD

**Issue by AliOsm** [probonopd/linuxdeployqt#224]
When I download `linuxdeployqt-continuous-x86_64.AppImage` and run it from terminal:

`./linuxdeployqt-continuous-x86_64.AppImage XMinuteReminder`

It only make `AppRun` file and nothing more.

And when run `qmake --version`, the output:

```
QMake version 3.1
Using Qt version 5.9.1 in /usr/lib/x86_64-linux-gnu
```

But I'm using Qt version 5.10.0 and it is installed on `~/Programs/Qt`

Any help?

**Comment by TheAssassin** [comment]
Append `-verbose=3` (i.e., put it _after_ your directory parameter) and check the output.

**Comment by AliOsm** [comment]
@TheAssassin nothing changed, only `AppRun` file and no terminal outputs.

**Comment by TheAssassin** [comment]
Could you upload your AppDir, please?

**Comment by AliOsm** [comment]
It is here: https://github.com/AliOsm/XMinuteReminder

**Comment by TheAssassin** [comment]
Well, now I understand. You're using linuxdeployqt the wrong way.

linuxdeployqt won't compile and package your project. You have to compile the project, create a so-called AppDir, then run linuxdeployqt on a desktop file in said AppDir. Check out the example Travis script: https://github.com/probonopd/linuxdeployqt#using-linuxdeployqt-with-travis-ci

**Comment by AliOsm** [comment]
I have compiled the project and make an executable file then run `linuxdeployqt` on this file: `linuxdeployqt app-binary [options]`

**Comment by AliOsm** [comment]
Every thing work great now, thank you @TheAssassin :)

**Comment by TheAssassin** [comment]
You're welcome. If you have further questions, you should get on IRC. We're on Freenode, channel #appimage.
