### ISSUE TITLE
Set qt_prfxpath=.

### ISSUE THREAD

**Issue by probonopd** [probonopd/linuxdeployqt#23]
windeployqt unpatches (i.e. neuters) Qt's installation path in Qt5Core.dll.
So perhaps linuxdeployt could do the same, i.e. neuter the path to my Qt installation (e.g. change `prfxpath=/home/henry/Qt/5.7/gcc_64` to `prfxpath=.` in libQt5Core.so.

**Comment by Larpon** [comment]
From windeployqt patch:
https://codereview.qt-project.org/#/c/121731/4//ALL

**Comment by probonopd** [comment]
Thanks. Do I smell a pull request? ;-)

**Comment by Larpon** [comment]
Hehe I'm actually trying my luck at a recursive library locator ATM (using objdump, $LD_LIBRARY_PATH, DT_RPATH and DT_RUNPATH - the code is ugly and need some more care though :/

**Comment by probonopd** [comment]
In Qt? Cool!

**Comment by probonopd** [comment]
Watch out for [this](https://github.com/probonopd/linuxdeployqt/blob/7c2590e38791912bac804055bb67cc43c8f7f02c/shared/shared.cpp#L730).

**Comment by probonopd** [comment]
Might indeed help against "mysterious" errors in AppImages that are missing some Qt components and where the system falls back to loading system Qt instead, like

```
$ ./xdgurl-release-2.0.0-13-g2756f9b-x86-64.appimage asd
QQmlApplicationEngine failed to load component
qrc:/qml/main.qml:1 plugin cannot be loaded for module "QtQuick": Cannot load library /tmp/.mount_wrniMy/qml/QtQuick.2/libqtquick2plugin.so: (/usr/lib/x86_64-linux-gnu/libQt5Quick.so.5: version `Qt_5_PRIVATE_API' not found (required by /tmp/.mount_wrniMy/qml/QtQuick.2/libqtquick2plugin.so))
```

**Comment by Chaz6** [comment]
Normally I suggest DT_RUNPATH but for AppImage I think DT_RPATH is preferred, to prevent a custom LD_LIBRARY_PATH interfering. Alternatively it could use DT_RUNPATH with a mechanism to pass a custom LD_LIBRARY_PATH if that's what the user *really* wants to do, but for the normal case I don't think it is worth it.

**Comment by probonopd** [comment]
@Larpon are you still considering to send a PR on this?

**Comment by probonopd** [comment]
Closing this since it is a duplicate of https://github.com/probonopd/linuxdeployqt/issues/12

**Comment by Larpon** [comment]
I would love to if I had the time. So for the time being no, unfortunately not.
