### ISSUE TITLE
Sql plugin needs special treatment

### ISSUE THREAD

**Issue by vadrian89** [probonopd/linuxdeployqt#235]
The issue is that it deploys every Sql plugin which means:  
- postgresql-client needs to be installed  
- libmysqlclient needs to be installed   

The issue is not the installation, but the mysql plugin might need rebuilding because the libmysqlclient version on the system is different but this can lead to a lot of frustration because the multiple errors it can arise when using newer Qt versions on LTS distributions.  
As an example I went from forum to forum and after loosing some time searching for solutions just because the libqsqlmysql.so was built for libmysqlclient18 and Ubuntu 16.04.3 ships with libmysqlclient20.    
For this I had to:   

This info can be found on the Qt sql driver doc page     
- install libmysqlclient-dev package   

This after thorough search through multiple forums  

- qmake on qtbase   
- qmake on sqldrivers  

This again needed to be researched  

- make symbolic link: sudo ln -s /usr/lib/x86_64-linux-gnu/libmysqlclient.so /usr/lib/x86_64-linux-gnu/libmysqlclient_r.so   

And only then I could continue to build the correct mysql plugin.  
After I ran linuxdeployqt I found out that I also needed to install postrgresql-client package because of a missing library.   
All of the above were needed for my application which requires only SQLite.   

I am writing because I want to know your thoughts on how this can be done to improve the deployment process, as I can start working on it in my spare time(hopefully).

**Comment by TheAssassin** [comment]
Well, as a workaround, you could install both packages on your build system, and add a `rm -f appdir/usr/lib/...` line to delete the unnecessary MySQL and PostgreSQL libraries.

We've been reported problems related to the SQL libs a couple of times already. We're working on a conceptual fix.

**Comment by vadrian89** [comment]
The issue isn't deleting, the issue is the deployment.  
In my opinion, the sql plugin should be manually deployed, here is a possbile workflow:   

- find out the application requires sql plugins  
- search the extra-plugins list to see if a manual deployment is requested(search the list for anything which contains \"sqldrivers\/\*sql\*.so\"       
- if it exists, continue the workflow  
- if not, request the user a sql plugin or \"no\"

**Comment by TheAssassin** [comment]
My comment was meant to quickly fix your problem. 

linuxdeployqt has a couple of security issues due to its architecture, and we're discussing a refactoring or rewrite at the moment. Such a rewrite could be plugin based, allowing users to switch on specific plugins in order to bundle e.g., the SQL plugin. We could allow you to choose which SQL libraries to bundle, e.g., SQLite3, MySQL etc.

But I think your `extra-plugins` trick could work, too. CC @probonopd

**Comment by sgaist** [comment]
Hi,

They both deploy all available plugins by scanning the respective folders.

**Comment by probonopd** [comment]
> They both deploy all available plugins by scanning the respective folders for modules used by the application.

Hi @sgaist can you point me to specific code in `macdeployqt` that you think is missing from/not working properly in `linuxdeployqt`? Thanks.

**Comment by sgaist** [comment]
I think there's a misunderstanding here. They both take the same approach as linuxdeployqt currently: deploy all the plugins and their dependencies.

Something that would be nice to have is some sort of whitelist for plugins that the application developer currently wants to deploy like in this case, SQLite only.

**Comment by probonopd** [comment]
Can this be closed now that we have #253 merged?

**Comment by vadrian89** [comment]
sure thing by me, ty

Dum, 20 mai 2018, 20:10 probonopd <notifications@github.com> a scris:
