### ISSUE TITLE
How to deploy translation files with appImage

### ISSUE THREAD

**Issue by DamirPorobic** [probonopd/linuxdeployqt#240]
How can I deploy translation files (*.qm) with an AppImage?

I'm using following configuration to build the AppImage:
https://github.com/DamirPorobic/ksnip/blob/master/.travis.yml

I see in your documentation that you have the `-no-translations` flag so I'm under the impression that it should be doable but it's not working in my case.

**Comment by probonopd** [comment]
Ping @ribtoks

**Comment by ribtoks** [comment]
@DamirPorobic @probonopd As we all know, [code is the best documentation](https://github.com/probonopd/linuxdeployqt/blob/master/tools/linuxdeployqt/shared.cpp#L1309). `linuxdeployqt` was capable of bundling Qt translations (if you set up Qt path correctly) but it knows nothing about your own translations therefore you should copy them manually on your own to `/translations` dir inside bundle created by `linuxdeployqt`.

**Comment by DamirPorobic** [comment]
@ribtoks with "not working" I mean that there is no translation used with the appImage but it is working when I build from source and install. You might be pointing in the right direction, the .qm files are probably at the wrong location. I'm installing them to `/usr/share/ksnip/translations/*.qm` so if I get you correctly, they should be in `appdir/translations`, would a change like this be enough:

mkdir appdir/translations ; mv appdir/usr/share/ksnip/translations/*.qm ./appdir/translations ; rm -rd ./appdir/usr/share/ksnip/translations/

**Comment by ribtoks** [comment]
@DamirPorobic yes, translations should be in `$appdir/translations` but only if your app knows it should load them from this path. _There's no automatic miracle._ `QtCore` knows it can load translations from `/translations` but if you put your app-specific ones there as well, it should explicitly open and load them.

Also still you are not 100% clear. Are you talking about system Qt translations or your own app translations?

**Comment by DamirPorobic** [comment]
@ribtoks I'm talking about my own translations, two .qm files that were generated from two .ts files for my application. 
My application expects them to be in `/usr/share/ksnip/translations/` and the CI installed them initially  in `appdir/usr/share/ksnip/translations/` , but the AppImage was not able to find them. Next, I've tried to to move them to `/translations` and of course, the AppImage was not able to find them as it doesn't know that they are there. 

I'm not expecting any miracles, I'm just trying to understand what needs to be changed. I do not work with AppImages every day so my AppImage related knowledge is limited.

**Comment by DamirPorobic** [comment]
I'll try to bundle the translation files as resource in the executable, that should hopefully resolve this kind of issues.

**Comment by ribtoks** [comment]
@DamirPorobic I also don't work with AppImage every day, just for the reference (and I don't work with linuxdeployqt anymore, because I [rewrote it](https://github.com/ribtoks/linuxdeploy) and my tool works better for me). I gave you the link to **linuxdeployqt source code** which deals with translations - you can take a look there to get **ultimate understanding** what do you have to do.

I don't understand  this:
> but the AppImage was not able to find them

It looks like you're heavily messing `linuxdeployqt` and `AppImageTool`. 

Your plan should be:
1. Bundle all libraries with `linuxdeployqt`
2. Copy your own translation to where _your app_ expects to load them from
3. Then you should bundle AppDir (where everything from (1) and (2) is) with `AppImageTool`

I guess I won't be able to help you more than this list.

**Comment by DamirPorobic** [comment]
@ribtoks this part I don't understand:

> Copy your own translation to where your app expects to load them from

My app expects them to load from: `/usr/share/ksnip/translations/ksnip_de.qm`, but where is this location in the appdir? Is this`appdir/usr/share/ksnip/translations/ksnip_de.qm`? 

I've got the feeling that we miss each others point and that I'm just wasting your time...

**Comment by ribtoks** [comment]
@probonopd Please now it's your turn: where is location `/usr/share/ksnip/translations/ksnip_de.qm` in the AppDir :)

**Comment by DamirPorobic** [comment]
@probonopd any thoughts? :)

**Comment by probonopd** [comment]
What normally goes to `/usr/share/ksnip` should go to `[AppDir]/usr/share/ksnip`, with `[AppDir]` = the root directory of the AppDir = the directory that contains the `AppRun` file or symlink.

**Comment by DamirPorobic** [comment]
Ok, the executable is found in following directory by linuxdeployqt tool:
`Found binary from desktop file: "/home/travis/build/DamirPorobic/ksnip/appdir/usr/bin/ksnip"`
The translation files are installed to:
```
-- Installing: appdir/usr/share/ksnip/translations/ksnip_de.qm
-- Installing: appdir/usr/share/ksnip/translations/ksnip_es.qm
```
Which is basically the `/home/travis/build/DamirPorobic/ksnip/appdir/usr/bin/ksnip/translations/` directory.
If linuxdeployqt is not copying the files somewhere else, I presume that the `/home/travis/build/DamirPorobic/ksnip/appdir/`is the AppDir and the translation files are where they're supposed to be, but I don't see that anything is copied according to the output:

```
$ ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage
linuxdeployqt 4 (commit e915ad0), build 485 built on 2018-02-10 11:35:15 UTC
Desktop file as first argument: "appdir/usr/share/applications/ksnip.desktop"
desktopExecEntry: "ksnip"
desktopIconEntry: "ksnip"
Found binary from desktop file: "/home/travis/build/DamirPorobic/ksnip/appdir/usr/bin/ksnip"
FHS-like mode with PREFIX, fhsPrefix: "/home/travis/build/DamirPorobic/ksnip/appdir/usr"
app-binary: "/home/travis/build/DamirPorobic/ksnip/appdir/usr/bin/ksnip"
appDirPath: "/home/travis/build/DamirPorobic/ksnip/appdir"
relativeBinPath: "usr/bin/ksnip"
Found icons from desktop file: ("/home/travis/build/DamirPorobic/ksnip/appdir/ksnip.png", "/home/travis/build/DamirPorobic/ksnip/appdir/usr/share/pixmaps/ksnip.png")
WARNING: "/home/travis/build/DamirPorobic/ksnip/appdir/usr/bin/qt.conf" already exists, will not overwrite.
appimagetool, continuous build (commit continuous-4-g06f10fa), build 1452 built on 2018-02-10 10:23:13 UTC
Name: ksnip
Icon: ksnip
Exec: ksnip
Comment: Screenshot tool inspired by Windows Snipping Tool and made with Qt for Linux.
Type: Application
Categories: Utility;
/home/travis/build/DamirPorobic/ksnip/appdir/usr/bin/ksnip used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libtasn1.so.6 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libcups.so.2 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libXdamage.so.1 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libkrb5support.so.0 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libxcb-dri3.so.0 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libxcb-image.so.0 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libQt5Network.so.5 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libXxf86vm.so.1 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libxcb-present.so.0 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libxcb-shm.so.0 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libQt5XcbQpa.so.5 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libdbus-1.so.3 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libicui18n.so.52 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libQt5DBus.so.5 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libavahi-common.so.3 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libkrb5.so.3 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libxcb-render.so.0 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libXdmcp.so.6 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libglapi.so.0 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libk5crypto.so.3 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libQt5Widgets.so.5 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libxcb-sync.so.1 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libXi.so.6 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libxcb-dri2.so.0 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libQt5X11Extras.so.5 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libQt5PrintSupport.so.5 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libavahi-client.so.3 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libfreetype.so.6 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libpng12.so.0 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libxcb-shape.so.0 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libXau.so.6 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libX11-xcb.so.1 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libgssapi_krb5.so.2 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libQt5Gui.so.5 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libxcb-util.so.0 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libxcb-icccm.so.4 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libxcb-randr.so.0 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libgcrypt.so.11 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libffi.so.6 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libQt5Core.so.5 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libxcb-glx.so.0 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libXext.so.6 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libxcb-keysyms.so.1 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libpcre.so.3 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libQt5Xml.so.5 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libXfixes.so.3 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libicuuc.so.52 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libxcb-xfixes.so.0 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libxshmfence.so.1 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libxcb-xinerama.so.0 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libxcb-render-util.so.0 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libgnutls.so.26 used for determining architecture x86_64
/home/travis/build/DamirPorobic/ksnip/appdir/usr/lib/libicudata.so.52 used for determining architecture x86_64
Using architecture x86_64
App name for filename: ksnip
dest_path: ksnip-x86_64.AppImage
Generating squashfs...
Parallel mksquashfs: Using 2 processors
Creating 4.0 filesystem on ksnip-264-5c09df3-x86_64.AppImage, block size 131072.
[===============================================================-] 536/536 100%
```
Am I supposed to see the files being copied in the output? 
The travis log https://travis-ci.org/DamirPorobic/ksnip

**Comment by probonopd** [comment]
If you have put the files into `appdir/usr/share/ksnip/translations/` already, then they are already where they need to be and `linuxdeployqt` doesn't need to copy them anywhere because they are already where they need to be.

Now, possibly you need to modify your Qt application to ensure that they get loaded from there at runtime, using a relative path (relative to the executable) rather than a hardcoded path from `/usr`. At least, that is what I think @ribtoks meant with 

>  only if your app knows it should load them from this path. There's no automatic miracle.

**Comment by DamirPorobic** [comment]
Yeah, that makes sense. Currently, it tries to load the translations from `/usr/bin/ksnip/translations/`, when I tell it now to load the translation from `../usr/bin/ksnip/translations/` won't that be relative to the location where the appImage is currently executed from? For example, when the appImage runs from `~/downloads/ksnip.appimage`, won't that be `~/usr/bin/ksnip/translations/`?

**Comment by DamirPorobic** [comment]
Executed `pwd` and `cd .. && pwd` from the Qt application and got:
```
/home/dporobic/downloads
/home/dporobic
```
Which was the relative path to the .appImage file. 

But when I use `QCoreApplication::applicationDirPath()` from the Qt Application, I get `/tmp/.mount_ksnip-mUUwLU/usr/bin` which is the relative path based on the initial AppDir, and from there I was able to locate the path to the translation files. This fix my issue.

Thanks for the help!

**Comment by TheAssassin** [comment]
@DamirPorobic pro tip: use the environment variable `APPDIR`, which resolves to the mountpoint (in your example, `/tmp/.mount_ksnip-mUUwLU/`.

**Comment by probonopd** [comment]
`QCoreApplication::applicationDirPath()` is the better way to do this, since it will also work when the AppImage is extracted to an AppDir.

**Comment by DamirPorobic** [comment]
@TheAssassin @probonopd thanks for the tips, will have a look into both options. `APPDIR` is more convenient as I don't have to step back, though it is nice to also support AppDir when that is possible.

**Comment by TheAssassin** [comment]
@probonopd sure. I'm just providing @DamirPorobic with a Qt-less alternative for future apps.

**Comment by probonopd** [comment]
Thank you for the clarification. I think we should add something about how translations can be bundled using `QCoreApplication::applicationDirPath()` to the documentation. PRs welcome.
