### ISSUE TITLE
Release binary not found!!!

### ISSUE THREAD

**Issue by Surendrajat** [probonopd/linuxdeployqt#251]
Hi. It's not much of an issue but travis-ci build for my project is failing because the linuxdeployqt's release AppImage file is no longer there in repo. May I ask when will it be uploaded again? Or must I have to copy older release somewhere temporarily?
```bash
$ wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
--2018-03-06 06:14:11--  https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
Resolving github.com (github.com)... 192.30.255.112, 192.30.255.113
Connecting to github.com (github.com)|192.30.255.112|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-03-06 06:14:11 ERROR 404: Not Found.
```

**Comment by martinrotter** [comment]
Yes, happens to me too.

**Comment by TheAssassin** [comment]
Thanks for noticing this. I just saw we had a release draft laying around, which was a couple of weeks old. I tried to delete it and retriggered a build on Travis CI.

**Comment by TheAssassin** [comment]
Release has been published. Should work again. Feel free to reopen in case there's further issues.
