### ISSUE TITLE
libfontconfig 

### ISSUE THREAD

**Issue by patrickelectric** [probonopd/linuxdeployqt#259]
I would like to include libfontconfig in my appimage.
Motive:
```
 ✘ patrick@dell  ~/Downloads/squashfs-root  export QT_DEBUG_PLUGINS=1                     
 patrick@dell  ~/Downloads/squashfs-root  ./program
ping.logger: qml true
ping.logger: ping.waterfallGradient true
ping.logger: ping.waterfall true
ping.logger: ping.logger true
ping.logger: ping.util true
ping.logger: ping.main true
QFactoryLoader::QFactoryLoader() checking directory path "/mnt/hd/Downloads/squashfs-root/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() looking at "/mnt/hd/Downloads/squashfs-root/plugins/platforms/libqxcb.so"
Found metadata in lib /mnt/hd/Downloads/squashfs-root/plugins/platforms/libqxcb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "xcb"
        ]
    },
    "className": "QXcbIntegrationPlugin",
    "debug": false,
    "version": 330241
}


Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/mnt/hd/Downloads/squashfs-root/platforms" ...
Cannot load library /mnt/hd/Downloads/squashfs-root/plugins/platforms/libqxcb.so: (/usr/lib/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var)
QLibraryPrivate::loadPlugin failed on "/mnt/hd/Downloads/squashfs-root/plugins/platforms/libqxcb.so" : "Cannot load library /mnt/hd/Downloads/squashfs-root/plugins/platforms/libqxcb.so: (/usr/lib/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var)"
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.
```

Same thing with [this one](https://github.com/sithlord48/atcore/releases/download/continuous/AtCore_Test_Client-x86_64.AppImage).

Any motive to not include it ? [Line.](https://github.com/probonopd/linuxdeployqt/blob/c01cf7727d24f04956815eac52105a574fa65077/tools/linuxdeployqt/shared.cpp#L476)

I'm running arch linux with the last version of this library.

**Comment by probonopd** [comment]
https://github.com/AppImage/AppImages/blob/master/excludelist#L81-L83

```
libfontconfig.so.1
# Workaround for:
# Application stalls when loading fonts during application launch; e.g., KiCad on ubuntu-mate
```

**Comment by probonopd** [comment]
Where is your Qt coming from? Please use the Qt from https://launchpad.net/~beineri/+archive/ubuntu/opt-qt594-trusty and see if the problem persists; if so feel free to reopen.

**Comment by patrickelectric** [comment]
I have two repositories with the same problem, [AtCore](https://github.com/KDE/atcore) that uses:
```
sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa; 
sudo add-apt-repository --yes ppa:beineri/opt-qt591-trusty; 
```

And a second project that uses:
```
sudo add-apt-repository --yes ppa:beineri/opt-qt-5.10.1-trusty;
```

I'll try with 594, but it should be possible to add this libs manually ?

**Comment by TheAssassin** [comment]
@patrickelectric @probonopd didn't want to say you must use 5.9.4, but you should use one of Stephan Binner's PPAs at all.

Also, @probonopd _explained_ why libfontconfig isn't bundled. You are free to `cp /usr/<wherever arch puts its libraries>/libfontconfig.so* AppDir/usr/lib`, if you insist in bundling. Beware of the issues mentioned in @probonopd's link.

**Comment by probonopd** [comment]
> in archlinux the binary is different of the others distros now after the last update (1.11)

If libfontconfig in Arch Linux cannot run binaries anymore that were working before, then possibly barckward compatibility in libfontconfig in Arch Linux is broken, and the issue should be reported to the libfontconfig and/or Arch Linux team.

```
/usr/lib/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var
```

I cannot even find the offending symbol `FT_Done_MM_Var` on https://abi-laboratory.pro/index.php?view=navigator&symbol=FT_Done_MM_Var#result

**Comment by probonopd** [comment]
Please comment on or create tickets for [libfontconfig](https://bugs.freedesktop.org/enter_bug.cgi?product=fontconfig) ([mailing list](https://lists.freedesktop.org/mailman/listinfo/fontconfig)) and [Arch](https://bugs.archlinux.org/), and describe the issue and its effects (e.g., by linking to tickets resulting from this) - before this spreads to other distributions.

* https://bugs.archlinux.org/index.php?string=FT_Done_MM_Var - no results so far
* https://bugs.freedesktop.org/buglist.cgi?quicksearch=FT_Done_MM_Var - no results so far

**Comment by patrickelectric** [comment]
@probonopd Removing ./lib/libfreetype.so.6 solved my problem ! Ty !
