### ISSUE TITLE
qmlimportscanner not found 

### ISSUE THREAD

**Issue by usercz** [probonopd/linuxdeployqt#26]
I'm using the appimage build.

```
 ./linuxdeployqt  ~/dev/cool-retro-term/build/cool-retro-term -appimage -qmldir=~/dev/cool-retro-term/
"/tmp/.mount_9l9Smc/usr/bin:/home/salvo/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"
app-binary: "/home/salvo/dev/cool-retro-term/build/cool-retro-term"
ERROR: FIXME: Here I would like to determine the original rpath of the main executable, but get: QSet("$ORIGIN/lib")
ERROR: qmlimportscanner not found at "/tmp/.mount_9l9Smc/qmlimportscanner"
ERROR: Rebuild qtdeclarative/tools/qmlimportscanner
```

**Comment by probonopd** [comment]
Yes, the whole QML stuff is entirely untested and likely broken at the moment; help would be appreciated.

**Comment by probonopd** [comment]
Related to #25, QML is not working yet. Hence closing here.

**Comment by usercz** [comment]
Please leave them open, so newcomers see the amount of open issues and think twice before trying to use this.

**Comment by probonopd** [comment]
Yes, I have left #25 open which is the root cause. But having 3 duplicates of "QML is not working yet" is not helping me prioritize ;-)

**Comment by probonopd** [comment]
qmlimportscanner is tried to be loaded from the location under the qt_prfxpath that is hardcoded in libQtCore.so.5, or, as a fallback, from the location next to the linuxdeployqt binary. I have added qmlimportscanner to the linuxdeployqt AppImage for now. The error should be gone.
