### ISSUE TITLE
Not copied libraries

### ISSUE THREAD

**Issue by EndrII** [probonopd/linuxdeployqt#266]
After the startup, nothing happens, only apprun is created, which is no different from the original binaries.
My actions:
* `export PATH=path/to/my/qt/dir/bin:PATH`
* `./linuxdeployqt /path/to/myApp -qmldir=/path/to/qml/dir `

Log with verbose = 3 :

`./linuxdeployqt '/home/andrei/build-untitled1-Desktop_Qt_5_9_2_GCC_64bit-Release/untitled1' -verbose=3` 
`linuxdeployqt 4 (commit 5843744), build <local dev build> built on 2018-04-06 07:37:43 UTC
`
After run this command added only one file, it is apprun.

I use ubuntu 17.10.
Really need your help. thanks.

**Comment by probonopd** [comment]
Please run on Ubuntu 14.04 and see whether you are getting the same issue there. I have never tested this on later versions, since I want my generated AppImages to run on the oldest still-supported LTS version of Ubuntu.

**Comment by EndrII** [comment]
Thanks for the help, but I would really like to see support for the latest versions of ubuntu in the flesh until 18.04.

**Comment by probonopd** [comment]
Please keep in mind that binaries compiled on 14.04 will run on 18.04 but not the other way around. Hence it is always a good idea to build on the oldest still-supported version.

**Comment by probonopd** [comment]
Is https://github.com/QuasarApp/Hanoi-Towers the app in question?

**Comment by EndrII** [comment]
Yes, I tried to pack this application, but alas it did not work out, I'll try again at 14 04, but if I do not get to use snap

**Comment by probonopd** [comment]
Built AppImage at https://github.com/probonopd/Hanoi-Towers/releases and sent a Pull Request.

**Comment by EndrII** [comment]
Thanks you!)
