### ISSUE TITLE
Shadowed build is broken because of LINUXDEPLOYQT_GIT_COMMIT

### ISSUE THREAD

**Issue by Skycoder42** [probonopd/linuxdeployqt#267]
When trying to shadow-build linuxdeployqt (build a folder that is not that source folder), `make` fails because of the build not happening in a git repository, and this `LINUXDEPLOYQT_GIT_COMMIT` fails to execute.

Steps to reproduce:
```
git clone https://github.com/probonopd/linuxdeployqt.git
mkdir build && cd build
qmake ../linuxdeployqt/
make qmake_all
make
```
The compile fails with: `fatal: no git repository`

Solution: run the git command from the original src dir by cding into `$$PWD`:

```
DEFINES += LINUXDEPLOYQT_GIT_COMMIT="'\"$(shell cd $$PWD && git rev-parse --short HEAD)\"'"

DEFINES += LINUXDEPLOYQT_VERSION="'\"$(shell cd $$PWD && git describe --tags $(shell cd $$PWD && git rev-list --tags --skip=1 --max-count=1) --abbrev=0)\"'"
```

**Comment by TheAssassin** [comment]
Would you be willing to send a PR? I am not a qmake expert, and expected these lines to have some potential for error when writing them.

**Comment by Skycoder42** [comment]
on my way

**Comment by TheAssassin** [comment]
Thanks.
