### ISSUE TITLE
Recent AppImages are broken

### ISSUE THREAD

**Issue by vadi2** [probonopd/linuxdeployqt#269]
Mudlet 3.7.0 built with linuxdeployqt on 2017-12-23 works fine on Ubuntu 17.10 ([binary](https://www.mudlet.org/download/Mudlet-3.7.1-linux-x64.AppImage.tar), [linuxdeployqt log](https://hastebin.com/jururikeqe.go)).

Mudlet 3.8.0 built with linuxdeployqt on 2017-04-09 fails to launch on Ubuntu 17.10 and a host of others ([binary](https://www.mudlet.org/download/Mudlet-3.8.0-linux-x64.AppImage.tar), [linuxdeployqt log](https://hastebin.com/oripijerak.go))

Exact log is:

```
 vadi  ~  Downloads  3.8.0  export QT_DEBUG_PLUGINS=1
 vadi  ~  Downloads  3.8.0  ./Mudlet.AppImage 
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_MudletQA6ttV/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_MudletQA6ttV/plugins/platforms/libqxcb.so"
Found metadata in lib /tmp/.mount_MudletQA6ttV/plugins/platforms/libqxcb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "xcb"
        ]
    },
    "className": "QXcbIntegrationPlugin",
    "debug": false,
    "version": 329987
}


Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_MudletQA6ttV/platforms" ...
Cannot load library /tmp/.mount_MudletQA6ttV/plugins/platforms/libqxcb.so: (/tmp/.mount_MudletQA6ttV/lib/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16))
QLibraryPrivate::loadPlugin failed on "/tmp/.mount_MudletQA6ttV/plugins/platforms/libqxcb.so" : "Cannot load library /tmp/.mount_MudletQA6ttV/plugins/platforms/libqxcb.so: (/tmp/.mount_MudletQA6ttV/lib/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16))"
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.
Aborted (core dumped)
```

What can we do to fix this and is there a link to a previously working linuxdeployqt?

Note that we did not change our build configuration or Qt versions in the meantime, so the only variable is this continuous release linuxdeployqt

**Comment by probonopd** [comment]
Please `--appimage-extract` 3.7.0, then `ldd squashfs-root/plugins/platforms/libqxcb.so`. Delete `squashfs-root/`, then repeat with 3.8.0. Are there any differences in the output?

**Comment by probonopd** [comment]
Not sure if this could have to do with the automated excludelist generation, https://github.com/probonopd/linuxdeployqt/commit/1894c66a8f3341a4864b31ea4e32a91d70b30ff9

**Comment by keneanung** [comment]
```
--- ldd_3.7.1.log	2018-04-09 21:02:03.007254076 +0200
+++ ldd_3.8.0.log	2018-04-09 21:04:45.498206169 +0200
@@ -1,11 +1,11 @@
 	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0
 	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6
 	libdbus-1.so.3 => /home/keneanung/tmp/squashfs-root/plugins/platforms/../../lib/libdbus-1.so.3
 	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2
 	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1
 	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1
-	libfreetype.so.6 => /home/keneanung/tmp/squashfs-root/plugins/platforms/../../lib/libfreetype.so.6
+	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6
 	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1
 	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0
 	libGL.so.1 => /usr/lib/nvidia-384/libGL.so.1
@@ -18,6 +18,7 @@
 	libnvidia-tls.so.384.130 => /usr/lib/nvidia-384/tls/libnvidia-tls.so.384.130
 	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3
 	libpng12.so.0 => /home/keneanung/tmp/squashfs-root/plugins/platforms/../../lib/libpng12.so.0
+	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16
 	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0
 	libQt5Core.so.5 => /home/keneanung/tmp/squashfs-root/plugins/platforms/../../lib/libQt5Core.so.5
 	libQt5DBus.so.5 => /home/keneanung/tmp/squashfs-root/plugins/platforms/../../lib/libQt5DBus.so.5
@@ -48,3 +49,4 @@
 	libXi.so.6 => /home/keneanung/tmp/squashfs-root/plugins/platforms/../../lib/libXi.so.6
 	libz.so.1 => /home/keneanung/tmp/squashfs-root/plugins/platforms/../../lib/libz.so.1
 	linux-vdso.so.1 => 
+squashfs-root/plugins/platforms/libqxcb.so: /home/keneanung/tmp/squashfs-root/plugins/platforms/../../lib/libz.so.1: version 'ZLIB_1.2.9' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16)
```
I cut off the hex numbers at the end of the `ldd` lines as they were all different. This way you see the different lines only.

**Comment by TheAssassin** [comment]
@keneanung these hex values can be considered "random", they're dynamically assigned by the operating system, when the libraries are loaded by `ldd`. It's safe to cut them off.

**Comment by probonopd** [comment]
It's loading a bundled `libz.so.1` when in fact as per https://github.com/AppImage/AppImages/blob/master/excludelist this (and other libs) should _not_ be bundled.

**Comment by probonopd** [comment]
@keneanung just for testing, what happens if you delete all the files that are mentioned in the excludelist?

**Comment by keneanung** [comment]
Looks like it starts up nicely on my machine. I will generate a test version with this change and give it to some people with different distro's (I'm on Ubuntu 17.10) to confirm it fixes their issues as well.

**Comment by keneanung** [comment]
Looks like removing the `libz.so.1` fixed it and we did not get any reports about other issues popping up with the AppImage. It was tested with Ubuntu 17.10, Ubuntu MATE 17.10 and Fedora 26.

Thanks for your help!

**Comment by probonopd** [comment]
Did you find out why this library ended up in the AppImage?

**Comment by keneanung** [comment]
As I said, we explicitly included it. But I did not find the reason as to _why_. We're hoping that the reasons where either fixed or we will find another solution to issues that pop up because of it (and document them this time around :D)
