### ISSUE TITLE
Other failure

### ISSUE THREAD

**Issue by usercz** [probonopd/linuxdeployqt#27]
```
$ ./linuxdeployqt  ~/dev/cool-retro-term/build/cool-retro-term -appimage
"/tmp/.mount_n6Y2pw/usr/bin:/home/salvo/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"
app-binary: "/home/salvo/dev/cool-retro-term/build/cool-retro-term"
ERROR: FIXME: Here I would like to determine the original rpath of the main executable, but get: QSet("$ORIGIN/lib")
```

I tried without scanning for qml files (which I suspect will make a cool-retro-term that won't start), but that's what I get.

**Comment by probonopd** [comment]
I think you are running in #2, so please try (instead of `/tmp/.mount_QtCreator-5.7.0-x86_64/5.7` use the path where your Qt installation is):

```
export QT_PLUGIN_PATH=/tmp/.mount_QtCreator-5.7.0-x86_64/5.7/gcc_64/plugins/ 
export LD_LIBRARY_PATH=/tmp/.mount_QtCreator-5.7.0-x86_64/5.7/gcc_64/lib/
export QTDIR=/tmp/.mount_QtCreator-5.7.0-x86_64/5.7/gcc_64 # not needed?
```

Then run linuxdeployqt. Afterwards

```
unset QT_PLUGIN_PATH
unset LD_LIBRARY_PATH
unset QTDIR
```

**Comment by probonopd** [comment]
Related to #25, QML is not working yet. Hence closing here.

**Comment by probonopd** [comment]
You have to run `$ ./linuxdeployqt  ~/dev/cool-retro-term/build/cool-retro-term -qmldir=~/dev/cool-retro-term/build/cool-retro-term/qml -appimage -bundle-non-qt-libs`.
