### ISSUE TITLE
Add a function to print the excludelist

### ISSUE THREAD

**Issue by probonopd** [probonopd/linuxdeployqt#270]
@patrickelectric now that the excludelist is being generated dynamically, it would help a __lot__ in debugging if there was a `-print-excludelist` option that would show, at runtime, which libraries are being excluded. Do you think you could implement it?

Before, I could just look this information up in the source code on GitHub. But no longer...

**Comment by TheAssassin** [comment]
@probonopd the list is generated from the excludelist in the AppImages repository, you can just check there, and if you want to be on the safe side, you can check the Travis log, where it's documented in the log.

**Comment by probonopd** [comment]
Could help in situations like https://github.com/openscad/openscad/issues/1849#issuecomment-379768364.

**Comment by probonopd** [comment]
> @probonopd the list is generated from the excludelist in the AppImages repository

Yes, but it's not obvious which version of that was the version in use for a certain build of `linuxdeployqt`.

So, point in case, why was `libpthread.so.0` not excluded in [this](https://github.com/openscad/openscad/issues/1849#issuecomment-379768364) poor fellow's build

**Comment by patrickelectric** [comment]
I agree with @probonopd, will check this in my free time.
