### ISSUE TITLE
Make it show the version on OBS, too

### ISSUE THREAD

**Issue by probonopd** [probonopd/linuxdeployqt#271]
According to this [log file](https://build.opensuse.org/public/build/home:t-paul/AppImage/x86_64/OpenSCAD-Release/_log) the version used by OBS is `linuxdeployqt  (commit ), build <local dev build> built on 2018-04-08 15:02:52 UTC`. This is not very helpful as it does not point to a git commit in this repository.

Can we improve this so that it shows the git commit in the OBS version as well?

**Comment by TheAssassin** [comment]
@probonopd if they don't clone the repository but just copy the contents, how could we possibly get that hash?

**Comment by probonopd** [comment]
Do you have any idea what exactly we need them to do, given how OBS works?

**Comment by TheAssassin** [comment]
You should ask _them_. I don't know how exactly OBS works. If they don't want to put the Git files on their build machines, maybe they can expose some information via environment variables? For example, the current git commit ID?

**Comment by probonopd** [comment]
Hello @adrianschroeter do you have an idea what we could do so that the git commit information would be shown in OBS builds of `linuxdeployqt` and our other tools (and be used as the version string)? This would greatly help debugging.

**Comment by patrickelectric** [comment]
I can build both cmake and qmake without internet, just need to define a exludelist variable when running both commands...
No issue from my part, everything is working at it should, with internet or without it.

**Comment by probonopd** [comment]
@patrickelectric you are in the wrong ticket

**Comment by TheAssassin** [comment]
I agree. It's more a matter of the OBS environment being _very_ special.

**Comment by patrickelectric** [comment]
Sorry, a lot of mails about it !

**Comment by TheAssassin** [comment]
Closing this issue. This is a mess of at least two different issues, see #272. I will create new issues accordingly.
