### ISSUE TITLE
Make it work on OBS again

### ISSUE THREAD

**Issue by probonopd** [probonopd/linuxdeployqt#272]
According to https://build.opensuse.org/package/live_build_log/OBS:AppImage/linuxdeployqt/toolchain/x86_64, `linuxdeployqt` cannot be built correctly on OBS anymore since it tries, at compile time, to use `wget` to get the exludelist from https://raw.githubusercontent.com/probonopd/AppImages/master/excludelist.

On OBS, build scripts _do not have Internet access_.

Unfortunately, this means that __currently all AppImage builds on OBS are broken__ because they are using a broken version of `linuxdeployqt` without an excludelist.

So we either need to
* Rewrite the OBS build script to not use `wget` but the OBS way of downloading files, or
* Revert back to 9e95a47 when it was still working (__this is the default action that I will take 7 days from now if this is not otherwise solved until then__)

```
[   75s] /home/abuild/rpmbuild/BUILD/linuxdeployqt-3.1523199587.88aba55/tools/linuxdeployqt/../excludelist.sh: line 4: wget: command not found
[   75s] /home/abuild/rpmbuild/BUILD/linuxdeployqt-3.1523199587.88aba55/tools/linuxdeployqt/../excludelist.sh: line 9: blacklisted: bad array subscript
[   75s] make[2]: Entering directory '/home/abuild/rpmbuild/BUILD/linuxdeployqt-3.1523199587.88aba55/build/tools/linuxdeployqt'
[   75s] /bin/sh: git: command not found
```

cc @patrickelectric @TheAssassin

**Comment by patrickelectric** [comment]
I'll take a look.

**Comment by probonopd** [comment]
> I can build both cmake and qmake without internet, just need to define a exludelist variable when running both commands...
> No issue from my part, everything is working at it should, with internet or without it.

So you are saying it works if you have no internet during building?
Where does it get its excludelist from?

**Comment by patrickelectric** [comment]
I can build both cmake and qmake without internet, just need to define a exludelist variable when running both commands...
No issue from my part, everything is working at it should, with internet or without it.

**Comment by probonopd** [comment]
So you are saying it works if you have no internet during building?
Where does it get its excludelist from?

**Comment by probonopd** [comment]
> just need to define a exludelist variable

I guess the build on OBS doesn't do that. Can we make it so that it works without them having to change anything?

**Comment by TheAssassin** [comment]
@probonopd there used to be a "fallback" solution, with a static excludelist. But in any case, _how_ the excludelist variable is generated doesn't matter, really, it just needs to be passed as a macro.

If you really want to make this complicated, we could add AppImages as a submodule and use the file from there. Then, you can update the submodule every time there is an update for the exclude list. But the point of this whole change was to get rid of all this maintenance overhead.

Please wait for the OBS team to respond before making any hasty decisions...

**Comment by probonopd** [comment]
Well, since getting stuff from the outside is against the philosophy of OBS for the reason that the source should be converted into binary in a fully reproducible way and this does not work if we pull in stuff at runtime, I guess we need to at least mirror the excludelist inside this repository. @patrickelectric do you agree?

**Comment by patrickelectric** [comment]
@probonopd The exclude list is empty.. just need to define it while calling cmake or qmake to solve this issue.

**Comment by TheAssassin** [comment]
> I guess we need to at least mirror the excludelist inside this repository.

No! Not at all! Check my last comment:

> If you really want to make this complicated, we could add AppImages as a submodule and use the file from there. Then, you can update the submodule every time there is an update for the exclude list. But the point of this whole change was to get rid of all this maintenance overhead.

All this guesswork...

**Comment by TheAssassin** [comment]
This is so messy, please decide one single issue where you want to discuss this. Also, please try to be a bit more elaborate. There is a huge misunderstanding here.

**Comment by probonopd** [comment]
Back to the basics.

The OBS philosophy (which took me a while to understand) is that they want to make builds reproducible, which means that using the same source code tarball, the same binary packages should be produced.

For this very reason they don't want to have stuff downloaded during build time. All the information needs to be in the source tarball.

Hence, I think the excludelist needs to be in the linuxdeployqt source tarball.

**Comment by TheAssassin** [comment]
Closing this issue. This is a mess of at least two or three issues. I will create new issues accordingly.
