### ISSUE TITLE
findDependencyInfo() misses the first dependency on systems without vdso

### ISSUE THREAD

**Issue by xaxaxa-dev-0** [probonopd/linuxdeployqt#283]
The code
```c++
   if ((binaryPath.contains(".so.") || binaryPath.endsWith(".so")) && (!lddOutputContainsLinuxVDSO(output))) {
        const QRegularExpressionMatch match = regexp.match(outputLines.first());
        if (match.hasMatch())  {
            info.installName = match.captured(1);
        } else {
            LogError() << "Could not parse ldd output line:" << outputLines.first();
        }
        outputLines.removeFirst();
    }
```
in findDependencyInfo() (in shared.cpp) seems to assume that the first line of the ldd output is the "install name" of the library when it's not a vdso line, but this seems not to be the case (on scaleway arm vps):
```
user@scw-303077:~$ ldd /bin/bash
        libncurses.so.5 => /lib/arm-linux-gnueabihf/libncurses.so.5 (0xb6eee000)
        libtinfo.so.5 => /lib/arm-linux-gnueabihf/libtinfo.so.5 (0xb6ec3000)
        libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0xb6eb0000)
        libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0xb6dc2000)
        /lib/ld-linux-armhf.so.3 (0xb6f13000)
user@scw-303077:~$ 
```
It causes qt dependencies to be missed and creates broken appimages; deleting the above code seems to fix the appimage.
I'm not sure if this code can just be removed or if it's necessary on some other systems.

**Comment by probonopd** [comment]
Thanks, I did not know that there are systems where there is no vdso in the output. Also, I have no such system to test with. Can you confirm that with when deleting the above code, then it still works for x86_64?

**Comment by probonopd** [comment]
Thanks for pointing this out, removed the code.
