### ISSUE TITLE
Positioning module not available in AppImage

### ISSUE THREAD

**Issue by vadrian89** [probonopd/linuxdeployqt#287]
Just wanted to let you know that the positioning module is not working in the AppImage package.  
I get "No position info source available." message when making a new default source.  
Or am I doing something wrong?  
I am trying this on Ubuntu 16.04, latest updates.   
[Cumulus AppImage package](https://transfer.sh/Br0Uc/Cumulus-git.b4e5be7-x86_64.AppImage)   
[Travis build](https://travis-ci.org/vadrian89/cumulus-qt)

**Comment by probonopd** [comment]
Need to tell `linuxdeployqt` to deploy this module using the `-extra-plugins=` option.

**Comment by probonopd** [comment]
Is there a way to detect automatically in which circumstances this plugin should be deployed? What do `macdeployqt` and `windeployqt` do?

**Comment by vadrian89** [comment]
I don't know how mac and win versions deploy this, but the library for positioning is deployed just not the plugin....hmmm....this is weird.    

Entry from travis, proving that the library is getting deployed: 
`/home/travis/build/vadrian89/cumulus-qt/appdir/usr/lib/libQt5Positioning.so.5 used for determining architecture x86_64`

**Comment by vadrian89** [comment]
At a first look, in the source code, it seems there is no deployment for positioning plugin whatsoever :).    
It can be added easily when positioning library is deployed, or people can just use extra plugin option.

**Comment by vadrian89** [comment]
Deploying the plugin sovled the issue.

**Comment by probonopd** [comment]
From what you write it seems that we should deploy the positioning plugin whenever `libQt5Positioning.so.5` gets deployed. Can you confirm this strategy?

**Comment by probonopd** [comment]
I guess there is only one way to find out... try it out:
https://github.com/probonopd/linuxdeployqt/commit/bba42c7cc02a5ce23393e9efef78b5b8065451b1
Will be in the next continuous build.

**Comment by vadrian89** [comment]
Seems to work, cheers.
