### ISSUE TITLE
: symbol , version  not defined in file  with link time reference

### ISSUE THREAD

**Issue by probonopd** [probonopd/linuxdeployqt#29]
`: symbol , version  not defined in file  with link time reference` when trying to run an AppImage generated by linuxdeployqt on Travis CI. To be investigated.

[Build log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/165336833/log.txt)

https://github.com/chkmue/qttravisCI_1

**Comment by probonopd** [comment]
The error goes away when Qt 5.7 is used at build time.

```
source /opt/qt57/bin/qt57-env.sh
/opt/qt57/bin/qmake
```

**Comment by probonopd** [comment]
Might be related to https://github.com/NixOS/patchelf/issues/46 - @darealshinji do you have an idea?

**Comment by probonopd** [comment]
Same as https://github.com/NixOS/patchelf/issues/99?

**Comment by probonopd** [comment]
I want to be able to use Qt 5.6 too and I suspect that it being working with Qt 5.7 just being a coincidence.

**Comment by vadi2** [comment]
I can confirm that building with Qt 5.7 fixed this particular issue for me as reported in #66.

**Comment by probonopd** [comment]
Please try https://github.com/probonopd/linuxdeployqt/releases/tag/continuous. Turns out that `strip` has a bug that cripples binaries on which `patchelf` was previously run (https://github.com/NixOS/patchelf/issues/10). Therefore, I am now checking whether a binary has a `rpath` starting with $ (indicating that we already ran `patchelf` on it), and _not_ run `strip` in that case. https://github.com/probonopd/linuxdeployqt/commit/c643d6a5094f1dafcf0dc82c33d11d24ec622876

Let me know if this solves it for you.

**Comment by probonopd** [comment]
I am going to assume that this is fixed now. Please leave a comment if you think otherwhise.

**Comment by probonopd** [comment]
With https://github.com/NixOS/patchelf/pull/117 merged, patchelf will hopefully allow binaries to be stripped after running patchelf.

**Comment by probonopd** [comment]
Seeing
`symbol  version  not defined in file  with link time reference`
for the binaries on https://download.opensuse.org/repositories/home:/rncbc/AppImage/ as of today. Similar issue? cc @adrianschroeter
