### ISSUE TITLE
QtQuick Controls not getting deployed, Controls.2 does

### ISSUE THREAD

**Issue by kviktor** [probonopd/linuxdeployqt#300]
I'm trying to deploy a program that uses `CircularGauge` which uses `QtQuick.Controls 1.4`. In my own QML files I only use  `QtQuick.Controls 2.1/2.2`. In the deployed filed I have both Controls and Controls.2 directories, the Controls directory has no files, however it has subfolders that have files in them. The Controls.2 directory has qml files and a .so file too. If I just manually copy the Controls folder from my build machine to the testing VM everything is great.

I've also tried adding a "dummy" `import QtQuick.Controls 1.4` to my file and copying the CircularGauge.qml to my qmldir but neither worked.

**Comment by probonopd** [comment]
linuxdeployqt internally uses `qmlscanner` to determine which QML imports need to be bundled. Have you tried supplying an additiona `-qmldir=...` command line option pointing to the directory in which the file is that imports Controls?

**Comment by probonopd** [comment]
It's `-qmldir=...` not `-qmdir=...`

**Comment by probonopd** [comment]
It looks like CircularGauge  gets deployed (at least partly):

```
Log: Deploying QML import "QtQuick.Extras"
Log: path: "/home/builder/Qt/5.9.1/gcc_64/qml/QtQuick/Extras"
Log: type: "module"
Log: copy: "/home/builder/Qt/5.9.1/gcc_64/qml/QtQuick/Extras" "/home/builder/myapp_build/myapp/myapp/qml/QtQuick/Extras"
Log:  copied: "/home/builder/Qt/5.9.1/gcc_64/qml/QtQuick/Extras/CircularGauge.qml"
Log:  to "/home/builder/myapp_build/myapp/myapp/qml/QtQuick/Extras/CircularGauge.qml"
Log: copyCopyrightFile: "/home/builder/Qt/5.9.1/gcc_64/qml/QtQuick/Extras/CircularGauge.qml"
Log:  copied: "/home/builder/Qt/5.9.1/gcc_64/qml/QtQuick/Extras/CircularGauge.qmlc"
Log:  to "/home/builder/myapp_build/myapp/myapp/qml/QtQuick/Extras/CircularGauge.qmlc"
Log: copyCopyrightFile: "/home/builder/Qt/5.9.1/gcc_64/qml/QtQuick/Extras/CircularGauge.qmlc"
```

In your logfile, there is a couple of instances of

```
Skip import: name or path is empty
```

Are these the files that are missing in the end, and are preventing the application from running correctly? Where do the original files live, in `/home/builder/Qt/5.9.1/gcc_64/qml/` as well or somewhere else?

**Comment by kviktor** [comment]
`CircularGauge.qml` itself is not a problem, it gets deployed properly. The problem is that it has an `import QtQuick.Controls 1.4` statement in it but only Controls2 gets copied over (that I use from my code), Controls is not (apart from the Styles folders) even tho I tried manually copying the file to my qmldir before to make linuxdeployqt detect it.

Looking at the skips, I think it's the `QtQuick.Controls.impl` what I'm missing. Under `/home/builder/Qt/5.9.1/gcc_64/` I have a regular Qt installation from their online installer.

Also may I ask where that `qmlscanner` program lives? Cause apparently after a Qt update our Mac release is showing the same problems, so it might not be an linuxdeployqt issue.

**Comment by probonopd** [comment]
Since `linuxdeployqt` was started off using from the `macdeployqt` codebase, we might well have inherited https://github.com/therecipe/qt/issues/113...

**Comment by probonopd** [comment]
Indeed it seems from your log that `libqtquickcontrolsplugin` does not get deployed here but maybe should. What happens if you temporarily move away `libqtquickcontrolsplugin` from a working setup, does it still work then?

**Comment by probonopd** [comment]
> Also may I ask where that qmlscanner program lives?

As your log says,

```
Log: Looking for qmlimportscanner at "/home/builder/Qt/5.9.1/gcc_64/bin/qmlimportscanner"
Log: qmlImportsPath (QT_INSTALL_QML): "/home/builder/Qt/5.9.1/gcc_64/qml"
Log: "/home/builder/Qt/5.9.1/gcc_64/bin/qmlimportscanner" ("-rootPath", "/home/builder/myapp_sources/client/gui_qt/layouts", "-importPath", "/home/builder/Qt/5.9.1/gcc_64/qml")
```

**Comment by kviktor** [comment]
If I remove `libqtquickcontrolsplugin.so` I get
```
qrc:/myapp.qml:245 Type CircularGauge unavailable
file:///myapp/qml/QtQuick/Extras/CircularGauge.qml:42 module "QtQuick.Controls" plugin "qtquickcontrolsplugin" not found
```

If I remove the `qmldir` file from the `Controls` directory I get my original error
```
qrc:/myapp.qml:245 Type CircularGauge unavailable
file:///myapp/qml/QtQuick/Extras/CircularGauge.qml:42 module "QtQuick.Controls" version 1.4 is not installed
```

Could I have problems later if I just manually copy the folder over as a workaround?

**Comment by probonopd** [comment]
In which exact path does " qmldir file from the Controls directory" live and what is its contents?

**Comment by kviktor** [comment]
I removed the qmldir file from my working installation as a test, it lived in `myapp/qml/QtQuick/Controls` but the whole folder is the exact copy of the original Qt one.

**Comment by probonopd** [comment]
Please give the full paths of the original and copy qmldir file.

**Comment by kviktor** [comment]
The original is in the Qt installation dir: `/home/builder/Qt/5.9.1/gcc_64/qml/QtQuick/Controls`
The one from the working application is in: `/home/builder/myapp_build/myapp/myapp/qml/QtQuick/Controls` (but this was manually copied over)

**Comment by kviktor** [comment]
With that `QtQuick.Controls` got copied over however `QtQuick.Extras` didn't (same thing, it had a Private directory so it was probably skipped). 

With this workaround things seem to work great: 05e7f70c6bb1c74f3876554c3fcd7f57f997ccf3 (originally I just removed the whole if/return part but with that the program ran for about 15 mins, with the current one it takes around 5 min to complete which is close to the original one)

**Comment by probonopd** [comment]
Cool. Thanks @kviktor!
