### ISSUE TITLE
override appimage appname

### ISSUE THREAD

**Issue by LyzardKing** [probonopd/linuxdeployqt#301]
Is it possible to override the appname?
For instance, the .desktop file is AppName.desktop,
but for consistency I want it to be lowercase..
could I do something like:
`export APPNAME=appname`
before I run linuxdeployqt?

**Comment by probonopd** [comment]
Thanks @LyzardKing.

We generally recommend AppImage files to use the name of the application (including capitalization) as-is for the filename and encourage people to do so by having `appimagetool` do that by default.

Is there any reason to use lowercase? I know it seems to be common practice in the Linux world for package names, but I think of AppImages more as _applications_ than as _packages that contain applications_; e.g., on the Mac, GUI applications are usually uppercase. 

As long as you are not using zsync files for binary delta updates, you can simply rename the AppImage after it has been generated, if you absolutely need to. In any case, we are trying to keep the number of configurability to a minimum, and do the rest "just right"; hence this is not something I'd like to implement.

**Comment by LyzardKing** [comment]
It was just to retain consistency with the windows and macos versions, that are all lowercase.
Basically I'm running linyxdeployqt, then renaming it.
Would that break the delta updates? (I actually have no idea how the updates work...)

**Comment by probonopd** [comment]
macOS .dmg files are usually reflecting the name of the application.

According to Learning Cocoa with Objective-C by James Duncan Davidson, Apple

> The common practice in naming applications is that command-line applications should be lowercase and GUI applications should be initial capitalized

If you are using binary delta updates, you are producing zsync files. Since these refer to the name of the AppImage file, they will break if you are renaming the AppImage manually. If you don't use binary delta updates nor zsync files, then you can rename the AppImage without any side effect.

**Comment by LyzardKing** [comment]
I wanted to contribute a travis build of texstudio, since they now have builds for win and macos.
I managed using linuxdeployqt and just adding one extra qt module.
This is the PR: https://github.com/texstudio-org/texstudio/pull/194
I tried (before uploading the PR) to push to transfer.sh and download (to test) the images.
They work (they don't come with texlive, but neither do the win/macos ones)...

If I rename the Appimage, and I (travis in this case) am the one distributing it, it shouldn't break then, right?

**Comment by probonopd** [comment]
According to the GitHub page, the official name is _TeXstudio_, and hence that capitalization is what I recommend for naming the AppImage (just like on the Mac, one would call it TeXstudio.app and TeXstudio.dmg).

Especially for continuous builds, also uploading the zsync file is the way to go, as it allows for binary delta updates. In which case renaming the AppImage would break the mechanism.

**Comment by LyzardKing** [comment]
In the releases page every release is lowercase, that's why I changed it.
But it's easy to change back...
