### ISSUE TITLE
extra plugin option

### ISSUE THREAD

**Issue by ukinoki** [probonopd/linuxdeployqt#303]
Hi,
Deployment of mysql driver can't be done individualy, linuxqtdeploy can't find individual file : 

when using -extra-plugins=sqldrivers/libqsqlmysql.so
WARNING: The plugin "/opt/qt510/plugins/sqldrivers/libqsqlmysql.so" could not be found. Please check spelling and try again!
even if it does exist...

use of -extra-plugins=sqldrivers do work and deploy all the libs : 
Log: Deploying extra plugins.
Log: pluginList after having detected hopefully all required plugins: ("platforms/libqxcb.so", "platforminputcontexts/libcomposeplatforminputcontextplugin.so", "platforminputcontexts/libibusplatforminputcontextplugin.so", "imageformats/libqgif.so", "imageformats/libqico.so", "imageformats/libqjpeg.so", "xcbglintegrations/libqxcb-glx-integration.so", "printsupport/libcupsprintersupport.so", "bearer/libqconnmanbearer.so", "bearer/libqgenericbearer.so", "bearer/libqnmbearer.so", "sqldrivers/libqsqlite.so", "sqldrivers/libqsqlmysql.so", "sqldrivers/libqsqlodbc.so", "sqldrivers/libqsqlpsql.so", "sqldrivers/libqsqltds.so", "mediaservice/libgstaudiodecoder.so", "mediaservice/libgstcamerabin.so", "mediaservice/libgstmediacapture.so", "mediaservice/libgstmediaplayer.so", "audio/libqtaudio_alsa.so", "audio/libqtmedia_pulse.so", "sqldrivers/libqsqlite.so", "sqldrivers/libqsqlmysql.so", "sqldrivers/libqsqlodbc.so", "sqldrivers/libqsqlpsql.so", "sqldrivers/libqsqltds.so")

**Comment by probonopd** [comment]
@vadrian89 do you have an idea what might be causing this?

**Comment by vadrian89** [comment]
Strange, are you sure that you are deploying from that path? Are the libraries deployed from /opt/qt510 and not another installation?

**Comment by vadrian89** [comment]
@ukinoki the argument -extra-plugins is there in case linuxdeployqt does not deploy a plugin automatically, it does not filter plugins already deployed.   
Without the argument it still deploys all the sql plugins, am I right?   

@probonopd It is a message bug, as you can see libqsqlmysql.so still is in the final pluginList before mediaservice plugins and afterwards, it is there because linuxdeployqt deploys the entire sqldriver directory, whenever linuxdeployqt detects the Qt5Sql library.   

The message bug is here: 
```
if (!pluginList.contains(plugin)) {
                    if (QFile::exists(pluginSourcePath + "/" + plugin)) {
                        pluginList.append(plugin);
                        LogDebug() << plugin << "appended";
                    }
                    else {
                        LogDebug() << "The plugin" << plugin << "was already deployed." ;
                    }
                }
                else {
                    LogWarning() << "The plugin" << pluginSourcePath + "/" + plugin << "could not be found. Please check spelling and try again!";
                }
```

It should be this way: 
```
if (!pluginList.contains(plugin)) {
                    if (QFile::exists(pluginSourcePath + "/" + plugin)) {
                        pluginList.append(plugin);
                        LogDebug() << plugin << "appended";
                    }
                    else {
                        LogWarning() <<"The plugin" << pluginSourcePath + "/" + plugin << "could not be found. Please check spelling and try again!";
                    }
                }
                else {
                    LogDebug() <<  "The plugin" << plugin << "was already deployed." ;
                }
```


@probonopd think you can add the messages? It would take me longer.

**Comment by probonopd** [comment]
Like this? https://github.com/probonopd/linuxdeployqt/commit/ac2d5c21800cb24048aebf371165ddbde229544d (acually I meant to do this on a branch... well)

**Comment by ukinoki** [comment]
@vadrian89 yes, the sql plugins are deployed even without the argument...
