### ISSUE TITLE
Icon not showing when executing AppImage

### ISSUE THREAD

**Issue by PabloF7** [probonopd/linuxdeployqt#304]
Hi,
Should the application show the application icon when i execute it? It works fine, but it shows no icon.
I've read other issues related to icons, but could not solve this.
Icons inside application are shown correctly, i'm talking about the application icon.

linuxdeployqt.AppImage executes correctly and gives me no error.
Thanks

**Comment by PabloF7** [comment]
Nevermind, i was confused in the relative path to icon. My bad, but i was with that problem for a long time.
Zorry...

**Comment by probonopd** [comment]
Which icon are you missing? Please add a screenshot. Thanks.

**Comment by PabloF7** [comment]
I was missing the icon that should appear in task bar, but i had a mistake in the path i had written in source code. 
Thanks. Now i'm having some problems trying to add the app to AppImage https://github.com/AppImage/appimage.github.io.

**Comment by TheAssassin** [comment]
Closing as invalid.
