### ISSUE TITLE
OBS: linuxdeployqt does not show version

### ISSUE THREAD

**Issue by probonopd** [probonopd/linuxdeployqt#308]
https://github.com/probonopd/linuxdeployqt/blob/63e768b82580a3f10ae1461f22e4f530f038f824/tools/linuxdeployqt/CMakeLists.txt#L6-L10

This does not seem to work on OBS at the moment. Not sure whether the fault is in our project or at OBS.

Reference:
https://bugzilla.opensuse.org/show_bug.cgi?id=1101257

cc @TheAssassin @adrianschroeter

**Comment by TheAssassin** [comment]
@probonopd apparently the Git data isn't available. `<local dev build>` is actually correct, it's not a Travis build.

**Comment by probonopd** [comment]
How can we make sure that if they do a `git pull` and build it from there, the git commit hash gets used?

**Comment by probonopd** [comment]
And how can we ensure the same in case they download the zip or tarball? (If possible)

**Comment by probonopd** [comment]
Alternatively, how could they best "hand over" the version information from their metadata?

**Comment by TheAssassin** [comment]
Well, I don't want to implement workarounds for limitations of a single build system. I can't help they're not including the Git commit history. They could, without violating their "no internet connection during builds" policy. Please ask OBS to fix this.

**Comment by probonopd** [comment]
Is there any way to get the version into the build that does not require to be online at the moment of the build?

**Comment by TheAssassin** [comment]
It's as simple as including `.git`. Then, it's a Git repository. The version information isn't fetched from the Internet right from the commit history, that's why I said it can be fixed without online access.

**Comment by TheAssassin** [comment]
@probonopd the app is still using qmake for anything but development.

**Comment by TheAssassin** [comment]
We decided to build using CMake on OBS and set the Git data via CMake parameters in the spec file. See also #310.

**Comment by probonopd** [comment]
Thank you for looking into this and for finding a solution. Please ping me once it is live on OBS.

**Comment by TheAssassin** [comment]
Ping @probonopd

**Comment by probonopd** [comment]
Wow. The quickest ping ever. Cool :+1:
