### ISSUE TITLE
Build on OBS results in corrupted binary in AppImage

### ISSUE THREAD

**Issue by t-paul** [probonopd/linuxdeployqt#313]
Looks similar to #29, but happens since maybe 2 or 3 weeks on [OBS](https://build.opensuse.org/package/show/home:t-paul/OpenSCAD) - [logs](https://build.opensuse.org/package/live_build_log/home:t-paul/OpenSCAD/AppImage/x86_64).

I could not find a way to get builds working again yet.

```
$ ./OpenSCAD-Nightly-0-Build2280.3.glibc2.14-x86_64.AppImage 
openscad: openscad: no version information available (required by openscad)
...
openscad: openscad: no version information available (required by openscad)
openscad: relocation error: openscad: symbol  version  not defined in file  with link time reference
```

**Comment by probonopd** [comment]
Which version of Qt are you using?

**Comment by probonopd** [comment]
Can we find out whether the patchelf version used by OBS has recently changed? cc @TheAssassin

**Comment by TheAssassin** [comment]
`patchelf --version` maybe?

**Comment by t-paul** [comment]
Right now that gives `patchelf 0.8` for the AppImage repo build.

**Comment by probonopd** [comment]
cc @adrianschroeter

**Comment by TheAssassin** [comment]
I doubt @adrianschroeter will react to that, as he never reacted to @mentions before.

**Comment by probonopd** [comment]
@t-paul do you have any chance of making an AppImage outside of OBS (e.g., using Travis CI as described in the linuxdeployqt README), to see whether that works?

@TheAssassin maybe you can point him here via IRC, especially if something appears to be broken on OBS which seems to be fine outside of OBS.

**Comment by adrianschroeter** [comment]
some times I do;) (sorry, way to much noise in inbox of stuff like this)

you have full control over the build env. Just add KDE:Qt5/openSUSE_Leap_42.3 as first path element in your AppImage repo (in project meta) to get a newer qt5.

@probonopd this is how you can find out which patchelf is used (from 42.3 here, never updated):
```

# osc buildinfo science:unstable FreeCAD.appimage AppImage             x86_64 | grep patchelf
  <bdep name="patchelf" version="0.8" release="9.2" arch="x86_64" project="openSUSE:Leap:42.3" repository="standard" />

```

**Comment by probonopd** [comment]
Thank @adrianschroeter for checking in from time to time, greatly appreciated! (Only together can we make this fly - there are some intricacies of OBS that I still don't fully understand yet.)

**Comment by t-paul** [comment]
Updated `appimage.yml` with `-no-strip`.

**Comment by t-paul** [comment]
That seems to work without even increasing the image size (because it was already stripped by the build?). - https://download.opensuse.org/repositories/home:/t-paul/AppImage/OpenSCAD-Nightly-latest-x86_64.AppImage

**Comment by t-paul** [comment]
Closing, the no-strip option fixes the problem.
