### ISSUE TITLE
extra-plugins "forget" plugins

### ISSUE THREAD

**Issue by magisterRab** [probonopd/linuxdeployqt#314]
Command
 -extra-plugins=imageformats/libqsvg.so,iconengines/libqsvgicon.so
sometimes forget to put these plugins. This for some reason depends on the binary file. On one binary file it works, on the other it does not work.
There is a feeling that plugin sql affects the this

log deploy:
ERROR: ldd outputLine: "libpq.so.5 => not found"
ERROR: for binary: "/opt/Qt/5.10.1/gcc_64/plugins/sqldrivers/libqsqlpsql.so"
ERROR: Please ensure that all libraries can be found by ldd. Aborting.

Several times I saw in the log
WARNING: The plugin "/opt/Qt/5.10.1/gcc_64/plugins/imageformats/libqsvg.so" could not be found. Please check spelling and try again!
WARNING: The plugin "/opt/Qt/5.10.1/gcc_64/plugins/iconengines/libqsvgicon.so" could not be found. Please check spelling and try again!

But this does not always happen, and these files are there

**Comment by probonopd** [comment]
Very strange. Whenever you see

```
ERROR: ldd outputLine: "... => not found"
```

then the `ldd` tool invoked by linuxdeployqt cannot find a needed library. Possibly `export LD_LIBRARY_PATH=...` can help in those situations.

**Comment by magisterRab** [comment]
[binarys.zip](https://github.com/probonopd/linuxdeployqt/files/2345285/binarys.zip)

Here is an example. Empty main project. Differences in the sql module
QT += webengine webenginewidgets network websockets sql

**Comment by probonopd** [comment]
Can you set `LD_LIBRARY_PATH` so that `ldd` finds the libraries in question?

**Comment by magisterRab** [comment]
I understood. He didn't find the library and stopped the deploy. This week I'm very stupid :)
Can I somehow forbid linking this library? Flag -exclude-libs=libqsqlpsql.so does not help

**Comment by probonopd** [comment]
#253 suggests `-exclude-libs=libqsqlibase,libqsqlodbc,libqsqlpsql,libqsqltds`

**Comment by magisterRab** [comment]
Thank you. I think the issue can be closed
