### ISSUE TITLE
LD_LIBRARY_PATH not recognised?

### ISSUE THREAD

**Issue by IlyaBizyaev** [probonopd/linuxdeployqt#318]
After building my application and installing it to AppDir, I launch linuxdeployqt and get the following error:
```
ERROR: ldd outputLine: "/home/ilya/Projects/MyApp/AppDir/usr/bin/myapp: /usr/lib64/libQt5Core.so.5: version `Qt_5.11' not found (required by /home/ilya/Projects/MyApp/AppDir/usr/bin/myapp)"
```
In a clean terminal session ldd finds all libraries without issues:
```
        ...
        libgloox.so.17 => /usr/lib64/libgloox.so.17 (0x00007fd96d974000)
        libQt5Qml.so.5 => /home/ilya/Qt/5.11.1/gcc_64/lib/libQt5Qml.so.5 (0x00007fd96d37f000)
        libQt5Gui.so.5 => /home/ilya/Qt/5.11.1/gcc_64/lib/libQt5Gui.so.5 (0x00007fd96c7ee000)
        libQt5Core.so.5 => /home/ilya/Qt/5.11.1/gcc_64/lib/libQt5Core.so.5 (0x00007fd96c094000)
        ...
```
According to #179 I should set `LD_LIBRARY_PATH`; however, that has no effect.

How should I specify additional library search paths for linuxdeployqt?

**Comment by probonopd** [comment]
Yes, linuxdeployqt is identifying the Qt installation based on where qmake is. I hope this is OK, otherwise let me know and I will reopen.
