### ISSUE TITLE
Proper way to deploy 3rdparty Qt Quick plugins

### ISSUE THREAD

**Issue by IlyaBizyaev** [probonopd/linuxdeployqt#319]
Hello! What is the recommended way to add custom Qt Quick plugins into the AppImage?

E.g. I use Kirigami, and my build script uses this trick:
```
./3rdparty/linuxdeployqt-continuous-x86_64.AppImage ./AppDir/usr/share/applications/kaidan.desktop -qmake=$QT_LINUX/bin/qmake -qmldir=./src/qml/ -bundle-non-qt-libs
    
cp $KIRIGAMI_BUILD/lib64/libKF5Kirigami2.so* ./AppDir/usr/lib
cp -r $KIRIGAMI_BUILD/lib64/qml/org ./AppDir/usr/qml
    
./3rdparty/linuxdeployqt-continuous-x86_64.AppImage ./AppDir/usr/share/applications/kaidan.desktop -qmake=$QT_LINUX/bin/qmake -qmldir=./src/qml/ -appimage
```

It works, but requires to launch linuxdeployqt twice.

**Comment by IlyaBizyaev** [comment]
Fair point! :)
Now it's one run, but still feels a bit hacky.

**Comment by TheAssassin** [comment]
Not at all. That's how it works, if [your build system doesn't do the job correctly](https://docs.appimage.org/packaging-guide/native-binaries.html#using-the-build-system-to-build-the-basic-appdir).

Closing as resolved.

**Comment by IlyaBizyaev** [comment]
My app uses CMake. Is it possible to do the job correctly with it?

**Comment by TheAssassin** [comment]
Make it install all your files using https://cmake.org/cmake/help/v3.12/command/install.html, and then follow the guide.

**Comment by IlyaBizyaev** [comment]
qmlimportscanner is capable of receiving multiple `-importPath` arguments, so I'm able to specify 3rdparty module location and get correct output for it:
```
    ...
    {
        "classname": "KirigamiPlugin",
        "name": "org.kde.kirigami",
        "path": "/tmp/kirigami-linux-build/lib64/qml/org/kde/kirigami.2",
        "plugin": "kirigamiplugin",
        "relativePath": "org/kde/kirigami.2",
        "type": "module",
        "version": "2.0"
    },
    ...
```
Maybe linuxdeployqt should be able to accept a list of QML import paths or at least use QML2_IMPORT_PATH env variable?

https://github.com/probonopd/linuxdeployqt/blob/master/tools/linuxdeployqt/shared.cpp#L1561

**Comment by probonopd** [comment]
You can pass in additional directories using one or more `-qml` options,

https://github.com/probonopd/linuxdeployqt/blob/c6c68984648f9908b304b5414792531feb1b4239/tools/linuxdeployqt/shared.cpp#L1553-L1559

Does this solve it for you @IlyaBizyaev?

**Comment by IlyaBizyaev** [comment]
No, unfortunately, it doesn't.

Passing a path as a `-qmldir` option to linuxdeployqt makes it add that path as a `-rootPath` argument to qmlimportscanner (see the snippet above). But `rootPath` is a location of application's *.qml files, not QML library install path, and it's treated accordingly (scanned for `import *`).

By default libraries that are needed to satisfy those imports are only searched in the Qt installation, qml subdirectory. You can specify additional search paths at runtime using the `QML2_IMPORT_PATH` env variable, but here the goal is to bundle them into the AppImage to avoid separate distribution. To do that, we need to ensure they are located by qmlimportscanner, which can be achieved by passing the `-importPath` option to it (notice the difference in name).

linuxdeployqt, however, only [passes](https://github.com/probonopd/linuxdeployqt/blob/master/tools/linuxdeployqt/shared.cpp#L1561) that qml subdirectory of the Qt installation (the default location), so one cannot specify custom locations for library search. As a hack one can create a link to the custom location from inside the Qt installation, but it is inconvenient if a distribution-provided Qt is used (requires root permissions) or there are multiple versions of this library.

As a solution, linuxdeployqt could provide a flag like `-qmlimport` and process it just like `-qmldir`, but for the `-importPath` argument. Or, alternatively, it could read the `QML2_IMPORT_PATH` env variable, which is also widely used in Qt.

**Comment by probonopd** [comment]
Thanks @IlyaBizyaev for the explanation. Let me understand this correctly:

If a QML import needs a .so file as a dependency, then the path to the directory in which the .so file resides needs to be passed in using `-importPath`?

What is the scenario in which you woould need to pass in an `-importPath` rather than a `-rootPath`? (I was assuming that the latter was for application-provided QML files; and that Qt-provided QML files is nothing that need to be changed.)

**Comment by IlyaBizyaev** [comment]
> I was assuming that `-rootPath` was for application-provided QML files

Yeah, that's right :)
> and that Qt-provided QML files is nothing that need to be changed

The idea is not to replace Qt files, but to use a Qt Quick library that is neither part of Qt nor part of the application.

Consider the following situation:
![bitmap](https://user-images.githubusercontent.com/11175213/46429409-0846c680-c74f-11e8-8675-88af67ebe3d4.png)
> If a QML import needs a .so file as a dependency, then the path to the directory in which the .so file resides needs to be passed in using `-importPath`?

Not exactly. Qt Quick uses the idea of import paths, which basically are paths to the root directories of package installations, kind of like Java's [CLASSPATH](https://en.wikipedia.org/wiki/Classpath_(Java)#Supplying_as_application_argument). E.g. if I have a Qt quick module imported like this:
```
import com.example.test 1.0
```
and located in `/home/user/dev/quick-modules/com/example/test`, I need to specify `/home/user/dev/quick-modules/` as the import path, and qmlimportscanner will locate the package. Qt will then read a `qmldir` file inside it:
```
module com.example.test
plugin testplugin
classname TestPlugin
depends QtQuick.Controls 2.0
depends QtGraphicalEffects 1.0
designersupported
```
and load `libtestplugin.so` from this directory.

For example, this is how Kirigami looks when built:
![screenshot_20181003_211633](https://user-images.githubusercontent.com/11175213/46430465-ad629e80-c751-11e8-8da9-52f1f6316787.png)

> if the application can run on the build system prior to running linuxdeployqt, then clearly all the needed information must be "there" somewhere?

It can be run thanks to the `QML2_IMPORT_PATH` variable queried by Qt at startup:
```
QML2_IMPORT_PATH=/tmp/kirigami-linux-build/lib64/qml ./build/bin/kaidan
```
Without this definition, you get an error like this:
```
QQmlApplicationEngine failed to load component
qrc:/qml/main.qml:33 module "org.kde.kirigami" is not installed
```
— which is explained by the fact that the QML module is not required at compilation, so paths don't get recorded. Qt searches for modules in their [default locations](http://doc.qt.io/qt-5/qtqml-syntax-imports.html#qml-import-path), and on Linux it's ok and works for all sorts of packages.

> As a solution, linuxdeployqt could provide a flag like `-qmlimport` and process it just like `-qmldir`, but for the `-importPath` argument.

From how I understand the code, a block like this:
https://github.com/probonopd/linuxdeployqt/blob/c6c68984648f9908b304b5414792531feb1b4239/tools/linuxdeployqt/main.cpp#L408-L415
will need to be added for `-qmlimport`, and then a loop like this:
https://github.com/probonopd/linuxdeployqt/blob/c6c68984648f9908b304b5414792531feb1b4239/tools/linuxdeployqt/shared.cpp#L1553-L1559
to add `-importPath`s to qmlimportscanner's call.

> Would it be possible for you to send a PR with the requested changes?

Yes it would, but will take me a while to build linuxdeployqt from source code.

**Comment by probonopd** [comment]
Thank you very much for your detailed explanation, I think I understand it now. Would highly welcome a PR. Again, thank you very much.

**Comment by IlyaBizyaev** [comment]
Opened a [pull request](https://github.com/probonopd/linuxdeployqt/pull/320).

**Comment by probonopd** [comment]
...merged 👍 💯

**Comment by trmdi** [comment]
Hello, could you please tell me how to apply these flags for my case? https://build.opensuse.org/package/view_file/home:trmdi:test/latte-dock/appimage.yml?expand=1
I can't find it anywhere in the docs.

**Comment by probonopd** [comment]
Please see

https://github.com/probonopd/linuxdeployqt/pull/320/files#diff-1e7279c8098c42e32e06f1ef908c14e7b616ac746d56043cab30f041f52c61edR92
