### ISSUE TITLE
Build products not uploaded to GitHub Releases

### ISSUE THREAD

**Issue by benma** [probonopd/linuxdeployqt#322]
Hi. It would be great if you could make a new tag and release. Thanks.

**Comment by probonopd** [comment]
We are generally trying to do everything with continuous builds, which you are free to mirror a "known good" version of. Would that be sufficient for your use case?

**Comment by benma** [comment]
Why not both (regular releases and continuous ones)? :) 

It would be useful to have an official release (as you have in the past), so everyone can benefit instead of repeating the work of mirroring, which is upfront work, but also more work in keeping in sync. Continuous builds are nice to have a new version to test without a hassle, but it can also be unreliable. 

Please let me know.

**Comment by benma** [comment]
@probonopd thanks so much, I saw you tagge https://github.com/probonopd/linuxdeployqt/releases/tag/5.

Could you also add `linuxdeployqt-continuous-x86_64.AppImage` to the release files?

**Comment by TheAssassin** [comment]
@probonopd you know that uploadtool can upload new tags just fine? You shouldn't rename tags, but create them from scratch, build them properly on Travis CI and have uploadtool create the release for the tag.

**Comment by probonopd** [comment]
I created a release in the GUI, waiting for uploadtool to upload the build artifacts, but it didn't happen...

**Comment by probonopd** [comment]
...and as a result broke continuous. Boy do I dislike this releasing chore...

**Comment by TheAssassin** [comment]
@probonopd well your deployment stuff is just horribly out of date then. Especially CD infrastructure needs maintenance...

**Comment by probonopd** [comment]
How exactly do you make a release with build artefacts there, using the GitHub web interface?

**Comment by TheAssassin** [comment]
@probonopd just create a new tag for the latest commit. I never used the GitHub web interface for that (because, why?), but it's surely possible. That triggers Travis, and what your Travis stuff does with the information it's a tag that is built is none of Travis' concerns. uploadtool evaluates the build type vars, recognizes whether a tag is built, and creates a new release in that case instead of using `continuous`.

**Comment by benma** [comment]
@probonopd now everything seems good. Thanks a lot! :heart:

**Comment by probonopd** [comment]
@TheAssassin 

https://docs.travis-ci.com/user/environment-variables

> TRAVIS_BRANCH: for builds triggered by a tag, this is the same as the name of the tag (TRAVIS_TAG).

Could this be used?

**Comment by TheAssassin** [comment]
Perhaps `[ "$TRAVIS_TAG" != "" ]`? Or `[ "$TRAVIS_TAG" == "$TRAVIS_BRANCH" ]`?

**Comment by probonopd** [comment]
If `[ "$TRAVIS_TAG" == "$TRAVIS_BRANCH" ]` then do __NOT__ do `if [ "$TRAVIS_BRANCH" != "master" ]; then export TRAVIS_EVENT_TYPE=pull_request; fi`.

**Comment by TheAssassin** [comment]
```bash
if [ "$TRAVIS_TAG" != "$TRAVIS_BRANCH" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
    ....
```

**Comment by probonopd** [comment]
lgtm, adding it. Thanks!

**Comment by probonopd** [comment]
Seems to be working for me in this repo. Do you want to add it to AppImageKit too, @TheAssassin? Or upstream it to uploadtool?

**Comment by TheAssassin** [comment]
Short term fix will be to replace that part in all existing Travis scripts. Long term should be uploadtool ofc, but I don't have time to test that now.

**Comment by TheAssassin** [comment]
Closing as resolved.
