### ISSUE TITLE
Svg Icons don't show up in AppImage

### ISSUE THREAD

**Issue by DamirPorobic** [probonopd/linuxdeployqt#325]
After switching some icons from PNG to SVG in my application, they don't show up anymore in the AppImage. When building from source, everything works fine. 

AppImage:
![image](https://user-images.githubusercontent.com/12796236/46930574-acc9e200-d046-11e8-8eac-66a8e4449042.png)

Build from Source:
![image](https://user-images.githubusercontent.com/12796236/46930600-d5ea7280-d046-11e8-91e6-a831977ab036.png)

Am I missing something? Except for the icons, nothing changed.

**Comment by probonopd** [comment]
Maybe some Qt plugins need to be bundled. What happens if you use the `-extra-plugins=iconengines,imageformats` argument for `linuxdeployqt`?

**Comment by probonopd** [comment]
It _should_ work if you add it to either. Does `/opt/qt56/plugins/iconengines` exist?

**Comment by DamirPorobic** [comment]
Looks like its not there:
```
$ ls /opt/qt56/plugins
bearer
designer
generic
imageformats
platforminputcontexts
platforms
platformthemes
printsupport
qmltooling
sqldrivers
xcbglintegrations
```
Any idea what provides it? I thought it was part of qtbase.

**Comment by probonopd** [comment]
Excellent question, really. Should ask some of the Qt folks.

**Comment by DamirPorobic** [comment]
It looks it was in `qt56svg` 

With `qt56svg` installed and `-extra-plugins=iconengines,imageformats` set in `linuxdeployqt` the icon finally show up.
