### ISSUE TITLE
Building AppImage in docker container fails to find fuse

### ISSUE THREAD

**Issue by DamirPorobic** [probonopd/linuxdeployqt#326]
Is it possible to build AppImage inside a docker container? I've started with building the AppImage on travis CI but was not happy with the UI that I get when building on Ubuntu, so I'm trying to build it on a OpenSUSE container. I'm currently stuck with:

```
a5087695d7ef:/home/dporobic # ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -bundle-non-qt-libs
fuse: device not found, try 'modprobe fuse' first

Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
open dir error: No such file or directory
```
Prior to this error, I was following this guide https://github.com/AppImage/AppImageKit/wiki/FUSE and installed fuse but linuxdeployqt was complaining about not being able to find libfuse:
`dlopen(): error loading libfuse.so.2`

So I installed the library `zypper in libfuse2` but now it's complaining that it's not able to find the device and I can't run modprobe in the container.

**Comment by DamirPorobic** [comment]
OK, looks like I can mitigate this issue by running the docker container with the `--privileged` flag. After that I had no problems building the appImage.

**Comment by TheAssassin** [comment]
@DamirPorobic using `--privileged` is a security nightmare. Your problem is not that you cannot build AppImages in FUSE. Your problem is that you failed to run the linuxdeployqt AppImage in a standard Docker container, due to lack of FUSE there. Please try to be more precise when choosing issue titles.

You can simply [extract any AppImage](https://docs.appimage.org/user-guide/run-appimages.html#extract-the-contents-of-an-appimage), and run the AppImage's contents by calling `squashfs-root/AppDir`. A shortcut for that has been implemented recently, i.e., in more recent AppImages, you can automate this using `--appimage-extract-and-run`. Please beware of the drawbacks, and don't advertise that option for anything but usage in Docker.

**Comment by probonopd** [comment]
> I've started with building the AppImage on travis CI but was not happy with the UI that I get when building on Ubuntu,

What do you mean by this? AppImageKit does not have a GUI, and in order to compile GUI apps that go into an AppImage you don't need to compile AppImageKit yourself.

**Comment by TheAssassin** [comment]
@DamirPorobic probably referred to the really old Qt version that was available there from the trusty repos.

**Comment by DamirPorobic** [comment]
> What do you mean by this? AppImageKit does not have a GUI, and in order to compile a GUI app that goes into an AppImage you don't need to compile AppImageKit yourself.

I don't mean the AppImage GUI but GUI of my application. The same application looks different when build from source:
![image](https://user-images.githubusercontent.com/12796236/47235095-43e0c200-d3d8-11e8-9d66-63c94717766a.png)

Or run as AppImage:
![image](https://user-images.githubusercontent.com/12796236/47235122-5955ec00-d3d8-11e8-8b9e-e1cb1552853b.png)

In both cases I use the same Qt version 5.6.2.
All the time I thought it was related to the fact that the image was build on a Ubuntu worker on Travis CI, but today when I tried build it in a OpenSUSE docker container, it looked the same.

**Comment by TheAssassin** [comment]
@DamirPorobic the issue is not in the Qt version but in the bundled Qt theme vs. system Qt theme.

You might want to try a more recent version of Qt. There's PPAs provided by Stephan Binner for trusty, allowing to build AppImages on trusty with more recent versions of Qt. We use them everywhere.

**Comment by probonopd** [comment]
And possibly bundle some additional plugins. It’s kinda black magic...

**Comment by DamirPorobic** [comment]
I have been using this one which I think is from him:
```
before_install:
- sudo add-apt-repository ppa:beineri/opt-qt562-trusty -y
```
Also, as said, when build in a OpenSUSE docker container, it looked the same.

**Comment by DamirPorobic** [comment]
One more think, don't know if it's related but when I search for one of the plugins on the Travis CI worker, I find the installed qt56 version, but there pops up also this qt4 version and all the used widget do look like as if they come from an older version of Qt. Could that be somehow related?

```
$ sudo find / -name "iconengines"
/opt/qt56/plugins/iconengines
/usr/lib/x86_64-linux-gnu/qt4/plugins/iconengines
```
Here again the controls next to each other, left appImage, right from source on OpenSUSE
![image](https://user-images.githubusercontent.com/12796236/47253520-47b22a00-d454-11e8-96ad-60aae2d95d68.png)

**Comment by probonopd** [comment]
I don't think Qt4 plugins can mix and match with Qt5 plugins. Are you sure your application was compiled with the Qt version you intended?

**Comment by DamirPorobic** [comment]
I hope it was, here is the yml file, if you could have a quick look: 
https://github.com/DamirPorobic/ksnip/blob/master/.travis.yml

**Comment by probonopd** [comment]
Lgtm on first glance. This whole Qt theming thing is a bit a mystery to me, to be honest.
