### ISSUE TITLE
Fedora 29 - Could not initialize GLX

### ISSUE THREAD

**Issue by Dekker1** [probonopd/linuxdeployqt#331]
Our Qt application is build on Ubuntu 16.04 and is using Qt 5.9.6 and it's been recently broad to my attention that the build of our application doesn't work on Fedora 29. I've confirmed that they work on a clean installation of Fedora 28, but not on a clean installation of Fedora 29. Running the AppImage (or the extracted version) gives the following error:
```
Could not initialize GLX
Aborted (core dumped)
```

I've looked through the changes in Fedora 29 and I do see that the GLIBC version has been updated, but I would have expected a different error message if this was the problem. I'm afraid I'm not knowledgable enough on Qt to spot any other relevant changes.

Has anybody come across this error before or know what the breaking change in Fedora 29 is? Otherwise is there any way in which more information about the problem can be acquired?

**Comment by TheAssassin** [comment]
@Dekker1 have you tried to run your application through strace? Does it load the right GPU driver libs (i.e., the one from the system, not some (accidentally) bundled stuff)?

**Comment by probonopd** [comment]
Similar:
* https://github.com/GoldenCheetah/GoldenCheetah/issues/2915
* https://github.com/SuperTux/supertux/issues/928

Please try:

```
./MiniZincIDE-build37336228-x86_64.AppImage --appimage-extract
find squashfs-root/ -iname '*libxcb-dri3*' -delete
./squashfs-root/AppRun
```

**Comment by TheAssassin** [comment]
@Dekker1 please feel free to add that command to your build scripts, it will take a while until a new version of linuxdeployqt is available. Once the issue here is closed, you can remove it again, I guess.

**Comment by Dekker1** [comment]
Okay, thank you guys for the assistance! Just a note that linuxdeployqt also includes `libxcb-dri2.so.0`, which seems awfully similar and also seems to be removable for all virtual machines I tend to test on. It might be worth investigating if this library should also not be included.

**Comment by probonopd** [comment]
3a003b1 should have it, so the next continuous build that should appear in a couple of minutes should contain the fix. Please test and then close the issue if it works, thank you.

**Comment by Dekker1** [comment]
@probonopd I've been trying to find the download for the newest continuous build, but the link in the readme and in the releases folder both point me to https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage and this has been updated last on 16 october. `-version` on the build reports like the Releases page:
```linuxdeployqt 4 (commit d183578), build 576 built on 2018-10-15 18:50:09 UTC```

**Comment by probonopd** [comment]
Seems like we have a bug that prevents builds from being uploaded. In the meantime, please retry using 

https://transfer.sh/MHueQ/linuxdeployqt-continuous-x86_64.AppImage

**Comment by probonopd** [comment]
Should be working now? @Dekker1?

**Comment by Dekker1** [comment]
A new build for my project with the new continuous build of linuxdeployqt removes the need for the workaround. Everything seems to be successfully working again. Thank you guys for all the help!

**Comment by emerson-drogaria** [comment]
Try this command on terminal:

`export QT_XCB_GL_INTEGRATION=none`
