### ISSUE TITLE
relocation error: version version Qt_5_PRIVATE_API not defined in file libQt5Gui.so.5 with link time reference

### ISSUE THREAD

**Issue by danividanivi** [probonopd/linuxdeployqt#333]
My app is working fine when running from build directory.
However, once I create the AppImage with 

`./linuxdeployqt-continuous-x86_64.AppImage ~/build-src-Desktop_Qt_5_11_2_GCC_64bit-Default/app.desktop -appimage`

When I try to run the result file, I get this error

`./app-x86_64.AppImage: relocation error: /tmp/.mount_ctt-x80HQgo5/APP-0.1.1-Linux/bin/../lib/libQt5Widgets.so.5: symbol _ZN23QPlatformSystemTrayIcon20contextMenuRequestedE6QPointPK15QPlatformScreen version Qt_5_PRIVATE_API not defined in file libQt5Gui.so.5 with link time reference`

**Comment by probonopd** [comment]
Hi @danividanivi and welcome. Which build OS and version and which Qt version are you using? The only tested and known-working combination is Ubuntu 14.04 (trusty) with Qt 4 or Qt 5.8+ from https://launchpad.net/~beineri as described in https://github.com/probonopd/linuxdeployqt#using-linuxdeployqt-with-travis-ci

**Comment by danividanivi** [comment]
> Hi @danividanivi and welcome. Which build OS and version and which Qt version are you using? The only tested and known-working combination is Ubuntu 14.04 (trusty) with Qt 4 or Qt 5.8+ from https://launchpad.net/~beineri as described in https://github.com/probonopd/linuxdeployqt#using-linuxdeployqt-with-travis-ci

Thank you for the information.
I was unaware of that, I am using Ubuntu 18.04 with Qt 5.11.2.

**Comment by probonopd** [comment]
Please retry using Ubuntu 14.04 (trusty) and Qt 5.8+ from https://launchpad.net/~beineri, thanks.
