### ISSUE TITLE
Builds do not get uploaded

### ISSUE THREAD

**Issue by probonopd** [probonopd/linuxdeployqt#334]
Commits do not result in new continuous builds being uploaded. Example:
https://github.com/probonopd/linuxdeployqt/commit/3a003b1687ef6fc9fc5248ebfd9437a864686443

https://travis-ci.org/probonopd/linuxdeployqt/builds/460617347#L1864-L1876

```
bash ./upload.sh ./linuxdeployqt-*.AppImage*
Release uploading disabled for pull requests
```

__Why?__

I am puzzled here, since this is not a pull request and the message above should only appear if ` "$TRAVIS_EVENT_TYPE" == "pull_request"`.

https://github.com/probonopd/uploadtool/blob/27066299131e9af259821bdc4508c8469eb1997c/upload.sh#L96-L110

Any idea @TheAssassin?

**Comment by probonopd** [comment]
__EDIT:__ I see that `.travis.yml` has 

```
https://github.com/probonopd/linuxdeployqt/blob/b7b68612343ea63772a8caa58899c022d25e7c29/.travis.yml#L23
```

I vaguely remember that this had to do with someone wanting releases...

**Comment by probonopd** [comment]
Looks like this is a continuation of https://github.com/probonopd/linuxdeployqt/issues/322 @TheAssassin

**Comment by TheAssassin** [comment]
```
- if [ "$TRAVIS_TAG" != "$TRAVIS_BRANCH" ] && [ "$TRAVIS_BRANCH" == "master" ]; then export TRAVIS_EVENT_TYPE=pull_request; fi
```

The second check is broken in there. Noticed and fixed that in some other repos already. Just use this instead:

```
- if [ "$TRAVIS_TAG" != "$TRAVIS_BRANCH" ] && [ "$TRAVIS_BRANCH" != "master" ]; then export TRAVIS_EVENT_TYPE=pull_request; fi
```
