### ISSUE TITLE
depends on icu56

### ISSUE THREAD

**Issue by r3d9u11** [probonopd/linuxdeployqt#337]
Hi. I have excepted compilation with:
```
:-1: warning: libicui18n.so.56, needed by /home/imx6/Qt/5.12.0/gcc_64/lib/libQt5Core.so, not found (try using -rpath or -rpath-link)
:-1: warning: libicuuc.so.56, needed by /home/imx6/Qt/5.12.0/gcc_64/lib/libQt5Core.so, not found (try using -rpath or -rpath-link)
:-1: warning: libicudata.so.56, needed by /home/imx6/Qt/5.12.0/gcc_64/lib/libQt5Core.so, not found (try using -rpath or -rpath-link)
/home/imx6/Qt/5.12.0/gcc_64/lib/libQt5Core.so:-1: error: undefined reference to `ucal_clone_56'
/home/imx6/Qt/5.12.0/gcc_64/lib/libQt5Core.so:-1: error: undefined reference to `ucnv_close_56'
...
...
```
Is it really needed a strong conformity of icu versions (56 only)? _For example on Ubutnu 16.04 / Linux Mint 18.x available only ICU 55, ubuntu 18.04+ (as I know) have ICU 60 in repos._
Is there way to workaround that?
Thanks.

**Comment by probonopd** [comment]
Please give some context. What are you trying to do when you see this error? Which system and version are you building on?

The only tested and supported configuration at this time is Ubuntu 14.04 (trusty), the oldest currently still-supported distribution release, with Qt from https://launchpad.net/~beineri.

**Comment by r3d9u11** [comment]
@probonopd I cloned this repository, then I opened tools/linuxdeployqt.pro in QtCreator with Qt 5.12.0 (which was installed via official online installer) and tried to build project.
No, I didn't try to do some cross-compilation for this tool. I tried to use default (was autodetected) version of Qt 5.12.0 for x86_64.

**Comment by probonopd** [comment]
Do you have a pressing need to compile it yourself? We provide an AppImage of `linuxdeployqt` which we generally recommend, since it is built, tested, and supported by us. We don't have the time to debug multiple different built systems with "random" versions of everything.

**Comment by r3d9u11** [comment]
@probonopd ah, no, I don't need to compile it by myself. I'll use an AppImage. Thanks!

**Comment by probonopd** [comment]
If you are building AppImages (or other types of portable binaries) please remember to compile your application on the oldest still-supported target system, e.g., Ubuntu 14.04 (trusty) so that the binaries will run on all still-supported Linux distributions. Thanks!
