### ISSUE TITLE
Deploy SVG icon engine

### ISSUE THREAD

**Issue by fathomssen** [probonopd/linuxdeployqt#36]
When using SVG icons as system tray icon or within a Qt application, the SVG icon engine has to be deployed as well.

For a simple workaround, please have a look at https://github.com/fathomssen/redtimer/blob/f34d6c5b6fced0d672978fd38e12b9b7fa6b51a1/.travis/deploy.linux.sh#L23-L25 as discussed in issue https://github.com/fathomssen/redtimer/issues/71.

Best regards
Frederick Thomssen

**Comment by probonopd** [comment]
Thanks for reporting this. Do you have an idea how linuxdeployqt might detect under which circumstances libqsvgicon.so or other iconengines should be deployed?

**Comment by fathomssen** [comment]
Well, I guess that you always have to deploy it when including QtSvg...

**Comment by probonopd** [comment]
OK, so current hypothesis: 
* Also deploy `plugins/iconengines/libqsvgicon.so` whenever `libQt5Svg.so.*` is about to be deployed.
As this is about SVG icons in QIcon, not about generic SVG support in QImage, can we be sure that this hypothesis is correct?

**Comment by bjorn** [comment]
> As this is about SVG icons in QIcon, not about generic SVG support in QImage, can we be sure that this hypothesis is correct?

For the generic SVG support in QImage you are already shipping the image plugin when QtSvg is shipping. You should indeed do the same with the SVG icon engine. The icon engine is very small since most of the functionality is in QtSvg, so it can simply always be included as soon as QtSvg is.

**Comment by probonopd** [comment]
Thanks for the confirmation @bjorn

**Comment by fathomssen** [comment]
Hi @probonopd 

Since or before release 3, QtSvg is no longer shipped for some reason.

Best regards
Frederick Thomssen

**Comment by bjorn** [comment]
@fathomssen See issue #82, with the solution decided upon in [this comment](https://github.com/probonopd/linuxdeployqt/issues/82#issuecomment-289317542).
