### ISSUE TITLE
Qt 4 application cannot be bundled, qm files claimed to be missing

### ISSUE THREAD

**Issue by probonopd** [probonopd/linuxdeployqt#360]
https://github.com/ktechlab/ktechlab/issues/47#issuecomment-477125751

> `linuxdeployqt 5 (commit 37631e5), build 631 built on 2019-01-25 22:47:58 UTC FHS-like mode with PREFIX, fhsPrefix: "/tmp/ktechlab-prefix/usr" app-binary: "/tmp/ktechlab-prefix/usr/bin/ktechlab" appDirPath: "/tmp/ktechlab-prefix" relativeBinPath: "usr/bin/ktechlab" ERROR: Could not find any translations in "/usr/share/qt4/translations" (developer build?)`
>
> The "/usr/share/qt4/translations" directory contains *.qm files, though...

This is the code in question. Not sure if it fails here, or shortly thereafter.

https://github.com/probonopd/linuxdeployqt/blob/cfa4dc561ab8454dda15103f2db6834bb61b90d7/tools/linuxdeployqt/shared.cpp#L1864-L1880

**Comment by probonopd** [comment]
@megastallman where are you running the AppImage generation?
https://gitlab.com/megastallman/ktechlab_qt4_appimage/pipelines is empty.

**Comment by megastallman** [comment]
Hi @probonopd 
At the moment I've just got 2 scripts in `ubuntu-14.04` directory. `ubuntu1404-ktechlab-builder.sh` is used to build Ktechlab on Ubuntu 14.04. Then I check it runs fine. After I'm running `ubuntu1404-ktechlab-linuxdeployqt-builder.sh` and get the error above.

**Comment by probonopd** [comment]
Where are you building? On your local machine? Can you get it to build on GitLab CI?

**Comment by megastallman** [comment]
At the moment - on Xubuntu 14.04 VM. So I'll try to move to Gitlab CI, if possible.

**Comment by megastallman** [comment]
Hi @probonopd !
Can I use Travis in my standard free public Gitlab account?
Could you please also explain how to explicitly specify the ubuntu-14.04 environment to comply with AppImage requirements? I've seen this: https://github.com/probonopd/linuxdeployqt/#using-linuxdeployqt-with-travis-ci , but the distro is not specified here.

**Comment by probonopd** [comment]
Yes, you can use Travis CI for free for open source projects. Just follow https://github.com/probonopd/linuxdeployqt/#using-linuxdeployqt-with-travis-ci by copy-and-paste, and go from there. It uses trusty. You could also change trusty to xenial if you really have to.

**Comment by megastallman** [comment]
@probonopd Hi!

I see the "qtbase_*.qm" template doesn't match the QT4 translation file names, which look like "qt_uk.qm" and "qt_help_uk.qm".
Is it worth changing this template to  "qt*.qm"? Wouldn't it be too broad?

**Comment by probonopd** [comment]
If it helps, then let's do it

**Comment by probonopd** [comment]
@megastallman over at https://github.com/ktechlab/ktechlab/issues/47#issuecomment-487418742:

> I've patched and rebuilt Linuxdeployqt according to probonopd/linuxdeployqt#360. It grabs QT4 binaries fine

How exactly did you patch it, can you send a pull request please? Thanks.

**Comment by megastallman** [comment]
I just replaced `qtbase_*.qm` with `qt*.qm`. That is all I did to make the AppImage build.

**Comment by probonopd** [comment]
@megastallman thanks, can you please test whether https://transfer.sh/JZykE/linuxdeployqt-continuous-x86_64.AppImage (link available for 14 days) works for you? Thank you very much.

**Comment by megastallman** [comment]
Thanks, @probonopd !

Just checked the Linuxdeployqt.AppImage. It grabs the translations.
