### ISSUE TITLE
copy file take a lot of time

### ISSUE THREAD

**Issue by Match-Yang** [probonopd/linuxdeployqt#363]
wen I use linuxdeployqt for my Qt3D(QtQuick) project, it take a lot of time to copy qml file. Can this tool use multi-thread to copy file to make the progress faster?It almost take 5min to copy the files right now.

**Comment by probonopd** [comment]
I am not going to invest time into optimizing performance for this tool since it is only running at build time. But check out https://github.com/linuxdeploy/linuxdeploy-plugin-qt whether it works for you. Its performance may be better.
