### ISSUE TITLE
can't create appimage by using -appimage

### ISSUE THREAD

**Issue by Hapoa** [probonopd/linuxdeployqt#367]
Current build folder just includes `data_interconnection`, `linuxdeployqt-6-x86_64.AppImage`. ( data_interconnection is my release program)

By using `./linuxdeployqt-6-x86_64.AppImage ./data_interconnection -appimage -always-overwrite -no-copy-copyright-files -qmake='/opt/5.10.1/gcc_64/bin/qmake'`, but after it ends ,i can't find the .appimage file. Here is the output,

```
relativeBinPath: "data_interconnection"
ERROR: Desktop file missing, creating a default one (you will probably want to edit it)
ERROR: Icon file missing, creating a default one (you will probably want to edit it)
appimagetool, continuous build (commit cddcc2e), build 2034 built on 2019-01-22 15:01:38 UTC
NOTE: Using the output of 'git rev-parse --short HEAD' as the version:
      69f88f7
      Please set the $VERSION environment variable if this is not intended
Categories entry not found in desktop file
.desktop file is missing a Categories= key
```

And then I search keyword `appimage` in `issues`, and I find [one issue](https://github.com/probonopd/linuxdeployqt/issues/58), he also create file `qt.conf`, `app.desktop`, so I tried it, It successed.

So why? Why I can't create .appimage until I create `qt.conf` and `.desktop`? I think the package solution should be same with `windeployqt` in Windows. Is it a unavoidable step in Linux???

**Comment by probonopd** [comment]
You need to create the desktop file because `linuxdeployqt` cannot guess its values (where should it know them from?). Be sure to check the validity of your desktop file with `desktop-file-validate`.

You do not need to create a qt.conf file because `linxudeployqt` does it for you.
