### ISSUE TITLE
QtQuick debug shared libraries are copied over

### ISSUE THREAD

**Issue by haampie** [probonopd/linuxdeployqt#373]
After building an app with `linuxdeployqt`, I found there is 46MB of debug libraries included:

```
$ find -name "*.debug" | xargs du -ach
1.7M    ./qml/QtGraphicalEffects/private/libqtgraphicaleffectsprivate.so.debug
368K    ./qml/QtGraphicalEffects/libqtgraphicaleffectsplugin.so.debug
296K    ./qml/QtQuick.2/libqtquick2plugin.so.debug
3.6M    ./qml/QtQuick/Controls.2/Universal/libqtquickcontrols2universalstyleplugin.so.debug
3.3M    ./qml/QtQuick/Controls.2/Imagine/libqtquickcontrols2imaginestyleplugin.so.debug
3.5M    ./qml/QtQuick/Controls.2/Fusion/libqtquickcontrols2fusionstyleplugin.so.debug
3.7M    ./qml/QtQuick/Controls.2/Material/libqtquickcontrols2materialstyleplugin.so.debug
3.9M    ./qml/QtQuick/Controls.2/libqtquickcontrols2plugin.so.debug
3.6M    ./qml/QtQuick/Controls/Universal/libqtquickcontrols2universalstyleplugin.so.debug
3.3M    ./qml/QtQuick/Controls/Imagine/libqtquickcontrols2imaginestyleplugin.so.debug
3.5M    ./qml/QtQuick/Controls/Fusion/libqtquickcontrols2fusionstyleplugin.so.debug
3.7M    ./qml/QtQuick/Controls/Material/libqtquickcontrols2materialstyleplugin.so.debug
624K    ./qml/QtQuick/Shapes/libqmlshapesplugin.so.debug
2.6M    ./qml/QtQuick/Layouts/libqquicklayoutsplugin.so.debug
2.6M    ./qml/QtQuick/Templates.2/libqtquicktemplates2plugin.so.debug
5.2M    ./qml/QtQuick/PrivateWidgets/libwidgetsplugin.so.debug
452K    ./qml/QtQuick/Window.2/libwindowplugin.so.debug
46M     total
```
Further all `designer` qml files are copied over as well. Can we prune this?

**Comment by haampie** [comment]
Relatedly, it would be nice if I could avoid bundling

```
qml/QtQuick/Controls.2/Universal/
qml/QtQuick/Controls.2/Imagine/
qml/QtQuick/Controls.2/Fusion/
qml/QtQuick/Controls.2/Material/
```

altogether, as I'm not using them. Could that possibly be a command line option as well?

**Comment by probonopd** [comment]
Thanks for reporting this. Do you think you can send a pull request to ignore `*so.debug` files?

> it would be nice if I could avoid bundling (...) altogether, as I'm not using them

Is there any way for `linuxdeployqt` to know this?

**Comment by haampie** [comment]
> Is there any way for `linuxdeployqt` to know this?

No, not at all, it's runtime configurable with environment variables. But we could maybe add a flag like `linuxdeployqt [binary] -qmldir=... -quickcontrolsthemes=comma separated list` which defaults to `Universal,Imagine,Fusion,Material` or so.

**Comment by probonopd** [comment]
Thanks for the idea, but I don't want to make `linuxdeployqt` more complex than it already is, adding more options. Maybe https://github.com/linuxdeploy/linuxdeploy-plugin-qt is open to this suggestion.

In the meantime, you can prepare the AppDir using `linuxdeployqt`, then manually delete the files, and then manually run `appimagetool` on it to convert the AppDir into an AppImage. Let me know if you need help doing this.
