### ISSUE TITLE
ERROR: The host system is too new. Please run on a system with a glibc version no newer than what comes with the oldest

### ISSUE THREAD

**Issue by Daibingh** [probonopd/linuxdeployqt#374]
the error occurs when i run it on Ubuntu18.04,

**Comment by probonopd** [comment]
Works as intended.

**Comment by Daibingh** [comment]
Thanks for your reply. I am a newer, and can you give me some advice?

**Comment by probonopd** [comment]
Please build your software on e.g., Ubuntu xenial.

**Comment by Daibingh** [comment]
OK, thans.

**Comment by ArbitCode** [comment]
Do we need to switch to Ubuntu Xenial from ubuntu Focal Fossa to resolve this issue? It will be a great pleasure if someone explains this.

**Comment by probonopd** [comment]
It has been explained in #340.
