### ISSUE TITLE
libdouble-conversion.so.1 not copied

### ISSUE THREAD

**Issue by mitchcurtis** [probonopd/linuxdeployqt#378]
I recently got a report that a user is unable to start my Qt application on Linux:

https://github.com/mitchcurtis/slate/issues/130

I had a similar report a while ago that was fixed by moving from regular static builds without linuxdeployqt to dynamic builds with linuxdeployqt:

https://github.com/mitchcurtis/slate/issues/112

However, it seems that while linuxdeployqt does copy libicui18n.so.60 into the output directory, it doesn't copy libdouble-conversion.so.1.

I've only seen this issue reported since building my application with Qt 5.13, so it could just be that linuxdeployqt hasn't been tested with that yet?

**Comment by probonopd** [comment]
Could it be that this is opened with [dlopen()](url)? Is it shown by `ldd`?

> Qt 5.13, so it could just be that linuxdeployqt hasn't been tested with that yet?

True.

**Comment by mitchcurtis** [comment]
> Could it be that this is opened with `dlopen()`? Is it shown by `ldd`?

Yes, it shows up with `ldd`:

>         linux-vdso.so.1 (0x00007ffcc85da000)
>         libslate.so => /home/mitch/dev/slate-releases/Slate-v0.8.0-linux/lib/libslate.so (0x00007fc6f8e91000)
>         libQt5Widgets.so.5 => /home/mitch/dev/slate-releases/Slate-v0.8.0-linux/lib/libQt5Widgets.so.5 (0x00007fc6f862b000)
>         libQt5Quick.so.5 => /home/mitch/dev/slate-releases/Slate-v0.8.0-linux/lib/libQt5Quick.so.5 (0x00007fc6f7f7a000)
>         libQt5Qml.so.5 => /home/mitch/dev/slate-releases/Slate-v0.8.0-linux/lib/libQt5Qml.so.5 (0x00007fc6f78d8000)
>         libQt5Gui.so.5 => /home/mitch/dev/slate-releases/Slate-v0.8.0-linux/lib/libQt5Gui.so.5 (0x00007fc6f710c000)
>         libQt5Core.so.5 => /home/mitch/dev/slate-releases/Slate-v0.8.0-linux/lib/libQt5Core.so.5 (0x00007fc6f6913000)
>         libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fc6f658a000)
>         libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fc6f6372000)
>         libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc6f5f81000)
>         libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc6f5d62000)
>         libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc6f59c4000)
>         libQt5Network.so.5 => /home/mitch/dev/slate-releases/Slate-v0.8.0-linux/lib/libQt5Network.so.5 (0x00007fc6f561e000)
>         libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fc6f541a000)
>         libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007fc6f518e000)
>         libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007fc6f4f5c000)
>         libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fc6f4d3f000)
>         libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007fc6f4aa1000)
>         libicui18n.so.60 => /home/mitch/dev/slate-releases/Slate-v0.8.0-linux/lib/libicui18n.so.60 (0x00007fc6f4598000)
>         libicuuc.so.60 => /home/mitch/dev/slate-releases/Slate-v0.8.0-linux/lib/libicuuc.so.60 (0x00007fc6f41be000)
>         libdouble-conversion.so.1 => /usr/lib/x86_64-linux-gnu/libdouble-conversion.so.1 (0x00007fc6f3fad000)
>         libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fc6f3c97000)
>         /lib64/ld-linux-x86-64.so.2 (0x00007fc6f93ff000)
>         libGLX.so.0 => /usr/lib/x86_64-linux-gnu/libGLX.so.0 (0x00007fc6f3a66000)
>         libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007fc6f37b0000)
>         libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fc6f34fc000)
>         libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007fc6f32cf000)
>         libicudata.so.60 => /home/mitch/dev/slate-releases/Slate-v0.8.0-linux/lib/libicudata.so.60 (0x00007fc6f1725000)
>         libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fc6f14b3000)
>         libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fc6f117b000)
>         libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fc6f0f53000)
>         libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fc6f0d4f000)
>         libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fc6f0b49000)
>         libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007fc6f0934000)
>         librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fc6f072c000)

**Comment by probonopd** [comment]
May possibly be a bug then. Not sure yet. Where do you get your Qt from, andere which distro and version are you building on?

**Comment by mitchcurtis** [comment]
Self-built Qt on Ubuntu 18.04.2.

**Comment by mitchcurtis** [comment]
I tried with the official Qt 5.13.0 package from the online installer and got the same result. Here's the verbose (2) output of linuxdeployqt using that Qt version:

[linuxdeployqt.txt](https://github.com/probonopd/linuxdeployqt/files/3362505/linuxdeployqt.txt)

**Comment by mitchcurtis** [comment]
These are the libraries that are currently being copied:

> mitch@mitch-ubuntu-18:~/dev$ ls ~/dev/slate-releases/Slate-test-linux/lib
> libicudata.so.56  libicuuc.so.56   libQt5DBus.so.5  libQt5Network.so.5  libQt5QuickControls2.so.5  libQt5QuickTemplates2.so.5  libQt5Svg.so.5      libQt5XcbQpa.so.5
> libicui18n.so.56  libQt5Core.so.5  libQt5Gui.so.5   libQt5Qml.so.5      libQt5Quick.so.5           libQt5RemoteObjects.so.5    libQt5Widgets.so.5  libslate.so

I tried `-bundle-non-qt-libs`, and while it copied a tonne of extra libraries, it still doesn't copy `libdouble-conversion.so.1`:

> mitch@mitch-ubuntu-18:~/dev$ ls ~/dev/slate-releases/Slate-test-linux/lib
> libbsd.so.0         libGLX.so.0          libicuuc.so.56  libpng16.so.16   libQt5Network.so.5         libQt5QuickTemplates2.so.5  libQt5XcbQpa.so.5  libXau.so.6      libXext.so.6
> libdbus-1.so.3      libgthread-2.0.so.0  liblz4.so.1     libQt5Core.so.5  libQt5Qml.so.5             libQt5RemoteObjects.so.5    libslate.so        libxcb-glx.so.0  libxkbcommon.so.0
> libgcrypt.so.20     libicudata.so.56     liblzma.so.5    libQt5DBus.so.5  libQt5QuickControls2.so.5  libQt5Svg.so.5              libsystemd.so.0    libxcb-xkb.so.1  libxkbcommon-x11.so.0
> libGLdispatch.so.0  libicui18n.so.56     libpcre.so.3    libQt5Gui.so.5   libQt5Quick.so.5           libQt5Widgets.so.5          libX11-xcb.so.1    libXdmcp.so.6    libXrender.so.1

**Comment by probonopd** [comment]
The log says:

```
WARNING: Not checking glibc on the host system.
         The resulting AppDir or AppImage may not run on older systems.
         This mode is unsupported and discouraged.
         For more information, please see
         https://github.com/probonopd/linuxdeployqt/issues/340
```

The newest supported Ubuntu release is 16.04 (xenial) at this time. As per our policy, we don't support versions newer than the oldest still-supported LTS release.

**Comment by mitchcurtis** [comment]
I have read that issue before, that's how I learned about the argument to pass to it.

Can you please explain how that is relevant to this issue? As I understand it, the underlying issue is that a user has a _newer_ version of libdouble-conversion.so than what my application uses, not the other way around.

**Comment by probonopd** [comment]
Your log shows that you are running on an unsupported version, hence I am not supporting it.

**Comment by mitchcurtis** [comment]
That's fair enough, I suppose.

I am not that familiar with how packages, library versions, etc. work on Linux, but based on the libdouble-conversion version numbers (my 1 vs their 3.1.5), I don't see how this problem could possibly be a result of me using a recent version of Ubuntu. Anyhow, just as you understandably don't want to spend time maintaining unsupported versions, I do not want to either. Packaging my application on three different platforms is already tedious enough without having to have VMs to test older Ubuntu versions.

For anyone else that's curious, I don't see libdouble-conversion.so on e.g. [this](https://github.com/AppImage/pkg2appimage/blob/master/excludelist) list, so my only other idea is to just copy it manually and see if that resolves it.

**Comment by probonopd** [comment]
> Anyhow, just as you understandably don't want to spend time maintaining unsupported version

So please use a supported one: xenial. It is supported by Ubuntu, and it is supported by linuxdeployqt, and it is supported by me :.)
