### ISSUE TITLE
Will you compress libs while linuxdeployqt copy the dependent libraries?

### ISSUE THREAD

**Issue by Hapoa** [probonopd/linuxdeployqt#382]
I use **linuxdeployqt** to pack my program, and it used openssl.

After packed successfully, I found the size of `libssl.so.1.1` in `APP.Dir/lib` is smaller than `/usr/local/libssl.so.1.1`, and also `libcrypto.so.1.1`.

**Comment by probonopd** [comment]
Maybe because we are stripping it?

**Comment by Hapoa** [comment]
Sorry, what's meaning of `stripping`? Could you show more details?

**Comment by probonopd** [comment]
https://en.wikipedia.org/wiki/Strip_(Unix)

**Comment by Hapoa** [comment]
Get it! Thanks for your warm response.
