### ISSUE TITLE
appimage not building

### ISSUE THREAD

**Issue by rahmanshaber** [probonopd/linuxdeployqt#383]
ubuntu 16.04 
```
asd@ubuntu:~/Desktop/d$ ./linuxdeployqt-continuous-x86_64.AppImage ./build-coreuniverse-Desktop-Debug/coreuniverse -appimage
linuxdeployqt de6d873 (commit c721bc9), build 700 built on 2019-07-28 19:03:56 UTC
Not using FHS-like mode
app-binary: "/home/asd/Desktop/d/build-coreuniverse-Desktop-Debug/coreuniverse"
appDirPath: "/home/asd/Desktop/d/build-coreuniverse-Desktop-Debug"
relativeBinPath: "coreuniverse"
ERROR: Desktop file missing, creating a default one (you will probably want to edit it)
ERROR: Icon file missing, creating a default one (you will probably want to edit it)
WARNING: Plugin "/usr/lib/x86_64-linux-gnu/qt5/plugins/styles/libqgtk2style.so" not found, skipping
appimagetool, continuous build (commit fef038a), build 2093 built on 2019-07-07 12:07:34 UTC
fatal: Not a git repository (or any of the parent directories): .git
Failed to run 'git rev-parse --short HEAD: Child process exited with code 128 (code 128)
Categories entry not found in desktop file
.desktop file is missing a Categories= key

```

any idea to fix this

**Comment by probonopd** [comment]
> .desktop file is missing a Categories= key

Please post your desktop file here. Thanks.

**Comment by rahmanshaber** [comment]
yes. and here is the repo https://gitlab.com/cubocore/coreuniverse.
as linuxdeployqt is searching for desktop file in build folder and it  is not there so the build fails ?
but i see it is a git related .

**Comment by probonopd** [comment]
`.desktop file is missing a Categories= key` is the real error.

**Comment by rahmanshaber** [comment]
```
asd@ubuntu:~/Desktop/d$ ./linuxdeployqt-continuous-x86_64.AppImage ./build-coreuniverse-Desktop-Debug/coreuniverse -appimage
linuxdeployqt de6d873 (commit c721bc9), build 700 built on 2019-07-28 19:03:56 UTC
Not using FHS-like mode
app-binary: "/home/asd/Desktop/d/build-coreuniverse-Desktop-Debug/coreuniverse"
appDirPath: "/home/asd/Desktop/d/build-coreuniverse-Desktop-Debug"
relativeBinPath: "coreuniverse"
Keeping existing AppRun
WARNING: Plugin "/usr/lib/x86_64-linux-gnu/qt5/plugins/styles/libqgtk2style.so" not found, skipping
WARNING: "/home/asd/Desktop/d/build-coreuniverse-Desktop-Debug/qt.conf" already exists, will not overwrite.
appimagetool, continuous build (commit fef038a), build 2093 built on 2019-07-07 12:07:34 UTC
fatal: Not a git repository (or any of the parent directories): .git
Failed to run 'git rev-parse --short HEAD: Child process exited with code 128 (code 128)
Using architecture x86_64
/home/asd/Desktop/d/build-coreuniverse-Desktop-Debug should be packaged as CoreUniverse-x86_64.AppImage
/usr/share/icons/hicolor/scalable/apps/coreuniverse.svg{.png,.svg,.xpm} defined in desktop file but not found
For example, you could put a 256x256 pixel png into
/home/asd/Desktop/d/build-coreuniverse-Desktop-Debug/usr/share/icons/hicolor/scalable/apps/coreuniverse.svg.png

````

desktop file 
```
[Desktop Entry]
Name=CoreUniverse
Comment=Shows releated information of apps from CuboCore Application Suite.
Exec=coreuniverse
Icon=/usr/share/icons/hicolor/scalable/apps/coreuniverse.svg
Type=Application
Categories=Qt;Utility;Documentation;
Terminal=false
StartupNotify=true
```

files in the the build folder
```
asd@ubuntu:~/Desktop/d/build-coreuniverse-Desktop-Debug$ ls
AppRun  coreuniverse          default.png  icons  Makefile  qt.conf
build   coreuniverse.desktop  doc          lib    plugins   translations

```

**Comment by probonopd** [comment]
Please make it `Icon=coreuniverse`

**Comment by probonopd** [comment]
Did you see all my various PRs I have sent to your projects?

**Comment by rahmanshaber** [comment]
> 
> 
> Did you see all my various PRs I have sent to your projects?

are you talking about pull request? where?

it build fine. 

libqt5libqgtk2 is installed my system but it complains 
```
WARNING: Plugin "/usr/lib/x86_64-linux-gnu/qt5/plugins/styles/libqgtk2style.so" not found, skipping
```
the created appImage icon is not the apps icon.

**Comment by probonopd** [comment]
CoreBox, CoreFM, CorePaint, CoreTerminal.
Did you not see the pull requests on https://github.com/notifications?

**Comment by rahmanshaber** [comment]
ok. i did not have any.
![image](https://user-images.githubusercontent.com/30831735/62844684-8f60b580-bcf5-11e9-903a-bfc9aaa592dc.png)

As we move our whole project to gitlab so github is not that important now.
can we do this in gitlab? [CuboCore](https://gitlab.com/cubocore). 
We have a matrix channel if you want to talk IRC/Matrix #cubocore:matrix.org.

One question, every time we do git push there will be a new appimage? or only one ( old one will be deleted and replace it with new one) ?

**Comment by probonopd** [comment]
There will be only one, and always the latest one only.
Can you port over my PRs from GitHub to GitLab please? I don't have the time right now to redo them, sorry.

**Comment by rahmanshaber** [comment]
i can, but i am not sure about the github token in gitlab. i will try.

**Comment by probonopd** [comment]
That will not work of course, you need to "port" = adapt it to GitLab and use the GitLab CI format for `.gitlab-ci.yml`, and the GitHub mechanism for storing build artifacts.

Here is an example that should get you started:
https://gitlab.com/probono/QtQuickApp/blob/master/.gitlab-ci.yml

**Comment by michel47** [comment]
about the missing categories in the .desktop file you need to have a "registered on" 
(https://specifications.freedesktop.org/menu-spec/latest/apa.html)

see also https://github.com/michel47/hello-world-appimage
