### ISSUE TITLE
QtHelp doesn't work inside AppImage?

### ISSUE THREAD

**Issue by collin80** [probonopd/linuxdeployqt#386]
I'm using TravisCI to automatically build releases for my project SavvyCAN. The whole process was successful and I can run the program once packed into an AppImage. The problem is that the program uses the QtHelp system to provide context aware help for users. This works fine outside of an AppImage but immediately breaks inside. I have used the mount command to mount the AppImage to a directory. It fails to load help that way too. But, if I copy all the files to another directory, leaving the whole directory structure the same, it works. The only difference I can see is that AppImages are read only and so when I copy the files elsewhere they are now on a writable point and so it works. Is there a problem with my AppImage that could cause this or does it make any sense that QtHelp requires write access just to show help?!

**Comment by probonopd** [comment]
Hi @collin80 that is interesting. Especially that you say it is working when you extract the AppImage and run the application from the extracted AppDir.

Using https://github.com/collin80/SavvyCAN/releases/download/continuous/SavvyCAN-305dafd-x86_64.AppImage the application is runnnig well, but how can I access help? There is no "About > help" menu visible.

**Comment by collin80** [comment]
Oh, sorry, yes that would help. Push F1 on any screen to get help.

**Comment by probonopd** [comment]
Hardly discoverable ;-)

**Comment by probonopd** [comment]
This is what happens if I press F1:

```
[pid  9007] openat(AT_FDCWD, "/tmp/.mount_SavvyC0siJpE/local/bin/SavvyCAN.qhc", O_RDWR|O_CREAT|O_CLOEXEC, 0644) = -1 EROFS (Read-only file system)
```

Could it be related? What does it want to write there?

**Comment by collin80** [comment]
Well that's probably it since it is a readonly file system. The thing is, that file already exists in that location. But, apparently QT opens it read/write with the ability to create it. That makes sense I suppose because the documentation for QtHelp says that it will create the file if it doesn't exist. So, this seems like a QT issue and not a linuxdeployqt related issue. I suppose I should raise this issue with them... Or perhaps I could read up on how to install files on the local computer with an AppImage - which it seems like I've heard is possible. Thanks for looking into it.

**Comment by probonopd** [comment]
Search for "read-only" at https://doc.qt.io/qt-5/assistant-custom-help-viewer.html.

**Comment by collin80** [comment]
Aha! Yes, you found exactly what I needed it see it seems. Thank you! I'll work on getting things fixed up. Awesome!
