### ISSUE TITLE
System Qt gets picked up by LinuxDeployQt

### ISSUE THREAD

**Issue by sarthakpati** [probonopd/linuxdeployqt#388]
Hi,

I am trying to package an application using LinuxDeployQt (LDQ) on CentOS7 but for some reason, LDQ packages the system Qt (which is 5.9.2) instead of the one I am building the application against (which is 5.11.1). I have ensured that the `$PATH` and `$LD_LIBRARY_PATH` variables have the correct version of Qt in the beginning. Any help would be appreciated.

Thanks.

**Comment by probonopd** [comment]
Please use Ubuntu trusty or xenial to see if the error occurs there, too.
The only tested and supported configuration is https://github.com/probonopd/linuxdeployqt/#using-linuxdeployqt-with-travis-ci.

**Comment by sarthakpati** [comment]
I have been using this on Azure DevOps' Xenial image and it works perfectly over there. Anyway, if it isn't supported, I'll just work around that. Thanks.

**Comment by probonopd** [comment]
Thanks for letting us know. Our small team can't test and support all possible combinations of distributions and Qt versions, but in case you can identify what is causing the issue and can send a pull request we'd of course be happy to merge it.
