### ISSUE TITLE
What versions of Qt are supported?

### ISSUE THREAD

**Issue by stardast** [probonopd/linuxdeployqt#392]
I have not found indicated which versions of Qt are supported (and tested).
I think it's important to document it somewhere, can you put it in the ReadMe?

Thanks!

**Comment by probonopd** [comment]
5.8 and later from https://launchpad.net/~beineri should be fine.

The tested and supported configuration is documented at
https://github.com/probonopd/linuxdeployqt#using-linuxdeployqt-with-travis-ci
