### ISSUE TITLE
Disable/Exclude plugins

### ISSUE THREAD

**Issue by rodlie** [probonopd/linuxdeployqt#395]
Hi,

I noticed that several plugins I don't use are included in the AppImage, how can I disable specific (and/or group of) plugins?

Or could we have that ``-no-plugins`` combined with ``-extra-plugins`` only bundled the plugins in ``-extra-plugins``?

**Comment by probonopd** [comment]
> I noticed that several plugins I don't use are included in the AppImage, how can I disable specific (and/or group of) plugins?

Can you please be specific and name the plugins you do _not_ need. `linuxdeployqt` is trying to figure out which plugins are in use, and only bundle those. Apparently it doesn't get it right for your app.

**Comment by rodlie** [comment]
Since I need to get my AppImage working I just rebuilt Qt without the plugins I don't want.

Anyway, would be great to have an option in the future to disable plugins.

How do you handle imageformats? You can't probe the application regarding this, so I assume you always copy everything in the imageformats folder regardless? (I have not looked at the source). Also, what about SVG? linuxdeployqt always bundle libQtSvg when my app does not require or want it, I can at least add that library to the exclude list.

**Comment by probonopd** [comment]
Many users here pointed out that things start breaking if one does not ship the imageformats (e.g., icons break in the GUI). Similarly, using e.g., Chinese keyboards break if platforminputcontexts are not bundled (or something along those lines), and some graphics stuff breaks if xcbglintegrations are not present. Are you really 100% sure that it is a good idea to leave them away, and can you think of a way for `linuxdeployqt` to determine when they are needed vs. when they are not needed?

I want to avoid configurability, especially if it means that people can "shoot themselves in the foot".

**Comment by rodlie** [comment]
For my app is perfectly fine to exclude most of the plugins, other apps? I don't know. It depends, and that's why we should have an option.

Anyway, not important to me anymore since I build the AppImage manually.

**Comment by probonopd** [comment]
Thanks. As long as it works, I think we can close this. Feel free to reopen if you think it' still a needed feature.

**Comment by mardy** [comment]
I was about to create a patch to fix this, when I realized that this is already fixed: commit 5843744a95e2bb040b7db12f7daae97e748ea558 (MR #253) introduced the `-exclude-lib` command line option which can also be used to exclude Qt plugins. In my program I'm now using it like this:
```
    -exclude-libs=libqsqlodbc,libqsqlpsql
```
(I want SQLite, but not other DB engines).

**Comment by ungive** [comment]
I tried this, but it doesn't work for me: `'/opt/linuxdeployqt' '/build/packages/_CPack_Packages/Linux/RPM/musicpresence-2.4.0-beta.10-linux-x86_64/usr/.linuxdeployqt/AppDir/usr/share/applications/musicpresence.desktop' '-appimage' '-exclude-libs="libQt6Quick.so.6,libqtga.so,libqtiff.so,libqwbmp.so,libqicns.so,libblkid.so.1,...`

```
./musicpresence-2.4.0-beta.10-linux-x86_64.AppImage --appimage-extract
tree -rf . | grep -i libqtiff
│   │   │   │   ├── ./squashfs-root/usr/plugins/imageformats/libqtiff.so
```

Is there something I'm missing?

**Comment by probonopd** [comment]
@ungive have you tried leaving away the `.so` file suffix?

But be aware that normally these things get deployed for a reason; in other words if your application does not use Qml, then libQt6Quick will not be deployed, and if you are using Qml, then it _must_ be deployed.

**Comment by ungive** [comment]
> have you tried leaving away the .so file suffix?

This worked, thank you!

> But be aware that normally these things get deployed for a reason; in other words if your application does not use Qml, then libQt6Quick will not be deployed, and if you are using Qml, then it must be deployed.

I'm aware, thank you! I do not use Qml anywhere and I'm excluding non-Qt libraries (like libblkid.so.1) only with RPM/DEB packages when they have a corresponding dependency declared in the package.
