### ISSUE TITLE
System libraries override custom libraries

### ISSUE THREAD

**Issue by rodlie** [probonopd/linuxdeployqt#397]
linuxdeployqt seems to prefer system (/usr/lib*) library path over custom (example LD_LIBRARY_PATH). I have Qt on my system and a custom Qt build for use with the AppImage. This never work for me, as linuxdeployqt always try to use the system Qt.

```
ERROR: ldd outputLine: "/home/olear/Development/cyan/build-appimage/AppDir/usr/lib///libQt5Gui.so.5: /usr/lib64/../lib64/libQt5Core.so.5: version `Qt_5.13' not found (required by /home/olear/Development/cyan/build-appimage/AppDir/usr/lib///libQt5Gui.so.5)"
ERROR: for binary: "/home/olear/Development/cyan/build-appimage/AppDir/usr/lib///libQt5Gui.so.5"
ERROR: Please ensure that all libraries can be found by ldd. Aborting.
```
As you can see libQt5Gui.so.5 is correct (it's from my custom build), but then linuxdeployqt "loose" or ignores LD_LIBRARY_PATH and starts check the depends  of my custom library against the system, this should not happen.

Btw, If I run the deploy command again it "works", as existing files in AppDir/usr/lib are ignored (why?).

Also the same issue with plugins:
```
ERROR: ldd outputLine: "/home/olear/Development/cyan/sdk/plugins/platforms/libqxcb.so: /usr/lib64/libQt5Core.so.5: version `Qt_5.13' not found (required by /home/olear/Development/cyan/sdk/plugins/platforms/libqxcb.so)"
ERROR: for binary: "/home/olear/Development/cyan/sdk/plugins/platforms/libqxcb.so"
ERROR: Please ensure that all libraries can be found by ldd. Aborting.
```

Also the same issue with FFmpeg, I had to built it static to get around this.

**Comment by probonopd** [comment]
Do you think reversing the order of

https://github.com/probonopd/linuxdeployqt/blob/42e51ea7c7a572a0aa1a21fc47d0f80032809d9d/tools/linuxdeployqt/shared.cpp#L1152

would do the trick?

**Comment by rodlie** [comment]
When I think about it linuxdeployqt will not work for my use case, I mostly use custom builds and linuxdeployqt can't know where the files are with just ldd, so it will always fallback to the system (and that's probably how it should be, it seems linuxdeployqt is designed to deploy using the libraries from the system your are building on, that's not how I do it).

Sorry for the noise :)

**Comment by probonopd** [comment]
>  I mostly use custom builds

Of what? Qt? Other libraries?

**Comment by rodlie** [comment]
> For other libraries, just install your custom builds to the /usr prefix and ldd will pick them up from there.

That's the problem, I don't taint the running system with my custom libraries (I normally have a folder called 'sdk' that has most of the depends for my app(s)), so ldd will not copy the correct files.

I just made a simple shell script that builds the AppImage for me manually.

**Comment by probonopd** [comment]
> That's the problem, I don't taint the running system with my custom libraries (I normally have a folder called 'sdk' that has most of the depends for my app(s)), so ldd will not copy the correct files.

Ah, I see. Alternatively you could use a service like Travis CI that "throws away" the system after the build succeeded. In such a system you can install stuff into the system without risk.

**Comment by probonopd** [comment]
> I just made a simple shell script that builds the AppImage for me manually.

Looks like that didn't go all that well:

```
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: xcb.
```

**Comment by rodlie** [comment]
Works fine on the systems I tested.

* Ubuntu 16.04/18.04/19.04/19.10
* Fedora
* Manjaro
* Slackware

**Comment by probonopd** [comment]
I am testing on Ubuntu Xenial with no Qt on the system.

**Comment by rodlie** [comment]
You are probably missing one of the following:

* libX11-xcb.so.1
* libxcb.so.1
* libXrender.so.1
* libXext.so.6
* libX11.so.6
* libSM.so.6
* libICE.so.6
* libxkbcommon-x11.so.0
* libxkbcommon.so.0

I do not bundle X11 related libraries, I assume a working X11/desktop session is used when running the application.

**Comment by probonopd** [comment]
See, you disagreed with the list of what should and should not be bundled, and now things are not passing the test... For example, where does the assumption come from that `libX11-xcb.so.1` is present on every target system?

**Comment by rodlie** [comment]
I assume that a proper installation of X11 is present, XCB is part of that. The AppImage works on all the systems I target (2016+ releases).

Of course there will be certain installations where some depends may be missing and the app will not run, but I won't bundle more than needed (I target a normal system installation with a DE/WM), especially things I consider common on all installation.

Btw, in your exclude list you have pangocairo, how can you assume that every installation has that? And pangocairo mostly depends on libxcb* on most systems btw. As I said earlier there are no absolutes when it comes to this, either you bundle everything or find a middle-road somewhere that makes sense for you and your targeted audience.

Anyway, the AppImage works for my needs. Thanks for maintaining the AppImage project :)
