### ISSUE TITLE
Error while loading shared libraries on AppImage run

### ISSUE THREAD

**Issue by akontsevich** [probonopd/linuxdeployqt#405]
Hi @probonopd and @TheAssassin. As You may remember I was able to build and run AppImage successfully under CentOS 7.x based docker image here: https://github.com/AppImage/AppImageKit/issues/998#issuecomment-543368166

However when we migrate to Ubuntu 18.04 and added `libgdal` and `boost` dependencies to the app some problems appeared with shared libraries on AppImage run:
```
error while loading shared libraries: <lib_name>: cannot open shared object file: 
No such file or directory
```

And this happens with tens or hundreds shared libraries so I can't solve the issue copying them manually to app lib dir like in the link [above](https://github.com/AppImage/AppImageKit/issues/998#issuecomment-543368166). So copying libraries like this:
```
# copy some missed libs to the bundle
libs=(libssl.so.1 libcrypto.so.1 libicui18n.so libicuuc.so libicudata.so \
     libgdal.so libarmadillo.so libproj.so libjson-c.so libqhull.so libwebp.so \
     libpoppler.so libepsilon.so libkmlbase.so libkmldom.so libkmlengine.so \
     libnetcdf.so libhdf5_serial.so libmfhdfalt.so libdfalt.so libogdi.so \
     libgeotiff.so libdapclient.so libdap.so libpcre.s)
for lib in "${libs[@]}"
do
    cp $(ldconfig -p | grep ${lib} | head -n1 | tr ' ' '\n' | grep /) ./$APP.AppDir/Qt/libs/    
done
```
does not work any more as there are too much libraries and previous 80 MB AppImage which worked everywhere grows now in more than 2 times and does not work. I saw `./linuxdeploy-x86_64.AppImage` output and it strips these libraries from final AppImage for some reason - see libs list above after adding `gdal` and `boost` (previously it was necessary to deploy manually only following `libssl.so.1, libcrypto.so.1, libicui18n.so, libicuuc.so, libicudata.so`).

See `./linuxdeploy-x86_64.AppImage` output: [appimage_bug.txt](https://github.com/probonopd/linuxdeployqt/files/3903099/appimage_bug.txt)

If I run create AppImage outside docker it builds and runs fine, however have size: 377 MB.

Any ideas? What the problem could be, how to solve? Thanks!

**Comment by probonopd** [comment]
The tested and supported way of using linuxdeployqt is https://github.com/probonopd/linuxdeployqt#using-linuxdeployqt-with-travis-ci - what happens if you follow that?

**Comment by akontsevich** [comment]
@probonopd sorry, I put this to wrong topic again. I mean we use `linuxdeploy` not linuxdeploy**qt**.

**Comment by akontsevich** [comment]
Sorry, I thought linuxdeploy is also Yours. What AppImage tool better to use?

**Comment by akontsevich** [comment]
Your tools fails on Ubuntu 18.04 completely:
```
ERROR: The host system is too new.
Please run on a system with a glibc version no newer than what comes with the oldest
currently still-supported mainstream distribution (xenial), which is glibc 2.23.
This is so that the resulting bundle will work on most still-supported Linux distributions.
For more information, please see
https://github.com/probonopd/linuxdeployqt/issues/340
```

**Comment by probonopd** [comment]
@akontsevich this is intentional. Please build your software on the oldest still-supported LTS release of Ubuntu or another similarly old distribution. The reasons are given in https://github.com/probonopd/linuxdeployqt/issues/340.

**Comment by akontsevich** [comment]
I can't do as I have Ubuntu 18.04 as a requirement.

**Comment by probonopd** [comment]
> I can't do as I have Ubuntu 18.04 as a requirement.

For _building_?

How are users that are not using that version of Ubuntu supposed to run your application then?

**Comment by akontsevich** [comment]
Users use Ubuntu 18.04.

**Comment by azubieta** [comment]
> I can't do as I have Ubuntu 18.04 as a requirement.

@akontsevich please check out https://github.com/AppImageCrafters/appimage-builder/

**Comment by akontsevich** [comment]
> > I can't do as I have Ubuntu 18.04 as a requirement.
> 
> @akontsevich please check out https://github.com/AppImageCrafters/appimage-builder/

Thanks @azubieta! Will try in case of a necessity.
