### ISSUE TITLE
Error in path: lconvert not found

### ISSUE THREAD

**Issue by PierreM18** [probonopd/linuxdeployqt#410]
I get the following error:
```
ERROR: lconvert not found at "/tmp/.mount_linuxd3HdVVu/usr/bin/lconvert"
ERROR: Failed to copy translations
```
when i use the linuxdeployqt-continuous-x86_64.AppImage in order to create an AppImage.

lconvert is in the file "/usr/bin/lconvert" but il seems to add a part to the path corresponding to tempory path.
I'am on Ubuntu 18.04.3 LTS.

Have you got a solution to solve this issue ?

Thanks

**Comment by probonopd** [comment]
Can you please point me to the `.travis.yml` (see README.md) where this issue can be reproduced? Thanks.

**Comment by PierreM18** [comment]
After little more try it's working. thanks you for the help i close thé issue.

**Comment by m-alansary** [comment]
What is the solution that worked for you as I am facing the same problem?

**Comment by nils-werner** [comment]
I could fix this, although I don't know exactly why it fixes it. I encounter this issue when I provide an appdir like

```
└── usr
    ├── bin
    │   └── your_app
    ├── lib
    └── share
        ├── applications
        │   └── your_app.desktop
        └── icons
            └── <theme>
                └── <resolution> 
                    └── apps 
                        └── your_app.png
```

But I don't encounter this issue when I provide an appdir like

```
├── your_app
├── your_app.desktop
└── your_app.png
```
