### ISSUE TITLE
How to use a toolchain for old version of glibc

### ISSUE THREAD

**Issue by DevDorrejo** [probonopd/linuxdeployqt#417]
Hello, i have configure a toolchain with the old version of glibc 2.23, looking for a solution of the limit of version, but i export the libraries to LD_LIBRARY_PATH, and looks like linuxdeployqt not grab this variable.

what can i do? thank.

**Comment by probonopd** [comment]
The easiest solution is probably to compile on a build system with a distribution version that comes with glibc 2.23 or earlier. For example, if you use Ubuntu xenial, then it should work.

**Comment by DevDorrejo** [comment]
Ok, thank you for the response.

But what is the hardest solution?

**Comment by probonopd** [comment]
A way around this is to compile dependencies yourself on a not too recent base system, and/or to use [LibcWrapGenerator](https://github.com/probonopd/AppImageKit/tree/master/LibcWrapGenerator) or [glibc_version_header](https://github.com/wheybags/glibc_version_header).
