### ISSUE TITLE
Unable to determine the path to the executable when it is located in a subfolder

### ISSUE THREAD

**Issue by YonicDev** [probonopd/linuxdeployqt#418]
I'm trying to deploy an AppImage with Travis CI of my application, but when parsing the desktop file it fails to locate the path to the executable because mostly everything is stored in a folder at `appimage/usr/bin`.

[Build log in Travis CI](https://travis-ci.com/YonicDev/mpdr-qt/builds/150729753)
[Repository](https://github.com/YonicDev/mpdr-qt)

Should I try to place the application at `appimage/usr/bin` and move the other files it uses somewhere else? Or is there a workaround to this?

**Comment by probonopd** [comment]
Please move your main executable to `usr/bin` within the AppDir. This is what we call a "[FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard)-style AppDir".

**Comment by YonicDev** [comment]
It does work after reorganizing everything in an FHS-style AppDir, but I wonder if it could be adapted to work for those who cannot comply to that style.

**Comment by probonopd** [comment]
Thanks for confirming @YonicDev. Since I am working on an entirely new successor tool, I won't be implementing this but am happy to consider pull requests that do.
