### ISSUE TITLE
unable to deploy additional platform plugins

### ISSUE THREAD

**Issue by shi-yan** [probonopd/linuxdeployqt#419]
I want to deploy the libqoffscreen.so platform plugin.

unable to do so. tried:

`-extra-plugins=plugins/platforms/libqoffscreen.so`

`-extra-plugins=offscreen`

**Comment by probonopd** [comment]
Shouldn't it be `-extra-plugins=platforms/libqoffscreen.so`?

**Comment by shi-yan** [comment]
confirm `-extra-plugins=platforms/libqoffscreen.so ` fixes the problem. Thank you.

**Comment by probonopd** [comment]
Thanks for confirming.
