### ISSUE TITLE
Please, add all system dependecies in your distribution.

### ISSUE THREAD

**Issue by 88aleksandr88** [probonopd/linuxdeployqt#421]
I am a teacher. I use new software, new compilers, with all updates. And I can not have another old GNU/Linux distribution for each student only for deployment builds. Can you add all necessary  files to your distribution that it works good at new systems too without showing message "the host system is too new" and result will be compatible with older distributions too. Windeployqt does not require the oldest Windows version.

**Comment by probonopd** [comment]
This is currently under discussion in the AppImage project: https://github.com/AppImage/AppImageKit/issues/225

I am working on an experimental linuxdeployqt replacement that will be able to do this:
https://github.com/probonopd/go-appimage/tree/master/src/appimagetool

**Comment by 88aleksandr88** [comment]
Thank you for reply.
