### ISSUE TITLE
Can't Generate AppImage Because "git"?

### ISSUE THREAD

**Issue by DevDorrejo** [probonopd/linuxdeployqt#427]
hello, i am trying generate a AppImage and at the last line appear this:

`appimagetool, continuous build (commit cddcc2e), build 2034 built on 2019-01-22 15:01:38 UTC
fatal: Not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
NOTE: Using the output of 'git rev-parse --short HEAD' as the version:
      
      Please set the $VERSION environment variable if this is not intended
Desktop file not found, aborting
Log: ret 256
Log: WEXITSTATUS(ret) 1
`

`appdir/
└── usr
    ├── AppRun -> local/bin/app
    └── local
        ├── bin
        │   ├── app
        │   └── qt.conf
        ├── lib
        │   ├── libavahi-client.so.3
        │   ├── libavahi-common.so.3
        │   ├── libbz2.so.1
        │   ├── libcap.so.2
        │   ├── libcups.so.2
        │   ├── libdbus-1.so.3
        │   ├── libffi.so.7
        │   ├── libgcrypt.so.20
        │   ├── libGLdispatch.so.0
        │   ├── libGLX.so.0
        │   ├── libgmp.so.10
        │   ├── libgnutls.so.30
        │   ├── libgssapi_krb5.so.2
        │   ├── libgthread-2.0.so.0
        │   ├── libhogweed.so.4
        │   ├── libicudata.so.56
        │   ├── libicui18n.so.56
        │   ├── libicuuc.so.56
        │   ├── libidn2.so.0
        │   ├── libk5crypto.so.3
        │   ├── libkrb5.so.3
        │   ├── libkrb5support.so.0
        │   ├── liblz4.so.1
        │   ├── liblzma.so.5
        │   ├── libnettle.so.6
        │   ├── libnspr4.so
        │   ├── libnss3.so
        │   ├── libnssutil3.so
        │   ├── libpcre.so.1
        │   ├── libplc4.so
        │   ├── libplds4.so
        │   ├── libpng16.so.16
        │   ├── libQt5Concurrent.so.5
        │   ├── libQt5Core.so.5
        │   ├── libQt5DBus.so.5
        │   ├── libQt5Gui.so.5
        │   ├── libQt5Network.so.5
        │   ├── libQt5Positioning.so.5
        │   ├── libQt5PrintSupport.so.5
        │   ├── libQt5QmlModels.so.5
        │   ├── libQt5Qml.so.5
        │   ├── libQt5Quick.so.5
        │   ├── libQt5QuickWidgets.so.5
        │   ├── libQt5SerialPort.so.5
        │   ├── libQt5Svg.so.5
        │   ├── libQt5WebChannel.so.5
        │   ├── libQt5WebEngineCore.so.5
        │   ├── libQt5WebEngineWidgets.so.5
        │   ├── libQt5Widgets.so.5
        │   ├── libQt5XcbQpa.so.5
        │   ├── libselinux.so.1
        │   ├── libsmime3.so
        │   ├── libsqlite3.so.0
        │   ├── libsystemd.so.0
        │   ├── libtasn1.so.6
        │   ├── libunistring.so.2
        │   ├── libX11-xcb.so.1
        │   ├── libXau.so.6
        │   ├── libxcb-glx.so.0
        │   ├── libxcb-xkb.so.1
        │   ├── libXcomposite.so.1
        │   ├── libXcursor.so.1
        │   ├── libXdamage.so.1
        │   ├── libXext.so.6
        │   ├── libXfixes.so.3
        │   ├── libXi.so.6
        │   ├── libxkbcommon.so.0
        │   ├── libxkbcommon-x11.so.0
        │   ├── libXrandr.so.2
        │   ├── libXrender.so.1
        │   └── libXtst.so.6
        ├── libexec
        │   ├── qt.conf
        │   └── QtWebEngineProcess
        ├── plugins
        │   ├── bearer
        │   │   ├── libqconnmanbearer.so
        │   │   ├── libqgenericbearer.so
        │   │   └── libqnmbearer.so
        │   ├── iconengines
        │   │   └── libqsvgicon.so
        │   ├── imageformats
        │   │   ├── libqgif.so
        │   │   ├── libqicns.so
        │   │   ├── libqico.so
        │   │   ├── libqjpeg.so
        │   │   ├── libqsvg.so
        │   │   ├── libqtga.so
        │   │   ├── libqtiff.so
        │   │   ├── libqwbmp.so
        │   │   └── libqwebp.so
        │   ├── platforminputcontexts
        │   │   ├── libcomposeplatforminputcontextplugin.so
        │   │   └── libibusplatforminputcontextplugin.so
        │   ├── platforms
        │   │   └── libqxcb.so
        │   ├── position
        │   │   ├── libqtposition_geoclue2.so
        │   │   ├── libqtposition_geoclue.so
        │   │   ├── libqtposition_positionpoll.so
        │   │   └── libqtposition_serialnmea.so
        │   ├── printsupport
        │   │   └── libcupsprintersupport.so
        │   └── xcbglintegrations
        │       ├── libqxcb-egl-integration.so
        │       └── libqxcb-glx-integration.so
        ├── resources
        │   ├── icudtl.dat
        │   ├── qtwebengine_devtools_resources.pak
        │   ├── qtwebengine_resources_100p.pak
        │   ├── qtwebengine_resources_200p.pak
        │   └── qtwebengine_resources.pak
        ├── share
        │   ├── applications
        │   │   └──app.desktop
        │   └── icons
        │       └── hicolor
        │           └── 64x64
        │               └── app.png
        └── translations
            ├── qt_ar.qm
            ├── qt_bg.qm
            ├── qt_ca.qm
            ├── qt_cs.qm
            ├── qt_da.qm
            ├── qt_de.qm
            ├── qt_en.qm
            ├── qt_es.qm
            ├── qt_fi.qm
            ├── qt_fr.qm
            ├── qt_gd.qm
            ├── qt_he.qm
            ├── qt_hu.qm
            ├── qt_it.qm
            ├── qt_ja.qm
            ├── qt_ko.qm
            ├── qt_lv.qm
            ├── qt_pl.qm
            ├── qt_ru.qm
            ├── qt_sk.qm
            ├── qt_uk.qm
            ├── qtwebengine_locales
            │   ├── am.pak
            │   ├── ar.pak
            │   ├── bg.pak
            │   ├── bn.pak
            │   ├── ca.pak
            │   ├── cs.pak
            │   ├── da.pak
            │   ├── de.pak
            │   ├── el.pak
            │   ├── en-GB.pak
            │   ├── en-US.pak
            │   ├── es-419.pak
            │   ├── es.pak
            │   ├── et.pak
            │   ├── fa.pak
            │   ├── fil.pak
            │   ├── fi.pak
            │   ├── fr.pak
            │   ├── gu.pak
            │   ├── he.pak
            │   ├── hi.pak
            │   ├── hr.pak
            │   ├── hu.pak
            │   ├── id.pak
            │   ├── it.pak
            │   ├── ja.pak
            │   ├── kn.pak
            │   ├── ko.pak
            │   ├── lt.pak
            │   ├── lv.pak
            │   ├── ml.pak
            │   ├── mr.pak
            │   ├── ms.pak
            │   ├── nb.pak
            │   ├── nl.pak
            │   ├── pl.pak
            │   ├── pt-BR.pak
            │   ├── pt-PT.pak
            │   ├── ro.pak
            │   ├── ru.pak
            │   ├── sk.pak
            │   ├── sl.pak
            │   ├── sr.pak
            │   ├── sv.pak
            │   ├── sw.pak
            │   ├── ta.pak
            │   ├── te.pak
            │   ├── th.pak
            │   ├── tr.pak
            │   ├── uk.pak
            │   ├── vi.pak
            │   ├── zh-CN.pak
            │   └── zh-TW.pak
            └── qt_zh_TW.qm

`

**Comment by probonopd** [comment]
Please retry with https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage.

**Comment by anferoar96** [comment]
I had the same issue. My solution was:
1. Delete all the files except for the default.desktop and the default.png 
2. Add  this line **Categories=Office;** to the default.desktop file
3. Re-build the appimage with the command
