### ISSUE TITLE
Bundling a third-party executable

### ISSUE THREAD

**Issue by pajah2** [probonopd/linuxdeployqt#428]
My program is using a third-party executable utility installed via `apt-get install` and currently located in `/usr/bin`. I tried passing it to `linuxdeployqt` via `-executable`, no luck. Is there any standard way to bundle a third-party binary (including its dependencies) to the resulting AppImage?

**Comment by probonopd** [comment]
Please copy that executable to <AppDir>/usr/bin first, and then pass the path inside the AppDir to the copied executable to `linuxdeployqt` via `-executable`.

**Comment by pajah2** [comment]
Thanks a lot for your reply @probonopd!

You mean copy from `/usr/bin` to `appdir/usr/bin`?
I did it and specified the path via `-executable`. However, `findDependencyInfo` (`ldd`) reports `No such file or directory`, though the file **does** exist.

I believe the issue is described here:
https://unix.stackexchange.com/questions/76490/no-such-file-or-directory-on-an-executable-yet-file-exists-and-ldd-reports-al

**Comment by probonopd** [comment]
Can you please run with `-verbosity=2 > log.txt ` and attach the zipped output to this ticket, thanks.

**Comment by pajah2** [comment]
Currently I have no chance to compile and provide the full log, unfortunately. However, here is the particular message:
```
ERROR: findDependencyInfo: "ldd: appimage/usr/bin/adb: No such file or directory\n"
ERROR: getBinaryRPaths: "/usr/bin/objdump: 'appimage/usr/bin/adb': No such file\n"
```
Again, the file **does** exist. This happens to the `adb` package.

These commands should reproduce the behavior:

```
apt install adb
cp /usr/bin/adb appdir/usr/bin
./linuxdeployqt.AppImage appdir/usr/share/applications/foo.desktop -appimage -executable=appimage/usr/bin/adb
```

**Comment by pajah2** [comment]
Oops, there was typo in my script. My bad.
Thanks a lot for your help!
