### ISSUE TITLE
Need a way to name the final output file [Feature Request]

### ISSUE THREAD

**Issue by Light-Wizzard** [probonopd/linuxdeployqt#432]
I searched for a way to do this before posting, it seems so important I could not believe there was no way to name the output of linuxdeployqt, but if there is, I could not find it.
 
I am using Travis builds, and I want my file to have a specific name for the desktop file that is made before the file is created. 

Currently, I pass it the desktop file, this causes it to use the Name, which is Capitalized, and not the same as the exe name, which is bin/lowercase, but my real problem is that I cannot just rename the file because that breaks the zsync file, giving me no control over the name unless I missed something.

Maybe a Feature request for a switch like:

```
./linuxdeployqt*.AppImage "usr/share/applications/${BIN}.desktop" -name=${BIN} -appimage; 
or -appimage=${BIN}; 
and keep it status quo if missing
```

Where BIN is the name of the desktop file, and the file name I want, instead of one with numbers for version or architecture appended to it, and where -name is the switch that will use this name if present as an argument.

I think this feature will help everyone with this issue.

Update: Some thoughts on how to accomplish this:

main.cpp
```
QString appName;

Cut in:
        } else if (argument.startsWith("-name=")) {
            LogDebug() << "Argument found:" << argument;
            int index = argument.indexOf("=");
            appName = argument.mid(index+1);
        }
```

line 557

```
int result = createAppImage(appDirPath, appName);
```

Line 1779

```
/master/tools/linuxdeployqt/shared.cpp/createAppImage
calls 
appimagetool -v 
```
function createAppImage needs to be modified.

```
int createAppImage(const QString &appDirPath)
too
int createAppImage(const QString &appDirPath, const QString &appName)
```

Line 1790

```
if (appName.length > 0)
{
    QString appImageCommand = "appimagetool '" + appDirPath + "' -n " + updateInfoArgument + "--name=" + appName;
}
else
{
    QString appImageCommand = "appimagetool -v '" + appDirPath + "' -n " + updateInfoArgument;
}
```

Now appimagetool needs to be modified to take this new argument.

```
gchar *binary_name = NULL;

static GOptionEntry entries[] =
{ "name", 0, 0, G_OPTION_ARG_STRING, &binary_name, "Binary name", NULL },
```

Line 652
main
 
```char *destination;```

This is where that magic comes in, and you have to hunt down how this is created and modify it.

Around line 832 in main
```
This is what I mean Magic, this is not a path, nor do I know what destination looks like.
if (binary_name != NULL) destination = binary_name;

 int result = sfs_mksquashfs(source, destination, size);
```

I do not know how you would want to implement this, so I did not make a patch, just a rough idea of how much work is involved, and that Magic part will take a little bit more work.

Thanks

**Comment by probonopd** [comment]
> Currently, I pass it the desktop file, this causes it to use the Name, which is Capitalized

This is by design. We want the AppImage name to be the same spelling as the `Name=` key in the desktop file. Like on the Mac.
