### ISSUE TITLE
-verbose=X suppresses errors

### ISSUE THREAD

**Issue by mikhailnov** [probonopd/linuxdeployqt#434]
```
[root@alt-p8 ~]# linuxdeployqt /usr/share/applications/trueconf.desktop  -verbose=3
linuxdeployqt  (commit ), build <local dev build> built on 2020-04-17 15:41:55 UTC
[root@alt-p8 ~]# echo $?
1
[root@alt-p8 ~]# linuxdeployqt /usr/share/applications/trueconf.desktop  -verbose=1
linuxdeployqt  (commit ), build <local dev build> built on 2020-04-17 15:41:55 UTC
[root@alt-p8 ~]# linuxdeployqt /usr/share/applications/trueconf.desktop  -verbose=0
linuxdeployqt  (commit ), build <local dev build> built on 2020-04-17 15:41:55 UTC
[root@alt-p8 ~]# echo $?
1
[root@alt-p8 ~]# linuxdeployqt /usr/share/applications/trueconf.desktop
linuxdeployqt  (commit ), build <local dev build> built on 2020-04-17 15:41:55 UTC
QDir::exists: Empty or null file name
[root@alt-p8 ~]# 
```

I think that error must be printed in verbose mode.

**Comment by mikhailnov** [comment]
adding any other oprion. e.g. `-appimage` has the same effect

**Comment by mikhailnov** [comment]
I had to run it under gdb to see the real error
```
354	    if (QDir().exists(appBinaryPath)) {
(gdb) n
QDir::exists: Empty or null file name
357	        LogError() << "Error: Could not find app-binary" << appBinaryPath;
(gdb) 
```

**Comment by mikhailnov** [comment]
I think it is because in the 1st case there is only one arg, in the second case there are 2 arrgs, but code under `if (argc > 2) {` is different

**Comment by probonopd** [comment]
Thanks @mikhailnov - would you be able to send a pull request please? That would be a great help.

**Comment by mikhailnov** [comment]
I don't know how to fix it quickly because it will require rework of logics of parsing arguements, I think

**Comment by probonopd** [comment]
As I am deprecating this project in favor of https://github.com/probonopd/go-appimage/tree/master/src/appimagetool I will not work on this. But I will definitely honor pull requests should someone choose to.
