### ISSUE TITLE
have to specify LD_LIBRARY_PATH - will that cause problems?

### ISSUE THREAD

**Issue by hn-88** [probonopd/linuxdeployqt#439]
Hi,

In my earlier projects, creating AppImages with Travis on trusty and later xenial would work with the sample code as given in the documentation, where unset LD_LIBRARY_PATH is called before the call to linuxdeployqt.

But in a new project, I have made one change, which is to use pre-compiled binaries for OpenCV using a script,
https://github.com/hn-88/OCVvid2fulldome/blob/master/opencv430install.sh

When I do this, I need to specify
```export LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib ```
or else linuxdeployqt fails, saying ldd could not find the opencv so files. 

After specifying the LD_LIBRARY_PATH in this way, the AppImage is created without any problem.

My question is, will specifying LD_LIBRARY_PATH in this way cause any problems or incompatibilities in the resulting AppImage?

Here is the build log link,
https://travis-ci.org/github/hn-88/OCVvid2fulldome/builds/686038264

**Comment by probonopd** [comment]
Hi  @hn-88. No, that should not cause problems with the resulting AppImages.

**Comment by hn-88** [comment]
Thanks @probonopd  - that's good to know.
