### ISSUE TITLE
report ERROR: The host system is too new on debian 10

### ISSUE THREAD

**Issue by carlos444** [probonopd/linuxdeployqt#440]
linuxdeployqt
linuxdeployqt 6 (commit c6bcad2), build 715 built on 2020-04-12 12:21:56 UTC
ERROR: The host system is too new.
Please run on a system with a glibc version no newer than what comes with the oldest
 
First time get report that debian's library is too new, any way to use it on debian 10?

**Comment by probonopd** [comment]
Debian 10 is from 2019. It is much too new. To produce binaries that will run on all still-supported LTS distributions please build on an older system, e.g., Ubuntu xenial which is from 2016.

**Comment by ArbitCode** [comment]
Do we need to change the operating system 20.04 to Ubuntu xenial as we can see there ubuntu xenial is lower version of Linux distribution?

**Comment by probonopd** [comment]
Yes.

> Please run on a system with a glibc version no newer than what comes with the oldest
currently still-supported mainstream distribution (**xenial**), which is glibc 2.23.
