### ISSUE TITLE
Simple QT app causes "xcb" crash

### ISSUE THREAD

**Issue by rmacyn** [probonopd/linuxdeployqt#442]
Hey Guys,

We're having some issues using linuxdeployqt on our main application (http://www.squidnetsoftware.com). For whatever reason, I keep getting that dreaded "xcb" error:

"This application failed to start because it could not find or load the Qt platform plugin "xcb".
Reinstalling the application may fix this problem."

After spending a few days on this, we decided to try building a smaller application to see if we could isolate the issue. We used an example project from the Qt examples database and were able to recreate the issue by simply including a reference to a QSettings object in the the main.cpp source file. We've scoured the web and noticed a lot of issues with the same output message ... but all with different causes.  

Enabled "export QT_DEBUG_PLUGINS=1" debugging to get this:

 ./nestedlayouts--x86_64.AppImage 
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_nestedLYs8Aw/platforms" ... 
This application failed to start because it could not find or load the Qt platform plugin "xcb".

Reinstalling the application may fix this problem.
Aborted (core dumped)

If we simply remove this line:

static QSettings        settings("MyTest", "MyApp"); 

All is good !!!

What are we doing wrong here? Obviously, we don't understand something :( ....Can you please help us get past this??

Test project files attached:

Here's our setup:
Build host:
    Ubuntu 14.04
    QMake version: Using Qt version 5.2.1 in /usr/lib/x86_64-linux-gnu

Test host:
   OpenSuse (opensuse-tumbleweed)
  Fedora (latest)

Runtime output logs:

We've attached the complete log below (with extraction and ldd outputs)

ralvarez@localhost:~/nested_app> ./nestedlayouts--x86_64.AppImage 
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_nestedLYs8Aw/platforms" ... 
This application failed to start because it could not find or load the Qt platform plugin "xcb".

Reinstalling the application may fix this problem.
Aborted (core dumped)

./nestedlayouts--x86_64.AppImage --appimage-extract
squashfs-root/.DirIcon
squashfs-root/AppRun
squashfs-root/doc
squashfs-root/doc/libasyncns0
squashfs-root/doc/libasyncns0/copyright
squashfs-root/doc/libc6-dbg
squashfs-root/doc/libc6-dbg/copyright
squashfs-root/doc/libdbus-1-3
squashfs-root/doc/libdbus-1-3/copyright
squashfs-root/doc/libffi6
squashfs-root/doc/libffi6/copyright
squashfs-root/doc/libflac8
squashfs-root/doc/libflac8/copyright
squashfs-root/doc/libgraphite2-3
squashfs-root/doc/libgraphite2-3/copyright
squashfs-root/doc/libicu52
squashfs-root/doc/libicu52/copyright
squashfs-root/doc/libjpeg-turbo8
squashfs-root/doc/libjpeg-turbo8/copyright
squashfs-root/doc/libjson-c2
squashfs-root/doc/libjson-c2/copyright
squashfs-root/doc/libogg0
squashfs-root/doc/libogg0/copyright
squashfs-root/doc/libpcre3
squashfs-root/doc/libpcre3/copyright
squashfs-root/doc/libpng12-0
squashfs-root/doc/libpng12-0/copyright
squashfs-root/doc/libpulse0
squashfs-root/doc/libpulse0/copyright
squashfs-root/doc/libqt5core5a
squashfs-root/doc/libqt5core5a/copyright
squashfs-root/doc/libqt5dbus5
squashfs-root/doc/libqt5dbus5/copyright
squashfs-root/doc/libqt5gui5
squashfs-root/doc/libqt5gui5/copyright
squashfs-root/doc/libqt5multimedia5
squashfs-root/doc/libqt5multimedia5/copyright
squashfs-root/doc/libqt5network5
squashfs-root/doc/libqt5network5/copyright
squashfs-root/doc/libqt5widgets5
squashfs-root/doc/libqt5widgets5/copyright
squashfs-root/doc/libsndfile1
squashfs-root/doc/libsndfile1/copyright
squashfs-root/doc/libvorbis0a
squashfs-root/doc/libvorbis0a/copyright
squashfs-root/doc/libvorbisenc2
squashfs-root/doc/libvorbisenc2/copyright
squashfs-root/doc/libwrap0
squashfs-root/doc/libwrap0/copyright
squashfs-root/doc/libx11-xcb1
squashfs-root/doc/libx11-xcb1/copyright
squashfs-root/doc/libxau6
squashfs-root/doc/libxau6/copyright
squashfs-root/doc/libxcb-glx0-dev
squashfs-root/doc/libxcb-glx0-dev/copyright
squashfs-root/doc/libxcb-icccm4
squashfs-root/doc/libxcb-icccm4/copyright
squashfs-root/doc/libxcb-image0
squashfs-root/doc/libxcb-image0/copyright
squashfs-root/doc/libxcb-keysyms1
squashfs-root/doc/libxcb-keysyms1/copyright
squashfs-root/doc/libxcb-present0
squashfs-root/doc/libxcb-present0/copyright
squashfs-root/doc/libxcb-randr0-dev
squashfs-root/doc/libxcb-randr0-dev/copyright
squashfs-root/doc/libxcb-render-util0
squashfs-root/doc/libxcb-render-util0/copyright
squashfs-root/doc/libxcb-render0-dev
squashfs-root/doc/libxcb-render0-dev/copyright
squashfs-root/doc/libxcb-shape0-dev
squashfs-root/doc/libxcb-shape0-dev/copyright
squashfs-root/doc/libxcb-shm0
squashfs-root/doc/libxcb-shm0/copyright
squashfs-root/doc/libxcb-sync1
squashfs-root/doc/libxcb-sync1/copyright
squashfs-root/doc/libxcb-util0
squashfs-root/doc/libxcb-util0/copyright
squashfs-root/doc/libxcb-xfixes0
squashfs-root/doc/libxcb-xfixes0/copyright
squashfs-root/doc/libxcb-xkb1
squashfs-root/doc/libxcb-xkb1/copyright
squashfs-root/doc/libxdamage1
squashfs-root/doc/libxdamage1/copyright
squashfs-root/doc/libxdmcp6
squashfs-root/doc/libxdmcp6/copyright
squashfs-root/doc/libxext6
squashfs-root/doc/libxext6/copyright
squashfs-root/doc/libxfixes3
squashfs-root/doc/libxfixes3/copyright
squashfs-root/doc/libxi6
squashfs-root/doc/libxi6/copyright
squashfs-root/doc/libxkbcommon-x11-0
squashfs-root/doc/libxkbcommon-x11-0/copyright
squashfs-root/doc/libxkbcommon0
squashfs-root/doc/libxkbcommon0/copyright
squashfs-root/doc/libxrender1
squashfs-root/doc/libxrender1/copyright
squashfs-root/doc/libxshmfence1
squashfs-root/doc/libxshmfence1/copyright
squashfs-root/doc/libxxf86vm1
squashfs-root/doc/libxxf86vm1/copyright
squashfs-root/lib
squashfs-root/lib/libFLAC.so.8
squashfs-root/lib/libQt5Core.so.5
squashfs-root/lib/libQt5DBus.so.5
squashfs-root/lib/libQt5Gui.so.5
squashfs-root/lib/libQt5Multimedia.so.5
squashfs-root/lib/libQt5Network.so.5
squashfs-root/lib/libQt5Widgets.so.5
squashfs-root/lib/libX11-xcb.so.1
squashfs-root/lib/libXau.so.6
squashfs-root/lib/libXdamage.so.1
squashfs-root/lib/libXdmcp.so.6
squashfs-root/lib/libXext.so.6
squashfs-root/lib/libXfixes.so.3
squashfs-root/lib/libXi.so.6
squashfs-root/lib/libXrender.so.1
squashfs-root/lib/libXxf86vm.so.1
squashfs-root/lib/libasyncns.so.0
squashfs-root/lib/libdbus-1.so.3
squashfs-root/lib/libffi.so.6
squashfs-root/lib/libgraphite2.so.3
squashfs-root/lib/libicudata.so.52
squashfs-root/lib/libicui18n.so.52
squashfs-root/lib/libicuuc.so.52
squashfs-root/lib/libjpeg.so.8
squashfs-root/lib/libjson-c.so.2
squashfs-root/lib/libnsl.so.1
squashfs-root/lib/libogg.so.0
squashfs-root/lib/libpcre.so.3
squashfs-root/lib/libpng12.so.0
squashfs-root/lib/libpulse.so.0
squashfs-root/lib/libpulsecommon-4.0.so
squashfs-root/lib/libsndfile.so.1
squashfs-root/lib/libvorbis.so.0
squashfs-root/lib/libvorbisenc.so.2
squashfs-root/lib/libwrap.so.0
squashfs-root/lib/libxcb-glx.so.0
squashfs-root/lib/libxcb-icccm.so.4
squashfs-root/lib/libxcb-image.so.0
squashfs-root/lib/libxcb-keysyms.so.1
squashfs-root/lib/libxcb-present.so.0
squashfs-root/lib/libxcb-randr.so.0
squashfs-root/lib/libxcb-render-util.so.0
squashfs-root/lib/libxcb-render.so.0
squashfs-root/lib/libxcb-shape.so.0
squashfs-root/lib/libxcb-shm.so.0
squashfs-root/lib/libxcb-sync.so.1
squashfs-root/lib/libxcb-util.so.0
squashfs-root/lib/libxcb-xfixes.so.0
squashfs-root/lib/libxcb-xkb.so.1
squashfs-root/lib/libxkbcommon-x11.so.0
squashfs-root/lib/libxkbcommon.so.0
squashfs-root/lib/libxshmfence.so.1
squashfs-root/nestedlayouts
squashfs-root/nestedlayouts.desktop
squashfs-root/nestedlayouts.png
squashfs-root/plugins
squashfs-root/plugins/bearer
squashfs-root/plugins/bearer/libqconnmanbearer.so
squashfs-root/plugins/bearer/libqgenericbearer.so
squashfs-root/plugins/bearer/libqnmbearer.so
squashfs-root/plugins/imageformats
squashfs-root/plugins/imageformats/libqgif.so
squashfs-root/plugins/imageformats/libqico.so
squashfs-root/plugins/imageformats/libqjpeg.so
squashfs-root/plugins/platforminputcontexts
squashfs-root/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so
squashfs-root/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so
squashfs-root/plugins/platforms
squashfs-root/plugins/platforms/libqxcb.so
squashfs-root/qt.conf
ralvarez@localhost:~/nested_app> cd ./squashfs-root/
ralvarez@localhost:~/nested_app/squashfs-root> ldd ./AppRun 
	linux-vdso.so.1 (0x00007ffe0bfcb000)
	libQt5Multimedia.so.5 => /home/ralvarez/nested_app/squashfs-root/./lib/libQt5Multimedia.so.5 (0x00007fe2fe2be000)
	libQt5Widgets.so.5 => /home/ralvarez/nested_app/squashfs-root/./lib/libQt5Widgets.so.5 (0x00007fe2fda30000)
	libQt5Network.so.5 => /home/ralvarez/nested_app/squashfs-root/./lib/libQt5Network.so.5 (0x00007fe2fd6db000)
	libQt5Gui.so.5 => /home/ralvarez/nested_app/squashfs-root/./lib/libQt5Gui.so.5 (0x00007fe2fd043000)
	libQt5Core.so.5 => /home/ralvarez/nested_app/squashfs-root/./lib/libQt5Core.so.5 (0x00007fe2fc96b000)
	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007fe2fc77e000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fe2fc762000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fe2fc59c000)
	libpulse.so.0 => /home/ralvarez/nested_app/squashfs-root/./lib/libpulse.so.0 (0x00007fe2fc353000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fe2fc331000)
	libgobject-2.0.so.0 => /usr/lib64/libgobject-2.0.so.0 (0x00007fe2fc2d2000)
	libglib-2.0.so.0 => /usr/lib64/libglib-2.0.so.0 (0x00007fe2fc1a8000)
	libX11.so.6 => /usr/lib64/libX11.so.6 (0x00007fe2fc062000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fe2fbf1c000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fe2fbf02000)
	libpng12.so.0 => /home/ralvarez/nested_app/squashfs-root/./lib/libpng12.so.0 (0x00007fe2fbcda000)
	libharfbuzz.so.0 => /usr/lib64/libharfbuzz.so.0 (0x00007fe2fbc00000)
	libGL.so.1 => /usr/lib64/libGL.so.1 (0x00007fe2fbb67000)
	libicui18n.so.52 => /home/ralvarez/nested_app/squashfs-root/./lib/libicui18n.so.52 (0x00007fe2fb714000)
	libicuuc.so.52 => /home/ralvarez/nested_app/squashfs-root/./lib/libicuuc.so.52 (0x00007fe2fb37e000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fe2fb379000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fe2fb36e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fe2fe5b1000)
	libjson-c.so.2 => /home/ralvarez/nested_app/squashfs-root/./lib/libjson-c.so.2 (0x00007fe2fb162000)
	libpulsecommon-4.0.so => /home/ralvarez/nested_app/squashfs-root/./lib/libpulsecommon-4.0.so (0x00007fe2faef4000)
	libdbus-1.so.3 => /home/ralvarez/nested_app/squashfs-root/./lib/libdbus-1.so.3 (0x00007fe2facac000)
	libffi.so.8 => /usr/lib64/libffi.so.8 (0x00007fe2faca0000)
	libpcre.so.1 => /usr/lib64/libpcre.so.1 (0x00007fe2fac08000)
	libxcb.so.1 => /usr/lib64/libxcb.so.1 (0x00007fe2fabdd000)
	libfreetype.so.6 => /usr/lib64/libfreetype.so.6 (0x00007fe2fab1d000)
	libgraphite2.so.3 => /usr/lib64/libgraphite2.so.3 (0x00007fe2faafb000)
	libGLX.so.0 => /usr/lib64/libGLX.so.0 (0x00007fe2faac9000)
	libGLdispatch.so.0 => /usr/lib64/libGLdispatch.so.0 (0x00007fe2faa0b000)
	libicudata.so.52 => /home/ralvarez/nested_app/squashfs-root/./lib/libicudata.so.52 (0x00007fe2f919d000)
	libwrap.so.0 => /home/ralvarez/nested_app/squashfs-root/./lib/libwrap.so.0 (0x00007fe2f8f90000)
	libsndfile.so.1 => /home/ralvarez/nested_app/squashfs-root/./lib/libsndfile.so.1 (0x00007fe2f8d27000)
	libasyncns.so.0 => /home/ralvarez/nested_app/squashfs-root/./lib/libasyncns.so.0 (0x00007fe2f8b20000)
	libXau.so.6 => /usr/lib64/libXau.so.6 (0x00007fe2f8b1b000)
	libbz2.so.1 => /usr/lib64/libbz2.so.1 (0x00007fe2f8afb000)
	libpng16.so.16 => /usr/lib64/libpng16.so.16 (0x00007fe2f8ab3000)
	libbrotlidec.so.1 => /usr/lib64/libbrotlidec.so.1 (0x00007fe2f8aa3000)
	libnsl.so.1 => /home/ralvarez/nested_app/squashfs-root/./lib/libnsl.so.1 (0x00007fe2f8887000)
	libFLAC.so.8 => /home/ralvarez/nested_app/squashfs-root/./lib/libFLAC.so.8 (0x00007fe2f8652000)
	libvorbisenc.so.2 => /home/ralvarez/nested_app/squashfs-root/./lib/libvorbisenc.so.2 (0x00007fe2f8182000)
	libvorbis.so.0 => /home/ralvarez/nested_app/squashfs-root/./lib/libvorbis.so.0 (0x00007fe2f7f54000)
	libogg.so.0 => /home/ralvarez/nested_app/squashfs-root/./lib/libogg.so.0 (0x00007fe2f7d48000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fe2f7d30000)
	libbrotlicommon.so.1 => /usr/lib64/libbrotlicommon.so.1 (0x00007fe2f7d0d000)
ralvarez@localhost:~/nested_app/squashfs-root> 

   

[linuxdeployqt_bug.tar.gz](https://github.com/probonopd/linuxdeployqt/files/4690793/linuxdeployqt_bug.tar.gz)

**Comment by probonopd** [comment]
Hello @rmacyn can you try with exactly the setup described in https://github.com/probonopd/linuxdeployqt#using-linuxdeployqt-with-travis-ci please? And if it does not work, point me to your `.travis.yml` file?

Thanks a lot.

**Comment by rmacyn** [comment]
Hi ... thanks for the tip !!

I was able to fix my issue copying the ./appdir/usr/plugins/platforms folder to ./appdir/usr/bin/.

Then, issuing my build command created a successful applimage:

../../QtTools/Linux/linuxdeployqt-continuous-x86_64.AppImage ./appdir/usr/share/applications/cloud_ui.desktop -appimage -always-overwrite -qmake=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake -extra-plugins=iconengines,platforms,imageformats,platformthemes,organizer,bearer,platformthemes/libqgtk2.so

I was able to very that my application runs on OpenSUSE and Fedora distros !!

Thanks again for the help

**Comment by probonopd** [comment]
> I was able to fix my issue copying the ./appdir/usr/plugins/platforms folder to ./appdir/usr/bin/.

Do you have anything special in there? Because normally `linuxdeployqt` should do this for you...
