### ISSUE TITLE
vlc libraries not binding

### ISSUE THREAD

**Issue by abhay44** [probonopd/linuxdeployqt#45]
Vlc libraries(libvlc or vlc) are not binding to the appimage eventhough I used `-bundle-non-qt-libs`.

**Comment by probonopd** [comment]
Which library/application is supposed to be loading which vlc libraries using which mechanism?

**Comment by abhay44** [comment]
I built a [media_player](https://github.com/abhay44/media_player) using vlc-qt.I get this error[https://github.com/abhay44/media_player/issues/1] when I open the appimage.When I export the vlcpluginpath appimage opens.So,it means vlc is not binding to the appimage..right?

**Comment by abhay44** [comment]
Does this tool bind the system libraries(in my case vlc)?I checked with other sources which don't use vlc.They worked perfectly after deploying.

**Comment by probonopd** [comment]
run with `LD_DEBUG=libs ./Some.AppImage` to see which libraries get loaded by what and from where.

**Comment by abhay44** [comment]
checked.But libvlc is not binding with the tool.

**Comment by probonopd** [comment]
Where is it located?

**Comment by abhay44** [comment]
It's located in `/usr/lib/vlc` directory

**Comment by probonopd** [comment]
Try
```
export LD_LIBRARY_PATH=/usr/lib/vlc
./Your.AppImage
```

**Comment by abhay44** [comment]
Same error `core libvlc error:` .If I export the vlc plugin path,my app is running.It's not binding at all.

**Comment by probonopd** [comment]
Your AppImage does not bundle any VLC plugins.
You need to add them to the AppImage.
