### ISSUE TITLE
AppRun script with gksu or pkexec won't start application

### ISSUE THREAD

**Issue by meetnick** [probonopd/linuxdeployqt#454]
I'm using the following script as my AppRun script:

```
#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"
export LD_LIBRARY_PATH=${HERE}/usr/lib:$LD_LIBRARY_PATH
gksu "${HERE}/usr/bin/launcher" "$@"
#pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS "${HERE}/usr/bin/launcher" "$@"
```

The problem is I can run AppRun without any issues and launcher is launched with sudo permission after entering password by directly executing it. But the same is not true after I deploy an AppImage.

by executing the .AppImage, it asks the password but:
- Suddenly exists after typing correct password with gksu (no output is given)
- Won't start launcher after typing correct password, but the following output is given:
`/usr/bin/env: /tmp/.mount_Launcher_zj3Csd/usr/bin/launcher: Permission denied`

So what is happening and how to work around it? How should I run a program as sudo by forcing user to type sudo password?

**Comment by probonopd** [comment]
AppImages typically get mounted by FUSE, and FUSE restricts other users' access to the mounted filesystem (including root).

So you may want to write out a helper file to `/tmp`, and invoke that helper file with root permissions.

Does this make sense?

**Comment by meetnick** [comment]
OK I did exactly what you suggested and it worked!

Thank you so much Sr. I wish the best for this amazing project!
