### ISSUE TITLE
The Host System is too new.

### ISSUE THREAD

**Issue by ArbitCode** [probonopd/linuxdeployqt#455]
while running ./linuxdeployqt-7-x86_64.AppImage comand in terminal on linux 20.4. 

there is showing error like this

linuxdeployqt 6 (commit d41e234), build 724 built on 2020-07-31 15:51:47 UTC
ERROR: The host system is too new.
Please run on a system with a glibc version no newer than what comes with the oldest
currently still-supported mainstream distribution (xenial), which is glibc 2.23.
This is so that the resulting bundle will work on most still-supported Linux distributions.
For more information, please see
https://github.com/probonopd/linuxdeployqt/issues/340
  
How can we resolve it?

**Comment by probonopd** [comment]
For more information, please see
#340
