### ISSUE TITLE
build error on ubuntu 20.04

### ISSUE THREAD

**Issue by xiedeacc** [probonopd/linuxdeployqt#457]
ERROR: The host system is too new.
Please run on a system with a glibc version no newer than what comes with the oldest
currently still-supported mainstream distribution (xenial), which is glibc 2.23.
This is so that the resulting bundle will work on most still-supported Linux distributions.

**Comment by Silicomancer** [comment]
See https://github.com/probonopd/linuxdeployqt/issues/340
