### ISSUE TITLE
How does linuxdeployqt determine which directory to use as AppDir?

### ISSUE THREAD

**Issue by zilti** [probonopd/linuxdeployqt#458]
As the title says. It seems to have an annoyingly intransparent way of determining it. To the point where I now have the issue that I want to create an Emacs AppImage, but when I set Emacs' prefix to /usr using `./configure --prefix=`, the AppImage will have `/local` as top directory, and when I set the prefix to `./configure --prefix=""` it will have `/usr/local`.

**Comment by probonopd** [comment]
Hi @zilti.

Please use

```
./configure --prefix=/usr
make -j$(nproc)
make install DESTDIR=$(readlink -f appdir) ; find appdir/
```

as described [here](https://github.com/probonopd/linuxdeployqt#for-projects-that-use-cmake-autotools-or-meson-with-ninja-instead-of-qmake).

Are you aware that https://github.com/probonopd/Emacs.AppImage exists?

**Comment by zilti** [comment]
I am aware, yes, but that is very outdated.

I tried to use that code, but when using it, I end up getting `ERROR: Could not determine the path to the executable based on the desktop file`.

**Comment by zilti** [comment]
As a second addendum: Re "Why does this work?" - it doesn't, I still have the same issue as in my initial question

**Comment by probonopd** [comment]
> I am aware, yes, but that is very outdated.

What is outdated about it?

> I tried to use that code, but when using it, I end up getting ERROR: Could not determine the path to the executable based on the desktop file.

Please post your desktop file.

> Why does this work?

* `./configure --prefix=/usr` results in `/usr` being compiled into the binaries as the prefix
* `make install DESTDIR=` results in the files being installed into that location. The prefix from the line above will be inside `DESTDIR`

> And why the find AppDir/?

To see what is in the AppDir. Useful for debugging if things don't work as expected.

**Comment by zilti** [comment]
> > I am aware, yes, but that is very outdated.
> 
> What is outdated about it?

For one, the last release is from 2016

> > I tried to use that code, but when using it, I end up getting ERROR: Could not determine the path to the executable based on the desktop file.
> 
> Please post your desktop file.

```
[Desktop Entry]
Name=Emacs
StartupWMClass=emacs
Comment=An extensible, customizable, free/libre text editor — and more.
GenericName=Text Editor
Exec=emacs
Icon=emacs
Type=Application
Categories=Utility;TextEditor;
X-AppImage-Version=27.1
```

> 
> > Why does this work?
> 
>     * `./configure --prefix=/usr` results in `/usr` being compiled into the binaries as the prefix
> 
>     * `make install DESTDIR=` results in the files being installed into that location. The prefix from the line above will be inside `DESTDIR`

Okay, yes, that is exactly what my code already did, so, no surprise there that changing it to your example didn't result in any different outcome. Now I am still stuck with the fact that, with `--prefix=/usr`, linuxdeployqt ends up thinking AppDir/usr is the AppDir (and thus all the files end up in /squashfs-root/local), and with `--prefix=""`, linuxdeployqt ends up thinking AppDir is the AppDir (and thus all the files end up in /squashfs-root/usr/local).

> 
> > And why the find AppDir/?
> 
> To see what is in the AppDir. Useful for debugging if things don't work as expected.

Okay, good, I was at first thinking that there might be some "magic" going on with that.

**Comment by probonopd** [comment]
> For one, the last release is from 2016

Oh right, sorry, I didn't look at it in a long time :-)

Just to be sure, you do have the following?

```
AppDir/usr/bin/emacs
AppDir/usr/share/applications/emacs.desktop
AppDir/usr/share/icons/hicolor/...
```

?

**Comment by zilti** [comment]
I didn't have `AppDir/usr/share/applications/emacs.desktop`, because it fails as soon as I place it there and gives me an `ERROR: Could not determine the path to the executable based on the desktop file`. Now it worked though: https://travis-ci.com/github/zilti/Emacs.AppImage/builds/184372268

It is still not possible to run it, but I guess that is a separate problem...

**Comment by probonopd** [comment]
> Now it worked though

What made it work?

> It is still not possible to run it, but I guess that is a separate problem...

Indeed. Feel free to open another issue in case you think `linuxdeployqt` is part of that issue.

Happy AppImaging :)
