### ISSUE TITLE
Issue to deploy when using QML...

### ISSUE THREAD

**Issue by mbruel** [probonopd/linuxdeployqt#459]
Hi,
I've found [this issue](https://github.com/probonopd/linuxdeployqt/issues/25) but I'm still not able to deploy my app ([ClementineRemote](https://github.com/mbruel/ClementineRemote))

I've created a qtquick folder where I've copied: 
```
cp -r /opt/Qt/5.15.0/gcc_64/qml/Qt qtquick
cp -r /opt/Qt/5.15.0/gcc_64/qml/QtQ* .
```

I run this command:
```
mb@SRV:/tmp/ClementineRemote$ ../linuxdeployqt-6-x86_64.AppImage release/ClementineRemote.desktop -appimage -qmake=/opt/Qt/5.15.0/gcc_64/bin/qmake -qmldir=/tmp/ClementineRemote/release/qtquick/
linuxdeployqt 5 (commit 37631e5), build 631 built on 2019-01-25 22:47:58 UTC
Desktop file as first argument: "release/ClementineRemote.desktop"
desktopExecEntry: "ClementineRemote"
desktopIconEntry: "ClementineRemote"
Found binary from desktop file: "/tmp/ClementineRemote/release/ClementineRemote"
Not using FHS-like mode
app-binary: "/tmp/ClementineRemote/release/ClementineRemote"
appDirPath: "/tmp/ClementineRemote/release"
relativeBinPath: "ClementineRemote"
Found icons from desktop file: ("/tmp/ClementineRemote/release/ClementineRemote.png")
preExistingToplevelIcon: "/tmp/ClementineRemote/release/ClementineRemote.png"
ERROR: ldd outputLine: "libodbc.so.2 => not found"
ERROR: for binary: "/opt/Qt/5.15.0/gcc_64/plugins/sqldrivers/libqsqlodbc.so"
ERROR: Please ensure that all libraries can be found by ldd. Aborting.
mb@SRV:/tmp/ClementineRemote$ du -hs release/
140M	release/
```

It's taking ages and the size of the release folder is 140MB... oO

How do I choose what I need to copy to the qtquick folder? Is this still needed?
I've the same result if I use `-qmldir=/opt/Qt/5.15.0/gcc_64/qml/`

If I don't use `-qmldir` it builds but then when I execute I'm getting:
```
QQmlApplicationEngine failed to load component
qrc:/main.qml:23:1: module "QtQuick.Window" is not installed
```

Thanks in advance for the help ;)
PS: if you try to compile my project, you first need to use protoc to generate the c++ files, in `ClementineRemote/src/protobuf` just run `protoc remotecontrolmessages.proto --cpp_out=.` (you need the pakages protobuf-compiler and libprotobuf-dev)

**Comment by mbruel** [comment]
my bad...
using the path of my project as qmldir it is working great \o/
The command is then: `linuxdeployqt-6-x86_64.AppImage release/ClementineRemote.desktop -appimage -qmake=/opt/Qt/5.15.0/gcc_64/bin/qmake -qmldir=/tmp/ClementineRemote/src/`

**Comment by probonopd** [comment]
Glad you figured it out @mbruel.

**Comment by mbruel** [comment]
Thanks,
I'm also using linuxdeployqt and AppImage for this project: https://github.com/mbruel/ngPost
