### ISSUE TITLE
don't just exit if there's not permission to /dev/fuse

### ISSUE THREAD

**Issue by darealshinji** [probonopd/linuxdeployqt#46]
If I get it right fuse is used to build the AppImage. But if you simply want to copy all the stuff into a bundle fuse shouldn't be required?

**Comment by probonopd** [comment]
FUSE is used to mount the AppImage at runtime. Alternatively, one can use `--appimage-extract` to extract the contents of the AppImage, which in theory would not require FUSE, if we could modify runtime.c to dlopen() rather than require libfuse.

**Comment by travisrecupero** [comment]
This only creates "AppRun" which is a symbolic link to the executable

**Comment by probonopd** [comment]
Running an AppImage with `--appimage-extract` will unpack the entire contents of the AppImage to a new folder called `squashfs-root`. Please let us know if it doesn't do that in your case.
