### ISSUE TITLE
Package not found error when running AppImage in a different system

### ISSUE THREAD

**Issue by Gowresh7** [probonopd/linuxdeployqt#460]
Hi guys,

I am creating a Qt based UI for a Robot Operating System (ROS) based application. I was able to create an AppImage using linuxdeployqt. The AppImage works perfect in systems having ROS installed. But in systems that do not have ROS, I am getting the following error:-

`[rospack] Error: package 'image_transport' not found
[librospack]: error while executing command
terminate called after throwing an instance of 'pluginlib::ClassLoaderException'
  what():  Unable to find package: image_transport
Aborted (core dumped)
`
This is just one of the libraries that I used for the UI. I used the ldd command to list the libraries associated with my binary, yielding the following:-

`linux-vdso.so.1 =>  (0x00007ffc3e710000)
	libimage_transport.so => /opt/ros/kinetic/lib/libimage_transport.so (0x00007fe3f154b000)
	libroscpp.so => /opt/ros/kinetic/lib/libroscpp.so (0x00007fe3f11b9000)
	librosconsole.so => /opt/ros/kinetic/lib/librosconsole.so (0x00007fe3f0f87000)
	libroscpp_serialization.so => /opt/ros/kinetic/lib/libroscpp_serialization.so (0x00007fe3f0d84000)
	librostime.so => /opt/ros/kinetic/lib/librostime.so (0x00007fe3f0b57000)
	libboost_system.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0 (0x00007fe3f0953000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fe3f0736000)
	libQt5Quick.so.5 => /home/ananta/Qt5.12.9/5.12.9/gcc_64/lib/libQt5Quick.so.5 (0x00007fe3f0096000)
	libQt5Gui.so.5 => /home/ananta/Qt5.12.9/5.12.9/gcc_64/lib/libQt5Gui.so.5 (0x00007fe3ef847000)
	libQt5Qml.so.5 => /home/ananta/Qt5.12.9/5.12.9/gcc_64/lib/libQt5Qml.so.5 (0x00007fe3ef1a4000)
	libQt5Core.so.5 => /home/ananta/Qt5.12.9/5.12.9/gcc_64/lib/libQt5Core.so.5 (0x00007fe3eea09000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fe3ee687000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fe3ee471000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe3ee0a7000)
	libmessage_filters.so => /opt/ros/kinetic/lib/libmessage_filters.so (0x00007fe3edea2000)
	libtinyxml2.so.2 => /usr/lib/x86_64-linux-gnu/libtinyxml2.so.2 (0x00007fe3edc8f000)
	libclass_loader.so => /opt/ros/kinetic/lib/libclass_loader.so (0x00007fe3eda6b000)
	libroslib.so => /opt/ros/kinetic/lib/libroslib.so (0x00007fe3ed859000)
	libboost_filesystem.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.58.0 (0x00007fe3ed641000)
	libconsole_bridge.so.0.2 => /usr/lib/x86_64-linux-gnu/libconsole_bridge.so.0.2 (0x00007fe3ed43c000)
	libxmlrpcpp.so => /opt/ros/kinetic/lib/libxmlrpcpp.so (0x00007fe3ed21d000)
	libcpp_common.so => /opt/ros/kinetic/lib/libcpp_common.so (0x00007fe3ed015000)
	libboost_thread.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.58.0 (0x00007fe3ecdef000)
	libboost_chrono.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_chrono.so.1.58.0 (0x00007fe3ecbe7000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fe3ec8de000)
	librosconsole_log4cxx.so => /opt/ros/kinetic/lib/librosconsole_log4cxx.so (0x00007fe3ec6c5000)
	librosconsole_backend_interface.so => /opt/ros/kinetic/lib/librosconsole_backend_interface.so (0x00007fe3ec4c3000)
	liblog4cxx.so.10 => /usr/lib/x86_64-linux-gnu/liblog4cxx.so.10 (0x00007fe3ec0ec000)
	libboost_regex.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_regex.so.1.58.0 (0x00007fe3ebde4000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fe3ebbdc000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fe3f17cd000)
	libQt5Network.so.5 => /home/ananta/Qt5.12.9/5.12.9/gcc_64/lib/libQt5Network.so.5 (0x00007fe3eb834000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1 (0x00007fe3eb5c0000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fe3eb3a6000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fe3eb1a2000)
	libicui18n.so.56 => /home/ananta/Qt5.12.9/5.12.9/gcc_64/lib/libicui18n.so.56 (0x00007fe3ead09000)
	libicuuc.so.56 => /home/ananta/Qt5.12.9/5.12.9/gcc_64/lib/libicuuc.so.56 (0x00007fe3ea951000)
	libicudata.so.56 => /home/ananta/Qt5.12.9/5.12.9/gcc_64/lib/libicudata.so.56 (0x00007fe3e8f6e000)
	libgthread-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0 (0x00007fe3e8d6c000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fe3e8a5b000)
	libPocoFoundation.so.9 => /usr/lib/libPocoFoundation.so.9 (0x00007fe3e86ff000)
	librospack.so => /opt/ros/kinetic/lib/librospack.so (0x00007fe3e84bd000)
	libapr-1.so.0 => /usr/lib/x86_64-linux-gnu/libapr-1.so.0 (0x00007fe3e828b000)
	libaprutil-1.so.0 => /usr/lib/x86_64-linux-gnu/libaprutil-1.so.0 (0x00007fe3e8064000)
	libicui18n.so.55 => /usr/lib/x86_64-linux-gnu/libicui18n.so.55 (0x00007fe3e7c02000)
	libicuuc.so.55 => /usr/lib/x86_64-linux-gnu/libicuuc.so.55 (0x00007fe3e786e000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fe3e7645000)
	libxcb-dri3.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0 (0x00007fe3e7442000)
	libxcb-present.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-present.so.0 (0x00007fe3e723f000)
	libxcb-sync.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1 (0x00007fe3e7038000)
	libxshmfence.so.1 => /usr/lib/x86_64-linux-gnu/libxshmfence.so.1 (0x00007fe3e6e35000)
	libglapi.so.0 => /usr/lib/x86_64-linux-gnu/libglapi.so.0 (0x00007fe3e6c04000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007fe3e69f2000)
	libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007fe3e67ef000)
	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007fe3e65e9000)
	libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007fe3e63e7000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fe3e60ad000)
	libxcb-glx.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0 (0x00007fe3e5e94000)
	libxcb-dri2.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0 (0x00007fe3e5c8f000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fe3e5a6d000)
	libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007fe3e5867000)
	libdrm.so.2 => /usr/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007fe3e5655000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fe3e53e5000)
	libtinyxml.so.2.6.2 => /usr/lib/x86_64-linux-gnu/libtinyxml.so.2.6.2 (0x00007fe3e51cf000)
	libboost_program_options.so.1.58.0 => /usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.58.0 (0x00007fe3e4f51000)
	libpython2.7.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 (0x00007fe3e49c3000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007fe3e47be000)
	libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007fe3e4586000)
	libicudata.so.55 => /usr/lib/x86_64-linux-gnu/libicudata.so.55 (0x00007fe3e2acf000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fe3e28cb000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fe3e26c5000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fe3e24c2000)
`

What steps should I take to make the AppImage work in all systems irrespective of whether ROS is installed or not?

**Comment by probonopd** [comment]
Hi @Gowresh7. 

>  package 'image_transport' not found

Note that it says "package", not "shared library". What is a "package"? Do you know how the missing file is named, and how it could be detected by `linuxdeployqt` that this file is needed? Is it `libimage_transport.so`? Is `libimage_transport.so` getting deployed into your AppDir/AppImage?

**Comment by Gowresh7** [comment]
>  What is a "package"? Do you know how the missing file is named, and how it could be detected by `linuxdeployqt` that this file is needed? Is it `libimage_transport.so`? Is `libimage_transport.so` getting deployed into your AppDir/AppImage?

Hi @probonopd Thanks for your reply.

A package in this case is a ROS package. image_transport is a ROS package installed in my development system where I run Qt Creator. When I run the AppImage in my development system or in systems that have ROS installed, it run perfectly. But in systems that do not have ROS, this error shows up.

The libimage_transport.so is getting deployed along with the AppImage. I can locate that file in the lib folder. But it is just not enough for the AppImage to run successfully in environments that do not have ROS installed.

This is how the image_transport ROS Package looks like:-

[https://github.com/ros-perception/image_common/tree/noetic-devel/image_transport](url)

This package is located in my development system in the following directory:-

/opt/ros/kinetic/share/image_transport/

**Comment by probonopd** [comment]
Closing since ROS is not supported at this time. Feel free to comment if someone would like to add ROS support.
