### ISSUE TITLE
how to restart an application that have been build with `linuxdeployqt` ?

### ISSUE THREAD

**Issue by Milerius** [probonopd/linuxdeployqt#462]
Hello @probonopd i would like to have a hint to restart an application that is build with `linuxdeployqt` the following code work for every platform including linux except for appimage, restarting an application is something that should be straightforward and i understand the mount of an appimage, but i just have no idea how to restart properly an application that's run through an appimage

```cpp
void
    application::restart()
    {
        qApp->quit();

        QProcess::startDetached(qApp->arguments()[0], qApp->arguments(), qApp->applicationDirPath());
    }
```

EDIT: i found a solution

```cpp
void
    application::restart()
    {
        const char* appimage = nullptr;
        if (appimage = std::getenv("APPIMAGE"); appimage)
        {
            spdlog::info("APPIMAGE path is {}", appimage);
        }

        qApp->quit();

        if (appimage == nullptr)
        {
            QProcess::startDetached(qApp->arguments()[0], qApp->arguments(), qApp->applicationDirPath());
        }
        else
        {
            QString path(appimage);
            QProcess::startDetached(path);
        }
    }
```

Not sure if it's the most idiomatic one but seems to work

**Comment by probonopd** [comment]
An AppImage is a self-mounting disk image that mounts itself and executes the application inside it. Once that application exits, the AppImage gets unmounted. So you have two options:

1. Wrap your application in a script/process that never exits until the last instance of your application has quit
2. Don't have your app restart itself but rather start the AppImage it is in if the environment variable `APPIMAGE` exists and is not empty. Conventiently this environment variable contains the path to the AppImage you need to start.

**Comment by Milerius** [comment]
> Hello @Milerius.
> 
> An AppImage is a self-mounting disk image that mounts itself and executes the application inside it. Once that application exits, the AppImage gets unmounted. So you have two options:
> 
> 1. Wrap your application in a script/process that never exits until the last instance of your application has quit
> 2. Don't have your app restart itself but rather start the AppImage it is in if the environment variable `APPIMAGE` exists and is not empty. Conventiently this environment variable contains the path to the AppImage you need to start.

I did the second solution (see my edit)

Works like a charm thanks for your help
