### ISSUE TITLE
More Applications using qtlinuxdeploy

### ISSUE THREAD

**Issue by OlivierLDff** [probonopd/linuxdeployqt#464]
I have couple of open source applications that are using linuxdeployqt from cmake build and are build in github Ci:

* https://github.com/OlivierLDff/QaterialGallery
* https://github.com/OlivierLDff/QaterialHotReload
* https://github.com/OlivierLDff/ArtnetConverter

They are all using a cmake function that wrap linuxdeployqt as a cmake target
* https://github.com/OlivierLDff/QtLinuxCMake

I use this docker image to build in github actions:
* https://github.com/OlivierLDff/QtLinuxCMakeDocker

Hope this examples might help some people.
Thank you for the great work.

**Comment by probonopd** [comment]
Does not run on Ubuntu xenial, built on a too new system:

```
/usr/bin/ArtnetConverter: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found 
```

**Comment by OlivierLDff** [comment]
Gcc 7.5.0 was used, is it too high?

**Comment by probonopd** [comment]
The oldest still-supported mainstream Linux distibution is xenial at this point.
According to https://packages.ubuntu.com/xenial/gcc 5.3.1 is the one that comes with xenial.

**Comment by OlivierLDff** [comment]
My bad the three application use `std::clamp` everywhere which come with gcc 7.1.
Is there any recommended workaround for me to downgrade to c++14?

**Comment by TheAssassin** [comment]
Use an alternative implementation that you can build into your application. For instance, boost's algorithms library provides an implementation, which you might be able to use (they use a permissive license).
