### ISSUE TITLE
can 20.04 appimage work on the 18.04 ?

### ISSUE THREAD

**Issue by MyraBaba** [probonopd/linuxdeployqt#467]
What is the possibility of the appImage created with 20.04 run on the 18.04 ? 

best

**Comment by probonopd** [comment]
The other way around: If you create AppImages on 16.04 then they will run on it and subsequent versions.

**Comment by MyraBaba** [comment]
Dear @probonopd  I know. I just asked is there any way ? 

Best

**Comment by probonopd** [comment]
https://github.com/AppImageCrafters/appimage-builder can do it.
