### ISSUE TITLE
libglib is missing from the AppImage

### ISSUE THREAD

**Issue by philippludwig** [probonopd/linuxdeployqt#468]
Since linuxdeployqt is released as an AppImage, I expected that it carries all required libraries to run; but, `libglib-2.0.so.0` is missing:

```
./linuxdeployqt-7-x86_64.AppImage /path/to/my/.desktop-file
/tmp/.mount_linuxdNJjlZJ/usr/bin/linuxdeployqt: error while loading shared libraries: libglib-2.0.so.0: cannot open shared object file: No such file or directory
```

So I think it would be nice if this library could be included in the AppImage.

**Comment by probonopd** [comment]
It is assumed to be part of the base system:

https://github.com/AppImage/pkg2appimage/blob/master/excludelist
