### ISSUE TITLE
How to add extra plugins in the build dir?

### ISSUE THREAD

**Issue by trmdi** [probonopd/linuxdeployqt#473]
Please see this file: https://download.opensuse.org/repositories/home:/trmdi:/test/AppImage/
(yml file: https://build.opensuse.org/package/view_file/home:trmdi:test/latte-dock/appimage.yml?expand=1)

I have 2 questions:

1, it seems that linuxdeployqt uses usr/lib and usr/plugins, while openSUSE uses usr/lib64 and usr/lib64/qt5/{plugins,qml}.
How to tell linuxdeploy to use the path like openSUSE?
2, as you see in the appimage file, there are still some files remain in the build dir at usr/lib64/qt5.
How to tell linuxdeployqt import those files?

**Comment by probonopd** [comment]
> How to tell linuxdeploy to use the path like openSUSE?

As far as I remember, this is not possible. AppImages made with linuxdeployqt use the "normalized" FHS-like structure with ?`usr/lib` and `usr/plugins`. 

> there are still some files remain in the build dir at `usr/lib64/qt5`

Probably the `make install` step of the build process of the application has put them there? Just move them to the locations which `linuxdeployqt` is using.

If you don't like this, then you may want to look into the newer `appimagetool deploy` in [go-appimage](https://github.com/probonopd/go-appimage/), which tries to use the filesystem structure of the host system.

Things like this have made me use FreeBSD as my daily driver. No more different distributions that all break things slightly differently to worry about.

**Comment by trmdi** [comment]
> Probably the make install step of the build process of the application has put them there? Just move them to the locations which linuxdeployqt is using.

Ok, I am trying it.

I still have a question, how about qml imports those installed in /usr/lib64/qt5/qml ? Can I just copy it to $AppDir/usr/qml?

**Comment by trmdi** [comment]
extra-plugins=a,b,c will copy files from the system /usr/lib64/qt5/plugins/{a,b,c} to $AppDir/usr/plugins right?
It is the same with copying files manually right?

**Comment by trmdi** [comment]
Excuse me, I created a custom AppRun file but why it is override ?
https://github.com/probonopd/linuxdeployqt/blob/d41e2345694e6d09820df66e5edb6e8c01db9fb9/tools/linuxdeployqt/main.cpp#L381

**Comment by trmdi** [comment]
Some plugins are still linked to the host's libs. For exmple:
```bash
/tmp/.mount_latte-WGN0AS                                                           
▶ ldd usr/plugins/plasma_containmentactions_lattecontextmenu.so 
        linux-vdso.so.1 (0x00007ffedcdd8000)
        libKF5Plasma.so.5 => /usr/lib64/libKF5Plasma.so.5 (0x00007f1cb261a000)
```
How can I solve this? Tried adding them to `-extra-plugins` but it doesn't work.

**Comment by trmdi** [comment]
Some plugins are still linked to the system's libraries. For example:
```bash
▶ ldd usr/plugins/plasma_containmentactions_lattecontextmenu.so | grep libQt5Quick
        libQt5Quick.so.5 => /usr/lib64/libQt5Quick.so.5 (0x00007f51d4717000)

/tmp/.mount_latte-WGN0AS                                                           
▶ find usr/lib -name libQt5Quick.so.5
usr/lib/libQt5Quick.so.5
```
How can I solve this?

**Comment by trmdi** [comment]
If the system qml dir is at `/usr/lib64/qt5/qml` and the app qml dir is at `$BUILD_APPDIR/usr/qml` then:
- what is `-qmlimport=`?
- what is `-qmldir=`?

**Comment by trmdi** [comment]
> How can I solve this?

linuxdeployqt does not deploy plugins inside $BUILD_APPDIR/usr/plugins?

**Comment by trmdi** [comment]
@probonopd 
Why does my appimage still load some libraries from the system? For example this:
```bash
[Debug : 11:27:08.236236] - "QQmlImports()::addLibraryImport: \"QtQuick\" 2.1 as \"\
""
[Debug : 11:27:08.236236] - "QQmlImports()::importExtension: loaded \"/usr/lib64/qt5
/qml/QtQuick.2/qmldir\""
[Warning : 11:27:08.237237] - "Found metadata in lib /usr/lib64/qt5/qml/QtQuick.2/libqtquick2plugin.so, metadata=\n{\n    \"IID\": \"org.qt-project.Qt.QQmlExtensionInterface/1.0\",\n    \"archreq\": 0,\n    \"className\": \"QtQuick2Plugin\",\n    \"debug\": false,\n    \"uri\": [\n        \"QtQuick.2\"\n    ],\n    \"version\": 331520\n}\n\n"
     26618:     
     26618:     file=/usr/lib64/qt5/qml/QtQuick.2/libqtquick2plugin.so [0];  dynamically loaded by /tmp/.mount_latte-V562iU/usr/lib/libQt5Core.so.5 [0]
```

**Comment by aziham** [comment]
@trmdi Hi! I saw that you were trying to build Latte-Dock as an AppImage.
I'm interested in doing the same thing and was wondering if you were able to get it working.
Have you had any success with this? If so, could you please share the steps you took to create the AppImage?
Thank you!

**Comment by probonopd** [comment]
Probably it would be best to ask the author of Latte-Dock to provide an officially supported AppImage.

**Comment by trmdi** [comment]
> Probably it would be best to ask the author of Latte-Dock to provide an officially supported AppImage.

He's dropped it so some people want to make the appimage in order to isolate it with the system library, I guess.

**Comment by trmdi** [comment]
> 

I tried that but didn't succeed. :(

**Comment by aziham** [comment]
> Probably it would be best to ask the author of Latte-Dock to provide an officially supported AppImage.

@probonopd

As @trmdi have mentioned, psifidotos (the creator of Latte-Dock) is no longer maintaining the software. It might not be possible to ask the author to provide an officially supported AppImage under these circumstances.

**Comment by aziham** [comment]
> @aziham I tried that but didn't succeed. :(

I was hoping that you could package Latte-dock as an AppImage. I tried doing it myself but was unsuccessful ☹️

My idea was to package Latte-dock along with necessary applets such as window title, global menu, virtual-desktop-bar, etc. I planned to use this package as a standalone program in my next minimal setup, which comprises only of a tiling window manager without a desktop environment.

The reason behind moving away from KDE Plasma is that dotfiles are scattered all over the place, which makes it difficult to keep track of all configurations even with dotfile managers like Chezmoi. Additionally, some KDE programs mix config and state in the same file, which adds to the complexity.

To create a custom setup with a similar Plasma workflow, the only missing piece for me is Latte-dock. Unfortunately, I haven't been able to find a bar that includes both a global menu and virtual desktops applet.
