### ISSUE TITLE
Files are exist but can not load

### ISSUE THREAD

**Issue by sonichy** [probonopd/linuxdeployqt#475]
Net video player based on Qt: https://github.com/sonichy/KuGou

AppRun.sh
```
export LD_LIBRARY_PATH=./lib
export GST_PLUGIN_SCANNER=./lib/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner
export GST_PLUGIN_PATH=./lib/gstreamer-1.0
export GST_PLUGIN_SYSTEM_PATH=
./App
```

```
Failed to load plugin './lib/gstreamer-1.0/libgstjpeg.so': libjpeg.so.8: cannot open shared object file: No such file or directory
                                                                                                                                                                                               
Failed to load plugin './lib/gstreamer-1.0/libgstlibav.so': libavfilter-ffmpeg.so.5: cannot open shared object file: No such file or directory
                                                                                                                                                                                               
Failed to load plugin './lib/gstreamer-1.0/libgstvpx.so': libvpx.so.3: cannot open shared object file: No such file or directory
```
libjpeg.so.8, libavfilter-ffmpeg.so.5, libvpx.so.3 are already in ./lib.

**Comment by probonopd** [comment]
`./` points to the current working directory, you want to point to the AppDir instead.

See https://github.com/probonopd/linuxdeployqt/wiki/Custom-wrapper-script-instead-of-AppRun#example-wrapper-in-bash.

**Comment by sonichy** [comment]
1.Load ubuntu16 iso, `sudo apt install gstreamer1.0-libav`, copy all the newly installed *.so in /usr/lib/x86_64-linux-gnu/ to appDir/lib, AppRun.sh can play video and audio on ubuntu16, but still can not play video and audio on Deepin20, elementaryOS, KDE neon (Your GStreamer installation is missing a plug-in).

2.`appimagetool appDir ` genarator appDir-x86_64.appimage run error:
`execv error: Exec format error`

**Comment by probonopd** [comment]
Does it also work with `#!/bin/sh`? (We should try to avoid BASHisms.)

**Comment by sonichy** [comment]
After test `#!/bin/sh` is OK !
And as you say `./` or `pwd`can not run in *.AppImage format, it transmit the *.AppImage directory, not /tmp/.mount* directory !

**Comment by probonopd** [comment]
`HERE="$(dirname "$(readlink -f "${0}")")"` is the key...

**Comment by sonichy** [comment]
Why GStreamer can not find video(audio) plug-in except ubuntu16 ?

**Comment by probonopd** [comment]
Probably becase GStreamer is not loading its resorces (like plugins) from a path inside the AppImage.
