### ISSUE TITLE
icon do not show

### ISSUE THREAD

**Issue by natxopedreira** [probonopd/linuxdeployqt#476]
i have a desktop file

```
[Desktop Entry]
Name=myApp
Exec=myApp
Icon=myApp
Type=Application
Categories=Utility;

and in the same level a png called myApp.png
```
Apps build and runs but app icon is not my png, can you please help me to make app use my icon

Thanks

**Comment by probonopd** [comment]
The 256x256 pixel icon file needs to be in `<AppDir>/myApp.png` and in `<AppDir>/usr/share/icons/hicolor/256x256/apps/myApp.png`.

**Comment by natxopedreira** [comment]
thank you, yes i also tried that and make a `<AppDir>/usr/share/icons/hicolor/256x256/apps/myApp.png` but i get the default gray icon

**Comment by natxopedreira** [comment]
ups, dumb mistake i wanted to post this over appimage repo... i dont use linuxdeployqt.... sorry!!
