### ISSUE TITLE
packaging with multiarch libraries

### ISSUE THREAD

**Issue by ljj7975** [probonopd/linuxdeployqt#479]
First of all, thank you for the great tool!

I am using ubuntu 18 to package my application and users are expected to use ubuntu 18 as well.
when I package my qt application with `-unsupported-allow-new-glibc -always-overwrite -appimage`

I have found that some of the files under `/usr/local/x86_64-linux-gnu`
```
/usr/lib/x86_64-linux-gnu/libGL.so.1
/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
/usr/lib/x86_64-linux-gnu/libX11.so.6
/usr/lib/x86_64-linux-gnu/libGLX.so.0
/usr/lib/x86_64-linux-gnu/libfreetype.so.6
/usr/lib/x86_64-linux-gnu/libSM.so.6
/usr/lib/x86_64-linux-gnu/libICE.so.6
/usr/lib/x86_64-linux-gnu/libGLdispatch.so.0
/usr/lib/x86_64-linux-gnu/libfontconfig.so.1
```
are `not found` when I test the executable on fresh ubuntu (docker) machine.

1. is there any particular reason these are not packaged together?
2. Is it possible to generate a package with these locally stored under lib? (or any other way)?

Ideally, users shouldn't need to install these dependencies manually

Thank you!

**Comment by probonopd** [comment]
`-unsupported-allow-new-glibc `

"unsupported"
