### ISSUE TITLE
Stripping not working

### ISSUE THREAD

**Issue by fathomssen** [probonopd/linuxdeployqt#48]
Hi

For RedTimer (https://github.com/fathomssen/redtimer), I create an AppImage, deb and rpm for Linux. The latter ones, I create using `fpm` according to the instructions in issue #9.

Now, `lintian` tells me that the binaries in the deb file have not been stripped:

```
$ lintian redtimer-v1.2-pre20-linux-x86_64.deb
E: redtimer: unstripped-binary-or-object opt/redtimer/redtimer
E: redtimer: unstripped-binary-or-object opt/redtimer/redtimercli
...
```

I used the following steps to generate the deb file (note that I DID NOT use `-no-strip`):

```
mkdir dist/opt/redtimer

cp gui/redtimer dist/opt/redtimer
cp cli/redtimercli dist/opt/redtimer

linuxdeployqt.AppImage dist/opt/redtimer/redtimer -qmldir=gui/qml
linuxdeployqt.AppImage dist/opt/redtimer/redtimercli -qmldir=gui/qml

fpm -s dir -t deb -m "..." --description "..." -n redtimer -v 1.2-pre20 -C dist -p redtimer-v1.2-pre20-linux-x86_64.deb
```

Best regards
Frederick Thomssen

**Comment by probonopd** [comment]
Thanks for the report @fathomssen - do you see any mention of `strip` when you run appimagetool with `-verbose=3`?

**Comment by fathomssen** [comment]
Hi

In the attached file [deploy.txt](https://github.com/probonopd/linuxdeployqt/files/612853/deploy.txt), you can find the two `linuxdeployqt` runs for `redtimer` and `redtimercli`. Both have stripping calls:

```
Log: Using strip:
Log:  stripping "/home/thomssen/redtimer.test/dist/opt/redtimer/redtimer"
...
Log: Using strip:
Log:  stripping "/home/thomssen/redtimer.test/dist/opt/redtimer/redtimercli"
```

Best regards
Frederick Thomssen

**Comment by fathomssen** [comment]
Btw: After a manual `strip redtimer`, `lintian` does not complain anymore. Maybe you don't strip enough to satisfy `lintian`?

**Comment by probonopd** [comment]
According to [this](https://github.com/probonopd/linuxdeployqt/blob/9a1fbab4453e13183160db4ca3afadd5553a3714/shared/shared.cpp#L624) like, `strip -x` is run on redtimer and redtimercli; maybe the `-x`hurts?

**Comment by fathomssen** [comment]
Maybe :)

**Comment by probonopd** [comment]
Please retest. Thanks
