### ISSUE TITLE
Cannot build appimage -- Desktop file not found, aborting

### ISSUE THREAD

**Issue by James-Hudson3010** [probonopd/linuxdeployqt#482]
I have a sample project at [https://github.com/jh3010-qt-questions/large\_qrc](https://github.com/jh3010-qt-questions/large_qrc) which I am working with.

I have setup my directory structure according to the instructions:

```
$ tree usr/
usr/
├── bin
│   └── large_qrc
├── lib
└── share
    ├── applications
    │   └── large_qrc.desktop
    └── icons
        └── hicolor
            └── 256z256
                └── apps
                    └── large_qrc.png
```

My desktop files looks like:

```
$ cat usr/share/applications/large_qrc.desktop
[Desktop Entry]
Type=Application
Name=Large QRC
Comment=The best Qt Application Ever
Exec=large_qrc
Icon=large_qrc
Categories=Office;⏎
```

I then call linuxdeployqt:

```
$ linuxdeployqt usr/bin/large_qrc -appimage -qmake=/home/jamesh/Qt5.12.10/5.12.10/gcc_64/bin/qmake -qmldir=/home/jamesh/depot_qt/questions/large_qrc

linuxdeployqt 4 (commit 8b3ded6), build 571 built on 2018-10-07 20:58:12 UTC
FHS-like mode with PREFIX, fhsPrefix: "/home/jamesh/depot_qt/questions/appimage/usr"
app-binary: "/home/jamesh/depot_qt/questions/appimage/usr/bin/large_qrc"
appDirPath: "/home/jamesh/depot_qt/questions/appimage"
relativeBinPath: "usr/bin/large_qrc"
appimagetool, continuous build (commit d185526), build 1855 built on 2018-10-07 20:18:45 UTC
Desktop file not found, aborting
```

What am I doing wrong?

If it matters, I am using Ubuntu 20.04.

**Comment by probonopd** [comment]
Try `linuxdeployqt usr/share/applications/large_qrc.desktop -appimage -qmake=/home/jamesh/Qt5.12.10/5.12.10/gcc_64/bin/qmake -qmldir=/home/jamesh/depot_qt/questions/large_qrc`

**Comment by James-Hudson3010** [comment]
that works. I did not realize that the tool, in this case, needed to point to the .desktop

**Comment by probonopd** [comment]
Looks correct.
But why `-no-copy-copyright-files`?

**Comment by keshavbhatt** [comment]
I don't know, since the option was there. Thought it will reduce size of AppImage.

**Comment by probonopd** [comment]
They are tiny text files and depending on what you are packaging they may be necessary for legal reasons.

**Comment by keshavbhatt** [comment]
Who unpacks an AppImage to see if one has shipped copyright images unless they are trying to sue someone. Kidding, I will remove that argument.
