### ISSUE TITLE
how can I control the name of the generated appimage?

### ISSUE THREAD

**Issue by James-Hudson3010** [probonopd/linuxdeployqt#483]
When I use the tool, I get a appimage with the name:

<prefix_is_Name_key_in_.desktop_file>-x84_64.AppImage.

I would like to be able to exercise more control over the name of the AppImage and not have -x84_64 appended. Is this possible? If so, how?

I can, of course, rename the file, but was hoping to avoid that step and just have it created with the name I want.

**Comment by probonopd** [comment]
Please do not rename the file if possible; this ensures that the AppImage is correctly recgnized by desktop integration tools.
Of course you can rename it for your own use, but if you plan to distribute the AppImage then best keep the name as is.
Why don't you like it? The `x84_64` is very important information to keep your AppImage apart from e.g., `aarch64` ones.
