### ISSUE TITLE
qmlimportscanner not found

### ISSUE THREAD

**Issue by James-Hudson3010** [probonopd/linuxdeployqt#484]
The project I am working with is a simple one located at https://github.com/jh3010-qt-questions/HelloWorld

I setup the structure according to the documentation which is:

```
usr
├── bin
│   └── HelloWorld
├── lib
└── share
    ├── applications
    │   └── HelloWorld.desktop
    └── icons
        └── hicolor
            └── 256x256
                └── apps
                    └── HelloWorld.png
```

I then call linuxdeployqt with

```
/home/jamesh/local/bin/linuxdeployqt ./usr/share/applications/HelloWorld.desktop -appimage -qmake=/opt/my-host/bin/qmake -qmldir=/home/jamesh/HelloWorld/HelloWorld -extra-plugins=egldeviceintegrations,platforminputcontexts,imageformats,platforms
```

I get the following error output:

```
linuxdeployqt 4 (commit 8b3ded6), build 571 built on 2018-10-07 20:58:12 UTC
Desktop file as first argument: "./usr/share/applications/HelloWorld.desktop"
desktopExecEntry: "HelloWorld"
desktopIconEntry: "HelloWorld"
Found binary from desktop file: "/home/jamesh/HelloWorld/other_appimage/usr/bin/HelloWorld"
FHS-like mode with PREFIX, fhsPrefix: "/home/jamesh/HelloWorld/other_appimage/usr"
app-binary: "/home/jamesh/HelloWorld/other_appimage/usr/bin/HelloWorld"
appDirPath: "/home/jamesh/HelloWorld/other_appimage"
relativeBinPath: "usr/bin/HelloWorld"
Found icons from desktop file: ("/home/jamesh/HelloWorld/other_appimage/usr/share/icons/hicolor/256x256/apps/HelloWorld.png", "/home/jamesh/HelloWorld/other_appimage/HelloWorld.png")
preExistingToplevelIcon: "/home/jamesh/HelloWorld/other_appimage/HelloWorld.png"
ERROR: qmlimportscanner not found at "/tmp/.mount_linuxdujO1Wf/usr/bin/qmlimportscanner"
ERROR: Please install it if you want to bundle QML based applications.
ERROR: findDependencyInfo: "ldd: /opt/my-target/plugins/platforms/libqxcb.so: No such file or directory\n"
ERROR: getBinaryRPaths: "objdump: '/opt/my-target/plugins/platforms/libqxcb.so': No such file\n"
ERROR: file copy failed from "/opt/my-target/plugins/platforms/libqxcb.so"
ERROR:  to "/home/jamesh/HelloWorld/other_appimage/usr/bin/..//plugins/platforms/libqxcb.so"
ERROR: lconvert not found at "/tmp/.mount_linuxdujO1Wf/usr/bin/lconvert"
ERROR: Failed to copy translations
```

I can confirm I have both tools in the expected location:

```
~ $ cd /opt
/opt $ find . -iname 'qmlimportscanner'
./my-host/bin/qmlimportscanner
./my-desktop/bin/qmlimportscanner
/opt $ find . -iname 'lconvert'
./my-host/bin/lconvert
./my-desktop/bin/lconvert
```

What is the solution so linuxdeployqt can locate these tools?

**Comment by probonopd** [comment]
How did ./my-host/bin/qmlimportscanner end up in that location? Seems like you are not using the Qt from the beineri ppa as we are recommending in the documentation. Possibly you need to use` -qmake=<path>            : The qmake executable to use.`

**Comment by James-Hudson3010** [comment]
My goal is to have linuxdeployqt create an AppImage that can be launched by a systemd service on an embedded device.

Both my host and embedded device are running Ubuntu 18.04.

First, I build the Qt Libraries myself with:

`./configure -opensource -confirm-license -verbose -pkg-config -no-use-gold-linker -device linux-nuc-g++ -device-option CROSS_COMPILE=/usr/bin/ -kms -gbm -sysroot / -system-freetype -fontconfig -skip webengine -verbose -recheck-all -make libs -prefix /usr/ -extprefix /opt/myapp-target -hostprefix /opt/myapp-host -qt-zlib -qt-libjpeg -qt-libpng -no-feature-bearermanagement -no-xcb -no-xcb-xlib -no-xkbcommon -no-xcb-xinput -no-linuxfb`

When I run linuxdeployqt with -verbose=3, I get the following in the log output:

```
Log: Application QML file path(s) is ("/home/jamesh/HelloWorld/HelloWorld")
Log: QML module search path(s) is ()
Log: Looking for qmlimportscanner at "/opt/myapp-target/bin/qmlimportscanner"
```

So, it seems like linuxdeployqt knows it should be looking for qmlimportscanner in the XXXX-target directory.  

However, building the Qt Libraries for my situation does not place a qmlimportscanner in the XXXX-target directory. It only places the tool in the XXXX-host directory.

In trying to understand this situation, I started a reddit thread at https://www.reddit.com/r/QtFramework/comments/mx17o7/identifiertargetbin_directory_does_not_contain/ , but have received no reply yet.

Because both my host and target are running Ubuntu 18.04, I am assuming that I can just simlink to them, but I know sometimes paths can be hardcoded, etc.

Or is there a better solution? Perhaps there is an additional flag I could pass to configure to have it compile the additional tools? Perhaps linuxdeployqt should be looking in the XXXX-host directory?

**Comment by probonopd** [comment]
Would it be possible to use Qt from https://launchpad.net/~beineri? These are the ones we test with. If it works with those but not with your self-compiled Qt, then we'd at least have a starting point for further debugging...
