### ISSUE TITLE
No longer able to build image on CentOS 7 (libStdC++ ABIs missing)

### ISSUE THREAD

**Issue by zakalawe** [probonopd/linuxdeployqt#489]
Running on:
 CentOS Linux release 7.9.2009 (Core)

The AppImage build is now failing due to missing libstdc++ ABI versions:

```
/tmp/.mount_linuxdanxbP3/usr/bin/linuxdeployqt: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/.mount_linuxdanxbP3/usr/bin/linuxdeployqt)
/tmp/.mount_linuxdanxbP3/usr/bin/linuxdeployqt: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/.mount_linuxdanxbP3/usr/bin/linuxdeployqt)
/tmp/.mount_linuxdanxbP3/usr/bin/linuxdeployqt: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/.mount_linuxdanxbP3/usr/bin/../lib/libQt5Core.so.5)
/tmp/.mount_linuxdanxbP3/usr/bin/linuxdeployqt: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /tmp/.mount_linuxdanxbP3/usr/bin/../lib/libQt5Core.so.5)
/tmp/.mount_linuxdanxbP3/usr/bin/linuxdeployqt: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /tmp/.mount_linuxdanxbP3/usr/bin/../lib/libicui18n.so.55)
/tmp/.mount_linuxdanxbP3/usr/bin/linuxdeployqt: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /tmp/.mount_linuxdanxbP3/usr/bin/../lib/libicuuc.so.55)
```

Is this expected, because linuxdeployqt was updated to require a newer libStdC++? Or is it a configuration error on my side? Up until this problem started last week, everything has been working perfectly building on CentOS 7 and deploying on many newer systems.

For reference, the (automated) build system on CentOS retrieves linuxdeployqt from: `https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage`

**Comment by zakalawe** [comment]
The available ABIs on Centos 7 are:
```
 strings /lib64/libstdc++.so.6 | grep CXXABI
CXXABI_1.3
CXXABI_1.3.1
CXXABI_1.3.2
CXXABI_1.3.3
CXXABI_1.3.4
CXXABI_1.3.5
CXXABI_1.3.6
CXXABI_1.3.7
CXXABI_TM_1
```

**Comment by zakalawe** [comment]
We switched to using a particular release (release 7) of the image and this has gone away.

**Comment by travisrecupero** [comment]
@zakalawe What do you mean by,

> We switched to using a particular release (release 7) of the image and this has gone away.

Thanks

**Comment by probonopd** [comment]
CentOS has pretty much been crippled by Red Hat by now; AlmaLinux and RockyLinux are at 9.x these days.
