### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by Surajj4837-th** [probonopd/linuxdeployqt#490]
I m using Ubuntu 20.04 with Qt5.13.2.
I created an appimage for my application, it ran perfectly on my system. Then I tested it on another system with Ubuntu 20.04 and it gave the following error:

`Illegal instruction (core dumped)`

My system has i5-8400H processor and the test system has  i7-6820HQ processor. Both of them support AVX instruction. How to debug this issue?

**Comment by probonopd** [comment]
You created the AppImage on a system running Ubuntu 20.04? Please post the exact command you used to create the AppImage. Thanks.

**Comment by Surajj4837-th** [comment]
`./linuxdeployqt-5-x86_64.AppImage Suraj/share/applications/LiDAR_SiLS.desktop -appimage`

**Comment by probonopd** [comment]
Ubuntu 20.04 (focal) has glibc 2.31.

As per https://github.com/probonopd/linuxdeployqt/commit/a3648aed4ad98bf91d087135a92d08806e52e291 `linuxdeployqt` should refuse to run with glibc 2.28 and higher.

Are you sure you did not use any `--unsupported-...` arguments?

**Comment by Surajj4837-th** [comment]
At first I used following command:
`./linuxdeployqt-5-x86_64.AppImage Suraj/bin/LiDAR_SiLS`
This generated an `AppRun` application, I tested it, worked fine and then I ran the following command:
`./linuxdeployqt-5-x86_64.AppImage Suraj/share/applications/LiDAR_SiLS.desktop -appimage`
This generated the `LiDAR_SiLS-x86_64.AppImage`, I tested it as well. It worked fine on my machine.

**Comment by probonopd** [comment]
Version 5 is way outdated. Please use version 7 or continuous.

**Comment by Surajj4837-th** [comment]
I used the suggested versions and as you mentioned earlier they are not supporting Ubuntu 20.04. Following error is thrown:

```
suraj@suraj:~/LinuxDeploy_ver7$ ./linuxdeployqt-7-x86_64.AppImage Suraj/bin/LiDAR_SiLS 
linuxdeployqt 6 (commit d41e234), build 724 built on 2020-07-31 15:51:47 UTC
ERROR: The host system is too new.
Please run on a system with a glibc version no newer than what comes with the oldest
currently still-supported mainstream distribution (xenial), which is glibc 2.23.
This is so that the resulting bundle will work on most still-supported Linux distributions.
For more information, please see
https://github.com/probonopd/linuxdeployqt/issues/340
suraj@suraj:~/LinuxDeploy_ver7$ ./linuxdeployqt-continuous-x86_64.AppImage Suraj/bin/LiDAR_SiLS 
linuxdeployqt 7 (commit b469748), build 734 built on 2021-06-13 13:17:57 UTC
ERROR: The host system is too new.
Please run on a system with a glibc version no newer than what comes with the oldest
currently still-supported mainstream distribution (Ubuntu Bionic), which is glibc 2.27.
This is so that the resulting bundle will work on most still-supported Linux distributions.
For more information, please see
https://github.com/probonopd/linuxdeployqt/issues/340

```

I also saw the related [issue#340](https://github.com/probonopd/linuxdeployqt/issues/340).  Is [this](https://github.com/probonopd/linuxdeployqt/issues/340#issuecomment-451956915) the solution to the problem else I dont see any relevant comment on the page?

**Comment by probonopd** [comment]
Now it is working as designed.

Your host system is _indeed_ too new.

Please _indeed_ run on a system with a glibc version no newer than what comes with the oldest
currently still-supported mainstream distribution (Ubuntu Bionic), which is glibc 2.27.
This is so that the resulting bundle will work on most still-supported Linux distributions.
For more information, please see
https://github.com/probonopd/linuxdeployqt/issues/340
