### ISSUE TITLE
Please tell me an example

### ISSUE THREAD

**Issue by Six-6Chen** [probonopd/linuxdeployqt#499]
Specify the input program and output directory and qmake path
Please give me an example of how to enter instructions

**Comment by probonopd** [comment]
```
export VERSION=... # linuxdeployqt uses this for naming the file
  - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage -qmake=/opt/Qt5.55/bin/qmake
```

**Comment by probonopd** [comment]
I will try my best, just let me know what you need.

Be aware that nowadays there are alternatives to `linuxdeployqt`: https://github.com/probonopd/go-appimage/tree/master/src/appimagetool is the newer code base.
Also, https://github.com/AppImageCrafters/appimage-builder may be of interest.

**Comment by Six-6Chen** [comment]
> 我会尽力而为，让我知道你需要什么。
> 
> 请注意，现在有替代方案`linuxdeployqt`：[https](https://github.com/probonopd/go-appimage/tree/master/src/appimagetool) : [//github.com/probonopd/go-appimage/tree/master/src/appimagetool](https://github.com/probonopd/go-appimage/tree/master/src/appimagetool)是较新的代码库。
> 此外，https://github.com/AppImageCrafters/appimage-builder可能会感兴趣。

I hope a script file like appimage-builder.yml can be used to control linuxdeployqt production

**Comment by probonopd** [comment]
有关示例，请参见 https://github.com/AppImageCrafters/appimage-builder/tree/master/examples
