### ISSUE TITLE
Dependencies of plugins do not get bundled

### ISSUE THREAD

**Issue by probonopd** [probonopd/linuxdeployqt#5]
And then it falls back to seaching the one from the system, which can lead to unexpected results, e.g.,
```
/home/me/build-untitled3-Desktop_Qt_5_7_0_GCC_64bit-Debug/plugins/platforms/libqxcb.so: /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5: version `Qt_5_PRIVATE_API' not found (required by /home/me/build-untitled3-Desktop_Qt_5_7_0_GCC_64bit-Debug/plugins/platforms/libqxcb.so)
```

When manually copying this in, then I can launch the app on another system...

**Comment by ddurham2** [comment]
What I see windeployqt doing is mapping each module to a **family** of plugins to pull in.. e.g. Qt5Gui pulls in all plugins from imageformats/, iconengines, accessible/, platforms/ and platforminputcontexts/.  (maybe with some filtering on only some platforms).  

Information like this should be common across variants of deploqt tools

**Comment by probonopd** [comment]
I like the macdeployqt approach better. Just becase I bundle Qt5Gui I don't necessarily want to bundle all platforms but the one I am deploying for. But it's really guesswork for me on what plugins are needed when; hence I strictly followed what linuxdeployqt does. Some official documentation or advice from someone in the Qt project is needed here.

**Comment by probonopd** [comment]
@msorvig in #qt-labs:

><msorvig> Yes, plugin selection currently needs to be implemented by the deployqt tool
<msorvig> we’ve discussed some ways to streamline it:
<msorvig> QTBUG-52798
<qt_gerrit> msorvig: Unify the *deployqt tools into a host tool in qtbase - https://bugreports.qt.io/browse/QTBUG-52798 (Reported)
<msorvig> QTBUG-50456
<qt_gerrit> msorvig: Improve deployment: "make deploy" - https://bugreports.qt.io/browse/QTBUG-50456 (Reported)

**Comment by probonopd** [comment]
@msorvig in #qt-labs:

> we scan the plugin binary for dependencies during deployment

So this must have been broken in the conversion apparently, needs to be fixed.

**Comment by skinnysuricate** [comment]
> but for some reason ldd doesn't find libQt5XcbQpa.so.5 which is why it is not bundled...

Hi, @probonopd ! First of all, thanks for this useful project. I guess I've found the issue.
`shared.cpp, line 813`, inside `deployPlugins` func,
```
QList<LibraryInfo> libraries = getQtLibraries(destinationPath, appDirInfo.path, deploymentInfo.rpathsUsed);
```
here `destinationPath` is passed, so `ldd` is called for just copied plugin, not 'origin' one. Which results `libQt5XcbQpa.so.5 => not found` . You should pass `sourcePath`, it worked for me.

**Comment by probonopd** [comment]
Thanks @skinnysuricate. Please reopen if the problem persists.

**Comment by OndraZizka** [comment]
Hi, have this problem with Qt5. What's the solution? Just copying the library next to the binary nor libqxcb.so doesn't help. Google took me here so your answer will be praised by millions :)

**Comment by probonopd** [comment]
Hi @OndraZizka what is the app in question? Also please post the exact output you are seeing. Thanks.

**Comment by probonopd** [comment]
Whenever these two numbers don't match it indicates that we haven't properly deployed (set rpath and copied dependencies) all .so files, which is a `linuxdeployqt` problem.

```
me@host:~$ find usr/ -name '*.so*' -exec grep '$ORIGIN' {} \; | wc -l
58
me@host:~$ find usr/ -name '*.so*' | wc -l
69
```

**Comment by probonopd** [comment]
May be fixed in linuxdeployqt trunk with https://github.com/probonopd/linuxdeployqt/commit/b71bd4d587051c2e543b08a3951cb9d2ee36c0c3 and https://github.com/probonopd/linuxdeployqt/commit/bace185665b3738cfc875a04edfa16998a06997c. More testing is needed.
