### ISSUE TITLE
The README should recommand appimagetool instead of 

### ISSUE THREAD

**Issue by lrineau** [probonopd/linuxdeployqt#50]
The [current version of README](https://github.com/probonopd/linuxdeployqt/blob/799f70436222919645000f1ecb670fbcc1f152fb/README.md) says:
> Optional if you want to generate AppImages: Download AppImageAssistant and put it into your $PATH,

It seems it should actually say "appimagetool".

**Comment by probonopd** [comment]
Good catch. `AppImageAssistant` has been replaced by `appimagetool` recently.
