### ISSUE TITLE
OpenCV libs not bundled despite specifying -bundle-non-qt-libs

### ISSUE THREAD

**Issue by florianblume** [probonopd/linuxdeployqt#501]
I tried - and succeeded to some extent - to create an AppImage of my app including all but the very core libraries like so

    ./linuxdeployqt-5-x86_64.AppImage app/6DPAT -extra-plugins=sceneparsers -bundle-non-qt-libs

Unfortunately, it doesn't bundle the necessary OpenCV libraries. When unpacking the AppImage and looking at the output of `ldd` I can see that they are definitely referenced. They are also not part of the default excludes, as far as I can tell.

Some other libraries next to Qt's are bundled, so I'm assuming the `-bundle-non-qt-libs` did work somehow, just not for OpenCV.

Any ideas why this might be? Otherwise I'd be willing to debug the code myself some time.

**Comment by probonopd** [comment]
Are they not found by `ldd`? Are they in a non-standard location? Are they opened by `ldopen()`? Any of those might cause this.

**Comment by florianblume** [comment]
Hey thanks for the answer! When using the image on my computer the libraries are found since I have OpenCV installed. But trying out the program in a Ubuntu live image doesn't work since they are missing. `ldd` on the built binary - before packing with linuxdeployqt and also after unpacking the appimage - resolves all libraries on my computer.

Qt is responsible for including the libraries so I'm not sure about the `ldopen()` function, I'm at least not calling that manually.

Maybe it is related to that I include OpenCV through `PKCONFIG += opencv4` to be able to either use Ubuntu's default OpenCV version or one that the user installed manually.

**Comment by probonopd** [comment]
Under which path are the libraries in question on your local machine? I would almost bet that they are not in one of the locations `ldd` can resolve.

**Comment by florianblume** [comment]
This is the output of `ldd` on the binary produced by QtCreator:

```
libopencv_features2d.so.4.3 => /usr/local/lib/libopencv_features2d.so.4.3 (0x00007f9049bdf000)
libopencv_flann.so.4.3 => /usr/local/lib/libopencv_flann.so.4.3 (0x00007f9049b70000) 
libopencv_imgproc.so.4.3 => /usr/local/lib/libopencv_imgproc.so.4.3 (0x00007f9047ff2000)
```

But I also used `ldd` on the binary extracted from the packed AppImage and this is the output:

```
libopencv_features2d.so.4.2 => /lib/x86_64-linux-gnu/libopencv_features2d.so.4.2 (0x00007f30a2fdb000)
libopencv_flann.so.4.2 => /lib/x86_64-linux-gnu/libopencv_flann.so.4.2 (0x00007f30a2f7c000)
libopencv_imgproc.so.4.2 => /lib/x86_64-linux-gnu/libopencv_imgproc.so.4.2 (0x00007f30a29d5000)
```

I'm assuming `/lib` means the lib folder in the squash-fs filesystem. But the OpenCV libraries are not contained in this folder.
How can I tell that `ldd` is not properly resolving the libraries? I realized Python 3 libs are not bundled either. Could this be related to how I include them?

This is an excerpt of the `.pro` file:

```
INCLUDEPATH += /usr/include/python3.8 \
               /usr/include/pybind11
LIBS += -lpython3.8

unix: CONFIG += link_pkgconfig
unix: PKGCONFIG += opencv4
```

**Comment by florianblume** [comment]
I was using an old version of your tool apparently. Using a newer version fixed it. Thanks for the help though.
