### ISSUE TITLE
Qt6 with Ubuntu 20.04

### ISSUE THREAD

**Issue by conradhuebler** [probonopd/linuxdeployqt#504]
Hey,

is there a chance to make linuxdeployqt compatible with a newer Ubuntu version? Qt6 does not work with 18.04 and therefore using GitHub Actions and Qt6, AppImages cannot be created.

Thanks and cheers,
Conrad

**Comment by probonopd** [comment]
linuxdeployqt will support this use case once 18.04 is no longer a supported release of Ubuntu.

If you need to use Qt 6 before that, you need to use a tool that can bundle _everything_, such as [go-appimage `appimagetool -s deploy`](https://github.com/probonopd/go-appimage/tree/master/src/appimagetool#appimagetool) or https://github.com/AppImageCrafters/appimage-builder/.
