### ISSUE TITLE
-libpath seems to have no effect

### ISSUE THREAD

**Issue by my-tien** [probonopd/linuxdeployqt#51]
Since the path to my plugins folder is at `/usr/lib/qt/plugins` but linuxdeployqt searches in the non-existent `/usr/plugins` (this is a separate problem I guess), I tried to pass the correct path via the `-libpath` option which seems to have no effect. This is what I did exactly:

I created a new folder, copied over a fresh build of my binary and ran: 
```
linuxdeployqt-1-x86_64.AppImage [binary name] -appimage -verbose=2 -bundle-non-qt-libs -always-overwrite
```
After this I saw following output:
```
Log: Deploying plugins from "/usr/plugins"
ERROR: file copy failed from "/usr/plugins/platforms/libqxcb.so"
ERROR:  to "./plugins/platforms/libqxcb.so"
ERROR: file copy failed from "/usr/plugins/printsupport/libcupsprintersupport.so"
ERROR:  to "./plugins/printsupport/libcupsprintersupport.so"
```
I cleared the folder, copied the binary over again and ran the same command with higher verbosity and additional `-libpath` option:

```
linuxdeployqt-1-x86_64.AppImage [binary-name] -appimage -verbose=3 -bundle-non-qt-libs -always-overwrite -libpath=/usr/lib/qt/plugins
```

I received the same output (https://www.dropbox.com/s/6mtyhoo15pnuogn/linuxdeploylog.txt?dl=0) and my local plugins folder remained empty. I have heard about the issue of linuxdeployqt having to run twice sometimes, so I ran the same command again on the changed folder with no effect either.

My system is ArchLinux, kernel: 4.8.11-1.
`qmake -v` output:
```
QMake version 3.0
Using Qt version 5.7.0 in /usr/lib
```
`qmake -query`:
```
QT_SYSROOT:
QT_INSTALL_PREFIX:/usr
QT_INSTALL_ARCHDATA:/usr/lib/qt
QT_INSTALL_DATA:/usr/share/qt
QT_INSTALL_DOCS:/usr/share/doc/qt
QT_INSTALL_HEADERS:/usr/include/qt
QT_INSTALL_LIBS:/usr/lib
QT_INSTALL_LIBEXECS:/usr/lib/qt/libexec
QT_INSTALL_BINS:/usr/bin
QT_INSTALL_TESTS:/usr/tests
QT_INSTALL_PLUGINS:/usr/lib/qt/plugins
QT_INSTALL_IMPORTS:/usr/lib/qt/imports
QT_INSTALL_QML:/usr/lib/qt/qml
QT_INSTALL_TRANSLATIONS:/usr/share/qt/translations
QT_INSTALL_CONFIGURATION:/etc/xdg
QT_INSTALL_EXAMPLES:/usr/share/doc/qt/examples
QT_INSTALL_DEMOS:/usr/share/doc/qt/examples
QT_HOST_PREFIX:/usr
QT_HOST_DATA:/usr/lib/qt
QT_HOST_BINS:/usr/bin
QT_HOST_LIBS:/usr/lib
QMAKE_SPEC:linux-g++
QMAKE_XSPEC:linux-g++
QMAKE_VERSION:3.0
QT_VERSION:5.7.0
```

**Comment by probonopd** [comment]
Indeed we inherited `-libpath` from macdeployqt and I have not come around to really really working on it or testing it so far. Pull requests welcome!

**Comment by probonopd** [comment]
What happens if you export the (absolute) path with `export LD_LIBRARY_PATH=...` prior to running linuxdeployqt? (linuxdepoyqt internally uses ldd, so this should be all that is needed)

**Comment by probonopd** [comment]
`-libpath` should probably be removed altogether since it can't do anything `LD_LIBRARY_PATH` couldn't. Objections?
