### ISSUE TITLE
Move to GitHub Actions

### ISSUE THREAD

**Issue by probonopd** [probonopd/linuxdeployqt#512]
Since Travis CI is no longer working, this needs to be moved to GitHub Actions so that we can build again.

This blocks all builds and PRs.

**Comment by humble-barnacle001** [comment]
@probonopd could you mention the version of qt you used earlier for creating so that I can write up an action

**Comment by probonopd** [comment]
Closed in https://github.com/probonopd/linuxdeployqt/commit/adf1eb084055e68bd7f62a47273fed5291eda9f2. Thanks @RICCIARDI-Adrien
