### ISSUE TITLE
linuxdeployqt 7 (commit b469748), build 734 built on 2021-06-13 13:17:57 UTC FHS-like mode with PREFIX, fhsPrefix: "/../.."

### ISSUE THREAD

**Issue by parisa-hr** [probonopd/linuxdeployqt#513]
I get this error when I want to deploy my simple Qt application. why did this happen?
I use ubuntu 18.04 and I want to deploy the app there.

![Screenshot from 2021-11-13 21-00-06](https://user-images.githubusercontent.com/44742050/141653330-e84401b4-e353-4440-beac-8dec0f2d6e7a.png)

**I also try another old release and I get this error :**
what should I do? this is the first time that I want to create a release `appimage` for my application.

![Screenshot from 2021-11-13 21-14-14](https://user-images.githubusercontent.com/44742050/141653863-bf2b2a5c-f4e3-4710-87ee-5bcc159b2089.png)

**Comment by probonopd** [comment]
Please retry with https://github.com/probonopd/linuxdeployqt/releases/tag/continuous

**Comment by parisa-hr** [comment]
> Please retry with https://github.com/probonopd/linuxdeployqt/releases/tag/continuous

thank you so much. it works.

**Comment by abbos1711** [comment]
I have also the same error and I tried as you posted but it doesn't work

**Comment by probonopd** [comment]
Please post the output you are seeing @abbos1711. Thanks!

**Comment by karunarane** [comment]
i have also got the same error and tried the posted solution , but it is not working for me

linuxdeployqt  (commit 2b38449), build 62 built on 2023-12-27 21:00:01 UTC
FHS-like mode with PREFIX, fhsPrefix: "/../.."
QDir::exists: Empty or null file name
ERROR: Error: Could not find app-binary ""
