### ISSUE TITLE
No documentation for zsync

### ISSUE THREAD

**Issue by SevenBlocks** [probonopd/linuxdeployqt#514]
There is no documentation for how to host or use the .zsync file to update the appimage. 
If the option `-updateinformation="zsync|https://myurl"` mean that the .zsync file should be at `https://myurl` then where is the new appimage url information stored? Does updating with zsync require ssh?

**Comment by probonopd** [comment]
https://github.com/AppImage/AppImageSpec/blob/master/draft.md#update-information
