### ISSUE TITLE
How to set the output file name for AppImage ?

### ISSUE THREAD

**Issue by abcfy2** [probonopd/linuxdeployqt#528]
I want to change the output file name for both AppImage and zsync. How to?

I try to use `mv output-x86_64.AppImage target.AppImage && mv output-x86_64.zsync target.zsync`, but it cannot change the `Filename` entity in zsync.

And I don't want to add `x86_64` in filename, how to ?

Thanks.

**Comment by probonopd** [comment]
The filename gets generated based on the `Name=` key in the desktop file. Please do not try to change it. The `x86_64` is required.
