### ISSUE TITLE
How to add GPG signature for AppImage ?

### ISSUE THREAD

**Issue by abcfy2** [probonopd/linuxdeployqt#529]
appimagetool can use `--sign-key` to sign AppImage with GPG key. Is there any way to support this feature in linuxdeployqt ?

Thanks.

**Comment by probonopd** [comment]
Unfortunately this is not supported by linuxdeployqt yet. As a workaround, you could generate an AppImage using `linuxdeployqt`, then extract it and turn the extracted AppDir into an AppImage again using `appimagetool --sign-key`.
