### ISSUE TITLE
Very long time to do the deploy !

### ISSUE THREAD

**Issue by lraimondi** [probonopd/linuxdeployqt#533]
Hi, I love LinuxDeployQty, works great, but...it takes over 15 minutes to do teh deploy. 
The project is ....nothing special. How could I speedup the whole thing ?
The command I use is lie:
`linuxdeployqt-continuous-x86_64.AppImage 
/home/rd/Documents/_Qt/WI18Deploy/bin/RVN 
-qmake=/home/rd/Qt/5.15.2/gcc_64/bin/qmake 
-qmldir=/home/rd/Documents/_Qt/WI18/WI18_UI 
-verbose=2`

Any suggestion ?
Thanks

**Comment by probonopd** [comment]
Yes, linnuxdeployqt is not very efficient regarding the time it takes to deploy an application. https://github.com/probonopd/go-appimage `appimagetool deploy` is a rewrite that should be more efficient.
