### ISSUE TITLE
Latest continuous linuxdeployqt build does not work on Ubuntu 20.04

### ISSUE THREAD

**Issue by arthurl09** [probonopd/linuxdeployqt#536]
If I run ./linuxdeployqt-continuous-x86_64.AppImage --version on m Ubuntu 20.04 the following error is written.

linuxdeployqt  (commit aeafcd2), build 13 built on 2022-01-28 22:37:07 UTC
ERROR: The host system is too new.
Please run on a system with a glibc version no newer than what comes with the oldest
currently still-supported mainstream distribution (Ubuntu Bionic), which is glibc 2.27.
This is so that the resulting bundle will work on most still-supported Linux distributions.
For more information, please see
https://github.com/probonopd/linuxdeployqt/issues/340

**Comment by probonopd** [comment]
Works as designed.
