### ISSUE TITLE
Cannot run linuxdeployqt on Ubuntu 20.04

### ISSUE THREAD

**Issue by archibate** [probonopd/linuxdeployqt#548]
First of all, thank for this cool project! Without it, we couldn't ship a working Linux binary distribution at all.
However, the GitHub Actions (which is used by our project for continuous deployment) have now deprecated the Ubuntu 18.04 image officially (see https://github.com/actions/runner-images/issues/6002).
They suggest (force) us to use Ubuntu 20.04 or later now, and we didn't plan to support Ubuntu 18.04 anymore too. But whenever we try to run `linuxdeployqt` it simply complains about GLIBC version (introduced in commit b9b57e266e080aab0f81706199bd0eb30e63f165) and exit. I know that use the `AppImage` approach would fix this on Ubuntu 20.04, but that's not what we want.
So may I ask if we could bypass the GLIBC version check (e.g. `--ignore-glibc-error`), so that we can run `linuxdeployqt` on Ubuntu 20.04 for now? (Actually, we don't have a plan to support Ubuntu 18.04 users at the first place...)

**Comment by Master811129** [comment]
i didn't test it but there is `-unsupported-allow-new-glibc` and `-unsupported-bundle-everything`.

**Comment by archibate** [comment]
It seems that the program always exit with 1 when having any of those `-unsupported` flags? Shall I ignore it or this indicates a true error?

**Comment by archibate** [comment]
```
linuxdeployqt  (commit 5fa79fa), build 36 built on 2022-08-21 12:36:03 UTC
WARNING: Not checking glibc on the host system.
         The resulting AppDir or AppImage may not run on older systems.
         This mode is unsupported and discouraged.
         For more information, please see
         https://github.com/probonopd/linuxdeployqt/issues/340
Desktop file as first argument: "build/out/usr/share/applications/zeno.desktop"
desktopExecEntry: "zenoedit"
desktopIconEntry: "zeno"
Found binary from desktop file: "/home/runner/work/zeno/zeno/build/out/usr/bin/zenoedit"
FHS-like mode with PREFIX, fhsPrefix: "/home/runner/work/zeno/zeno/build/out/usr"
app-binary: "/home/runner/work/zeno/zeno/build/out/usr/bin/zenoedit"
appDirPath: "/home/runner/work/zeno/zeno/build/out"
relativeBinPath: "usr/bin/zenoedit"
Copied "build/out/usr/share/applications/zeno.desktop" to "/home/runner/work/zeno/zeno/build/out/zeno.desktop"
Found icons from desktop file: ("/home/runner/work/zeno/zeno/build/out/usr/share/icons/hicolor/256x256/zeno.png")
Traceback (most recent call last):
  File "/home/runner/work/zeno/zeno/misc/ci/package.py", line 56, in <module>
    subprocess.check_call([
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/subprocess.py", line [369](https://github.com/zenustech/zeno/runs/7977903256?check_suite_focus=true#step:9:370), in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['../linuxdeployqt', 'build/out/usr/share/applications/zeno.desktop', '-bundle-non-qt-libs', '-unsupported-bundle-everything']' returned non-zero exit status 1.
```

**Comment by probonopd** [comment]
This mode is unsupported and discouraged.
         For more information, please see
         https://github.com/probonopd/linuxdeployqt/issues/340
