### ISSUE TITLE
Libraries not being copied on RaspberryPi4 

### ISSUE THREAD

**Issue by awcbantam** [probonopd/linuxdeployqt#549]
I have the tool built, and it seems to run and creates an appdir, but no libraries are copied into *.AppDir/usr/lib. I don't have an appimage of linuxdeployqt because I built it from source, so I am running this command 
`~/linuxdeployqt/bin/linuxdeployqt build/myapp.AppDir/usr/share/applications/myapp.desktop -executable=./build/myapp.AppDir/usr/bin/myapp -qmldir=../qrc2/qml/ -bundle-non-qt-libs -qmake=/usr/lib/aarch64-linux-gnu/ -unsupported-allow-new-glibc`

This is the console output from my run 
`linuxdeployqt 8 (commit d6ac06c), build <local dev build> built on 2022-08-17 18:06:50 UTC
WARNING: Not checking glibc on the host system.
         The resulting AppDir or AppImage may not run on older systems.
         This mode is unsupported and discouraged.
         For more information, please see
         https://github.com/probonopd/linuxdeployqt/issues/340
Desktop file as first argument: "build/myapp.AppDir/usr/share/applications/myapp.desktop"
desktopExecEntry: "myapp"
desktopIconEntry: "myapp"
Found binary from desktop file: "/home/bantam/otherplan/bin/build/myapp.AppDir/usr/bin/myapp"
FHS-like mode with PREFIX, fhsPrefix: "/home/bantam/otherplan/bin/build/myapp.AppDir/usr"
app-binary: "/home/bantam/otherplan/bin/build/myapp.AppDir/usr/bin/myapp"
appDirPath: "/home/bantam/otherplan/bin/build/myapp.AppDir"
relativeBinPath: "usr/bin/myapp"
Copied "build/myapp.AppDir/usr/share/applications/myapp.desktop" to "/home/bantam/otherplan/bin/build/myapp.AppDir/myapp.desktop"
Found icons from desktop file: ("/home/bantam/otherplan/bin/build/myapp.AppDir/myapp.png", "/home/bantam/otherplan/bin/build/myapp.AppDir/usr/share/icons/hicolor/256x256/myapp.png")`

Any suggestions about what I may be doing incorrectly?

**Comment by awcbantam** [comment]
Got it running with linuxdeploy and linuxdeploy-plugin-qt.

**Comment by probonopd** [comment]
Do not use `-unsupported-...` flags. They are not supported. They are bad.
