### ISSUE TITLE
No dependent libraries are generated on ubuntu20.04

### ISSUE THREAD

**Issue by WorstCodeWay** [probonopd/linuxdeployqt#550]
Hi, there. Thanks very much for this project.

I meet problem when deploying application using `linuxdeployqt`, I can't get any dependent libraties of my application.
My directory architecture is:
```bash
ppDir$ tree
.
├── usr
│   ├── bin
│   │   └── VisTrack-DeskTop
│   ├── lib
│   └── share
│       ├── applications
│       │   └── VisTrack-DeskTop.desktop
│       └── icons
│           └── hicolor
│               └── 32x32
│                   └── apps
│                       └── logo.png

9 directories, 5 files
```
And my desktop file:
```bash
[Desktop Entry]
Type=Application
Name=VisTrack-Studio
Comment=The best Qt Application Ever
Exec=VisTrack-DeskTop
Icon=logo
Categories=Office;
```

In terminal, I input following command and result:
```bash
./linuxdeployqt-continuous-x86_64.AppImage AppDir/usr/share/applications/VisTrack-DeskTop.desktop -unsupported-bundle-everything -appimage
linuxdeployqt  (commit 5fa79fa), build 36 built on 2022-08-21 12:36:03 UTC
WARNING: Not checking glibc on the host system.
         The resulting AppDir or AppImage may not run on older systems.
         This mode is unsupported and discouraged.
         For more information, please see
         https://github.com/probonopd/linuxdeployqt/issues/340
Desktop file as first argument: "AppDir/usr/share/applications/VisTrack-DeskTop.desktop"
desktopExecEntry: "VisTrack-DeskTop"
desktopIconEntry: "logo"
Found binary from desktop file: "/home/jason/Documents/vist/VisTrack-DeskTop/build/bin/AppDir/usr/bin/VisTrack-DeskTop"
FHS-like mode with PREFIX, fhsPrefix: "/home/jason/Documents/vist/VisTrack-DeskTop/build/bin/AppDir/usr"
app-binary: "/home/jason/Documents/vist/VisTrack-DeskTop/build/bin/AppDir/usr/bin/VisTrack-DeskTop"
appDirPath: "/home/jason/Documents/vist/VisTrack-DeskTop/build/bin/AppDir"
relativeBinPath: "usr/bin/VisTrack-DeskTop"
Keeping existing AppRun
Found icons from desktop file: ("/home/jason/Documents/vist/VisTrack-DeskTop/build/bin/AppDir/usr/share/icons/hicolor/32x32/apps/logo.png")
```

As a result, I can get a AppRun which links to my application, and a EMPTY *lib* directory.

What's the wrong thing I have done?

**Comment by zouhongwei** [comment]
I come into the same problem, don;t know how to fix it ..

**Comment by WorstCodeWay** [comment]
> I come into the same problem, don;t know how to fix it ..

Yeap, really weird. What will you do next in order to make your stuff to continue? Any suggestions?

**Comment by probonopd** [comment]
Closing since you are using an `-unsupported-...` parameter. Do not use unsupported parameters. We are not supporting them. They are broken. Bad.

**Comment by zouhongwei** [comment]
> @zouhongwei
> 
> > I come into the same problem, don;t know how to fix it ..
> 
> Yeap, really weird. What will you do next in order to make your stuff to continue? Any suggestions?

just run linuxdeployqt with `-unsupported-allow-new-glibc` as below:
`
linuxdeployqt your-app -appimage  -unsupported-allow-new-glibc

`

**Comment by probonopd** [comment]
**DO NOT USE** unsupported parameters. We are not supporting them. They are broken. Bad.
