### ISSUE TITLE
[QUESTION] Correctly adding gstreamer libraries

### ISSUE THREAD

**Issue by nitanmarcel** [probonopd/linuxdeployqt#551]
linuxdeployqt doesn't correctly handle gstreamer libraries from what I've read, so I had to manually add the `gstreamer-1.0` folder to the AppDir and then create the AppImage with [AppImageKit](https://github.com/AppImage/AppImageKit).

But even after I did it doesn't seem to load correctly:

`(VPS_Player-x86_64.AppImage:138289): GStreamer-WARNING **: 02:37:18.779: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstplayback.so': /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstplayback.so: undefined symbol: gst_type_mark_as_plugin_api
`

# The way I'm adding the libraries is:

## I'm creating the AppDir structure

```
          mkdir -p AppDir/usr/bin/
          mkdir -p AppDir/usr/lib/
          mkdir -p AppDir/usr/share/applications/
          mkdir -p AppDir/usr/share/icons/hicolor/128x128/apps/
          mkdir -p AppDir/usr/share/icons/hicolor/16x16/apps/
          mkdir -p AppDir/usr/share/icons/hicolor/256x256/apps/
          mkdir -p AppDir/usr/share/icons/hicolor/32x32/apps/
          mkdir -p AppDir/usr/share/icons/hicolor/64x64/apps/
          mkdir -p AppDir/usr/share/icons/hicolor/scalable/apps/
```

## I'm copying the gstreamer libraries

```
cp -rf /usr/lib/x86_64-linux-gnu/gstreamer-1.0 AppDir/usr/lib/
```

## I'm running linuxdeployqt to pull all the libs required by my app
```
./linuxdeployqt-continuous-x86_64.AppImage AppDir/usr/share/applications/com.github.fcrollet.vpsplayer.desktop -qmake=/opt/qt515/bin/qmake -bundle-non-qt-libs -no-translations  -verbose=1
```

## I'm creating the AppImage
```
./appimagetool-x86_64.AppImage AppDir
```

**Comment by probonopd** [comment]
linuxdeployqt is not capable of deploying gstreamer correctly. Maybe there are other tools that can do it, like https://github.com/linuxdeploy with https://github.com/linuxdeploy/linuxdeploy-plugin-gstreamer.
