### ISSUE TITLE
-bundle-non-qt-libs doesn't bundle all deps

### ISSUE THREAD

**Issue by victor-corchez** [probonopd/linuxdeployqt#561]
```
ldd libQt6Core.so.6 
	linux-vdso.so.1 (0x00007fffcffb0000)
	libicui18n.so.56 (0x00007fb5fb600000)
	libicuuc.so.56 (0x00007fb5fb200000)
	libicudata.so.56 (0x00007fb5f9800000)
	libdl.so.2 => /usr/lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb5fbafb000)
	libglib-2.0.so.0 (0x00007fb5f96b8000)
	libz.so.1 => /usr/lib/x86_64-linux-gnu/libz.so.1 (0x00007fb5fbadd000)
	libpthread.so.0 => /usr/lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb5fbad8000)
	libgthread-2.0.so.0 (0x00007fb5fbad2000)
	librt.so.1 => /usr/lib/x86_64-linux-gnu/librt.so.1 (0x00007fb5fbacd000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fb5f948e000)
	libm.so.6 => /usr/lib/x86_64-linux-gnu/libm.so.6 (0x00007fb5f93a7000)
	libgcc_s.so.1 => /usr/lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb5fbaab000)
	libc.so.6 => /usr/lib/x86_64-linux-gnu/libc.so.6 (0x00007fb5f917f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb5fc180000)
	libpcre.so.3 (0x00007fb5f9108000)
```
After deploying my app with -bundle-non-qt-libs it seems not all dependencies are bundled and some of them are still referenced from the system. The above ldd command was run on the bundled libQt6Core

**Comment by probonopd** [comment]
Correct, `-bundle-non-qt-libs` bundles _some_ non-Qt libs, not _all_ of them. It cannot do that because it doesn't have the code to bundle, e.g., glibc and all of its components properly.

**Comment by victor-corchez** [comment]
maybe this info should be added to the usage help. I thought that it was just adding all the dependencies as listed from the build system.. don't really understand what is specific for glibc in this case. Is there a way to specify a single lib to be bundled (beside Qt ones) ?
