### ISSUE TITLE
Wayland's lib could make conflict in AppImage

### ISSUE THREAD

**Issue by yanhuacuo** [probonopd/linuxdeployqt#564]
in the latest Qt6.x ，there is a Wayland's lib which be named  `libqt-plugin-wayland-egl.so`

if this lib absent from AppImage Package, the APP cannot move on Wayland ，Although the APP can run normally.

```
Failed to load client buffer integration: "wayland-egl"
```

if put it into 「plugins/wayland-shell-integration」, the App cannot  run .

```
symbol lookup error: /lib/x86_64-linux-gnu/libEGL_mesa.so.0: undefined symbol: wl_proxy_marshal_flags
```
However, if you run the APP with administrator privileges at this time, the APP is in a working state.

In the process of troubleshooting this problem, I found that some people have the same problem.

[https://forums.libretro.com/t/unable-to-launch-appimage-as-regular-user-ubuntu-22-04/39112](https://forums.libretro.com/t/unable-to-launch-appimage-as-regular-user-ubuntu-22-04/39112)

This problem only occurs when you use one computer to package software and then put the software on another computer to run.When running on the computer where the software is packaged, everything is normal.

This is My App: https://drive.google.com/file/d/1OiZ1HkAoDoISrKaDoYdaqAfotLOPJuM0/view?usp=share_link

**Comment by probonopd** [comment]
linuxdeployqt does not support Wayland.

**Comment by yanhuacuo** [comment]
> Hello @yanhuacuo. The Wayland developers seem to think that everyone has time for Wayland. But I don't have time for Wayland. And [Wayland breaks many things](https://gist.github.com/probonopd/9feb7c20257af5dd915e3a9f2d1f2277) I need. Hence, linuxdeployqt does not support Wayland.

Thank you, I agree with you.

**Comment by Silentdoer** [comment]
mark

**Comment by jlaine** [comment]
If the official position of the project in 2023 is "wayland is not supported", it would probably be worth stating this explicitly in the README. Currently developers are using `linuxdeployqt` expecting wayland to be supported on par with other platform plugins: https://github.com/musescore/MuseScore/blob/dd83e3c3f8097568023aadbf3b6c279c42938ac2/build/ci/linux/tools/make_appimage.sh#L107

**Comment by yanhuacuo** [comment]
> If the official position of the project in 2023 is "wayland is not supported", it would probably be worth stating this explicitly in the README. Currently developers are using `linuxdeployqt` expecting wayland to be supported on par with other platform plugins: https://github.com/musescore/MuseScore/blob/dd83e3c3f8097568023aadbf3b6c279c42938ac2/build/ci/linux/tools/make_appimage.sh#L107

**It is very clear that this is purely a problem of Wayland itself. Maybe fifty years later, Wayland will make a normal API**

**Comment by probonopd** [comment]
> If the official position of the project in 2023 is "wayland is not supported",

If the official position of Wayland is that all apps need to be changed specifically to support it, then... good luck with Wayland.

**Comment by jlaine** [comment]
I am not trying to re-ignite a debate on Wayland's technical merit here. I just spent a fair amount of time chasing down a bug, and think a one-liner change to the README would probably avoid such issues in the future.

**Comment by probonopd** [comment]
Fair point; added to the README.md.
