### ISSUE TITLE
Deploy APP for target device(arm linux) on host machine (x86 linux)

### ISSUE THREAD

**Issue by zhengbin-tdcq** [probonopd/linuxdeployqt#569]
Hi all,
I'm working on deploying my app for  target device(arm linux) on host machine (x86 linux).
How should I use the linuxdeployqt？Any ideas？
Thanks！

**Comment by zhengbin-tdcq** [comment]
is there anyone can help me ? thanks all.

**Comment by probonopd** [comment]
The easiest way is to use an ARM machine to make AppImages for ARM. After all, you probably also need to compile what goes into the AppImage on an ARM machine?
