### ISSUE TITLE
linuxdeployqt and qtwebengine

### ISSUE THREAD

**Issue by Alexorleon** [probonopd/linuxdeployqt#57]
Hi.
I use linuxdeployqt-x86_64.AppImage from the Releases page to transfer the program to another computer without Qt.

But when I run the program, it is crashes.
After searching the information I added icudtl.dat in the "resources" folder. The program is successfully launched.

Now I have a some errors:
Failed to load qtwebengine_resources.pak, qtwebengine_resources_100p.pak and qtwebengine_resources_200p.pak.
Then I added these files in the "resources" directory.

And
Installed Qt WebEngine locales directory not found at location .../qtwebengine_locales. Trying application directory...
Qt WebEngine locales directory not found at location .../qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
[0116/112551:WARNING:resource_bundle.cc(291)] locale_file_path.empty() for locale
Then I added a "translation" into the root.

Now I have a some errors:
Qt WebEngine ICU data not found at /opt/Qt/Qt5.6.2/5.6/gcc_64. Trying fallback directory.
...
qml: render process terminated
qml: Render process exited with code -1 (crashed)

And WebEngineView page is empty.

Qt 5.6.2, Ubuntu 64bit.

**Comment by probonopd** [comment]
Hmmm. linuxdeployqt _should_ handle these things for you properly automatically, but clearly something is going wrong. I don't know why it is not working in your case, but here is the relevant code:
https://github.com/probonopd/linuxdeployqt/blob/4951fd133b43e475d1bd64f32b9c5e265253485b/shared/shared.cpp#L885-L915

**Comment by Alexorleon** [comment]
I also copied qtwebengine_resources.pak, qtwebengine_resources_100p.pak,  qtwebengine_resources_200p.pak and icudtl.dat in the directory "libexec". Now it works!

**Comment by probonopd** [comment]
I am not really sure what is the difference between libexec and resources, and what needs to go where. Can this differ for different Qt builds/instances, and is there a generic way to find out where it would need to go?

**Comment by lrineau** [comment]
You may want to read the documentation:
https://doc-snapshots.qt.io/qt5-5.7/qtwebengine-deploying.html

> Deploying Resources
> 
> Qt WebEngine requires the following resource files:
> 
>     qtwebengine_resources.pak contains the resources needed by Chromium.
>     qtwebengine_devtools_resources.pak contains tools for remote debugging.
>     qtwebengine_resources_100p.pak contains images suitable for low resolution displays.
>     qtwebengine_resources_200p.pak contains images suitable for high DPI displays.
>     icudtl.dat provides support for International Components for Unicode (ICU). It is the Chromium version of ICU, which is not needed if Qt WebEngine was configured to use the system ICU.
> 
> Resources are searched from the following locations:
> 
>   - On Linux and Windows: the resources directory in the directory specified by `QLibraryInfo::location(QLibraryInfo::DataPath)`
>   - On macOS: `.app/Content/Resources`

**Comment by probonopd** [comment]
Excellent, so we need to find the content of `QLibraryInfo::location(QLibraryInfo::DataPath)` of the Qt instance to be bundled and use that.

**Comment by probonopd** [comment]
Autodesk Eagle seems to be running into this issue as well:
http://forums.autodesk.com/t5/eagle-forum/linux-educational-installation-freeze/td-p/6815841

```
me@host:~$ '/home/me/Downloads/eagle-8.0.0/eagle' 
Installed Qt WebEngine locales directory not found at location /home/me/Downloads/eagle-8.0.0/translations/qtwebengine_locales. Trying application directory...
Qt WebEngine locales directory not found at location /home/me/Downloads/eagle-8.0.0/qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
[0129/011129:WARNING:resource_bundle.cc(291)] locale_file_path.empty() for locale 
Qt WebEngine ICU data not found at /home/eagle/Qt/5.6/gcc_64/resources. Trying parent directory...
Qt WebEngine ICU data not found at /home/eagle/Qt/5.6/gcc_64. Trying application directory...
Installed Qt WebEngine locales directory not found at location /home/eagle/Qt/5.6/gcc_64/translations/qtwebengine_locales. Trying application directory...
Qt WebEngine locales directory not found at location /home/me/Downloads/eagle-8.0.0/libexec/qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
Qt WebEngine resources not found at /home/eagle/Qt/5.6/gcc_64/resources. Trying parent directory...
Qt WebEngine resources not found at /home/eagle/Qt/5.6/gcc_64. Trying application directory...
[0129/011129:WARNING:resource_bundle.cc(291)] locale_file_path.empty() for locale 
Bus error
```

Just verified this on `ubuntu-16.04-desktop-amd64.iso`.

**Comment by probonopd** [comment]
@all, please see @atehxx proposed patch at https://github.com/probonopd/linuxdeployqt/issues/55. Can we make it use `QLibraryInfo::location(QLibraryInfo::DataPath)`?

**Comment by kanekotic** [comment]
@Alexorleon could you share the command line you finally used and also the extra steps you did for the webengine?
i have tried the same as you but i end up in a few errors that i am not able to solve 
```
[0130/143807:ERROR:iau_util.cc(178)] Invalid file descriptor to ICU data received. [0130/143807:FATAL:content_main_runner.cc(705)] Check failed: base::i18n::InitializeICU()
```
and this are my command lines
```
gulp.task('prepare-linux-qt',shell.task([
            'mkdir ./dist-desktop/libexec/',
            'mkdir ./dist-desktop/plugins/',
            'mkdir ./dist-desktop/plugins/resources/',
            'mkdir ./dist-desktop/lib/',
            'mkdir ./dist-desktop/resources/',
            'cp /opt/Qt/5.8/gcc_64/resources/* ./dist-desktop/libexec/',
            'cp /opt/Qt/5.8/gcc_64/resources/* ./dist-desktop/plugins/resources/',
            'cp /opt/Qt/5.8/gcc_64/resources/* ./dist-desktop/resources/',
            'cp /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0.4800.1 ./dist-desktop/lib/libgthread-2.0.so.0.4800.1',
            'ln -sf ./dist-desktop/lib/libgthread-2.0.so.0.4800.1 ./dist-desktop/lib/libgthread-2.0.so.0',
            'linuxdeployqt ./dist-desktop/stremio -qmldir=./shell -bundle-non-qt-libs'
        ]));
```

**Comment by atehxx** [comment]
@Alexorleon had those files missing because current version has a bug which result in those files not being copied to application. There is a pull request which fixes that.
@kanekotic Qt is picking some wrong icudtl.icu file. When you have it in ./resources then add qt.conf file in ./libexec with content:
`[Paths]
Prefix = ../` and then it should work.
My pull request fixes that also.

**Comment by Alexorleon** [comment]
**@kanekotic** I copy the program to a directory and perform it there.

`export PATH=/opt/Qt/Qt5.6.2/5.6/gcc_64/bin/:$PATH`

This should be done twice.
`/home/alexorleon/Deployment/linuxdeployqt-2-x86_64.AppImage /home/alexorleon/Deployment/test/untitled -qmldir='/home/alexorleon/QtProjects/untitled'`

Then I copy qtwebengine_resources.pak, qtwebengine_resources_100p.pak, qtwebengine_resources_200p.pak and icudtl.dat in the directory "libexec" and "resources".

I do not know how it is right, but it works for me.

**Comment by kanekotic** [comment]
hello @atehxx and @Alexorleon . Sorry for the late reply thanks for both of your inputs. they have been very useful. Its still not working due some zigote issues in some machines but that is a different beast I think 😄 .
also i need to check if the dependency comes from webengine or somewhere else @probonopd, but some openGl plugins qt are also not added in (maybe because they are options). So i ended up having to:
```
cp /opt/Qt/5.8/gcc_64/plugins/xcbglintegrations/* ./dist-desktop/plugins/xcbglintegrations
```

**Comment by probonopd** [comment]
@Alexorleon please check if https://github.com/probonopd/linuxdeployqt/commit/74ca072c7f30d2dd7f57c6f91f66a7fb1edb35b3 solves the original issue of this ticket. @kanekotic please open a new issue for `xcbglintegrations`.

**Comment by probonopd** [comment]
@Alexorleon can you confirm this is fixed in 74ca072?

**Comment by Alexorleon** [comment]
I downloaded linuxdeployqt-continuous-x86_64.AppImage.

QMake version 3.0
Using Qt version 5.7.1 in /opt/Qt/Qt5.7.1/5.7/gcc_64/lib
patchelf 0.9

`/home/alexorleon/Deployment/linuxdeployqt-continuous-x86_64.AppImage /home/alexorleon/Deployment/VIC/VIC-client -qmldir='/home/alexorleon/QtProjects/VIC-client'`

"/tmp/.mount_SHCqrI/usr/bin/usr/bin:/usr/local/bin/:/opt/Qt/Qt5.7.1/5.7/gcc_64/bin/:/home/alexorleon/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin"
app-binary: "/home/alexorleon/Deployment/VIC/VIC-client"
Not using FHS-like mode, appBinaryPath: "/home/alexorleon/Deployment/VIC/VIC-client"
appDirPath: "/home/alexorleon/Deployment/VIC"
relativeBinPath: "VIC-client"
QIODevice::write (QFile, "/home/alexorleon/Deployment/VIC/VIC-client/../qt.conf"): device not open

Catalog "libexec" contains:
QtWebEngineProcess
and qt.conf
```
# Generated by linuxdeployqt
# https://github.com/probonopd/linuxdeployqt/
[Paths]
Prefix = ../
```

./VIC-client
`./VIC-client: error while loading shared libraries: libQt5WebEngine.so.5: cannot open shared object file: No such file or directory`

However, this file exists in the directory "lib".

**Comment by probonopd** [comment]
Please run appimagetool twice on the same directory. Does the error persist? Can you upload the directory for futher testing?

**Comment by Alexorleon** [comment]
`/home/alexorleon/Deployment/linuxdeployqt-continuous-x86_64.AppImage /home/alexorleon/Deployment/VIC/VIC-client -qmldir='/home/alexorleon/QtProjects/VIC-client'`

First run:
```
"/tmp/.mount_55udt7/usr/bin/usr/bin:/usr/local/bin/:/opt/Qt/Qt5.7.1/5.7/gcc_64/bin/:/home/alexorleon/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin"
app-binary: "/home/alexorleon/Deployment/VIC/VIC-client"
Not using FHS-like mode, appBinaryPath: "/home/alexorleon/Deployment/VIC/VIC-client"
appDirPath: "/home/alexorleon/Deployment/VIC"
relativeBinPath: "VIC-client"
QIODevice::write (QFile, "/home/alexorleon/Deployment/VIC/VIC-client/../qt.conf"): device not open
```

Second run:
```
"/tmp/.mount_VZJ4jm/usr/bin/usr/bin:/usr/local/bin/:/opt/Qt/Qt5.7.1/5.7/gcc_64/bin/:/home/alexorleon/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin"
app-binary: "/home/alexorleon/Deployment/VIC/VIC-client"
Not using FHS-like mode, appBinaryPath: "/home/alexorleon/Deployment/VIC/VIC-client"
appDirPath: "/home/alexorleon/Deployment/VIC"
relativeBinPath: "VIC-client"
WARNING: "/home/alexorleon/Deployment/VIC/libexec/qt.conf" already exists, will not overwrite.
QIODevice::write (QFile, "/home/alexorleon/Deployment/VIC/VIC-client/../qt.conf"): device not open
```
Error is still here.
./VIC-client
`./VIC-client: error while loading shared libraries: libQt5WebEngine.so.5: cannot open shared object file: No such file or directory`

HTML file. That's enough, or files are needed?
[DirectoryTree.zip](https://github.com/probonopd/linuxdeployqt/files/786597/DirectoryTree.zip)

**Comment by probonopd** [comment]
Thanks, Files are needed for analysis.

**Comment by Alexorleon** [comment]
@probonopd, the file is too large. Can you give me an e-mail, I'll send a link to google disc?

**Comment by probonopd** [comment]
probono /at/ puredarwin -dot- org

**Comment by Alexorleon** [comment]
https://drive.google.com/drive/folders/0B-4X4fhGAJs2REUyNHY4UUtWTlE?usp=sharing

**Comment by probonopd** [comment]
So it looks like QtWebEngine is there but isn't getting loaded.

```
me@host ~/Downloads/VIC $ ./AppRun 
./AppRun: error while loading shared libraries: libQt5WebEngine.so.5: cannot open shared object file: No such file or directory

me@host ~/Downloads/VIC $ find . | grep WebEngine
./qml/QtWebEngine
./qml/QtWebEngine/qmldir
./qml/QtWebEngine/plugins.qmltypes
./qml/QtWebEngine/libqtwebengineplugin.so
./qml/QtWebEngine/experimental
./qml/QtWebEngine/experimental/qmldir
./qml/QtWebEngine/experimental/libqtwebengineexperimentalplugin.so
./qml/QtWebEngine/UIDelegates
./qml/QtWebEngine/UIDelegates/qmldir
./qml/QtWebEngine/UIDelegates/PromptDialog.qml
./qml/QtWebEngine/UIDelegates/MessageBubble.qml
./qml/QtWebEngine/UIDelegates/MenuSeparator.qml
./qml/QtWebEngine/UIDelegates/MenuItem.qml
./qml/QtWebEngine/UIDelegates/Menu.qml
./qml/QtWebEngine/UIDelegates/FilePicker.qml
./qml/QtWebEngine/UIDelegates/ConfirmDialog.qml
./qml/QtWebEngine/UIDelegates/ColorDialog.qml
./qml/QtWebEngine/UIDelegates/AuthenticationDialog.qml
./qml/QtWebEngine/UIDelegates/AlertDialog.qml
./libexec/QtWebEngineProcess
./lib/libQt5WebEngineCore.so.5
./lib/libQt5WebEngine.so.5
```

For whatever strange reason, it seems like the rpath of the main executable is set to $ORIGIN rather than to $ORIGIN/lib as should be done by [this code](https://github.com/probonopd/linuxdeployqt/blob/eae604d2543a50b5d628f910a17d839162ef8c20/shared/shared.cpp#L810). Are you sure you used the latest continuous build of `linuxdeployqt`?

Fixing this manually:

```
patchelf --set-rpath '$ORIGIN/lib/' ./VIC-client

me@host ~/Downloads/VIC $ ./AppRun 
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Reinstalling the application may fix this problem.
Aborted

```

It is not finding the Qt plugins/platforms directory, and it can't, because there is neiter a qt.conf file next to the main executable binary, nor is `qt_prfxpath=` set correctly as [this code](https://github.com/probonopd/linuxdeployqt/blob/eae604d2543a50b5d628f910a17d839162ef8c20/shared/shared.cpp#L1239) should do. Again, are you using the latest continuous build of `linuxdeployqt`?

Manual workaround:

```
sed -i -e 's|qt_prfxpath=/o|qt_prfxpath=.\x00|g' ./lib/libQt5Core.so.5
```

And voilà, the app runs. But please do use the latest `linuxdeployqt` to do these things properly.

Let me know how it goes.

**Comment by Alexorleon** [comment]
I used ready file here https://github.com/probonopd/linuxdeployqt/releases.

Thank you! In the near future I will try again and report the results. If does not work, I will try to the source code.

**Comment by probonopd** [comment]
It depends which version you used. Please retry with the latest _continuous_ version.

**Comment by Alexorleon** [comment]
Everything works great! Thank you.

**Comment by randinterval** [comment]
@probonopd I built 32bit version of linuxdeployqt from source (latest version - downloaded last night). While trying to package the app, I'm getting the following errors: 

>  saad@saad-VirtualBox:~/Downloads/Build$ ./linuxdeployqt App
> Not using FHS-like mode
> app-binary: "/home/saad/Downloads/Build/App"
> appDirPath: "/home/saad/Downloads/Build"
> relativeBinPath: "App"
> WARNING: "/home/saad/Downloads/Build/libexec/qt.conf" already exists, will not overwrite.
> ERROR: file copy failed from "/home/saad/Qt5.5.1/5.5/gcc/resources/qtwebengine_resources.pak"
> ERROR:  to "/home/saad/Downloads/Build/resources/qtwebengine_resources.pak"
> ERROR: file copy failed from "/home/saad/Qt5.5.1/5.5/gcc/resources/qtwebengine_devtools_resources.pak"
> ERROR:  to "/home/saad/Downloads/Build/resources/qtwebengine_devtools_resources.pak"
> ERROR: file copy failed from "/home/saad/Qt5.5.1/5.5/gcc/resources/qtwebengine_resources_100p.pak"
> ERROR:  to "/home/saad/Downloads/Build/resources/qtwebengine_resources_100p.pak"
> ERROR: file copy failed from "/home/saad/Qt5.5.1/5.5/gcc/resources/qtwebengine_resources_200p.pak"
> ERROR:  to "/home/saad/Downloads/Build/resources/qtwebengine_resources_200p.pak"
> ERROR: file copy failed from "/home/saad/Qt5.5.1/5.5/gcc/resources/icudtl.dat"
> ERROR:  to "/home/saad/Downloads/Build/resources/icudtl.dat"
> WARNING: "/home/saad/Downloads/Build/qt.conf" already exists, will not overwrite.

The app launched fine, but as soon as I go to any part of the app that uses Webengine it crashes (unable to locate WebEngine pak files, and io file). I was able to fix this by manually copying these over to extensions and other folder...but I'm just wondering why it is failing to copy the webengine files..64bit version bundled webengine without any issues.
OS is Ubuntu 14.04

**Comment by probonopd** [comment]
Just for fun, can you try with a FHS-like directory structure (i.e., appdir/usr/bin/App, appdir/usr/lib,..)

**Comment by randinterval** [comment]
yes:

> saad@saad-VirtualBox:~/Downloads/Build$ ./linuxdeployqt appdir/usr/bin/App
> FHS-like mode with PREFIX, fhsPrefix: "/home/saad/Downloads/Build/appdir/usr"
> app-binary: "/home/saad/Downloads/Build/appdir/usr/bin/App"
> appDirPath: "/home/saad/Downloads/Build/appdir"
> relativeBinPath: "usr/bin/App"
> ERROR: file copy failed from "/home/saad/Qt5.5.1/5.5/gcc/resources/qtwebengine_resources.pak"
> ERROR:  to "/home/saad/Downloads/Build/appdir/usr/resources/qtwebengine_resources.pak"
> ERROR: file copy failed from "/home/saad/Qt5.5.1/5.5/gcc/resources/qtwebengine_devtools_resources.pak"
> ERROR:  to "/home/saad/Downloads/Build/appdir/usr/resources/qtwebengine_devtools_resources.pak"
> ERROR: file copy failed from "/home/saad/Qt5.5.1/5.5/gcc/resources/qtwebengine_resources_100p.pak"
> ERROR:  to "/home/saad/Downloads/Build/appdir/usr/resources/qtwebengine_resources_100p.pak"
> ERROR: file copy failed from "/home/saad/Qt5.5.1/5.5/gcc/resources/qtwebengine_resources_200p.pak"
> ERROR:  to "/home/saad/Downloads/Build/appdir/usr/resources/qtwebengine_resources_200p.pak"
> ERROR: file copy failed from "/home/saad/Qt5.5.1/5.5/gcc/resources/icudtl.dat"
> ERROR:  to "/home/saad/Downloads/Build/appdir/usr/resources/icudtl.dat"

**Comment by probonopd** [comment]
What happens if you manually try to copy `/home/saad/Qt5.5.1/5.5/gcc/resources/qtwebengine_resources.pak` to
`/home/saad/Downloads/Build/appdir/usr/resources/qtwebengine_resources.pak`?

**Comment by randinterval** [comment]
Yes, that is the workaround. Currently, I manually copy these files (qtwebengine_resources.pak, 
qtwebengine_resources_100p.pak, qtwebengine_resources_200p.pak,icudtl.dat).

**Comment by probonopd** [comment]
So you are saying you _can_ manually copy these files, but `linuxdeployqt` says `ERROR:` when trying to copy them. We need to find out why.

**Comment by randinterval** [comment]
ah, sorry, my mistake. I think i figured out the issue...it tries to look into resources folder but the .pak files and .dat are in gcc/bin not in gcc/bin/resources .

**Comment by probonopd** [comment]
Which may well be wrong. Where is `/Qt5.5.1/5.5/gcc/` coming from? What system are you using and where did you get that Qt from?

**Comment by probonopd** [comment]
This is the corresponding code:

https://github.com/probonopd/linuxdeployqt/blob/5dc2aaea62c0222dd7952fd9e0832e8fcdfcf672/tools/linuxdeployqt/shared.cpp#L1297-L1316

Is there a better way instead of `QDir::cleanPath(qtDataPath + "/resources/qtwebengine_resources.pak")`?

**Comment by randinterval** [comment]
I'm using Ubuntu 14.04 32 bit, and Qt was installed from qt.io (using online installer). This is the default installation location.

**Comment by randinterval** [comment]
On 64bit version, the files are indeed located in resources folder.

**Comment by probonopd** [comment]
According to https://bugreports.qt.io/browse/QTBUG-49400, 

> But you might also want to check out the latest 5.6 branch, because we changed the lookup of this file there (to QT_INSTALL_DATA/resources)

**Comment by randinterval** [comment]
@probonopd  Thank you, for 32bit they only pre-compiled binaries upto 5.5,  so looks like I'm going to have to build it from source. Thanks again for your assistance!

**Comment by probonopd** [comment]
Check https://launchpad.net/~beineri/+archive/ubuntu/opt-qt592-trusty and friends.
