### ISSUE TITLE
Ubuntu 20 yet?

### ISSUE THREAD

**Issue by kdabci** [probonopd/linuxdeployqt#570]
Since Ubuntu18 LTS is EOL by end of April I'm wondering if there are plans to support Ubuntu20 LTS (I mean, without resorting to the -unsupported-allow-new-glibc" option)

or maybe it already does support ubuntu20?

**Comment by probonopd** [comment]
Please try the latest continuous build and see whether it works for you.
Thank you very much.

**Comment by winterz** [comment]
ok, looks fine.  works as expected.

I think we can close this.
