### ISSUE TITLE
Ubuntu 18.04 is nearing its EOL

### ISSUE THREAD

**Issue by martinrotter** [probonopd/linuxdeployqt#572]
Will linuxdeployqt now support 20.04 LTS as THE system for building our appimages? Also, connected question is Qt 6 support which was defacto useless in 18.04, but will be of more importance as 20.04 actually contains relatively new Qt 6 binaries in repos.

Thanks for answers.

**Comment by probonopd** [comment]
> Will linuxdeployqt now support 20.04 LTS as THE system for building our appimages?

Yes, as per https://github.com/probonopd/linuxdeployqt/issues/570.

> Also, connected question is Qt 6 support

I guess only once https://github.com/probonopd/linuxdeployqt/pull/541/ can be merged.

Closing here as a duplicate, let's please continue discussion in the linked tickets.
