### ISSUE TITLE
How do I install this program on the arm platform？

### ISSUE THREAD

**Issue by njustxl** [probonopd/linuxdeployqt#578]
How do I install this program on the arm platform

**Comment by probonopd** [comment]
Unfortunately there are currently no builds for ARM, only for the x86_64 platform.
So you would have to build it from source.

Maybe https://github.com/probonopd/go-appimage/tree/master/src/appimagetool is an alternative for you? It has ARM versions.

**Comment by njustxl** [comment]
OK，thank you！
