### ISSUE TITLE
could not load multimedia backend "" QtMultimedia is not currently supported on this platform or compiler.

### ISSUE THREAD

**Issue by Nishithwi** [probonopd/linuxdeployqt#579]
Why is this error occuring when I run the app Image in ubuntu 20.04 ?

**Comment by probonopd** [comment]
Hi @Nishithwi. Please provide additional information:
* Which AppImage is giving you this error?
* Where can it be downloaded for testing?
* Which target system (distribution and version) are you trying to run it on?#
* Are you the author of the AppImage in question?
Thanks.

**Comment by assyhgit** [comment]
same problem 
1-i make own appimage
2-not any place
3-same system  Ubuntu 22.04.2 LTS, 64bit , gnome 42,5, X11
4-yes

Thank you ;)
