### ISSUE TITLE
AppImage not created

### ISSUE THREAD

**Issue by JaviBonilla** [probonopd/linuxdeployqt#58]
Hello,

I'm having issues generating an AppImage with this tool. I create a plain directory called "OptFMI.AppDir" then I place some files: 
- OptFMI (binary)
- default.appdata.xml
- OptFMI.desktop
- OptFMI.png
- OptFMI.svg
- qt.conf

Then, I execute _`linuxdeployqt-continuous-x86_64.AppImage "OptFMI" -appimage`_, this is the output:

```
_###"/tmp/.mount_ifKOyQ/usr/bin:/home/javi/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:.:/usr/lib64/qt5/bin/:/home/javi/connectiq/bin:.:/usr/lib64/qt5/bin/:/home/javi/connectiq/bin"
app-binary: "OptFMI"
WARNING: "./qt.conf" already exists, will not overwrite.
WARNING: To make sure the plugins are loaded from the correct location,
WARNING: please make sure qt.conf contains the following lines:
WARNING: [Paths]
WARNING:   Plugins = plugins
Desktop file: /home/javi/Documents/Git/OptFMI/Releases/linux64/OptFMI.AppDir/OptFMI.desktop
Name: OptFMI
Icon: OptFMI.svg
Exec: AppRun %F
Comment: OptFMI
Type: Application
Categories entry not found in desktop file
Categories: (null)
File used for determining architecture: /home/javi/Documents/Git/OptFMI/Releases/linux64/OptFMI.AppDir/lib/liblapack.so.3
Arch: 86_64
App name for filename: OptFMI
dest_path: OptFMI-x86_64.AppImage
DESTINATION not specified, so assuming OptFMI-x86_64.AppImage
/home/javi/Documents/Git/OptFMI/Releases/linux64/OptFMI.AppDir should be packaged as OptFMI-x86_64.AppImage
OptFMI.svg{.png,.svg,.svgz,.xpm} not present but defined in desktop file_

```
Apparently there are no errors, but the AppImage file is not generated.

**Comment by probonopd** [comment]
The error message could be a bit clearer, but apparently you have `Icon=OptFMI.svg` in your desktop file. Please change it to `Icon=OptFMI` and put a file called `OptFMI.svg` into the same directory as the executable.

If you want to use AppStream, please put a file into `usr/share/metainfo/OptFMI.appdata.xml` with usr being on the same directory level as your executable.

**Comment by JaviBonilla** [comment]
Thank you for your help, it works great!. Now, I have another issue related to AppStream, this is the output.

```
### "/tmp/.mount_RpCXFF/usr/bin:/home/javi/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:.:/usr/lib64/qt5/bin/:/home/javi/connectiq/bin:.:/usr/lib64/qt5/bin/:/home/javi/connectiq/bin"
app-binary: "OptFMI"
WARNING: "./qt.conf" already exists, will not overwrite.
WARNING: To make sure the plugins are loaded from the correct location,
WARNING: please make sure qt.conf contains the following lines:
WARNING: [Paths]
WARNING:   Plugins = plugins
Desktop file: /home/javi/Documents/Git/OptFMI/Releases/linux64/OptFMI.AppDir/OptFMI.desktop
Name: OptFMI
Icon: OptFMI
Exec: AppRun %F
Comment: A software tool for parameter optimization in FMI models
Type: Application
Categories: Science
File used for determining architecture: /home/javi/Documents/Git/OptFMI/Releases/linux64/OptFMI.AppDir/lib/liblapack.so.3
Arch: 86_64
App name for filename: OptFMI
dest_path: OptFMI-x86_64.AppImage
DESTINATION not specified, so assuming OptFMI-x86_64.AppImage
/home/javi/Documents/Git/OptFMI/Releases/linux64/OptFMI.AppDir should be packaged as OptFMI-x86_64.AppImage
Creating .DirIcon symlink based on information from desktop file
AppStream upstream metadata found in usr/share/metainfo/OptFMI.appdata.xml
W - OptFMI.appdata.xml:OptFMI.desktop:3
    The component ID is not a reverse domain-name. Please update the ID and that of 
    the accompanying .desktop file to follow the latest version of the Desktop-Entry 
    and AppStream specifications and avoid future issues.

E - OptFMI.appdata.xml:OptFMI.desktop
    Component metadata refers to a non-existing .desktop file.

Validation failed.
Failed to validate AppStream information with appstreamcli
```

The desktop file is placed on the same level as the executable, I also tried copying it to `usr/share/metainfo/`. Where am I supposed to placed this file then?, thanks!.

**Comment by probonopd** [comment]
Do you have
```
​<component type="desktop-application">
​  <id>OptFMI</id>
```
in your xml file as specified in https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html?

cc'ing @ximion

**Comment by ximion** [comment]
> The desktop file is placed on the same level as the executable, I also tried copying it to usr/share/metainfo/. Where am I supposed to placed this file then?, thanks!

The metainfo  file goes to `usr/share/metainfo`, but it appears like this is placed correctly. However, you either have a typo in your <id/> tag, or the .desktop file is not in `usr/share/applications/`.

**Comment by JaviBonilla** [comment]
Thank you, now it works. The missing thing here was that I didn't copy the desktop file in `usr/share/applications/`. 

The app executes fine, but `svg` icons are not shown in the GUI. If I manually copy the following files to the `plugin` folder, it works as expected.

```
/plugins/iconengines/libqsvgicon.so
/plugins/imageformats/libqsvg.so
```
So, do I have to change something in my Qt project file (pro file), so `linuxdeployqt` can automatically detect and copy those files?. I tried the following without success.

`QTPLUGIN += qsvg qsvgicon`

**Comment by ximion** [comment]
Btw, you might want to rename your .desktop file to follow a reverse-DNS scheme as outlined in the latest revision of the XDG desktop-entry spec: https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#basic-format
(it will work without it, but the reverse-DNS name allows for D-Bus activation and under Wayland allows the application to be matched properly with its icon)

**Comment by JaviBonilla** [comment]
Yes, I changed that. I realized from the warnings, thanks.

**Comment by probonopd** [comment]
@JaviBonilla 
> The app executes fine, but svg icons are not shown in the GUI. If I manually copy the following files to the plugin folder, it works as expected.
> /plugins/iconengines/libqsvgicon.so
> /plugins/imageformats/libqsvg.so

Looks like a shortcoming of `linuxdeployqt` that needs to be fixed.

Is `libQt5Svg.so.*` getting deployed by `linuxdeployqt`? Then, according to this code, `libqsvgicon.so` also _should_ be deployed:

https://github.com/probonopd/linuxdeployqt/blob/4951fd133b43e475d1bd64f32b9c5e265253485b/shared/shared.cpp#L843-L847

I didn't have `libqsvg.so` on my radar screen so far -- is it safe to assume that it should be deployed whenever `libQt5Svg.so.*` is being deployed?

**Comment by JaviBonilla** [comment]
Well, the thing is that in my case, `libQt5Svg.so.*` is not deployed and I do not need it, only `libqsvg.so` and `libqsvgicon.so`.

I only use `svg` files in my app for the icons stored in a resource file and also for some `Theme` icons that I use, but there is no mention in my code to `#include<QtSvg>`.

**Comment by probonopd** [comment]
How could a tool like `appimage` detect that `libqsvg.so` and `libqsvgicon.so` are needed?

**Comment by JaviBonilla** [comment]
I don't know because Qt plugins are loaded at run-time, I'll think about it.

On the other hand, I've been continuing testing the AppImage and I found two more issues, one of them is related to the Qt Data Visualization module, I got this error before packaging but in the AppDir.

```
QXcbIntegration: Cannot create platform offscreen surface, neither GLX nor EGL are enabled
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
Segmentation fault (core dumped)
```

The other is related to a library I used for extracting zip files `QuaZIP`, because I get an error when trying to opening a zip file. Is there any problem with AppImages if my app extracts zip files in given directory which is created from the current directory?

**Comment by probonopd** [comment]
Please try with an absolute path where to unpack to.

**Comment by JaviBonilla** [comment]
Yes, both problems are solved now thanks to your suggestions!. I will keep testing but it seems everything is working fine.

One question with respect to AppImage icons; is it possible to assign an icon to each particular AppImage or does this depend on the desktop environment?. In my Plasma 5 desktop I see all AppImages with kind of unknown extension icon.

**Comment by probonopd** [comment]
> In my Plasma 5 desktop I see all AppImages with kind of unknown extension icon

In the menu or on the file itself?

For the menus, if everything goes correctly, the optional `appimaged` daemon (if it is installed) should show the icon that is contained in the AppImage as the icon for the app entry.

**Comment by JaviBonilla** [comment]
Hi!, sorry for not answering before I completely forgot. The app works great.

Thank you for the info about the icons I had no idea. About writting thumbnailes, that would be great, but may be in the future, right now I am quite busy :-).

Thank you for your help!.

**Comment by probonopd** [comment]
Thanks for your update @JaviBonilla - is your app or a demo version of it available for download?

**Comment by JaviBonilla** [comment]
Not yet, but it will be soon!, there are still some issues that must be solved. I will tell you over here when it is online :-).

**Comment by probonopd** [comment]
Also, feel free to add it to https://github.com/probonopd/AppImageKit/wiki/AppImages

**Comment by JaviBonilla** [comment]
Ok, thanks.

**Comment by JaviBonilla** [comment]
Hi @probonopd,

I already have an alpha version of our app as a Linux AppImage and it is working great. The app is called Optifmus. It is intended for research, it optimizes dynamic models according to selected criteria. 

This is the repository. [https://gitlab.com/ciemat-psa/Optifmus](https://gitlab.com/ciemat-psa/Optifmus)

And this is the link to the AppImage. [https://gitlab.com/ciemat-psa/Optifmus/tree/master/bin/linux/Optifmus-0.1.0-x86_64.AppImage](https://gitlab.com/ciemat-psa/Optifmus/tree/master/bin/linux/Optifmus-0.1.0-x86_64.AppImage)

Regards,
Javier.

**Comment by probonopd** [comment]
Thanks @JaviBonilla, added to https://github.com/probonopd/AppImageKit/wiki/AppImages.
