### ISSUE TITLE
why not allow a file such as `env.sh` to custom the `env`？

### ISSUE THREAD

**Issue by yanhuacuo** [probonopd/linuxdeployqt#580]
why not allow a file such as `env.sh` to custom the `env`？

I need set a env `export QT_QPA_PLATFORM=xcb` for wayland user

When I test this: 

https://github.com/probonopd/linuxdeployqt/wiki/Custom-wrapper-script-instead-of-AppRun

it doesnot work ： `execv error: Permission denied`

this is my AppRun file 

```
#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"
export QT_QPA_PLATFORM=xcb
cd "${HERE}/usr/bin
exec ./newReader "$@"
```

**Comment by probonopd** [comment]
Argh. Wayland [breaks](https://gist.github.com/probonopd/9feb7c20257af5dd915e3a9f2d1f2277) so many things...

**Comment by probonopd** [comment]
Can you provide a link to your AppImage so that I can help? Thanks.

**Comment by yanhuacuo** [comment]
https://drive.google.com/file/d/19eyJ14V9ZtjxM6z-3_FMsjNoN9MZLyuW/view?usp=drive_link

**Comment by yanhuacuo** [comment]
Wayland in KDE Plasma 5.27.5，does not need 「xcb」 any more，everything is ok.

while，Wayland in Gnome，need 「xcb」 .
