### ISSUE TITLE
problem with patchelf

### ISSUE THREAD

**Issue by kanekotic** [probonopd/linuxdeployqt#59]
i am having problems with the step when the pathelf is running. But is strange for me as its not always the same file
1st run:
```
RROR: file copy failed from "/home/knek/workspace/Deploy-Linux/dist-desktop/lib/libXfixes.so.3"
ERROR:  to "dist-desktop/lib//libXfixes.so.3"
Log: Using patchelf:
Log:  change rpath in "dist-desktop/lib//libXfixes.so.3"
Log:  to "$ORIGIN"
ERROR: runPatchelf: "stat: No such file or directory\n"
ERROR: runPatchelf: ""
```
2nd run:
```
ERROR: file copy failed from "/home/knek/workspace/Deploy-Linux/dist-desktop/lib/libXrender.so.1"
ERROR:  to "dist-desktop/lib//libXrender.so.1"
ERROR: runPatchelf: "stat: No such file or directory\n"
ERROR: runPatchelf: ""
```
any idea on why this is happening?

**Comment by probonopd** [comment]
Don't know what is causing this, more investigation would be greatly appreciated.

**Comment by kanekotic** [comment]
It is true that the package is not there at that point. But also the paths of copy from and to seems very suspicious. 
```
ERROR: file copy failed from "/home/knek/workspace/Deploy-Linux/dist-desktop/lib/libXfixes.so.3"
ERROR:  to "dist-desktop/lib//libXfixes.so.3"
```
i will say its trying to copy a file that is on its rpath probably hardcoded on a relative path and not using $origin? it fails to copy it (as its same origin and destination after resolving the path). and it has been added to be resolved list (https://github.com/probonopd/linuxdeployqt/blob/4951fd133b43e475d1bd64f32b9c5e265253485b/shared/shared.cpp#L712). As it does not exist and is on the libraries list because is not blacklisted or copy it blows.
makes any sense?

**Comment by kanekotic** [comment]
ohhh btw...in that specific case `libXfixes.so.3` is a link

**Comment by probonopd** [comment]
How could it be fixed best?

**Comment by kanekotic** [comment]
uhmmm ... let me think about it but if there are links and not really so... there should be a test for it to just copy and add to the deps the related linked library and continue the normal workflow....i will think a bit about it, also for the other case i said mayne test if the path or rpath contain ./<something> ignore?

**Comment by kanekotic** [comment]
I will like to look in depth on it and work on a possible PR when i have some time for now i am up of work to the limit so can not look on it 😢

**Comment by probonopd** [comment]
Is this still an issue?

**Comment by kanekotic** [comment]
have not worked on it for a while so I will close.
