### ISSUE TITLE
build 55 built on 2023-09-23 13:33:41 UTC ERROR: The host system is too new.

### ISSUE THREAD

**Issue by parisa-hr** [probonopd/linuxdeployqt#594]
Hi 
I use Fedora 38 and as I  run `sudo ./linuxdeployqt-continuous-x86_64.AppImage `

I got 

> linuxdeployqt  (commit 6fcaf74), build 55 built on 2023-09-23 13:33:41 UTC
> ERROR: The host system is too new.
> Please run on a system with a glibc version no newer than what comes with the oldest
> currently supported mainstream distribution (Ubuntu Focal Fossa), which is glibc 2.31.
> This is so that the resulting bundle will work on most still-supported Linux distributions.
> For more information, please see
> https://github.com/probonopd/linuxdeployqt/issues/340

But I didn't understand what should I do.

![image](https://github.com/probonopd/linuxdeployqt/assets/44742050/bc7aad7d-5351-427f-9cdb-ca4b214f950e)

**Comment by probonopd** [comment]
The host system is too new.
Please run on a system with a glibc version no newer than what comes with the oldest
currently supported mainstream distribution (Ubuntu Focal Fossa), which is glibc 2.31.
