### ISSUE TITLE
Can I specify the output file name?

### ISSUE THREAD

**Issue by qsaker** [probonopd/linuxdeployqt#595]
I want to output a fixed(such as 123.AppImage) file name when create AppImage with linuxdeployqt.

**Comment by probonopd** [comment]
The output filename is based on the `Ǹame=...` in the `.desktop` file. So, if you set that key to the correct application name, you will get an AppImage with the correct naming (including the architecture) automatically.

**Comment by qsaker** [comment]
My .desktop file is:
```ini
[Desktop Entry]
Type=Application
Name=QtSwissArmyKnife
Comment=Qt Swiss Army Knife
Exec=QtSwissArmyKnife
Icon=QtSwissArmyKnife
Categories=Development;
```.
but the output file is: QtSwissArmyKnife-eccc148-x86_64.AppImage.
I mean that can I specifyed the output file name as 123.AppImage?

**Comment by probonopd** [comment]
The AppImage naming scheme is: ApplicationName + _ + version + architecture + ".AppImage".
So the generated filename is correct.

If your application would be called "123", then you should set `Name=123` and would get `123-eccc148-x86_64.AppImage`.

This naming scheme is a convention and is part of how AppImageUpdate works. Why would you like to name the AppImage differently than the name of your application?

**Comment by CJYate** [comment]
> The AppImage naming scheme is: ApplicationName + _ + version + _ + architecture + ".AppImage". So the generated filename is correct.
> 
> If your application would be called "123", then you should set `Name=123` and would get `123-eccc148-x86_64.AppImage`.
> 
> This naming scheme is a convention and is part of how AppImageUpdate works. Why would you like to name the AppImage differently than the name of your application?

Hi -- answering on behalf of OP but it would be much better for my automation process to have a predictable output filename.  Specifically, suppressing the git SHA fragment, if that's what it is, would be great.
