### ISSUE TITLE
why i use qt creater The app can run, but use linuxdeployqt it cannot work..

### ISSUE THREAD

**Issue by FangXS-github** [probonopd/linuxdeployqt#598]
linux: ubuntu22.04
qtcreater: qt5.13.3
linuxdeployqt:    linuxdeployqt continuous (commit 2b38449), build <local dev build> built on 2024-01-02 06:26:02 UTC

when i use qt creater to run my qt app , it works. but when i deploy it ,i got:
**Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/home/debix/build-hellowindow-Desktop-Release/platforms" ...
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in "/home/debix/build-hellowindow-Desktop-Release/plugins"
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: xcb.
Aborted (core dumped)**

how to slove my problem??

**Comment by FangXS-github** [comment]
platform :    imx8mp -- Linux 6.1.22

**Comment by FangXS-github** [comment]
and i already compiled linuxdeployqt on my machine.

**Comment by probonopd** [comment]
Are you running a Wayland session? Do you have XWayland installed? Please try with a Xorg session for comparison. Thanks.

**Comment by FangXS-github** [comment]
I tried：
$ sudo apt install qtwayland5
$ sudo apt-get install qtbase5-dev
then using  normal user( not root) run  ./app
it works.
