### ISSUE TITLE
When will ubuntu22.04 be support? 

### ISSUE THREAD

**Issue by yanhuacuo** [probonopd/linuxdeployqt#601]
I can understand the author's design of glibc version control, 
but a very embarrassing fact is that **the minimum requirement for Qt6 development components is Ubuntu22.04.**
The currently approved ubuntu20.04 is only suitable for Qt5 development.
Although this project supports Qt6,
 it restricts Qt6 in the glibc version. 
Is this inappropriate?

![2024-02-03_080152](https://github.com/probonopd/linuxdeployqt/assets/3107994/348c203f-4110-4b50-a651-d4b6cda6d48e)

**Comment by yanhuacuo** [comment]
// Ubuntu Focal Fossa (20.04) uses glibc 2.31

https://github.com/probonopd/linuxdeployqt/blob/master/tools/linuxdeployqt/main.cpp#L213

**Comment by probonopd** [comment]
Apr 2025, when 20.04 LTS (Focal Fossa) will no longer be in Standard Support.
