### ISSUE TITLE
Parallel deployment

### ISSUE THREAD

**Issue by fwren** [probonopd/linuxdeployqt#604]
If my project needs to deploy multiple programs, whether linuxdeployqt supports parallel deployment

**Comment by probonopd** [comment]
As in
```
   -executable=<path>       : Let the given executable use the deployed libraries
                              too
```
?

**Comment by fwren** [comment]
It means that if I use the command
```shell
    linuxdeploqt ./app1 -executable=./app2 -excutable=./app3
```
Will the app1 app2 app3 related dependent library be packed and deployed?

**Comment by probonopd** [comment]
Exactly.

**Comment by fwren** [comment]
Okay, thank you, I haven’t tried this option before
