### ISSUE TITLE
Build linuxdeployqt from sorce - qmake error

### ISSUE THREAD

**Issue by gregkr** [probonopd/linuxdeployqt#610]
`
/SHARED/install/linuxdeployqt-continuous$ qmake -v
QMake version 3.1
Using Qt version 6.7.0 in /home/tim/Qt/6.7.0/gcc_64/lib

/SHARED/install/linuxdeployqt-continuous$ qmake
/home/tim/SHARED/install/linuxdeployqt-continuous/.qmake.conf:1: Cannot find feature qt_build_config
/home/tim/SHARED/install/linuxdeployqt-continuous/.qmake.conf:1: Cannot find feature qt_build_config
/home/tim/SHARED/install/linuxdeployqt-continuous/linuxdeployqt.pro:1: Cannot find feature qt_parts
`

**Comment by probonopd** [comment]
Hello, linuxdeployqt is a Qt 5 application.

Its successor is https://github.com/probonopd/go-appimage.
