### ISSUE TITLE
 Using linuxdeployqt in UOS,only generate 3 files:Application AppRun default.png

### ISSUE THREAD

**Issue by hellokejian** [probonopd/linuxdeployqt#611]
I am using linuxdeployqt in UOS(another release of linux, called统信),and i came into a problem.

1.I have copy the linuxdeployqt.Appimage to /usr/local/bin
2.I have configured the QT lib dir for qmake
3.I can see linuxdeploy and qmake verison in terminal
4.I use " linuxdeployqt -appimage Test " to produce the dependency

but the result is,there is nothing but only the "Application AppRun default.png“ exist ,i can not see anything like lib/bin/platforms/Translation dir 。

Could you please help?Appreciate that!
![企业微信截图_20240604203805](https://github.com/probonopd/linuxdeployqt/assets/23314193/43cf6141-b786-480a-a6a5-98f0f5150943)
![企业微信截图_20240604203840](https://github.com/probonopd/linuxdeployqt/assets/23314193/9b5e9968-fbb2-47eb-b4d8-475a932b40a8)
![企业微信截图_20240604204116](https://github.com/probonopd/linuxdeployqt/assets/23314193/6e6c3562-7987-4aa6-afb3-04ea322fd76b)
![企业微信截图_20240604204144](https://github.com/probonopd/linuxdeployqt/assets/23314193/ea5843bd-66fa-4a9c-b6ac-941655f67a51)
![企业微信截图_20240604204914](https://github.com/probonopd/linuxdeployqt/assets/23314193/112b359d-66e5-4bd9-9a78-04e31fec1bc3)

**Comment by probonopd** [comment]
How does your AppDir look before you are running `linuxdeployqt`?

E.g.

```
YourAppDir/usr/share/yourapp.desktop
YourAppDir/usr/bin/yourapp
YourAppDir/usr/...
...
```

**Comment by hellokejian** [comment]
i am using "linuxdeployqt appname -appiamge" not "linuxdeployqt app.Desktop" , still need the "YourAppDir/usr/share/yourapp.desktop
YourAppDir/usr/bin/yourapp
YourAppDir/usr/..."?

**Comment by probonopd** [comment]
Yes, you always need this structure.

**Comment by hellokejian** [comment]
thank you for helping!
