### ISSUE TITLE
not working in other than debian

### ISSUE THREAD

**Issue by tigercoding56** [probonopd/linuxdeployqt#614]
im trying to build flightgear appimage on whatever distribution this is 
![image](https://github.com/probonopd/linuxdeployqt/assets/90169211/6066e3b9-1ee0-4199-b356-c24dd80b3699)
  but i get some kind of cryptic error 
![image](https://github.com/probonopd/linuxdeployqt/assets/90169211/22399ce4-290c-4f64-90a4-52f1e3b0ba63)
pls help i am noob with linux, it will only build on a old raspberry pi 0 running whatever this is 
![image](https://github.com/probonopd/linuxdeployqt/assets/90169211/6cc7ee52-586f-4d64-9fb2-c48acd75df12)
and that is very slow , and will not run on x86 pc since ARM63

jokes aside i want to suggest adding a command line argument that internally consults cloud big data , (insert other buzzword) ,cybersecurity cool hacker AI  systems  to neurally interpolate the error into the 5th dimension and just fix the error as the linked issue  (340?) in the error message did not resolve my issue because idk what qlibc is .

**Comment by probonopd** [comment]
It's designed run on the oldest still-supported Ubuntu LTS.
