### ISSUE TITLE
Host system too new

### ISSUE THREAD

**Issue by AndyW999** [probonopd/linuxdeployqt#616]
I am trying to run this on an RPI 4 so am not able to run this on another machine.

Is there a fix?

Thanks

Andy.

**Comment by probonopd** [comment]
Use a distribution using a glibc no newer than glibc 2.31. This means a distribution no newer than from ~2020.

**Comment by AndyW999** [comment]
A bit difficult as all the system images for RPI 4 are a bit later then that.

I understand why you have done this but it is not really very helpful to those of us with no choice in the matter.

Any suggestions to an alternative, or how to fix it?

Thanks

Andy.

**Comment by nmateo** [comment]
Fedora 40 here, i use the args: `-unsupported-bundle-everything -unsupported-allow-new-glibc` and it works just fine..
Took time to find the args, this should be better indicated imo that you can use this to build with newer versions.

**Comment by AndyW999** [comment]
Thanks for that - it seems to work but I had to put -no-strip in too.

There are errors - this one lots of times.
ERROR: getBinaryRPaths: "/usr/bin/objdump: error while loading shared libraries: /home/andy/RSL/Recorder/bin/../lib/libc.so.6: file too short\n"

Have to try deploying it!

Thanks

Andy.
