### ISSUE TITLE
Not compatible with Ubuntu 24.04.

### ISSUE THREAD

**Issue by Fabiolamb** [probonopd/linuxdeployqt#620]
On Ubuntu 24.04, installing appimage prompts me to install fuse. After installing it, it says the version is too high.

**Comment by probonopd** [comment]
Works as designed.

**Comment by SlySven** [comment]
What IS the still supported oldest version though - as a colleague on the project I code for has reported https://github.com/probonopd/linuxdeployqt/issues/630 Ubuntu 20.04 is starting to be browned out here on GH and will be dropped entirely by April 2025 - see https://github.com/actions/runner-images/issues/11101 .

Yet Ubuntu 22.04 is **too new** - so there is a couple of months before projects using linuxdeployqt for GitHub projects are totally hosed and they will already be getting intermittent build failures...

**Comment by probonopd** [comment]
https://ubuntu.com/about/release-cycle, once "End of standard support" is reached, linuxdeployqt will be updated to allow the then-oldest LTS that is still in standard support.
