### ISSUE TITLE
Appimage Build Success, But Exec AppImage Error(module "Qt.labs.xxx" is not installed import xxxxx).

### ISSUE THREAD

**Issue by TimelifeCzy** [probonopd/linuxdeployqt#625]
**System**
```
Ubuntu 18
Linux virtual-machine 5.4.0-150-generic #167~18.04.1-Ubuntu SMP Wed May  UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**linuxdeqloyqt**
```
linuxdeployqt  (commit b00a83d), build 70 built on 2024-09-08 11:56:56 UTC
```

**Qt Export**
```
QMake version 3.1
Using Qt version 5.15.2 in /opt/Qt/5.15.2/gcc_64/lib

export PATH="/opt/Qt/Tools/QtCreator/bin:/opt/Qt/5.15.2/gcc_64/bin:$PATH"
export LD_LIBRARY_PATH="/opt/Qt/5.15.2/gcc_64/lib:$LD_LIBRARY_PATH"
export QT_PLUGIN_PATH="/opt/Qt/5.15.2/gcc_64/plugins:$QT_PLUGIN_PATH"
export QML2_IMPORT_PATH="/opt/Qt/5.15.2/gcc_64/qml:$QML2_IMPORT_PATH"
```

**Build AppImage Softwaer to linphone**
```
cd build
linuxdeployqt ./OUTPUT/bin/linphone -appimage --verbose=2
or
linuxdeployqt ./OUTPUT/bin/linphone -qmake="/opt/Qt/5.15.2/gcc_64/bin/qmake"  -executable-dir="/project/linphone-desktop/build/OUTPUT/lib" -qmldir="/opt/Qt/5.15.2/gcc_64/qml" -appimage -verbose=2

tree:
# ls ./OUTPUT/
bin/          cmake/        include/      lib/          mkspecs/      plugins/      share/        translations/
# ls ./OUTPUT/bin/
cjpeg              djpeg              jpegtran           linphone           qt.conf            server_config.ini

Success: 
Exportable Squashfs 4.0 filesystem, gzip compressed, data block size 131072
        compressed data, compressed metadata, compressed fragments,
        compressed xattrs, compressed ids
        duplicates are removed
Filesystem size 546740.54 Kbytes (533.93 Mbytes)
        26.10% of uncompressed filesystem size (2094773.97 Kbytes)
Inode table size 174860 bytes (170.76 Kbytes)
        36.24% of uncompressed inode table size (482492 bytes)
Directory table size 131724 bytes (128.64 Kbytes)
        38.74% of uncompressed directory table size (340061 bytes)
Number of duplicate files found 1353
Number of inodes 13047
Number of files 11346
```

**Send SIP.AppImage to another computer Ubuntu 18, exec SIP.AppImage. **
[Warning]Core:linphone: QT: components/notifier/Notifier.cpp:105: "Errors found in `Notification` component 4:" (qrc:/ui/modules/Linphone/Notifications/NotificationSnapshotWasTaken.qml:5:1: Type NotificationBasic unavailable
    NotificationBasic {
    ^, qrc:/ui/modules/Linphone/Notifications/NotificationBasic.qml:8:1: Type Notification unavailable
    Notification {
    ^, qrc:/ui/modules/Linphone/Notifications/Notification.qml:8:1: Type DesktopPopup unavailable
    DesktopPopup {
    ^, qrc:/ui/modules/Common/Popup/DesktopPopup.qml:6:1: module "Qt.labs.platform" is not installed
    import Qt.labs.platform 1.0
    ^, qrc:/ui/modules/Common/Popup/DesktopPopup.qml:5:1: module "QtQuick.Layouts" is not installed
    import QtQuick.Layouts 1.3
    ^, qrc:/ui/modules/Common/Popup/DesktopPopup.qml:4:1: module "QtQuick.Controls" is not installed
    import QtQuick.Controls 2.2
    ^, qrc:/ui/modules/Common/Popup/DesktopPopup.qml:2:1: module "QtQuick.Window" is not installed
    import QtQuick.Window 2.2
    ^, qrc:/ui/modules/Common/Popup/DesktopPopup.qml:6:1: module "Qt.labs.platform" is not installed
    import Qt.labs.platform 1.0
    ^, qrc:/ui/modules/Common/Popup/DesktopPopup.qml:5:1: module "QtQuick.Layouts" is not installed
    import QtQuick.Layouts 1.3
    ^, qrc:/ui/modules/Common/Popup/DesktopPopup.qml:4:1: module "QtQuick.Controls" is not installed
    import QtQuick.Controls 2.2
    ^, qrc:/ui/modules/Common/Popup/DesktopPopup.qml:2:1: module "QtQuick.Window" is not installed
    import QtQuick.Window 2.2
    ^, qrc:/ui/modules/Common/Popup/DesktopPopup.qml:6:1: module "Qt.labs.platform" is not installed
    import Qt.labs.platform 1.0
    ^, qrc:/ui/modules/Common/Popup/DesktopPopup.qml:5:1: module "QtQuick.Layouts" is not installed
    import QtQuick.Layouts 1.3
    ^, qrc:/ui/modules/Common/Popup/DesktopPopup.qml:4:1: module "QtQuick.Controls" is not installed
    import QtQuick.Controls 2.2
    ^, qrc:/ui/modules/Common/Popup/DesktopPopup.qml:2:1: module "QtQuick.Window" is not installed
    import QtQuick.Window 2.2
    ^, qrc:/ui/modules/Common/Popup/DesktopPopup.qml:6:1: module "Qt.labs.platform" is not installed
    import Qt.labs.platform 1.0
    ^, qrc:/ui/modules/Common/Popup/DesktopPopup.qml:5:1: module "QtQuick.Layouts" is not installed
    import QtQuick.Layouts 1.3
    ^, qrc:/ui/modules/Common/Popup/DesktopPopup.qml:4:1: module "QtQuick.Controls" is not installed
    import QtQuick.Controls 2.2
    ^, qrc:/ui/modules/Common/Popup/DesktopPopup.qml:2:1: module "QtQuick.Window" is not installed
    import QtQuick.Window 2.2
    ^)
Aborted (core dumped)

**Comment by probonopd** [comment]
You probably need to use `-qmldir=` more than once and also point it to wherever the missing imports are located.

**Comment by TimelifeCzy** [comment]
> 您可能需要多次使用，并将其指向缺少的导入所在的位置。`-qmldir=`

linuxdeployqt ./OUTPUT/bin/linphone -qmake="/opt/Qt/5.15.2/gcc_64/bin/qmake"  -executable-dir="/project/linphone-desktop/build/OUTPUT/lib" -qmldir="/opt/Qt/5.15.2/gcc_64/qml" -appimage -verbose=2

Check whether qmldir is used correctly?( -qmldir="/opt/Qt/5.15.2/gcc_64/qml" )

**Comment by TimelifeCzy** [comment]
-qmldir="/opt/Qt/5.15.2/gcc_64/qml" , Module all present.
# pwd
/opt/Qt/5.15.2/gcc_64/qml
# ls
builtins.qmltypes  QtCharts             QtInsightTracker  QtPositioning  QtQuick.2        QtSensors     QtWebEngine
Qt                 QtDataVisualization  QtLocation        QtPurchasing   QtQuick3D        QtTest        QtWebSockets
Qt3D               QtGamepad            QtMultimedia      QtQml          QtRemoteObjects  QtWayland     QtWebView
QtBluetooth        QtGraphicalEffects   QtNfc             QtQuick        QtScxml          QtWebChannel

The result is the same.

**Comment by TimelifeCzy** [comment]
See: https://github.com/probonopd/linuxdeployqt/issues/459
-qmldir="项目qt src路径"
-qmldir="My Project qt src path" (-qmldir="/project/linphone/xxxx-app/src")
not /opt/Qt/5.15.2/gcc_64/qml.

**Comment by TimelifeCzy** [comment]
See: https://github.com/probonopd/linuxdeployqt/issues/459
-qmldir="项目qt src路径"
-qmldir="My Project qt src path" (-qmldir="/project/linphone/xxxx-app/src")
not /opt/Qt/5.15.2/gcc_64/qml.
