### ISSUE TITLE
libqxcb.so rpath not set correctly, could not find or load the Qt platform plugin "xcb" in ""

### ISSUE THREAD

**Issue by probonopd** [probonopd/linuxdeployqt#64]
From https://github.com/alamminsalo/orion/issues/48#issuecomment-278030431

> The libqxcb.so rpath hadn't been set correctly.
Running `patchelf --set-rpath '$ORIGIN/../../lib' plugins/platforms/libqxcb.so`
fixed that. After that, I figured `libexec/QtWebEngineProcess` was also missing rpath set to AppImages' `/lib` path, so I set the path there by `patchelf --set-rpath '$ORIGIN/../lib libexec/QtWebEngineProcess`

Original error was:

```
me@host:~$ /home/me/Downloads/Orion-1.4.1.AppImage 
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.
Aborted
```

**Comment by supertriodo** [comment]
I have encountered this problem with my just created AppImage while testing it in another PC.

This application failed to start because it could not find or load the Qt platform plugin "xcb" in "".

**Comment by probonopd** [comment]
Does running linuxdeployqt twice on the build machine solve this for you?

**Comment by supertriodo** [comment]
No

**Comment by mohdumar644** [comment]
Having the same issue.

My AppImage seems to find xcb in the temporary mount but can't load it, for the same reason that it is trying to pick `libQt5XcbQpa.so.5` from the system (which is a different version of Qt). 

My target system is Raspbian jessie. I've built everything from scratch for armhf.

**Comment by mohdumar644** [comment]
`patchelf --set-rpath '$ORIGIN/../../lib' plugins/platforms/libqxcb.so`

This works! Should be automated for plugins.

**Comment by supertriodo** [comment]
![example](https://cloud.githubusercontent.com/assets/8259393/22826160/46d57d70-ef91-11e6-816a-0a7ab80e054c.png)

This is my build dir. From where do I execute that command? And what is $ORIGIN set to?

**Comment by mohdumar644** [comment]
You should execute from the folder shown.

**Comment by probonopd** [comment]
It is important that `$ORIGIN` must not be expanded by bash, but literally "$ORIGIN" must be put into the rpath. At the runtime, it points to the directory in which the file is located.

**Comment by supertriodo** [comment]
This is the whole process I follow to get the .AppImage

Please tell me if I'm doing anything wrong.

1) Set the path to the correct qmake version I want.
`export PATH=~/Qt/5.7/gcc_64/bin:$PATH`

2) Go to the build dir.
`cd ~/Documentos/build-ArenaTracker-Desktop-Release/`

3) First call to linuxdeployqt. It gets Error stripping "libXi.so"
`linuxdeployqt.AppImage ArenaTracker -appimage`

"/tmp/.mount_d8H4Om/usr/bin:/home/triodo/Qt/5.7/gcc_64/bin:/home/triodo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
app-binary: "ArenaTracker"
ERROR: Desktop file missing, creating a default one (you will probably want to edit it)
ERROR: Icon file missing, creating a default one (you will probably want to edit it)
ERROR: Error stripping "libXi.so" : ""
ERROR: Error stripping "libXi.so" : ""

4) Second call to linuxdeployqt. It gets Error stripping "libpng12.so"
`linuxdeployqt.AppImage ArenaTracker -appimage`

"/tmp/.mount_l1p39i/usr/bin:/home/triodo/Qt/5.7/gcc_64/bin:/home/triodo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
app-binary: "ArenaTracker"
ERROR: Error stripping "libpng12.so" : ""
ERROR: Error stripping "libpng12.so" : ""

5) Third call to linuxdeployqt. It gets Error stripping "libpng12.so". As it gives me the same error I don't repeat the call to linuxdeployqt.
`linuxdeployqt.AppImage ArenaTracker -appimage`

"/tmp/.mount_x2kC6w/usr/bin:/home/triodo/Qt/5.7/gcc_64/bin:/home/triodo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
app-binary: "ArenaTracker"
ERROR: Error stripping "libpng12.so" : ""
ERROR: Error stripping "libpng12.so" : ""

6) Fix qxcb bug.
`patchelf --set-rpath '$ORIGIN/../../lib' plugins/platforms/libqxcb.so`

7) Create AppImage.
`appimagetool .`

WARNING: appstreamcli is missing, please install it if you want to use AppStream metadata
WARNING: appstream-util is missing, please install it if you want to use AppStream metadata
Arch: 86_64
DESTINATION not specified, so assuming Application-x86_64.AppImage
/home/triodo/Documentos/build-ArenaTracker-Desktop-Release should be packaged as Application-x86_64.AppImage
Deleting pre-existing .DirIcon
Creating .DirIcon symlink based on information from desktop file
WARNING: AppStream upstream metadata is missing, please consider creating it
         in usr/share/metainfo/default.appdata.xml
         Please see https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps
         for more information.
Generating squashfs...
Parallel mksquashfs: Using 8 processors
Creating 4.0 filesystem on Application-x86_64.AppImage, block size 131072.
[=====================================================================================================\] 716/716 100%

Exportable Squashfs 4.0 filesystem, gzip compressed, data block size 131072
	compressed data, compressed metadata, compressed fragments, no xattrs
	duplicates are removed
Filesystem size 30832.99 Kbytes (30.11 Mbytes)
	39.43% of uncompressed filesystem size (78186.91 Kbytes)
Inode table size 3461 bytes (3.38 Kbytes)
	48.77% of uncompressed inode table size (7097 bytes)
Directory table size 1586 bytes (1.55 Kbytes)
	43.96% of uncompressed directory table size (3608 bytes)
Number of duplicate files found 2
Number of inodes 146
Number of files 140
Number of fragments 27
Number of symbolic links  2
Number of device nodes 0
Number of fifo nodes 0
Number of socket nodes 0
Number of directories 4
Number of ids (unique uids + gids) 1
Number of uids 1
	root (0)
Number of gids 1
	root (0)
Embedding ELF...
Marking the AppImage as executable...
Success

**Comment by probonopd** [comment]
Also see https://github.com/alamminsalo/orion/issues/48

**Comment by supertriodo** [comment]
Following the 7-step process described in my previous comment still has the same problem.

This application failed to start because it could not find or load the Qt platform plugin "xcb" in "".

**Comment by probonopd** [comment]
If you upload your AppDir or AppImage somewhere, I can have a look at it.

**Comment by supertriodo** [comment]
AppImage without patchelf fix [here](https://drive.google.com/file/d/0B7S6qjtH-56hMjdaLWFNdUNMR28/view)

AppImage with patchelf fix [here](https://drive.google.com/file/d/0B7S6qjtH-56hTWU0blJqUk9aZUk/view)

Thx

**Comment by probonopd** [comment]
Let's investigate:

```
# Let's mount the AppImage

$ /home/me/Downloads/Application-x86_64-pathelf.AppImage --appimage-mount
/tmp/.mount_Xnh6ai # Different on each invocation

# Let's see what might prevent libqxcb.so from loading

me@host ~ $ ldd /tmp/.mount_Xnh6ai/plugins/platforms/libqxcb.so | grep found
/tmp/.mount_Xnh6ai/plugins/platforms/libqxcb.so: /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5: version `Qt_5' not found (required by /tmp/.mount_Xnh6ai/plugins/platforms/../../lib/)

# So it seems like libqxcb.so in the AppImage is trying to load
# libQt5DBus.so.5 from the system rather than from inside the AppImage,
# which is wrong. Let's check:

$ ldd /tmp/.mount_Xnh6ai/plugins/platforms/libqxcb.so | grep "libQt" | grep "=> /usr"
	libQt5DBus.so.5 => /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5 (0x00007f265e3e5000)

# Ouch yes, that is wrong!
# So the question is, what requires libQt5DBus.so.5 and why did linuxdeployqt
# not detect that libQt5DBus.so.5 is needed, and deploy it into the AppImage

$ grep -r libQt5DBus.so.5 /tmp/.mount_Xnh6ai/
Binary file /tmp/.mount_Xnh6ai/lib/libQt5XcbQpa.so.5 matches
Binary file /tmp/.mount_Xnh6ai/plugins/platforms/libqxcb.so matches

# So the question is, why didn't linuxdeployqt notice that libqxcb.so
# and libQt5XcbQpa.so.5 require libQt5DBus.so.5, and deploy libQt5DBus.so.5
# into the AppImage at that point? This is what puzzles me.
```

**Comment by neuro-sys** [comment]
I just had the same problem:

```
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in ""
```

**Comment by probonopd** [comment]
@neuro-sys which version of linuxdeployqt did you use, and can you provide your AppImage/AppDir for debugging?

**Comment by neuro-sys** [comment]
I just now used the last Release version from your github page, and here's the produced AppImage

https://drive.google.com/file/d/0BxIQVP1zErDPYlMwQUthVnF0TGc/view?usp=sharing

**Comment by probonopd** [comment]
@neuro-sys which system did you produce this on? I get 

```
AppRun: error while loading shared libraries: libpng16.so.16: cannot open shared object file: No such file or directory   
```

`libpng16.so.16`? Never heard of that. Please use debian oldstable, or Ubuntu trusty or older, to compile.

**Comment by neuro-sys** [comment]
@probonopd

I compiled this on `Linux neurosys-laptop 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux` which is Arch Linux.

**Comment by probonopd** [comment]
@neuro-sys If you use a rolling release distro like Arch, you are guaranteed that no users of older distributions (like on-rolling ones) can run your binaries, because you have dependencies on "too new" library versions. Better use e.g., a debian stable/oldstable or Ubuntu 14.04 Live CD or VM.

**Comment by neuro-sys** [comment]
Is it not possible to put **all** dynamically linked shared libraries (recursively) into the bundle, though? In my case, including `libpng16.so.16`?

**Comment by probonopd** [comment]
Even if we bundled `libpng16.so.16` that wouldn't solve the fundamental issue that by compiling on a very new build system, you are pulling in dependencies on very new library versions of system-provided, very basic libraries such as `glibc`. Hence I suggest you build e.g., on `trusty` on [Travis CI](https://travis-ci.org/).

**Comment by probonopd** [comment]
@carlos22 yes that would also be my suspicion. Where is your Qt installed, I wonder why you didn't get the warning about system Qt not being supported yet. Want to give a hand at implementing #79?

**Comment by carlos22** [comment]
@probonopd I got the warning, but only when using the latest continuous build - not with the release version (v3). Happy to give a hand, but I'm not really sure how to implement this - never used patchelf for such a thing.

**Comment by probonopd** [comment]
Yes, the warning was added only recently.

This is not something for `patchelf` but essentially we would need to find out what the default value should be for each of the mentioned ones in #79, and patch all of them along the lines of what we are doing [here](https://github.com/probonopd/linuxdeployqt/blob/af8d32bb8f2996dbaad5b42ce772e21f0778741f/shared/shared.cpp#L1203-L1292) already (e.g., convert this into a function that is called for each of the qt_* variables in the ticket, along with a suitable replacement. Would be really great if you could give that a go @carlos22

**Comment by carlos22** [comment]
I think the problem in my case (archlinux) is that the `qt_plugpath` is NOT set. Therefore it is also not patched - correct? Thats why it works with a qt.conf. So in this case we would need to add the plugpath (with plugins as value).

**Comment by probonopd** [comment]
No you don't need it. In this case, the Qt-wide default is qml inside qt_prfxpath. At lest, this is how I _think_ this works given the scarce information ;-)

**Comment by carlos22** [comment]
But why doesn't it work? `qt_prfxpath` is set to `'.'`. It's not qml that is not working - it is the platform plugin xcb... 

system version:
```
> strings /usr/lib/libQt5Core.so.5 | grep qt_ | grep = 
qt_prfxpath=/usr
qt_instdate=2012-12-20
```
patched version:
```
strings libQt5Core.so.5 | grep qt_ | grep =
qt_prfxpath=.
qt_instdate=2012-12-20
```

So the default should be ./plugins - but that is not working unless i put the qt.conf above (which also only configures 'plugins')...

**Comment by probonopd** [comment]
Sorry I meant the default is `plugins/platforms/libqxcb.so` inside `qt_prfxpath`.

**Comment by carlos22** [comment]
Ok. But that should work, right?
And if the default is good and all relative to prfxpath - the removal of the definitions would be best, but is not easy right?

**Comment by probonopd** [comment]
Well I think there is a difference between a `qt_*` not being there at all, versus it being set (patched) to `0x00`s. Need to study Qt's scarce documentation, and experiment. At least that's what I had to do for the one or two `qt_*` I handle so far...

**Comment by carlos22** [comment]
Ok, thats what i suspected.
Might it be possible that in my case a qt.conf (from /etc for example) is used and causes the problem?

**Comment by carlos22** [comment]
Hmm, another strange thing is: It doesn't matter if the `qt.conf` is a 0-byte file or it has real values. If the file is present - it works, otherwise not. This kind of supports the idea that another `qt.conf` is used in case there is none in the same folder as the binary.

**Comment by carlos22** [comment]
The qt.conf seems to be loaded here: https://github.com/qt/qtbase/blob/ad4f7b59ead6c4eb17e787bce25a7211b866063f/src/corelib/global/qlibraryinfo.cpp#L172

This seems to explain the 0-byte behaviour: https://github.com/qt/qtbase/blob/ad4f7b59ead6c4eb17e787bce25a7211b866063f/src/corelib/global/qlibraryinfo.cpp#L155

`havePaths` - needs to be true that it works in the case of no strings.

A workaround for me might be the addition of a `qt.conf` in the resources system. For a general fix i think the qt.conf is crucial...

**Comment by probonopd** [comment]
Thanks for investigating this @carlos22, makes sense to me. So, in other words, unless we want to go back to using `qt.conf` either inside the AppImage or outside the AppImage, we need to implement #79.

Which is what I think what we should do, because:
* Needing to mess around with `qt.conf` outside of the AppImage violates the AppImage principle that the user does not need to touch the base system for the AppImage to work
* Needing a `qt.conf` inside the AppImage is a) not as elegant and b) we would need one in ever location where an exectuable is located (this is a lot of work to ensure for each AppImage and can easily lead to bugs if it is forgotten, e.g., for a helper app in usr/libexec)

**Comment by carlos22** [comment]
@probonopd yes a totally agree with the reasons for implementing #79. But in my case (archlinux qt-libs) i don't see a solution to avoid `qt.conf` unless we can inject `qt_plugpath`.

**Comment by probonopd** [comment]
What happens if you set the ones you have like you have suggested [here](https://github.com/probonopd/linuxdeployqt/issues/79#issuecomment-288966150)?

**Comment by carlos22** [comment]
The problem is that i cannot set them because they are not present in the .so file. See:
```
> strings /usr/lib/libQt5Core.so.5 | grep qt_ | grep = 
qt_prfxpath=/usr
qt_instdate=2012-12-20
```
The only one present is `qt_prfxpath`. Thats why the suggestions in #79 do not help in my (archlinux qt-libs) case. Anyway is it a good idea to patch all if they are present.

**Comment by probonopd** [comment]
OK, and you are saying just patching `qt_prfxpath` is not sufficient in your case. Tough question, I think we need the help of some Qt gurus here then...

**Comment by probonopd** [comment]
Again, I don't think building on a rolling release distro like Arch is a good idea at all because it means that your application will run only on the latest distributions. Much better to use a LTS release (e.g., the oldest that is still supported and your code still runs on). 

That being said, we may need to patch away `qt.conf` and `Trolltech.conf` loading in our bundled Qt, so that it loads those only from within but not from without the AppDir. Does this make sense?

**Comment by probonopd** [comment]
The original issue of this ticket may be fixed in linuxdeployqt trunk with b71bd4d and bace185. @supertriodo @mohdumar644 please retry with the latest continuous build of linuxdeployqt.

**Comment by probonopd** [comment]
@supertriodo @mohdumar644 please comment here to reopen if the problem persists in the latest continuous build of linuxdeployqt when using a distribution _other than_ Arch Linux or openSUSE.

**Comment by supertriodo** [comment]
Bundled with the latest linuxdeployqt and appimagetool from continuous build releases. Waiting for someone with a virgin pc [to test it](https://www.reddit.com/r/ArenaTracker/comments/63d4c5/linux_users_test_this/).

**Comment by probonopd** [comment]
@supertriodo launches beautifully on 

* elementaryos-0.4-stable-amd64.20160921.iso
* Fedora-Workstation-Live-x86_64-24-1.2.iso
* Fedora-Workstation-Live-x86_64-25-20161105.n.0.iso
* linuxmint-18-cinnamon-64bit.iso
* maui-2.1-64bit.iso
* neon-devedition-gitunstable-20170326-0806-amd64.iso
* ubuntu-16.04-desktop-amd64.iso
* xubuntu-16.04.1-desktop-amd64.iso

but it asks for a `config.log` file which I don't have.

Does __not__ work on

* CentOS-7-x86_64-LiveGNOME-1511.iso
* debian-live-8.6.0-amd64-xfce-desktop.iso
* linuxmint-17.3-cinnamon-64bit.iso

Consider building on an older system (e.g., debian oldstable) if you want to support those too

**Comment by supertriodo** [comment]
That's really good news. It looks for your installation of Hearthstone that you don't have, that's why it's complaining.

Thx for this amazing tool!

**Comment by supertriodo** [comment]
https://github.com/supertriodo/Arena-Tracker/issues/44

People seem to still have problems with xcb.

**Comment by probonopd** [comment]
> Ubuntu 17.10 I'm trying to make Appimage

Please use 14.04 LTS as described in the documentation.
