### ISSUE TITLE
How to include dynamically loaded libraries in Lua?

### ISSUE THREAD

**Issue by vadi2** [probonopd/linuxdeployqt#67]
My application embeds a Lua runtime which in turn loads some C modules, and this'll never show up on ldd. How can I manually specify that these C modules should be included in the image?

**Comment by probonopd** [comment]
Right now your best bet is to
1. Run linuxdeployqt
2. Copy the extra C modules in manually
3. Run linuxdeployqt again 
I have not tested this but can imagine it could work. Possibly you have to set rpaths manually with `patchelf`.

**Comment by probonopd** [comment]
Just in case you already have a [PPA](https://launchpad.net/~mudlet-makers/+archive/ubuntu/ppa) for trusty or earlier, the easiest way would be to use that as ingredients and convert it into an AppImage.

**Comment by vadi2** [comment]
Where should I copy the modules? I put them into /lib, but it did not seem to have any effect. If that's the right location, how would I use patchelf?

There is a PPA but it's based on a Qt4-version of the software and is rather old. Needs to be updated.

**Comment by probonopd** [comment]
What loads them, and how?

**Comment by vadi2** [comment]
Lua loads them ([documentation](https://www.lua.org/pil/8.2.html)), and if I put my modules into the same folder as binary and do ``export LD_LIBRARY_PATH=$PWD:$LD_LIBRARY_PATH`` in my startup script, it finds them.

**Comment by probonopd** [comment]
OK then it should work if you put them in `usr/lib` in the AppImage, and set the rpath using patchelf on the library/lua that loads them. What is the exact file that does the loading?

**Comment by vadi2** [comment]
I don't have ``usr/lib`` but I do have ``lib/``, do you mean that? It's the ``mudlet`` binary that does the loading.

**Comment by probonopd** [comment]
Yes. in this case, run in the directory in which `mudlet` resides:

```
patchelf --set-rpath '$ORIGIN/lib' mudlet
```

$ORIGIN at runtime points to the directory in which the binary or library is located. So the above means "load libraries from the lib directory in the same directory as the mudlet binary".

In case you can't get it to work, please upload the AppImage or zipped directory somewhere so that I can have a look at it.

**Comment by vadi2** [comment]
Oh, yes you would be right. it's liblua that gets loaded by Mudlet that does the loading - so patchelf on the mudlet binary obviously didn't do much. However, Lua by default already searches in the current working directory when loading files, so no patching should be needed. The module search path is also configurable at runtime so I'm happy to add code to whatever AppImage would like to see.

[This](ufile.io/cadac) is my current working directory. ``build/`` is where I'm trying to assemble to appimage. ``src/`` is where the mudlet binary gets compiled. [This link](https://uploadfiles.io/296ab) contains the extra libraries that are loaded by Lua - to see if they are loaded, launch the application, press Connect, select any game icon and you should not have error messages about loading libraries on top.

**Comment by probonopd** [comment]
The current working directory is the directory in which the user is when calling the AppImage. Obviously the libraries won't be there. Can you change the logic to load the libraries from a path relative to the main executable?

**Comment by vadi2** [comment]
You can confirm Lua loads modules relative in the binary's directory already by copying the [modules](https://uploadfiles.io/296ab) into the ``build/`` folder and running the mudlet binary that's present there - there'll be no errors.

**Comment by vadi2** [comment]
I can, what should I set it to?

**Comment by probonopd** [comment]
> You can confirm Lua loads modules relative in the binary's directory already by copying the modules into the build/ folder and running the mudlet binary that's present there - there'll be no errors.

Also if you do a `cd ..` and then call the binary? If that works, then it should work in the AppImage too...

**Comment by vadi2** [comment]
That doesn't work.

**Comment by probonopd** [comment]
So you need to make it load libraries from the directory in which the executable is, or the `lib/` subdirectory, in addition to the current working directory. I have no clue about Lua, sorry.

**Comment by vadi2** [comment]
I'd need to know what's the directory then that AppImage creates in order to add a relative search path.

**Comment by vadi2** [comment]
Hmm, this was easy with a .desktop + shell script combination which set the pwd for me. I'll need to think about how to find out the executables directory from inside my application then.

**Comment by probonopd** [comment]
Seems like http://lua-users.org/lists/lua-l/2010-04/msg00693.html has some hints.

**Comment by vadi2** [comment]
I can set the searchpath from inside the C++ application, it doesn't have to be within Lua. That might be an easier search...

**Comment by probonopd** [comment]
See https://github.com/limbahq/binreloc

**Comment by vadi2** [comment]
Thanks, with that link I've arrived at [QCoreApplication::applicationDirPath()](http://doc.qt.io/qt-5/qcoreapplication.html#applicationDirPath) which seems like it would help. If I tell Lua to search in that directory, theoretically it should find the C modules.

**Comment by probonopd** [comment]
Looks promising. Be sure to include your app on https://github.com/probonopd/AppImageKit/wiki/AppImages once it is available.

**Comment by vadi2** [comment]
I've got most of the Lua libraries to work save for one:

```
[ ERROR ] - Cannot find Lua module zip.
            Lua error:error loading module 'zip' from file '/tmp/.mount_kmQgz5/lib/zip.so':
                    libzzip-0.so.13: cannot open shared object file: No such file or directory
```

I think zip.so is loading libzzip-0.so.13, and I've already ran ``patchelf --set-rpath '$ORIGIN/lib' zip.so``. Any ideas?

**Comment by vadi2** [comment]
[This topic](http://ogre3d.org/forums/viewtopic.php?f=2&t=7785) mentions that ldconfig fixes the issue, if that helps. [LuaZip](https://github.com/luaforge/luazip) is the library I'm trying to get to work.

**Comment by probonopd** [comment]
Looks like it tries to load `lib/zip.so` from inside the AppImage, and this needs `libzzip-0.so.13` which it doesn't find. So you need to patch `lib/zip.so` so that it searches for `libzzip-0.so.13` in the same directory as itself, a.k.a. `$ORIGIN`.

Like so:

```
patchelf --set-rpath '$ORIGIN' lib/zip.so
```

That's my best guess, anyways.

**Comment by vadi2** [comment]
Good guess, thanks!
