### ISSUE TITLE
How to bundle data with application?

### ISSUE THREAD

**Issue by vadi2** [probonopd/linuxdeployqt#68]
My application reads several times in at runtime - how can I bundle those files to be included in the AppImage?

**Comment by probonopd** [comment]
Just copy them into the directory in which your application resides, or a subdirectory of it, and read from a path relative to your binary.

**Comment by vadi2** [comment]
Alright. The fact that the current directory isn't set to the binary directory but to the appimage file requires extra work on my part to make use of this deployment mechanism. Appreciate your help in this though
