### ISSUE TITLE
[showstopper] [fhs-like mode] Qt platform plugin "xcb" missing

### ISSUE THREAD

**Issue by probonopd** [probonopd/linuxdeployqt#75]
Running `QtCreator-5.8.0-x86_64.AppImage` on `ubuntu-16.04-desktop-amd64.iso` and then doing

```
git clone --recursive https://github.com/LibrePCB/LibrePCB.git && cd LibrePCB
export PATH=/tmp/.mount_QtCreator-5.8.0-x86_64/5.8/gcc_64/bin/:$PATH
qmake -r ../librepcb.pro
sudo apt-get install libglu1-mesa-dev openssl zlib1g zlib1g-dev
make -j 8
mkdir -p LibrePCB.AppDir/usr
cp -r generated/unix  LibrePCB.AppDir/usr/bin
cp -r generated/{lib,share}  LibrePCB.AppDir/usr/
wget -c https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
chmod a+x linuxdeployqt-continuous-x86_64.AppImage 
./linuxdeployqt-continuous-x86_64.AppImage ./LibrePCB.AppDir/usr/bin/librepcb 
```

results in:

```
me@host:~/LibrePCB/build$ ./linuxdeployqt-continuous-x86_64.AppImage /home/me/LibrePCB/build/LibrePCB.AppDir/usr/bin/librepcb 
"/tmp/.mount_W7rCgi/usr/bin:/tmp/.mount_QtCreator-5.8.0-x86_64/5.8/gcc_64/bin/:/tmp/.mount_QtCreator-5.8.0-x86_64/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
app-binary: "/home/me/LibrePCB/build/LibrePCB.AppDir/usr/bin/librepcb"
FHS-like mode with PREFIX, fhsPrefix: "/home/me/LibrePCB/build/LibrePCB.AppDir/usr"
appDirPath: "/home/me/LibrePCB/build/LibrePCB.AppDir"
relativeBinPath: "usr/bin/librepcb"
ERROR: ldd outputLine: "\tlibmysqlclient.so.18 => not found"
ERROR: ldd outputLine: "\tlibssl.so.10 => not found"
ERROR: ldd outputLine: "\tlibcrypto.so.10 => not found"
ERROR: ldd outputLine: "\tlibpq.so.5 => not found"

me@host:~/LibrePCB/build$ ./LibrePCB.AppDir/AppRun 
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Reinstalling the application may fix this problem.
Aborted
```

This is because the `plugins/` directory has been generated in the top-level directory of the AppImage but `qt.conf` does not point there. A workaround is to move it to `usr/bin` where `qt.conf` resides.

**Comment by probonopd** [comment]
So where should `linuxdeployqt` put the `plugins` directory in fhs-like mode? `QtCreator-5.8.0-x86_64.AppImage` has it in `Tools/QtCreator/lib/Qt/plugins/`, so I think `usr/lib/Qt/plugins` might be appropriate?

**Comment by ubruhin** [comment]
> Which would probably mean that in FHS-like mode, we should set prefix = ../lib/Qt and leave the rest of qt.conf as-is, and move the plugins/ directory to usr/lib/Qt/plugins.

Looks good, the only thing I would change is to make `Qt` lowercase, i.e. `/usr/lib/qt/plugins` ;)

**Comment by probonopd** [comment]
Argh. Moving around stuff tends to break other stuff. E.g., 
```
me@host:~/LibrePCB/build/LibrePCB.AppDir$ /isodevice/Applications/patchelf --print-rpath  plugins/platforms/libqxcb.so 
$ORIGIN/../../lib
```
is wrong for FHS-like mode...

**Comment by ubruhin** [comment]
I wonder if a non-FHS-like mode is even required? Always using FHS would make the application simpler and thus less error-prone...

**Comment by probonopd** [comment]
Not all Qt applications can be installed to a FHS-like structure; in fact, that's the default case with Qt Creator.

**Comment by probonopd** [comment]
So actually Qt Creator uses a slightly different "FHS-like" structure; there is no dedicated lib/qt directory, but the subdirectories of the qt directory are right inside the qt_prfxpath, where bin/ and lib/ also are.

In other words, it looks like we should set qt_prfxpath to usr/ and put plugins/ etc. in ust/ too.

```
me@host:~/foo$ strings /tmp/.mount_QtCreator-5.8.0-x86_64/5.8/gcc_64/lib/libQt5Core.so.5 | grep qt_
qt_prfxpath=/tmp/.mount_QtCreator-5.8.0-x86_64/5.8/gcc_64

me@host:~/foo$ ls /tmp/.mount_QtCreator-5.8.0-x86_64/5.8/gcc_64
bin  include  libexec  phrasebooks  qml        translations
doc  lib      mkspecs  plugins      resources

```

**Comment by probonopd** [comment]
As per the tests, the  `tests/QtWidgetsApplication/QtWidgetsApplication.pro` example application gets bundled correctly in FHS-like mode, hence closing here. Please open individual tickets for remaining issues with FHS-like mode.

**Comment by probonopd** [comment]
Succeeded in making a LibrePCB AppImage like this:

git clone --recursive https://github.com/LibrePCB/LibrePCB.git && cd LibrePCB
export PATH=/tmp/.mount_QtCreator-5.8.0-x86_64/5.8/gcc_64/bin/:$PATH
qmake -r ../librepcb.pro
sudo apt-get install libglu1-mesa-dev openssl zlib1g zlib1g-dev
make -j 8
mkdir -p LibrePCB.AppDir/usr
cp -r generated/unix  LibrePCB.AppDir/usr/bin
cp -r generated/{lib,share}  LibrePCB.AppDir/usr/
wget -c https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
chmod a+x linuxdeployqt-continuous-x86_64.AppImage 
./linuxdeployqt-continuous-x86_64.AppImage ./LibrePCB.AppDir/usr/bin/librepcb
( cd LibrePCB.AppDir/ ; cp ./usr/share/applications/librepcb.desktop . )
( cd LibrePCB.AppDir/ ; cp ./usr/share/pixmaps/librepcb.svg . )
export VERSION=$(git rev-list --count HEAD).$(git describe --tags | cut -d - -f 3)
./linuxdeployqt-continuous-x86_64.AppImage ./LibrePCB.AppDir/usr/bin/librepcb -appimage
ls LibrePCB*AppImage
# LibrePCB-864.gf0d32a2-x86_64.AppImage

**Comment by ubruhin** [comment]
Very nice!

> Note that no wrapper script, no LD_LIBRARY_PATH, and no qt.conf file are used.

Does this also solve the problem with sourcing `/opt/qt57/bin/qt57-env.sh`?

**Comment by probonopd** [comment]
No, but I am not sure that this is a "problem" actually. Just unset the variables set by `/opt/qt57/bin/qt57-env.sh` prior to running `linuxdeployqt`. I think these variables are just doing their job, as they would with any other Qt application. Or am I wrong here?

**Comment by ubruhin** [comment]
With the release `linuxdeployqt-3-x86_64.AppImage` I still get this error when using Qt5.2 on Travis:
```
This application failed to start because it could not find or load the Qt platform plugin "xcb".
```

Here is my AppImage: https://bintray.com/librepcb/LibrePCB-Nightly/download_file?file_path=LibrePCB-Nightly-Linux-x86_64.AppImage

And here is the build output: https://travis-ci.org/LibrePCB/LibrePCB/jobs/203230997#L2705

When using Qt5.7 from a PPA, it works properly.

**Comment by probonopd** [comment]
For some weird reason that I don't understand yet, the following workaround is needed:

```
( cd opt/bin/ ;  ln -s ../plugins/platforms/ . ; cd - )
patchelf --set-rpath '$ORIGIN/../../lib:$ORIGIN' ./opt/plugins/platforms/libqxcb.so
patchelf --set-rpath '$ORIGIN/../../lib:$ORIGIN' ./opt/plugins/bearer/libqnmbearer.so 
patchelf --set-rpath '$ORIGIN/../../lib:$ORIGIN' ./opt/plugins/bearer/libqconnmanbearer.so 
patchelf --set-rpath '$ORIGIN/../../lib:$ORIGIN' ./opt/plugins/sqldrivers/libqsqlite
```
And it still fails to load the database. Is there a particular reason you don't use Qt 5.8?

**Comment by ubruhin** [comment]
With Qt5.2 from Ubuntu repository: `qt_plugpath=/usr/lib/x86_64-linux-gnu/qt5/plugins`

With Qt5.7 from PPA: `qt_prfxpath=..`

**Comment by probonopd** [comment]
Thanks for verifying @ubruhin 

Let's see if https://github.com/probonopd/linuxdeployqt/commit/3aca9d5c9beb829f23c7a64f9071e6bb3e01604a changes this.

**Comment by ubruhin** [comment]
Yes, the plugpath is now cleared (`qt_plugpath=`), but the AppImage still fails to start with the same error message (xcb missing) :( Shouldn't the path be set to ".."?

**Comment by probonopd** [comment]
Do you have `qt_prfxpath=..`?

**Comment by probonopd** [comment]
Please run with `export SET QT_DEBUG_PLUGINS=1`

**Comment by ubruhin** [comment]
```
$ export SET QT_DEBUG_PLUGINS=1
$ ./LibrePCB-Nightly-Linux-x86_64.AppImage 
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_V3eHXv/opt/bin/platforms" ... 
This application failed to start because it could not find or load the Qt platform plugin "xcb".
```

Obviously is the plugins path wrong, it isn't located inside the `bin` directory [as shown here](https://travis-ci.org/LibrePCB/LibrePCB/jobs/203268328#L2705).

**Comment by probonopd** [comment]
Thanks, can you confirm you have `qt_prfxpath=..` in `libQt5Core.so.5`?

**Comment by ubruhin** [comment]
As I wrote above, `qt_prfxpath` isn't set so `..` but cleared completely. This is also what the [implementation](https://github.com/probonopd/linuxdeployqt/commit/3aca9d5c9beb829f23c7a64f9071e6bb3e01604a#diff-c7aa376d303f54d2cc574b534fea2539R1268) looks like to do.

**Comment by probonopd** [comment]
`qt_plugpath` and `qt_prfxpath` are two separate things...

**Comment by probonopd** [comment]
Trying https://github.com/probonopd/linuxdeployqt/commit/b32682ba8ef46406daf45f08c350c46e2abf8d20, the next continuous build should have it. Please test

**Comment by probonopd** [comment]
Btw, we are on #AppImage on irc.freenode.net

**Comment by ubruhin** [comment]
Oops, I didn't realize that we discuss about two different paths :open_mouth: 

Qt5.2 from Ubuntu repository: `qt_prfxpath` isn't set(?)
Qt5.7 from PPA: `qt_prfxpath=..`

**Comment by probonopd** [comment]
Are you really sure? Please run
```
strings opt/lib/libQt5Core.so.5 | grep qt_p | grep =
# qt_prfxpath=..
# qt_plugpath=
```

**Comment by probonopd** [comment]
New https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage is available

**Comment by ubruhin** [comment]
> Are you really sure?

Here the `strings` command: https://travis-ci.org/LibrePCB/LibrePCB/jobs/203268328#L2454

And here its output: https://travis-ci.org/LibrePCB/LibrePCB/jobs/203268328#L2829

Bot now I need some sleep... ;)

**Comment by probonopd** [comment]
Now that is really strange. Could it be a Qt bug, even? Why is it not 

```
me@host:~/deleteme$ export SET QT_DEBUG_PLUGINS=1
me@host:~/deleteme$ ./squashfs-root/AppRun 
QFactoryLoader::QFactoryLoader() checking directory path "/home/me/deleteme/squashfs-root/opt/bin/platforms" ... 
This application failed to start because it could not find or load the Qt platform plugin "xcb".

me@host:~/deleteme$ strings ./squashfs-root/opt/lib/libQt5Core.so.5 | grep qt_p | grep =
qt_prfxpath=..
qt_plugpath=../plugins
```

Why doesn't it appear to use these paths?

**Comment by probonopd** [comment]
Omg, more strings to be patched in the distribution-provided one:

```
qt_

- stngpath=/etc/xdg
- qt_prfxpath=..
- qt_docspath=/usr/share/qt5/doc
- qt_hdrspath=/usr/include/qt5
- qt_libspath=/usr/lib/x86_64-linux-gnu
- qt_lbexpath=/usr/lib/x86_64-linux-gnu/qt5/libexec
- qt_binspath=/usr/lib/x86_64-linux-gnu/qt5/bin
- qt_plugpath=../plugins # May be wrong, plugins?
- qt_impspath=/usr/lib/x86_64-linux-gnu/qt5/imports
- qt_qml2path=/usr/lib/x86_64-linux-gnu/qt5/qml
- qt_adatpath=/usr/lib/x86_64-linux-gnu/qt5
- qt_datapath=/usr/share/qt5
- qt_trnspath=/usr/share/qt5/translations
- qt_xmplpath=/usr/lib/x86_64-linux-gnu/qt5/examples
- qt_tstspath=/usr/te

sts
```

**Comment by probonopd** [comment]
Just patching away `qt_plugpath` entirely does _not_ help:
`sed -i -e  's|qt_plugpath|xx_plugpath|g' opt/lib/libQt5Core.so.5`

So we need to set it to a sensible value.

**Comment by probonopd** [comment]
I think the original issue of this ticket should be solved now (no more `Qt platform plugin "xcb" missing` with the latest continous build, even using the distro-provided Qt).

I think for LibrePCB you still need to run
```
patchelf --set-rpath '$ORIGIN/../../lib:$ORIGIN' ./opt/plugins/platforms/libqxcb.so
patchelf --set-rpath '$ORIGIN/../../lib:$ORIGIN' ./opt/plugins/bearer/libqnmbearer.so 
patchelf --set-rpath '$ORIGIN/../../lib:$ORIGIN' ./opt/plugins/bearer/libqconnmanbearer.so 
patchelf --set-rpath '$ORIGIN/../../lib:$ORIGIN' ./opt/plugins/sqldrivers/libqsqlite.so
```

which is a separate issue. Hence closing here. Feel free to comment if you think otherwise.
