### ISSUE TITLE
Patch hardcoded absolute qt_ paths

### ISSUE THREAD

**Issue by probonopd** [probonopd/linuxdeployqt#79]
__This ticket does _not_ affect Qt builds from the [beineri ppas](https://launchpad.net/~beineri), which I recommend for building on Travis CI__ (verified with Qt 5.8 for trusty from the ppa).

`strings libQt5Core.so.5 | grep qt_ | grep = | cut -d "=" -f 1` reveals on a distribution-provided libQt5Core (Qt 5.2 from Ubuntu trusty repository) that there are many hardcoded absolute paths that we may need to change:

- qt_stngpath
- qt_prfxpath
- qt_docspath
- qt_hdrspath
- qt_libspath
- qt_lbexpath
- qt_binspath
- qt_plugpath
- qt_impspath
- qt_qml2path
- qt_adatpath
- qt_datapath
- qt_trnspath
- qt_xmplpath
- qt_tstspath

**Comment by probonopd** [comment]
According to https://patchwork.openembedded.org/patch/87519/ there is even more:

```
+-    "qt_prfxpath=$QT_INSTALL_PREFIX",
+-    "qt_docspath=$QT_INSTALL_DOCS",
+-    "qt_hdrspath=$QT_INSTALL_HEADERS",
+-    "qt_libspath=$QT_INSTALL_LIBS",
+-    "qt_lbexpath=$QT_INSTALL_LIBEXECS",
+-    "qt_binspath=$QT_INSTALL_BINS",
+-    "qt_plugpath=$QT_INSTALL_PLUGINS",
+-    "qt_impspath=$QT_INSTALL_IMPORTS",
+-    "qt_qml2path=$QT_INSTALL_QML",
+-    "qt_adatpath=$QT_INSTALL_ARCHDATA",
+-    "qt_datapath=$QT_INSTALL_DATA",
+-    "qt_trnspath=$QT_INSTALL_TRANSLATIONS",
+-    "qt_xmplpath=$QT_INSTALL_EXAMPLES",
+-    "qt_tstspath=$QT_INSTALL_TESTS",
+-    "qt_ssrtpath=$CFG_SYSROOT",
+-    "qt_hpfxpath=$QT_HOST_PREFIX",
+-    "qt_hbinpath=$QT_HOST_BINS",
+-    "qt_hlibpath=$QT_HOST_LIBS",
+-    "qt_hdatpath=$QT_HOST_DATA",
+-    "qt_ebinpath=$QT_EXTERNAL_HOST_BINS",
+-    "qt_targspec=$shortxspec",
+-    "qt_hostspec=$shortspec",
++    "qt_prfxpath=$QT_SYSROOT_PREFIX",
++    "qt_docspath=$QT_SYSROOT_DOCS",
++    "qt_hdrspath=$QT_SYSROOT_HEADERS",
++    "qt_libspath=$QT_SYSROOT_LIBS",
++    "qt_lbexpath=$QT_SYSROOT_LIBEXECS",
++    "qt_binspath=$QT_SYSROOT_BINS",
++    "qt_plugpath=$QT_SYSROOT_PLUGINS",
++    "qt_impspath=$QT_SYSROOT_IMPORTS",
++    "qt_qml2path=$QT_SYSROOT_QML",
++    "qt_adatpath=$QT_SYSROOT_ARCHDATA",
++    "qt_datapath=$QT_SYSROOT_DATA",
++    "qt_trnspath=$QT_SYSROOT_TRANSLATIONS",
++    "qt_xmplpath=$QT_SYSROOT_EXAMPLES",
++    "qt_tstspath=$QT_SYSROOT_TESTS",
++    "qt_ssrtpath=",
++    "qt_hpfxpath=$QT_SYSROOT_PREFIX",
++    "qt_hbinpath=$QT_SYSROOT_BINS",
++    "qt_hlibpath=$QT_SYSROOT_LIBS",
++    "qt_hdatpath=$QT_SYSROOT_LIBS/qt5",
++    "qt_targspec=linux-g++",
++    "qt_hostspec=linux-g++",
```

Is this documented somewhere?

**Comment by carlos22** [comment]
Archlinux:

```
> strings libQt5Core.so.5 | grep qt_ | grep = | cut -d "=" -f 1
qt_prfxpath
qt_instdate
```

```
> pacman -Qi qt5-base
Name                     : qt5-base
Version                  : 5.8.0-7
Beschreibung             : A cross-platform application and UI framework
Architektur              : x86_64
```

**Comment by carlos22** [comment]
Suggestion for some vars:
```
qt_prfxpath=.
qt_docspath=./doc
qt_hdrspath=./include
qt_libspath=./lib
qt_lbexpath=./libexec
qt_binspath=./bin
qt_plugpath=./plugins
qt_impspath=./imports
qt_qml2path=./qml
qt_adatpath=.
qt_datapath=.
qt_trnspath=./translations
qt_xmplpath=./examples
qt_tstspath=./tests
```

Based on: https://bugreports.qt.io/browse/QTBUG-31760

**Comment by carlos22** [comment]
## Qt Framework Installer
The Qt Installer Framework also patches the values, code is here: http://code.qt.io/cgit/installer-framework/installer-framework.git/tree/src/libs/installer/qtpatchoperation.cpp?id=0ff7968345752395af93334b174973ebefb95048#n106

```sh
> qmake -query "QT_INSTALL_CONFIGURATION"
/etc/xdg
```
Docs for the in the installer used replacements: http://doc.qt.io/qt-5/qmake-environment-reference.html

**Comment by probonopd** [comment]
Awesome investigation @carlos22 - do I smell a PR coming?

**Comment by probonopd** [comment]
When using https://launchpad.net/~beineri/+archive/ubuntu/opt-qt532-trusty then currently the following lands in the AppImage, which is clearly wrong:

```
[antergos@Antergos-ISO ~]$ strings squashfs-root/usr/lib/libQt5Core.so.5 | grep '^qt_.*='
qt_stngpath=/opt/qt53/etc/xdg
qt_prfxpath=..
qt_docspath=/opt/qt53/doc
qt_hdrspath=/opt/qt53/include
qt_libspath=/opt/qt53/lib
qt_lbexpath=/opt/qt53/libexec
qt_binspath=/opt/qt53/bin
qt_plugpath=plugins
qt_impspath=/opt/qt53/imports
qt_qml2path=/opt/qt53/qml
qt_adatpath=/opt/qt53
qt_datapath=/opt/qt53
qt_trnspath=/opt/qt53/translations
qt_xmplpath=/opt/qt53/examples
qt_tstspath=/opt/qt53/tests
qt_instdate=2015-03-11
qt_lcnsprod=OpenSource
qt_lcnsuser=Open Source
```

**Comment by probonopd** [comment]
Check out QtBinPatcher source code from
http://repo.msys2.org/mingw/sources/mingw-w64-i686-qtbinpatcher-2.2.0-1.src.tar.gz

Perhaps we can reuse parts of it or get some inspiration at least.

**Comment by probonopd** [comment]
So, my current working hypothesis is:

```
qt_prfxpath=..
qt_adatpath=.
qt_docspath=doc
qt_hdrspath=include
qt_libspath=lib
qt_lbexpath=libexec
qt_binspath=bin
qt_plugpath=plugins
qt_impspath=imports
qt_qml2path=qml
qt_datapath=.
qt_trnspath=translations
qt_xmplpath=examples
qt_demopath=demos
qt_tstspath=tests
qt_hpfxpath=.
qt_hbinpath=bin
qt_hdatpath=.
```

Plus patch away `qt.conf` loading from the system (e.g., `/etc`)

**Comment by probonopd** [comment]
Now @carlos22 can you give it a try to make a function that checks if a qt_ variable is there and if yes, patches it with the default values from above?

**Comment by probonopd** [comment]
I am writing this logic now...

**Comment by probonopd** [comment]
@carlos22 please try the latest continuous build and report back how it goes. If it still doesn't work, then I suspect that it is loading some Trolltech.conf or qt.conf from your system; verify this by using strace and temporarily removing the offending conf file from your system (temporarily move it away).

**Comment by probonopd** [comment]
@carlos22 @adrianschroeter please try the latest continuous build and report back how it goes. If it still doesn't work, then I suspect that it is loading some Trolltech.conf or qt.conf from your system; verify this by using strace and temporarily removing the offending conf file from your system (temporarily move it away).

**Comment by probonopd** [comment]
@carlos22 I think any remaining issues with distro Qt on Arch Linux may be unrelated to this, so let's continue on https://github.com/probonopd/linuxdeployqt/issues/98

**Comment by carlos22** [comment]
@probonopd yes thats what i expected. But good work with this issue :+1:
