### ISSUE TITLE
Copy certain plugins unless "-no-plugins" is specified

### ISSUE THREAD

**Issue by bjorn** [probonopd/linuxdeployqt#82]
When I released Tiled 0.18.1, the Linux archive built with linuxdeployqt (version 9a1fbab) contained `libQt5Svg.so.5` and the `libqsvg.so` image format plugin. Now that I'm using linuxdeployqt release 2, neither of these are included anymore.

I would like to use release 2, because it fixes the shipping of all other image format plugins. However I would prefer not to drop the SVG plugin. The problem is that Tiled does not itself rely on QtSvg (I tried linking it to QtSvg, but that was not enough to fool linuxdeployqt, I needed to [actually use it](https://github.com/bjorn/tiled/commit/d3f1996c43d9f40e51e73900372d156bd19609d1)).

What would a proper solution look like? I could imagine specifying additional Qt libraries to include, or specifying additional Qt plugins to include, or handling SVG explicitly with an `-qtsvg` command line option.

**Comment by probonopd** [comment]
What exactly in your AppImage requires/uses the SVG plugin, and how could `appimaged` detect that?

**Comment by bjorn** [comment]
There is no way to detect it because this is about shipping the SVG
image plugin. This plugin enables reading of SVG image files, but it is
only shipped when the application depends on QtSvg (checked specifically
by linuxdeployqt).

If the SVG image plugin would always be shipped, this would mean
linuxdeployqt would always ship QtSvg as well, which may not be
desirable because it increases the size of the package (though I think
only about 1 MB).

**Comment by probonopd** [comment]
Sorry for my ignorance here, but which component uses, i.e., takes advantage of a present, SVG image plugin? (So could we say, if this component is present, we should also deploy the SVG image plugin?)

**Comment by bjorn** [comment]
No component in my application uses this plugin. It is a Qt plugin, and
if it isn't there, Qt is not able to read images in SVG format. But that
means my application can't read SVG images either, so I'd like this
plugin to be included and I'm looking for a way to tell this to
linuxdeployqt.

**Comment by probonopd** [comment]
OK, I begin to understand, you are saying conceptually there is no way for `linuxdeployqt` to know that your application can benefit from this plugin. Is running `linuxdeployt`, then manually copying in the SVG image plugin, then running `linuxdeployqt -appimage` an accaptable solution?

**Comment by bjorn** [comment]
> Is running linuxdeployt, then manually copying in the SVG image plugin, then running linuxdeployqt -appimage an accaptable solution?

Hmm, I guess it would! I did not realize that I could use linuxdeployqt this way. I'll give it a try this evening.

**Comment by vadi2** [comment]
I don't think Qt needs QtSvg to read SVG format - I learnt that a couple of days ago myself on #qt. You only need QtSvg if you are actually ``QT+=svg`` and you so stuff with the ``QtSvg`` class. Try it to be sure, but I think this is a case of misunderstanding.

**Comment by bjorn** [comment]
> I don't think Qt needs QtSvg to read SVG format

The SVG image plugin uses QtSvg for rasterizing the SVG into a QImage. So, the plugin will not work if you do not distribute QtSvg with your program.

This of course does not apply when you're not distributing your program, or when the program is distributed as an operating system package with Qt as a dependency. In that case, the SVG image plugin installed on the system will be used, which will pick up the QtSvg library installed on the system and you don't need to worry about it.

**Comment by probonopd** [comment]
Actually we inherited from `macdeployqt` the sentence

> The accessibility, image formats, and text codec plugins are always copied, unless "-no-plugins" is specified

but didn't implement it so far... so would this solve your concern, do you think this would be a sensible thing to implement?

**Comment by vadi2** [comment]
I'd be fine with it

**Comment by bjorn** [comment]
Yeah, that would work fine for me as well.

The only problem I guess would be that packages are a little larger for those not shipped QtSvg, but the SVG image plugin is really small anyway (only about 23K), so I guess the logic meant to exclude it could just be removed.

**Comment by probonopd** [comment]
OK, the path of action is clear then:

> The accessibility, image formats, and text codec plugins are always copied, unless "-no-plugins" is specified

needs to be implemented.

**Comment by probonopd** [comment]
PR welcome!

**Comment by bjorn** [comment]
I've currently solved the issue in Tiled by [copying over the SVG image plugin](https://github.com/bjorn/tiled/blob/master/.travis.yml#L51) before running `linuxdeployqt`, like you suggested back in February:
```
cp /opt/qt58/plugins/imageformats/libqsvg.so Tiled/usr/plugins/imageformats/
```
But maybe I can try a PR for this on Monday.
