### ISSUE TITLE
32bit linuxdeployqt

### ISSUE THREAD

**Issue by vadi2** [probonopd/linuxdeployqt#88]
How can I get a 32bit version of linuxdeployqt to make an AppImage for my 32bit users?

**Comment by probonopd** [comment]
For the time being, you need to compile one.

**Comment by vadi2** [comment]
That's fine, thanks. Was more concerned about any incompatibility but it sounds like there isn't any.

**Comment by probonopd** [comment]
Not if you make it use the appimagetool binary from https://github.com/probonopd/AppImageKit/releases. That one is what is important for binary compatibility.

**Comment by vadi2** [comment]
How do I do that with linuxdeployqt?

**Comment by probonopd** [comment]
Look at the [`.travis.yml`](https://github.com/probonopd/linuxdeployqt/blob/master/.travis.yml) in this repository to see how to do this. This is how I build linuxdeployqt using appimagetool from https://github.com/probonopd/AppImageKit/releases.

**Comment by vadi2** [comment]
Github doesn't give any notifications when you edit things, so if you read the email reply only you miss the edit. Will have a look, thanks.
