### ISSUE TITLE
Need to be able to set the current working directory

### ISSUE THREAD

**Issue by vadi2** [probonopd/linuxdeployqt#90]
AppImage doesn't set the current working directory of the application to the applications binary, which requires patching the source to work with absolute paths when loading the data. This is a minor inconvenience for the author and is dealable with.

However, using absolute paths makes error reporting really, really ugly - for example when Lua reports an error that comes from a function that comes from a file, it uses the original path the file was loaded with. The result is that the errors are super long:

         </tmp/.mount_GPSika/mudlet-lua/lua/GUIUtils.lua:262: moveGauge: no such gauge exists.>

Making them push out the actual error message in a reasonably-sized window:

![ubuntu 14 04 32bit running - oracle vm virtualbox_009](https://cloud.githubusercontent.com/assets/110988/23983795/5475b64e-0a16-11e7-97fe-f36593bbd4df.png)

This puts users of an appimage at a disadvantage compared to the native packaging formats.

**Comment by probonopd** [comment]
When an AppImage is executed, it mounts itself to a temporary location and then executes the AppRun file at the mountpoint. What happens from thereon can entirely be controlled by the payload application. 

In the screenshot you provided, I assume that the Qt application shown launches the CLI commands shown in the text window. So it is the Qt application that determines how these are launched. The Qt application could, for example, chdir() to the directory in which the CLI tool lives and launch it from there using a relative path.

What exactly would you expect AppImage to do?

**Comment by vadi2** [comment]
It's not a CLI application, it's an embedded Lua runtime. I had to switch to using absolute paths as a consequence of #67. My application natively uses relative paths to the binary and thus the error messages are much shorter.

**Comment by probonopd** [comment]
Seems to be an issue of the payload application (Lua issue) that has been sorted out in #67 and I fail to understand what linuxdeployqt should do differently. Feel free to reopen if you think that linuxdeployqt needs to be changed.
