### ISSUE TITLE
How to give appimage an icon?

### ISSUE THREAD

**Issue by vadi2** [probonopd/linuxdeployqt#93]
Someone showed me this:

![unknown](https://cloud.githubusercontent.com/assets/110988/24078756/a4d2fefa-0c76-11e7-8060-c4a78b8cce36.png)

How can I get an icon on my elf binary as well? I do provide a valid ``Icon`` entry that gets picked up and turned into a ``.DirIcon`` link by the build process.

**Comment by probonopd** [comment]
Please see https://github.com/probonopd/AppImageKit/issues/346. This is outside of the scope of linuxdeployqt but is a topic for AppImageKit, hence closing here.
